### PR TITLE
Setting Up Codecov Environment (Documentation Update)

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

**Issue Number:** #1095 

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
In your next PR please upload the images to GitHub and reference them there so that we can be assured they will always be available.

**Comment by zakhaev26** [comment]
@palisadoes imo,given that static assets are being used in Markdown files , to be specific  : `CONTRIBUTING.md` and `INSTALLATION.md` of Talawa-API , in that case we should proceed with `public` directory as it offers various benefits like direct access to assets in the web server ,simplifies referencing them in Markdown files.Also by convention `/public` is more commonly used.

**Comment by duplixx** [comment]
> > 1. For my edification, what is the difference between the `public/` directory and the `src/assets` directory? They seem to have the same type of content.
> >    
> >    2. We have this issue created to try to standardize the locations of images for markdowns. I want to make sure that both repos have the same understanding of the purpose. @zakhaev26 is working on it.
> >       
> >       * [Standardize the location of repository assets talawa-api#1441 (comment)](https://github.com/PalisadoesFoundation/talawa-api/issues/1441#issuecomment-1837498896)
> 
> @duplixx Please respond it is important for a PR submitted by @zakhaev26


@zakhaev26 
I agree with your point. Using the "public" directory for static assets in Markdown files, like `CONTRIBUTING.md` and `INSTALLATION.md` of Talawa-API, makes perfect sense. The benefits of direct access to assets on the web server and simplified referencing in Markdown files, coupled with the convention of "/public" being more commonly used. Let's proceed with the "public" directory for enhanced accessibility and ease of use.

**Comment by palisadoes** [comment]
OK. Please update the PR with `public/` as the top most directory

**Comment by zakhaev26** [comment]
Okay,will do that.
Should we do this change across all the Talawa repos ? 
> For instance, Talawa-Admin too has `src/assets` convention.

**Comment by palisadoes** [comment]
1. Yes eventually.
2. The exception would be Talawa-Docs uses Docusaurus. It's all Markdown and we used the default location for the images. The root directory markdown files have no images.

**Comment by duplixx** [comment]
@palisadoes @aashimawadhwa @rishav-jha-mech can it be merged now ??

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
