### PR TITLE
Usertype removal - part 1

### LINKED ISSUE #1827: [userTypeFix] Admin: Remove legacy references to `userType`
**Is your feature request related to a problem? Please describe.**

We recently updated the code base to replace the authorization mechanism for users from being a `userType` field in the database’s User collection to an `appUserProfile` field.

**Describe the solution you'd like**

1. Though the updated code works, there are still many unused references to `userType` in the code base. 
1. Some of these references may still be accessible under certain circumstances creating malfunctioning code. These sections will need to be refactored.

The aim is for the  `userType`  to be removed, while maintaining the expected functionality of the app

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

1. This is the project tracking the `userType` adjustment
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. All tests must be valid and pass. There must be no reduction in test code coverage
1. All functionality must be maintained
1. These are the files that need to be updated in this repo

```
public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
schema.graphql
src/App.test.tsx
src/components/DeleteOrg/DeleteOrg.test.tsx
src/components/DeleteOrg/DeleteOrg.tsx
src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx
src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
src/components/LeftDrawer/LeftDrawer.test.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx
src/components/OrganizationScreen/OrganizationScreen.test.tsx
src/components/ProfileDropdown/profileDropdown.tsx
src/components/RequestsTableItem/RequestsTableItem.test.tsx
src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
src/components/UserPortal/Login/Login.test.tsx
src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx
src/components/UserPortal/StartPostModal/StartPostModal.test.tsx
src/GraphQl/Mutations/mutations.ts
src/GraphQl/Queries/Queries.ts
src/screens/MemberDetail/MemberDetail.test.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrgList/OrganizationModal.tsx
src/screens/OrgList/OrgListMocks.ts
src/screens/OrgList/OrgList.tsx
src/screens/OrgSettings/OrgSettings.test.tsx
src/screens/Requests/Requests.test.tsx
src/screens/Requests/Requests.tsx
src/screens/UserPortal/Chat/Chat.test.tsx
src/screens/UserPortal/Events/Events.tsx
src/screens/UserPortal/People/People.test.tsx
src/screens/UserPortal/People/People.tsx
src/screens/UserPortal/Settings/Settings.test.tsx
src/screens/Users/Users.tsx
src/utils/interfaces.ts
src/utils/memberFields.ts
```

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranshugupta54**
Ref #1827

- **OrgMemberConnection** - this needs some fix, it has `appUserProfileId` field which returns `null` always.
- Added  `// eslint-disable-line` to some lines which should be fixed separately (userType changes require me to fix lint in that file which is not relevant to this issue)

**Files:**

- [ ] public/locales/en.json - can skip translations 
- [ ] public/locales/fr.json - can skip translations 
- [ ] public/locales/hi.json - can skip translations 
- [ ] public/locales/sp.json - can skip translations 
- [ ] public/locales/zh.json - can skip translations 
- [ ] schema.graphql - https://github.com/PalisadoesFoundation/talawa-api/issues/2139
- [x] src/App.test.tsx
- [x] src/components/DeleteOrg/DeleteOrg.test.tsx
- [x] src/components/DeleteOrg/DeleteOrg.tsx
- [ ] src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx -> #1853
- [ ] src/components/LeftDrawerEvent/LeftDrawerEvent.tsx -> #1853
- [x] src/components/LeftDrawer/LeftDrawer.test.tsx
- [x] src/components/LeftDrawer/LeftDrawer.tsx
- [x] src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
- [ ] src/components/OrgAdminListCard/OrgAdminListCard.tsx -> #1852
- [x] src/components/OrganizationScreen/OrganizationScreen.test.tsx
- [x] src/components/ProfileDropdown/profileDropdown.tsx
- [x] src/components/RequestsTableItem/RequestsTableItem.test.tsx
- [x] src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
- [x] src/components/UserPortal/Login/Login.test.tsx
- [ ] src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx - **OrgMemberConnection**
- [x] src/components/UserPortal/StartPostModal/StartPostModal.test.tsx
- [ ] src/GraphQl/Mutations/mutations.ts - only 1 mutation - https://github.com/PalisadoesFoundation/talawa-api/issues/2139
- [x] src/GraphQl/Queries/Queries.ts
- [x] src/screens/MemberDetail/MemberDetail.test.tsx
- [ ] src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx - **eslint issue**
- [x] src/screens/OrganizationEvents/OrganizationEvents.tsx
- [ ] src/screens/OrganizationPeople/OrganizationPeople.test.tsx - **OrgMemberConnection**
- [ ] src/screens/OrgList/OrganizationModal.tsx - **not userType - it's InterfaceUserType**
- [ ] src/screens/OrgList/OrgListMocks.ts - **not userType - it's InterfaceUserType**
- [ ] src/screens/OrgList/OrgList.tsx - **not userType - it's InterfaceUserType**
- [x] src/screens/OrgSettings/OrgSettings.test.tsx
- [x] src/screens/Requests/Requests.test.tsx
- [ ] src/screens/Requests/Requests.tsx - **eslint issue**
- [ ] src/screens/UserPortal/Chat/Chat.test.tsx - **OrgMemberConnection**
- [ ] src/screens/UserPortal/Events/Events.tsx - **eslint issue**
- [ ] src/screens/UserPortal/People/People.test.tsx - **OrgMemberConnection**
- [ ] src/screens/UserPortal/People/People.tsx - **OrgMemberConnection**
- [x] src/screens/UserPortal/Settings/Settings.test.tsx
- [ ] src/screens/Users/Users.tsx - **eslint issue**
- [ ] src/utils/interfaces.ts - **removed unused InterfaceQueryRequestListItem and leaving InterfaceUserType as it is**
- [x] src/utils/memberFields.ts

### CODE REVIEW

**Comment by dhanagopu** [comment]
@pranshugupta54 Please fix the failing tests

**Comment by pranshugupta54** [comment]
- Introspection is irrelevant
- Added // eslint-disable-line to some lines which should be fixed separately (userType changes require me to fix lint in that file which is not relevant to this issue)

**Comment by palisadoes** [comment]
The lint check is too ensure we have consistent coffee quality.

It is therefore relevant to the PR

**Comment by pranshugupta54** [comment]
@palisadoes, we should take it separately. I haven't touched the functions which had linting issues, but fixed userType in those files. These eslint issues are there in the codebase for so long and should be taken in different issue or should be fixed by users working on the file.

**Comment by Anubhav-2003** [comment]
> * Introspection is irrelevant
> 
>     * Added // eslint-disable-line to some lines which should be fixed separately (userType changes require me to fix lint in that file which is not relevant to this issue)

Hey can you please tell me why is the introspection failing? Because it was fixed, and now it is the duty of all new future PR's to ensure that it passes, otherwise it would nullify the entire point of having it in the workflow. Thank You.

**Comment by Anubhav-2003** [comment]
> @palisadoes, we should take it separately. I haven't touched the functions which had linting issues, but fixed userType in those files. These eslint issues are there in the codebase for so long and should be taken in different issue or should be fixed by users working on the file. It's also going to take one person very long to understand each function of each file to fix those types.

Yes I agree with you on this point. Because the codebase has a lot of existing lint issues, and all of them cannot be solved trivially as one has to understand the context of each to replace the 'any' types. I don't think having the eslint disable workflow as a blocker for the testing is the right choice. It should be there to notify the reviewers about its usage, but should not block the tests from running. Thank you.

**Comment by pranshugupta54** [comment]
> Hey can you please tell me why is the introspection failing? Because it was fixed, and now it is the duty of all new future PR's to ensure that it passes, otherwise it would nullify the entire point of having it in the workflow. Thank You.
@Anubhav-2003, I don't think it's related to this PR.

Haven't changed mutation or schema
image

**Comment by palisadoes** [comment]
The application tests won't be completed until the linting is done.

This has been in place in this repo for months

**Comment by pranshugupta54** [comment]
@palisadoes, I've reverted 4 files to fix eslint issue. We can take those files later. Everything is passing well, except irrelevant introspection test.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
