### PR TITLE
Refactor CSS files in src/screens/OrgContribution (Fixs : #2520)

### LINKED ISSUE #2520: Refactor CSS files in src/screens/OrgContribution
# Refactor CSS files in src/screens/OrgContribution

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by amaan-aly246**
**What kind of change does this PR introduce?**

Refactor

**Issue Number:**

Fixes #2520 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot 2024-12-12 234946

**If relevant, did you update the documentation?**

Not relevant

**Summary**

The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced new CSS variables and class definitions for improved styling across components.
  
- **Bug Fixes**
	- Removed unused CSS styles to streamline the stylesheet.

- **Documentation**
	- Updated comments for improved clarity in GraphQL mutation definitions.

- **Style**
	- Removed several CSS files and associated styles, affecting the appearance of text and card components. 
	- Updated import paths for CSS in several components to a centralized stylesheet. 

- **Refactor**
	- Simplified prop access in the `ContriStats` component for better readability. 
	- Renamed the `orgContribution` component to `OrgContribution` for consistency with naming conventions.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@amaan-aly246 Please fix the failed tests.

**Comment by amaan-aly246** [comment]
currently working on resolving the 3rd failed test.

**Comment by palisadoes** [comment]
1. Please fix the failing tests. Click on the `Details` links for more information.
1. Please make sure that CodeRabbit.ai approves your changes

**Comment by amaan-aly246** [comment]
@palisadoes, I need help solving the failing test. I know a bit of GraphQL but am unable to resolve this error:
[log] in /home/runner/work/talawa-admin/talawa-admin/src/GraphQl/Mutations/FundMutation.ts: [log] - Cannot query field 'createFund' on type 'Mutation'. Did you mean 'createUser'?

I looked at the schema.graphql and FundMutation.ts files but couldn't find any issue in the schema and code is working fine on my end without any errors. 
Thanks

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
The introspection tests will be fixed in a few weeks.
Thanks

**Comment by amaan-aly246** [comment]
@palisadoes I want to contribute  more to this org. I have 2-3 question if you (or any maintainer)  can answer 

1. Do you guys have any stack/discord channel for development related issue, where I can ask question regarding the same?
2. Initially, I pulled the `main` branch of the forked repository (as mentioned in the README file about contributions) and made my changes there. However, when raising a PR, I was told to make changes to the `develop-postgres` branch. Should I fetch the updated code from develop-postgres and start development from that branch moving forward?
3. Will this organization be participating in GSoC'25 as a mentoring organization?

Thanks, looking forward to contribute more.

**Comment by Cioppolo14** [comment]
@amaan-aly246 I cannot answer #2, but you can find the link to our slack channel on our main github page for Palisadoes Foundation.  We do hope to participate in GSoC 2025 as a mentoring organization.

**Pull request merged**
