### PR TITLE
Fixed Redirect Issues on Reopening baseURL

### LINKED ISSUE #1775: [userTypeFix] Error on Redirect if Tab closed and reopened on baseUrl
**Describe the bug**
- If the user is logged in as user and then closes tab and reopens it from base url (here localhost:4321/) user is redirected to wrong screen causing error.

**To Reproduce**

1. Login as User
2. Close the tab
3. In new Tab enter base url (in this case `localhost:4321`)
4. Error is showned

**Expected behavior**
If we close the tab and reopen baseUrl `localhost:4321` then if previously logged in user is (Type) user should redirect to user home screen.

**Actual behavior**
If we close the tab and reopen baseUrl `localhost:4321` then error is shown.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/362d407a-bb71-4ed0-b363-8f45cbfba6fa

image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by GlenDsza**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1775 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/e1a8a4b8-92f4-41df-bc40-c7aa26f50457

**Summary**

Earlier when signed in as user if we reopen other tab on baseURL the user was redirected to admin home page causing error, fixed conditions to redirect to user home page.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by GlenDsza** [comment]
@palisadoes Test application check is failing due to failing tests in `src/screens/Users/Users.test.tsx` which is unrelated to above issues or changes made in this PR.

#1770 will fix failing tests in `src/screens/Users/Users.test.tsx`

**Review by varshith257 — APPROVED** [review]
LGTM

@palisadoes The Introspection workflow is failing due to some uncaught bugs in API. I would create their issues in API
https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/8407216776/job/23021925968?pr=1787

**Comment by akhilender-bongirwar** [comment]
@GlenDsza @varshith257 I have fixed all the tests in my PR #1678

**Comment by varshith257** [comment]
@GlenDsza Can you test the changes in the mobile repo due to the merge of userTypeFix into develop? It means the related merged screens

**Comment by GlenDsza** [comment]
> @GlenDsza Can you test the changes in the mobile repo due to the merge of userTypeFix into develop? It means the related merged screens yesterday

Sure👍

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
