### PR TITLE
[Feature Request] Forgot Password and Google Recaptcha added

### LINKED ISSUE #342: [Feature Request] New Features and responsiveness issues
**Is your feature request related to a problem? Please describe.**
Currently, in Talawa-admin, the feature for forgetting passwords is not present, and while logging in or signup there is no captcha to detect the bot activity. The pop-up alerts are not configured to pop up the correct exception.

**Describe the solution you'd like**
* Interactive alerts will be added i.e. react-toasts.
* Registration page and Login modal will be redesigned with google Recaptcha, better UX, and interactive alerts.
* Forgot password page will be added.
* Authorization will be added for accessing an organization, i.e. only the admin of an organization or super admin can access that particular organization.
* A new screen named Roles will be added to toggle users' roles between USER, ADMIN, and SUPER ADMIN. This feature will be helpful in order to make another person a SUPER ADMIN.
* A new screen named Requests will be added in order to approve the signup of only authorized admins. This makes the admin panel secure from the outside world.
* Only a SUPER ADMIN will access the pages' Roles and Requests.
* Search will be implemented in the Organization list, Roles, and Requests screens.
* Pagination will be implemented in the Organization list, Roles, and Requests screens.
* While creating a new organization, the option of tags will be added. Before this, hard-coded tags are listed in the dashboard. Also, the user experience is improved.
* A statistic of an organization will be added to the dashboard. The statistics contain the number of members, admins, etc.
* Pagination will be implemented in the Organization People screen.
* Hard-coded values of the member list, admin list, and user list will be changed to dynamic ones. 
* Multiple screen responsiveness issues will be fixed.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #342

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

* Google Recaptcha 
 Screenshot 2022-06-13 at 17-37-28 Talawa Admin

* Interactive Alerts
 Screenshot 2022-06-13 at 17-38-06 Talawa Admin

* OTP is sent to the registered email
 Screenshot 2022-06-13 at 17-38-42 Talawa Forgot Password

* Received OTP email
 Screenshot 2022-06-13 at 17-39-19 OTP for Talawa-admin forgot password - asmitsirohi9761@gmail com - Gmail_LI

* Password Changes Successfully
 Screenshot 2022-06-13 at 17-39-50 Talawa Forgot Password

**If relevant, did you update the documentation?**

Yes

**Summary**

This pull request includes features, which is required to implement. The complete info is as follows:

* Interactive alerts added i.e. react-toasts.
* Registration page and Login modal is redesigned with google Recaptcha, better UX, and interactive alerts.
* Forgot password page is added.
* Documentation is updated regarding the google Recaptcha key.

**Does this PR introduce a breaking change?**

No

**Other information**

This pull request is under GSoC'22.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by yasharth291** [comment]
@palisadoes merge this sir

**Comment by asmitsirohi** [comment]
@palisadoes sir, please merge this pull request. Without merging this pull request it is difficult for me to complete future tasks.

**Review by palisadoes — CHANGES_REQUESTED** [review]
There are errors in the workflow that are preventing the code coverage to be calculated. Some dependencies are incorrect. Please fix https://github.com/PalisadoesFoundation/talawa-admin/runs/6989097442?check_suite_focus=true

**Comment by asmitsirohi** [comment]
> There are errors in the workflow that are preventing the code coverage to be calculated. Some dependencies are incorrect. Please fix https://github.com/PalisadoesFoundation/talawa-admin/runs/6989097442?check_suite_focus=true

I'm not able to know where actually the error is, the code coverage is calculated successfully.

image

**Pull request closed without merging**
