### PR TITLE
[Fixes] Code Coverage: Create tests for OrgContriCards.tsx

### LINKED ISSUE #242: Code Coverage: Create tests for OrgContriCards.tsx
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/components/OrgContriCards/OrgContriCards.tsx`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/components/OrgContriCards/OrgContriCards.test.tsx`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/components/OrgContriCards/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #242 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Other information**

Parent issue: #241

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by yasharth291** [comment]
I don't think this change is a nessicity here @asmitsirohi

**Review by yasharth291 — CHANGES_REQUESTED** [review]
no need to change it i guess

**Comment by asmitsirohi** [comment]
@yasharth291  I thought the same thing because the code coverage for this file is already 100%.

I change test() to it() because if the test case fails then It() helps to faster understand what the test is about.

* What you get if something fails in it():

yourModule > should do this thing

* What you get if something fails in test():

yourModule > if it does this thing

In my opinion, it() really has a point when it comes to reading the result of a failing test that you haven't written yourself. It helps to faster understand what the test is about.

**Comment by yasharth291** [comment]
i understand it but it should not only check hard coded things but check if the data is properly coming or not.

**Comment by asmitsirohi** [comment]
@yasharth291, The OrgContriCards are used in src\screens\OrgContribution\OrgContribution.TSX but in the same file, hardcoded values are used for displaying the organization cards.

image

Till now, I made sure the tests for OrgContriCards are appropriate and I have added graphql server to the test, to make code consistent.

**Comment by yasharth291** [comment]
> @yasharth291, The OrgContriCards are used in src\screens\OrgContribution\OrgContribution.TSX but in the same file, hardcoded values are used for displaying the organization cards.
> 
> image
> 
> Till now, I made sure the tests for OrgContriCards are appropriate and I have added graphql server to the test, to make code consistent.

why only john doe not any other data?

**Comment by asmitsirohi** [comment]
> > @yasharth291, The OrgContriCards are used in src\screens\OrgContribution\OrgContribution.TSX but in the same file, hardcoded values are used for displaying the organization cards.
> > image
> > Till now, I made sure the tests for OrgContriCards are appropriate and I have added graphql server to the test, to make code consistent.
> 
> why only john doe not any other data?

Because it is used by most of the developers in the community, just to indicate dummy names.

**Comment by yasharth291** [comment]
same idhar h bhai you have to use dynamic data not hard coded change it like other one

**Comment by asmitsirohi** [comment]
Ok, cool I have made the required changes.

**Review by DangaRanga — APPROVED** [review]

**Comment by palisadoes** [comment]
Yasharth please take a look

**Comment by palisadoes** [comment]
@yasharth291 Please take a look

**Review by yasharth291 — APPROVED** [review]

**Pull request merged**
