### PR TITLE
Improved Grid view for the post newsfeed dashboard 

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**

feature
**Issue Number:**

Fixes #921

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/4aecfe72-7543-4d6d-9ba1-ee0163e22692

**If relevant, did you update the documentation?**
not required

**Summary**
Implemeneted grid system like Instagram web to provide with a concise and neat view of all the posts.
Features added in this PR:

-     Improved grid view for the dashboard in the post management.
-     A detailed view for post
-     elimination pagination to introduce infinite scroll.
-     Image and video previewer in the modal

**Does this PR introduce a breaking change?**

NO
**Other information**

NA
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

YES

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@tonythegr8 @ttaylor92

**Review by ttaylor92 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@aashimawadhwa I'm going to have to revert this PR.  The code coverage has declined by almost 4% and we are getting this DOM message.

image

**Comment by anshgoyalevil** [comment]
@palisadoes @ttaylor92 How did this PR got approved in the first place? With tests being removed and code coverage being declined.
Please review the code properly.

**Comment by aashimawadhwa** [comment]
@anshgoyalevil  we are working on it, the PR happened last minute, thank-you for your feedback .

**Pull request merged**
