### PR TITLE
fixes: #461 fixed pagination footer in post tab

### LINKED ISSUE #461: Bug Report : two pagionation footers in post tab
**Describe the bug**
there are two pagination footer in the post tab of the dashboard

**To Reproduce**

1. create an organization
2. click on manage organization to open the dashboard
3. click on the post tab
4. see the error

**Expected behavior**
there should be only one pagination footer.

**Actual behavior**
there are two pagination footer one over the other

**Screenshots**
Screenshot 2023-02-10 at 6 43 36 PM (2)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
Removed two footers from the post tab in the dashboard.

**Issue Number:**

Fixes #461 

**Did you add tests for your changes?**

 not required
**Snapshots/Videos:**

Screenshot 2023-02-12 at 1 27 14 AM

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
I have just removed repeated the code due to which , it is showing coverage drop.

**Comment by Tajcore** [comment]
> I have just removed repeated the code and it is showing coverage drop any specific reason ?

Maybe it's included in a test suite

**Comment by noman2002** [comment]
> > I have just removed repeated the code and it is showing coverage drop any specific reason ?
> 
> Maybe it's included in a test suite

It is dropped due to the removal of code. it happens with codecov sometimes.

**Review by noman2002 — APPROVED** [review]

**Review by Tajcore — APPROVED** [review]
LGTM

**Review by Kevoniat — APPROVED** [review]

**Pull request merged**
