### PR TITLE
Fix "Profile Update Not Working on Admin Portal #1508"

### LINKED ISSUE #1508: Profile Update Not Working on Admin Portal
**Describe the bug**
Any Changes to The Admin Profile cannot be made . We get a 404 error in response.

**To Reproduce**

1.Log in Admin Panel as Admin
2.Go to Update Profile section
3.Change Profile Details
4.Click Update Profile

**Expected behavior**
Profile Information Should be Updated

**Actual behavior**
Response is error

**Screenshots**
[Screencast from 28-01-24 04:42:58 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/121512095/9d263248-15f8-4964-be7f-2b9f36166795)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Shubh152**
**What kind of change does this PR introduce?**

bug-fix

**Issue Number:**

Fixes #1508 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
This pull request makes relevant changes in the admin repo for https://github.com/PalisadoesFoundation/talawa-api/issues/1750

**Does this PR introduce a breaking change?**

No

**Other information**

Continued from https://github.com/PalisadoesFoundation/talawa-admin/pull/1573

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Shubh152 Can you fix the failing test application check?

**Comment by pranshugupta54** [comment]
@Cioppolo14, this should be automatically fixed in the new design of this page. PR #1615

**Comment by Cioppolo14** [comment]
I believe this test needs to pass before we can move the PR forward in the review process.

**Comment by Shubh152** [comment]
The Test failure was unexpected as I have not made any changes that could have caused this. If this is resolved in PR https://github.com/PalisadoesFoundation/talawa-admin/issues/1615 / https://github.com/PalisadoesFoundation/talawa-admin/pull/1667 as claimed by @pranshugupta54, then we should close this PR.

**Comment by Shubh152** [comment]
Also the corresponding issue must be closed.

**Pull request closed without merging**
