### PR TITLE
Redesigned User Requests for talawa admin

### LINKED ISSUE #1631: ADMIN REDESIGN: redesign the User Request for the talawa admin portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the User Request for the admin portal .

**Screenshots**
- Attaching the screenshots for reference.

Desired Result:
Screenshot 2024-02-28 at 11 47 17 PM

Please refer the figma file for a detailed understanding : 

https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307%3A212&mode=design&t=hBVanpDXxbRFi51m-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sahi1l-Kumar**
**What kind of change does this PR introduce?**
A feature.

**Issue Number:**

Fixes #1631 

**Did you add tests for your changes?**
Yes.

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/135227614/9e33531c-1a04-4111-b7f8-29e61a3debd3

**If relevant, did you update the documentation?**

**Summary**
In the following PR, I have implemented the User Request Screen. Admin can accept or reject Membership Requests sent to the organization through this screen.

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@ttaylor92 @Tajcore Can you review this PR?

**Comment by Sahi1l-Kumar** [comment]
The search functionality in this component will only work when the API have these changes https://github.com/PalisadoesFoundation/talawa-api/pull/2010

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
Please fix the conflicting files. This is an important screen to have updated

**Comment by Sahi1l-Kumar** [comment]
@palisadoes  I have updated the PR

**Comment by palisadoes** [comment]
Please fix the failing test. It looks like this file.

- src/screens/Users/Users.test.tsx

**Comment by Sahi1l-Kumar** [comment]
@palisadoes Wasn't the failed tests to be corrected in this issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1770 ?

**Comment by palisadoes** [comment]
Thanks. I've assigned the issue.

**Comment by Sahi1l-Kumar** [comment]
@palisadoes I have fixed the failing tests locally which brought the coverage test to 100. So is that issue even needed anymore?

**Comment by palisadoes** [comment]
Please add a video of the requests workflow showing the design

**Comment by Sahi1l-Kumar** [comment]
> Please add a video of the requests workflow showing the design

Ok

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by Sahi1l-Kumar** [comment]
> Please fix the failing test

All tests are passing for me locally
image

**Comment by palisadoes** [comment]
Ask the `#talawa-admin` slack channel as to what could be wrong

**Comment by Sahi1l-Kumar** [comment]
@palisadoes Looks like the failed test is working fine now in the CI/CD

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by Sahi1l-Kumar** [comment]
> Please fix the conflicting files

done

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
