### PR TITLE
feat: Use of same Login/Register Component on User and Admin

### LINKED ISSUE #1377: Refactor: Use the same Login/Register Component on User and Admin
**Is your feature request related to a problem? Please describe.**
The user and admin currently have their respective Login and Register Components
The user portal's UI for Login and Register Component does not look similar to what we have in admin portal
This creates unnecessary dependency in our project where we always need to synchronise the UI and other elements for both the User portal and Admin portal.

**Describe the solution you'd like**
Keeping the logic intact for authentication of user and redirection to respective User Portal or Admin Panel, create a single Login/Register Component made from the base UI and code of Admin Panel's Login/Register Component.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
Follow this PR, as it implements tab based navigation b/w User Login and Admin Login (However the components are different and they should be one), make sure that you are also aware of the current changes that are being made to Login/Register Component.

https://github.com/PalisadoesFoundation/talawa-admin/pull/1371

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by rishabhbizzle**
**What kind of change does this PR introduce?**

This PR addresses the separate Login/Register components for Admin and User. In this we uses a single Login/Register Component made from the base UI and code of Admin Panel's Login/Register Component for both Admin & User page which helps in maintaining the DRY principle and also solves the issue of unnecessary dependency in the project where we always need to synchronise the UI and other elements for both the User portal and Admin portal.

**Issue Number:**

Fixes #1377 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
A video of demonstrating the whole login and register process for both admin & user:

https://github.com/PalisadoesFoundation/talawa-admin/assets/100997409/c2f60240-bbb3-41fb-a58c-683ce8602be5

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@rishabhbizzle Please fix the failing codecov tests.

**Comment by rishabhbizzle** [comment]
image

Please help me with this @rishav-jha-mech @aashimawadhwa.

**Comment by rishabhbizzle** [comment]
> @rishabhbizzle Please fix the failing codecov tests.

Done ✅  @Cioppolo14

**Comment by Cioppolo14** [comment]
@tasneemkoushar @beingnoble03 Please review this PR.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the conflicting files.

**Comment by rishabhbizzle** [comment]
> Please fix the conflicting files.

Done ✅ @noman2002

**Comment by palisadoes** [comment]
Please fix the failing tests
- Code coverage is declining. The tests for the files you have submitted are not complete

**Comment by rishabhbizzle** [comment]
These 2 lines are the reason coverage is declining slightly. Please help me with this @palisadoes @noman2002 
image

**Comment by palisadoes** [comment]
Search the code base for a similar construct and see how the coverage was handled in those cases

**Comment by beingnoble03** [comment]
@rishabhbizzle this can't be tested. So, for similar situations we have added `/* istanbul ignore next */` comment before the `if` branch to tackle the code coverage issue. You can observe that in the other files of the codebase.

**Comment by rishabhbizzle** [comment]
> @rishabhbizzle this can't be tested. So, for similar situations we have added `/* istanbul ignore next */` comment before the `if` branch to tackle the code coverage issue. You can observe that in the other files of the codebase.

Should I add this comment before the `try` line?? @beingnoble03

**Comment by beingnoble03** [comment]
I guess after that. Please check other files. I have used the same before.

**Comment by rishabhbizzle** [comment]
> I guess after that. Please check other files. I have used the same before.

I've added the comment but now the coverage is even lower than before even though the missing line count decreased from 2 to 1. I'm confused here please help @noman2002 @beingnoble03 
 
image

**Comment by rishav-jha-mech** [comment]
@rishabhbizzle 
In your PR, ensure that both the Admin and User tabs are exactly similar. Make the following changes: increase the height/padding of the text input boxes and buttons to match the Figma design. Also, ensure there is enough space between elements as they currently appear too clustered.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the conflicting files.

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by noman2002** [comment]
Closing due to inactivity.

**Pull request closed without merging**
