### PR TITLE
fix errorLink instance of Apllolink

### LINKED ISSUE #192: TS error on ApolloLink instance while running locally
This error did not pop up before. Now it shows this on running yarn serve:-

`Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.`

image
Line 31 of src/index.ts

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
Fixes #192 by removing errorLink to avoid AplloLink error Instance
(changes in other files rest are caused due to running yarn lint --fix)

### CODE REVIEW

**Comment by yasharth291** [comment]
fetch upstream @Devesh21700Kumar

**Comment by palisadoes** [comment]
@Devesh21700Kumar There have been significant changes to the code base in recent days. Please merge your code with the current `upstream/develop` branch, fix the conflicting files (if any), and push the result to your repo. The PR will be automatically updated.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar There have been significant changes to the code base in recent days. Please merge your code with the current `upstream/develop` branch, fix the conflicting files (if any), and push the result to your repo. The PR will be automatically updated.

Yep on it 
Thanks

**Comment by Devesh21700Kumar** [comment]
@yasharth291 @palisadoes  Done

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
