### PR TITLE
Refactor: src/screens/OrganizationTags/OrganizationTags.test.tsx from Jest to Vitest

### LINKED ISSUE #3071: Refactor: src/screens/OrganizationTags/OrganizationTags.test.tsx from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Rename the test file from having a `.test.*` suffix to a `.spec.*` suffix
3. Ensure all tests in the file pass after migration using `npm run test:vitest`
4. Maintain the test coverage for the file as 100% after migration
5. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
  https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
  https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by arpit-chakraborty**
**What kind of change does this PR introduce?**

Refactor: src/screens/OrganizationTags/OrganizationTags.test.tsx from Jest to Vitest

**Issue Number:**

Fixes #3071

**Did you add tests for your changes?**

yes

**Snapshot**

image

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Testing**
	- Migrated test suite from Jest to Vitest
	- Updated mocking strategies for `react-toastify` and `react-router-dom`

- **Refactor**
	- Updated mock constants to use dynamic organization ID references

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by palisadoes** [comment]
1. You don't have to close the PR
2. Just fix the file in your local repo, commit and push to your origin
3. The PR will automatically update

Reopening

**Comment by arpit-chakraborty** [comment]
i found the reason of conflict i will change the issue with a new commit

**Comment by palisadoes** [comment]
Please fix the new conflicting file

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
