### PR TITLE
Migrated src/components/AgendaItems/* from Jest to Vitest

### LINKED ISSUE #2792: Refactor `src/components/AgendaItems/*` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**

This files in this directory and all its subdirectories are currently tested using Jest. As part of our migration to Vitest, we need to refactor all these files' test cases to align with Vitest's syntax and features.

Files:

1. Refactor `src/components/AgendaItems/AgendaItemsContainer.test.tsx` from Jest to Vitest
2. Refactor `src/components/AgendaItems/AgendaItemsPreviewModal.test.tsx` from Jest to Vitest
3. Refactor `src/components/AgendaItems/AgendaItemsUpdateModal.test.tsx` from Jest to Vitest

**Acceptance Criteria**

For each `*.test.ts` and `*.test.tsx` file found under the parent:

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by mandeepnh5**
**What kind of change does this PR introduce?**
This PR will migrate the src/components/AgendaItems/* from Jest to Vitest.

**Issue Number:**
Fixes #2792 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
No

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **Tests**
	- Transitioned testing framework from Jest to Vitest across multiple test files.
	- Updated mock functions to utilize Vitest's mocking utilities.
	- Adjusted import statements to reflect the new testing framework.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please convert `src/components/AgendaItems/AgendaItemsPreviewModal.test.tsx`

**Comment by mandeepnh5** [comment]
> Please convert `src/components/AgendaItems/AgendaItemsPreviewModal.test.tsx`

@palisadoes 
image
its done right?

**Comment by palisadoes** [comment]
My mistake. This file is missing from the PR
- src/components/AgendaItems/AgendaItemsUpdateModal.test.tsx

**Comment by mandeepnh5** [comment]
> My mistake. This file is missing from the PR
> 
> * src/components/AgendaItems/AgendaItemsUpdateModal.test.tsx

@palisadoes there is a separate issue for that (#2491) which is assigned to me only I have created a separate pr for that

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Thanks

**Pull request merged**
