### PR TITLE
fixed #453: updated yarn.lock and package.JSON into the updated version

### LINKED ISSUE #453: Resolve dependency conflicts
**Describe the bug**
1. Run the commands
     ```
            npm i --package-lock-only
            npm audit
     ```
1. The output shows a large number of dependency conflicts

**To Reproduce**
See above

**Expected behavior**
1. These conflicts need to be resolved.
1.  Update the GitHub action for pull-requests so that they fail when future dependency conflicts are found.

**Actual behavior**

See above

**Screenshots**
This is sample output from the `npm i --package-lock-only` command
image

**Additional details**
See above

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
Updated a few packages in yarn.lock and package.JSON

**Issue Number:**

Fixes #453 

**Did you add tests for your changes?**
not required

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@palisadoes @xoldyckk WDYT now?

**Comment by palisadoes** [comment]
Please fix the failing formatting test

**Comment by aashimawadhwa** [comment]
> Please fix the failing formatting test

done @palisadoes

**Review by palisadoes — APPROVED** [review]

**Comment by xoldyckk** [comment]
@aashimawadhwa @palisadoes how exactly did this fix the problem?

**Comment by palisadoes** [comment]
- The GitHub Actions linting was failing because it was requesting this change. [src/state/helpers/Action.test.ts](https://github.com/PalisadoesFoundation/talawa-admin/pull/474/files#diff-82a7dc53798e6934bd8c6d1cc1404f578da4385f3cf8c4ce490b612f01cceaaa)
- It was not required in the linting on @aashimawadhwa 's system. I asked for the change and it passes.

**Comment by xoldyckk** [comment]
> * The GitHub Actions linting was failing because it was requesting this change. [src/state/helpers/Action.test.ts](https://github.com/PalisadoesFoundation/talawa-admin/pull/474/files#diff-82a7dc53798e6934bd8c6d1cc1404f578da4385f3cf8c4ce490b612f01cceaaa)
> * It was not required in the linting on @aashimawadhwa 's system. I asked for the change and it passes.
I meant how does this fix this issue? #453

**Comment by palisadoes** [comment]
@xoldyckk 
1. What do you propose? 
1. Should we also include fixing dependencies as part of a GSoC 2023 idea?

**Comment by aashimawadhwa** [comment]
@xoldyckk @palisadoes we cannot fix all the dependencies, a lot is there to revamp, yarn versions, packages (a few are even deprecated now) .. so as suggested I made a PR for all the updates I made. till we figure out how we will replace the deprecated dependencies, packages and scripts.

**Comment by xoldyckk** [comment]
> @xoldyckk @palisadoes we cannot fix all the dependencies, a lot is there to revamp, yarn versions, packages (a few are even deprecated now) .. so as suggested I made a PR for all the updates I made. till we figure out how we will replace the deprecated dependencies, packages and scripts.

There's only one update that I see and it is downgrading apollo-client version. Did you do this manually or some yarn/npm command?

**Comment by aashimawadhwa** [comment]
No I used NPM  and YARN upgrade commands and yes it fixed dependencies in yarn.lock file there were many changes. @xoldyckk

**Comment by xoldyckk** [comment]
> No I used NPM and YARN upgrade commands and yes it fixed dependencies in yarn.lock file there were many changes. @xoldyckk

EHHH. There's really no way to review the lock file tbh. Lock file only contains gibberish. I'll just approve it.

**Review by xoldyckk — APPROVED** [review]

**Comment by aashimawadhwa** [comment]
@palisadoes can you please merge this?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
