### PR TITLE
 Fixed: App can only be accessed on localhost

### LINKED ISSUE #1244: App can only be accessed on `localhost`
**Describe the bug**
1. The codebase hard codes localhost in many places
1. This means you cannot get Talawa-Admin to work while being accessed from a remote host without a proxy

**To Reproduce**

1. Install  Talawa-Admin on a remote system
1. Errors are seen when accessing the app directly from a remote host

**Expected behavior**
1. Access must be available from a remote host that is not located on `localhost`. This can only be truly tested when run from a completely different system.
1. The installation guide must show how to access Admin from a remote system
1. All hard coded instances of `localhost` must be replaced by configuration values in `.env`  and/or the browser URL where applicable

**Actual behavior**
- See screenshots

**Screenshots**

1. The `.env` file
image
1. Devtools output
image
1. The codebase hard codes localhost in many places
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

This pr fixes the problem of the portal not being able to be accessed if not on localhost.

**Issue Number:**

Fixes #1244 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

IMG_1534

**If relevant, did you update the documentation?**

Yes

**Summary**

This issue was caused mainly by the case in which the api url contains 'localhost'.

**Does this PR introduce a breaking change?**

No

**Other information**
There are 2 problems that occurred while working on the issue.
1. One problem occurring that needs to be fixed is the plugin store, which is coded incorrectly. in the src/components/AddOn/support/services/Plugin.helper.ts file.

```
    const result = await fetch(`http://localhost:${process.env.PORT}/store`);
    const result = await fetch(`http://localhost:3005/installed`);
```

are both fetching endpoints that do not exist and hence the addonstore component also does not work. 

2. The navbar button is not working on mobile devices.

Should I make issues for them?

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Olatade** [comment]
@aarishshahmohsin can you attempt to fix the failing tests?

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin can you attempt to fix the failing tests?

@Olatade the test failing, passes locally 
image

**Comment by Cioppolo14** [comment]
@aarishshahmohsin Please resolve the test application check.

**Comment by aarishshahmohsin** [comment]
@Olatade @Cioppolo14 I've done the changes

**Comment by Cioppolo14** [comment]
@anwersayeed @tasneemkoushar Can you review this PR?

**Comment by palisadoes** [comment]
1. This PR needs to be closed. The source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
1. Please create a new branch in your local repository with the changes
2. Make sure the branch name is named differently from the target branch (`develop`)
3. Resubmit your PR

You will see that other PRs are using non-develop branch names for this reason

**Comment by aarishshahmohsin** [comment]
> 1. This PR needs to be closed. The source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:
>        
>        1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
> 
>     2. Please create a new branch in your local repository with the changes
> 
>     3. Make sure the branch name is named differently from the target branch (`develop`)
> 
>     4. Resubmit your PR
> 
> 
> You will see that other PRs are using non-develop branch names for this reason

@palisadoes I have made the new PR. [link](https://github.com/PalisadoesFoundation/talawa-admin/pull/1697)

**Pull request closed without merging**
