### PR TITLE
fix: fixed hard-codes localhost

### LINKED ISSUE #1244: App can only be accessed on `localhost`
**Describe the bug**
1. The codebase hard codes localhost in many places
1. This means you cannot get Talawa-Admin to work while being accessed from a remote host without a proxy

**To Reproduce**

1. Install  Talawa-Admin on a remote system
1. Errors are seen when accessing the app directly from a remote host

**Expected behavior**
1. Access must be available from a remote host that is not located on `localhost`. This can only be truly tested when run from a completely different system.
1. The installation guide must show how to access Admin from a remote system
1. All hard coded instances of `localhost` must be replaced by configuration values in `.env`  and/or the browser URL where applicable

**Actual behavior**
- See screenshots

**Screenshots**

1. The `.env` file
image
1. Devtools output
image
1. The codebase hard codes localhost in many places
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by 1010varun**
**What kind of change does this PR introduce?**
this PR will remove all the hard-codes localhost present in source code with the necessary import from .env

**Issue Number:** 

Fixes #1244 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by 1010varun** [comment]
hey @palisadoes,
kindly review my PR.

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by 1010varun** [comment]
Hey @palisadoes, I have tested with localhost itself, but it is showing the same error.

**Comment by palisadoes** [comment]
1. The failing tests point to a small number of files that are impacted by your change.
2. Please take a look at them and resolve the failure

**Comment by 1010varun** [comment]
Hey @palisadoes,
The same test case is failing, runs perfectly on my local env
image

**Comment by palisadoes** [comment]
1. Make your local environment match that in our tests to verify operation. You can find details here
    - https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml
1. Please fix the conflicting files

**Comment by palisadoes** [comment]
Please work with the assigned reviewers to verify operation, review your code and approve.

**Comment by 1010varun** [comment]
@EshaanAgg @SiddheshKukade please review my PR #1404

**Comment by palisadoes** [comment]
There has been an increasing trend with PRs where they are closed without explanation even when they are made against the develop branch as expected. 

This is a real tax on all our time. 

1) The discussion history gets reset with the new PR
2) We have to find new assigned reviewers
3) Tracking becomes harder
4) The reviewers work is easier to get lost.

We have made many warnings about this with little progress.

With immediate effect we will unassign assignees whenever this happens against the develop branch.

I don't want to speculate on the reason, but we cannot let this continue.

**Comment by 1010varun** [comment]
yes sir I am

**Comment by 1010varun** [comment]
I will raise a new PR closing this one.

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories.

**Pull request closed without merging**
