### PR TITLE
Documentation: Tsdoc comments in whole codebase

### LINKED ISSUE #2114: Feature Request: Write tsdoc comments in complete codebase
**Is your feature request related to a problem? Please describe.**
write tsdoc comments and meaningful comments to get better understanding

**Additional context**
Part of Internship Phase-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2114 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by gautam-divyanshu** [comment]
@palisadoes I wrote comments in those files that have eslint errors already because of `any`. This is causing the **test application workflow** to get skipped.

**Comment by gautam-divyanshu** [comment]
I disabled them because I couldn't commit changes without doing so.

**Comment by gautam-divyanshu** [comment]
I won't be able to remove `any` type because there may not be other options; that's why they are there.

**Comment by gautam-divyanshu** [comment]
### **test cases in develop branch** 

image

### **in my pr**
image

**Comment by gautam-divyanshu** [comment]
@palisadoes So what should I do?

**Comment by gautam-divyanshu** [comment]
@palisadoes any suggestions?

**Comment by palisadoes** [comment]
We merged some updated packages recently. That may be the cause.
- https://github.com/PalisadoesFoundation/talawa-admin/pulls?q=is%3Apr+is%3Aclosed

**Comment by palisadoes** [comment]
The error explains what is wrong. We need to make sure the linting in those files is fixed.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/10081496851/job/27873822034?pr=2113

**Comment by gautam-divyanshu** [comment]
@palisadoes  I can try to fix, but mostly can't be fixed

**Comment by gautam-divyanshu** [comment]
I need to disable some linting errors

**Comment by palisadoes** [comment]
Do what you can. We shouldn't disable linting. I'll see if I can force merge when you are done.

**Comment by palisadoes** [comment]
Please fix the conflicting files.

**Comment by gautam-divyanshu** [comment]
@palisadoes we can merge this PR now.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
