### PR TITLE
Implementing day view in calendar of event screen for both admin and user portal

### LINKED ISSUE #1422: Implement day view in calendar of event screen for both admin and user portal
**Is your feature request related to a problem? Please describe.**
 Yes, there is a need for a multi-calendar view in both the admin and user portals, necessitating a solution to enhance the calendar functionality.

**Describe the solution you'd like**
 Implementation of a day view for the calendar, similar to the layout observed in Google Calendar. This would involve displaying events on a daily basis for improved user experience and functionality.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
To address this requirement, we recommend incorporating a day view feature into the calendar, inspired by the user-friendly design of Google Calendar. This would involve presenting events in a clear and organized manner on a day-to-day basis.

**Additional context**
Screenshot 2024-01-14 at 4 11 20 AM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by karthxk07**
**What kind of change does this PR introduce?**

Feature , Implements day view in calendar of event screen for both admin and user portal.

**Issue Number:**

Fixes #1422 

**Did you add tests for your changes?**

No. No new file added, tests already present.

**Snapshots/Videos:**

[Screencast from 2024-01-18 20-39-24.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/76a51178-64fe-4a0d-b194-3b05baefe720)

**If relevant, did you update the documentation?**

No, no documentation needed.

**Summary**

To fulfill the need for a multi-calendar view in both the admin and user portals, necessitating a solution to enhance the calendar functionality.
Implemented a day view for the calendar, similar to the layout observed in Google Calendar. This would involve displaying events on a daily basis for improved user experience and functionality.

**Does this PR introduce a breaking change?**

No, this PR does not introduce breaking changes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by karthxk07** [comment]
@Cioppolo14 can i get this reviewed please.

**Comment by aashimawadhwa** [comment]
can you change the calendar lines to gray that is used in the code and not black? and how does it looks in the mobile view? @karthxk07

**Comment by karthxk07** [comment]
@aashimawadhwa I have changed the borders to gray and pushed the commit 

[Screencast from 2024-01-19 16-55-02.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/c2a2813e-733d-44f4-94a6-e4a929b8f7a7)

**Comment by aashimawadhwa** [comment]
I have few more remarks for the UI changes, if you could implement those too?
- change the color of the time as well, please understand we have not used black color in admin that much.
- reduce the spacing between the rows
-  add am and pm instead of using 24 hrs format
- reduce the size of font used for time
- show a bar to indicate the current time 

Screenshot 2024-01-20 at 6 19 07 PM

Note: please try to replicate design from goggle calendar. we are really working on fine details for UI along with functionalities.

**Comment by karthxk07** [comment]
@aashimawadhwa Ok, I will be working on that

**Comment by noman2002** [comment]
@karthxk07 Please write the tests for the lines you have added, its dropping significantly.

**Comment by karthxk07** [comment]
@noman2002 ok

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please write the test for the lines you have added and get the coverage of modified lines to 100%.

**Comment by karthxk07** [comment]
@noman2002 i am almost done with the changes , i just need to add all the tests. I will push the commits

**Comment by karthxk07** [comment]
@aashimawadhwa I am done adding the requested changes. Does this look fine?

[Screencast from 2024-01-28 12-19-48.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/b19b353e-c517-4b07-821c-5a271c4fbd7a)

**Comment by karthxk07** [comment]
@noman2002 I have completed adding the tests too , :relaxed: can I get the pull request reviewed please  ?

**Comment by palisadoes** [comment]
Please fix the failing tests
1. Introspection

**Comment by karthxk07** [comment]
@palisadoes on it sir :+1: 

> Please fix the failing tests
> 
> 1. Introspection

**Comment by palisadoes** [comment]
Please fix the failing tests
- Code coverage is declining. The tests for the files you have submitted are not complete

**Comment by karthxk07** [comment]
@palisadoes Sir added tests for uncovered lines

**Comment by palisadoes** [comment]
Please fix the introspection error. New API code was pushed and Admin needs to be in sync.

**Comment by palisadoes** [comment]
Reimport the API data

**Review by noman2002 — APPROVED** [review]
Looks fine to me.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
