### PR TITLE
Issue 2016 resolved

### PR DESCRIPTION
**Pull request by Spoorthy1423**
# #2016

-Upgraded typescript package from 4.9.5 to 5.4.5 

**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **Chores**
	- Updated the TypeScript dependency to version 5.4.5, enhancing compatibility and bringing potential improvements and bug fixes to the development environment.

### CODE REVIEW

**Comment by varshith257** [comment]
@Spoorthy1423 I think your local branch is upstream with main. Change it to develop and raise a PR against develop branch here too.

And to fix #2016 you need to update some parts of codebase or dependencies which made depandabot fail while upgrading this package to . You can refer the changes in 5.4.x version docs of Typescript

**Comment by varshith257** [comment]
@Spoorthy1423 Closing this PR for above reasons and submit a new PR with above suggestions

**Comment by Spoorthy1423** [comment]
I would like to work on this issue further, please assign me this issue ..

**Comment by varshith257** [comment]
Assigned it. Go-ahead

**Pull request closed without merging**
