### PR TITLE
BugFix - Reduce Overhead in Organizations Member Search Feature

### LINKED ISSUE #1743: Reduce Overhead in Organizations Member Search Feature
**Is your feature request related to a problem? Please describe.**
Currently, the API call for searching members is triggered even when the input string is empty, leading to unnecessary overhead.

image

**Describe the solution you'd like**
To optimize this process, I suggest that the API call should only be made when the input string is not empty. Specifically, when the user presses the 'Backspace' key and the input string becomes empty, the API call should then be triggered.

image

**Additional context**

https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/c290a455-ed00-4451-99e1-dcc4d529edc7

I have worked on this issue, please assign this to me.
 
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1743 

**Did you add tests for your changes?**
No

**If relevant, did you update the documentation?**

**Summary**

API call is only made when the input string is not empty. Specifically, when the user presses the 'Backspace' key and the input string becomes empty, the API call should then be triggered.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by krishna619** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/pull/1744/files#diff-391c0bff9c5c1715af4a42c44374388d3bdb3e6d814d76858c2701ced7f84ae8

**Comment by Olatade** [comment]
@krishna619 can you fix the failing tests

**Comment by krishna619** [comment]
@Olatade Hi, I have fixed the coverage.
can you please check?

**Comment by Olatade** [comment]
@krishna619 you still have one test failing 
image

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
