### PR TITLE
Added the EventRegistrants Tab under Events in Admin

### LINKED ISSUE #1750: ADMIN REDESIGN: redesign the Event Management's Registrant tab for the talawa Admin portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management Registrant Tab for the talawa Admin portal
- we want to club show registrant and check-ins registrant in a single parent tab i.e registrant
- The show registrant is ready for now please leave check-in registrant button non functional for now.
- After clicking on the add registrant button , the registrant should dissapper from this screen after a react toast with success message.

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:
Screenshot 2024-03-20 at 12 22 18 AM

Desired Result:
Screenshot 2024-03-20 at 12 17 14 AM

Related Issues: 

#1748

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by syedali237**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #1750 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/user-attachments/assets/71b69dac-5f76-4c1d-8f10-8452b5d3c0a4

**If relevant, did you update the documentation?**

No

**Summary**
 
Added the Event Registrants Tab under Admin. Admin can now add registrants for an event and Check-In Registrants.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `EventRegistrants` component for managing and displaying event registrant information.
	- Added a new GraphQL query, `EVENT_REGISTRANTS`, to retrieve event attendees.
	- New CSS styles for event registrants to enhance UI presentation.

- **Bug Fixes**
	- Updated the button text in tests and components for consistency.

- **Tests**
	- Enhanced test coverage for the `AttendanceStatisticsModal` and `EventRegistrants` components.
	- Created a new test file for the `EventRegistrants` component.

- **Chores**
	- Updated various dependencies in the project configuration.

### CODE REVIEW

**Comment by syedali237** [comment]
@duplixx Do I need to raise this PR with develop-postgres?

**Comment by syedali237** [comment]
@duplixx should I close this PR then?

**Comment by duplixx** [comment]
@syedali237 switch to `develop-postgres` branch and pull changes from it

**Comment by palisadoes** [comment]
This PR has too many submitted files. 

Please ensure the following:

1. Fetch the latest upstream/develop-postgres files
2. Make your PR modifications based on the local copy of this `develop-postgres` branch
3. Submit your PRs against our `develop-postgres` branch.
4. Your source branch in your local repository must not be the same as the target branch

Closing

**Pull request closed without merging**
