### PR TITLE
[Fixes] Code Coverage: Create tests for store.tsx 

### LINKED ISSUE #277: Code Coverage: Create tests for store.ts
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/state/store.ts`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/state/store.test.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/state/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
What kind of change does this PR introduce?
Added Testcases for src/state/index.ts file

Issue Number:
#277 

Fixes #277 

Did you add tests for your changes?
Yes I have added a testfile

Summary
I have added a store.test.tsx file required for the issue #277  for Gsoc2022

Does this PR introduce a breaking change?
No

**SnapShots**

image

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Please let me know if I can improve and also the `state.text.tsx` file is added on the 3rd commit the first 2 commits are from another pull request #296

**Comment by palisadoes** [comment]
You have submitted a PR without the issue being assigned. I just assigned the issue and realized the PR was in the queue for some hours. Please follow the process. We need to make everyone have a chance to participate. If you do this in future, the PR will be closed.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please get the coverage up to 100%. At that point the PR will be reviewed.

**Comment by SiddheshKukade** [comment]
> You have submitted a PR without the issue being assigned. I just assigned the issue and realized the PR was in the queue for some hours. Please follow the process. We need to make everyone have a chance to participate. If you do this in the future, the PR will be closed.

I apologize, sir , this will not be repeated

**Comment by yasharth291** [comment]
there is no increase in the codebase so the pr makes no sense i guess

**Comment by SiddheshKukade** [comment]
> there is no increase in the codebase so the pr makes no sense i guess
wait i am improving the code

**Comment by SiddheshKukade** [comment]
@palisadoes  @yasharth291  I have a simple doubt 
On my machine when I run 
```bash 
 yarn test --watchAll=false --coverage

```
I get the following coverage 
100% coverage 
image

But in this Pull request the CODECOV shows following]
40% coverage only
image


please correct me If I'm going wrong at something

**Comment by yasharth291** [comment]
we have re-run the codecov on this you can close this one and open it again

**Comment by SiddheshKukade** [comment]
ok @yasharth291 sir

**Pull request closed without merging**
