### PR TITLE
[fix] : Organisation icon displaying fixed

### LINKED ISSUE #375: Organisation icon not visible
In the homepage of the admin portal, the icons of the organisations aren't visible. Screenshot attached below.

### Steps to reproduce the behaviour:
<ol>
<li>Open the Admin Portal Homepage</li>
<li>Create a new organisation</li>
<li>The icon you uploaded for the organisation won't be visible, as shown in the screenshot below</li>
</ol>

image

**Expected behaviour**
Icons of the organisation should be visible for better user experience.

**Actual behaviour**
Currently, any of the organisations icons aren't visible.

**Additional information**
I even tried uploading images with the 200x100 height width requirements. Still same issue persists.

### PR DESCRIPTION
**Pull request by rv602**
On the admin homepage, the organisation icons weren’t being rendered before. This PR fixes that issue.

### Issue type : -
bug

### Issue number : -
Fixes #375

### Fixes : -
The organisation icons are now being rendered at the admin homepage.

### Tests : -
No
I haven’t added test cases for this issue, as it was just an error in the post request while sending the image

#### before : -

image

#### now : -

image

### Summary

The icons of the organisation's image weren’t being rendered in the admin homepage. This PR fixes that issue.
Motivation of solving this issue : - When the icons weren't rendered in the admin homepage, it looks broken with the placeholder image. The site looks more appealing and professional with the icons being rendered successfully.

Since the backend of the talawa-admin is the talawa-api repository, I have opened an issue there as well (link attached below), I will make a PR there once I'm officially assigned. Both PRs must be merged for the functionality to work.
https://github.com/PalisadoesFoundation/talawa-api/issues/868

### Does this PR introduce a breaking change?
No.
This PR does not introduce any breaking change. Although there is a minor problem. When we create a new organisation, there is a text box that asks for tags you would like to add to the organisation. But that breaks the code with an error and the organisation is not created. I commented out that part and made the necessary changes as the 'tags not defined' error has already been opened by another contributor as an issue (link attached below), hence I haven’t touched that part of the code.
Issue link : - https://github.com/PalisadoesFoundation/talawa-api/issues/853

The input text of the tags attribute can be commented out for the time being to further develop the application until it's issue is solved and closed 
File from where tags input field is to be commented : (src/screens/OrgList.tsx)

### Other information : -
There were few errors in the backend (talawa-api repository) as well that led to this error. I have raised an issue regarding the same in that repository as well (link attached below) : -
https://github.com/PalisadoesFoundation/talawa-api/issues/868

Once I will be assigned to the above issue, I will create a PR there as well.
For the functionality to work as desired, both the PRs must be merged.

### Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@rv602 Thanks for the work and the vigilance.

1. Please add tests for these changes.
2. Make sure the code coverage for the files you modify is 100%
3. We need to make sure that this error doesn't repeat itself.

**Comment by palisadoes** [comment]
Please fix the failing tests, it may have something to do with your updates
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/3950662675/jobs/6764183016#step:4:1137

**Comment by rv602** [comment]
alright, I'll look into it

**Comment by palisadoes** [comment]
Please fix the failing test.

**Comment by palisadoes** [comment]
Kevonia, Mikey please review this.

**Comment by SiddheshKukade** [comment]
I see changes in `yarn.lock` but there are no changes in `package.json` . This seems a bit different. I'd suggest to test the changes with existing lockfile instead of modifying it without package updations

**Comment by rv602** [comment]
alright, I'll check it

**Comment by rv602** [comment]
@SiddheshKukade I checked the changes in the original and the modified yarn.lock file.

It is not changing the versions of any packages, it is just optimising the yarn.lock file.

I also verified it in the official Github repository of yarn. The same is thing is mentioned in the comment of an issue in yarn's repository (link of that issue attached below) : -
https://github.com/yarnpkg/yarn/issues/4379

**Review by SiddheshKukade — CHANGES_REQUESTED** [review]
`LoginPage.tsx` has some changes not related to this issue. remove them. IDK why the test for `LoginPage` is also changed.

**Comment by rv602** [comment]
@SiddheshKukade I have removed the changes from ```Login.tsx```
Regarding the test of ```Login.tsx```, I had changed it as it had cleared some warnings while running ```npm run test```.
I can undo that as well if needed and make a commit accordingly.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by Kevoniat — COMMENTED** [review]
Are the tags loading  here since there were removed in the mutations file?

**Comment by rv602** [comment]
@Kevoniat actually there was an issue with the tags in the backend, due to which organisation creation wasn’t possible before. Hence I had removed it.
But now that has been resolved in another issue, so I'll pull all the changes, add the ```tags``` and make a new commit shortly.

**Comment by palisadoes** [comment]
@rv602 Please fix the failing tests.

**Comment by noman2002** [comment]
@rv602 any update on this one ?

**Comment by rv602** [comment]
@noman2002 sorry for the delay.
Right now my University end sem exams are ongoing so there is a slight delay from my side due to the same.
I will make a new commit with the necessary changes shortly.

**Comment by noman2002** [comment]
Its been more than a month on this PR. closing this for now. Submit a fresh PR once completed. Or unassign the issue and give everyone a chance.

**Pull request closed without merging**
