### PR TITLE
Redesigned the Event Details Modal for the Talwa User and Admin portal

### LINKED ISSUE #1610: USER REDESIGN: redesign the Event Details Modal for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the event details modal for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation :
Screenshot 2024-02-21 at 1 38 17 AM

Desired Result:
Screenshot 2024-02-21 at 1 39 22 AM
Screenshot 2024-02-21 at 1 39 43 AM

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sahi1l-Kumar**
**What kind of change does this PR introduce?**
A feature.

**Issue Number:**

Fixes #1610 

**Did you add tests for your changes?**
Yes.

**Snapshots/Videos:**

Admin:
image

User:
image

**If relevant, did you update the documentation?**

**Summary**
In the following PR, I have redesigned the Event Details Modal according to the figma file [here](https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1). 

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by Sahi1l-Kumar** [comment]
With the current logic in the API, only the Event Admin is able to Update the Event but the same is not true for deleting the events. Shouldn't Admins and SuperAdmins be able to Update Events?

**Comment by palisadoes** [comment]
> With the current logic in the API, only the Event Admin is able to Update the Event but the same is not true for deleting the events. Shouldn't Admins and SuperAdmins be able to Update Events?

Yes,

1. We need delete capability for the event admin / creator
2. We also need the ability for admins and super admins to update events created by all members

Please open issues in the API to implement this. The original design was for this to be implemented.

**Comment by Sahi1l-Kumar** [comment]
This should be ready for review.
PS: When a Creator/ Event Admin is a USER and tries to open event dashboard they are directed to the 404 page. This should probably be fixed in another issue as it would require changing secure routing.

**Comment by palisadoes** [comment]
How are you preventing others from viewing the dashboard?

Is the event details button hidden, greyed out, or is there an error message? It'll be best not to show it to reduce confusion.

**Comment by Sahi1l-Kumar** [comment]
The Users who are not Creator/Admin/SuperAdmin only gets the option to register for the event.

Show Event Dashboard button is present only for the creator of the event, admin of the organization, and superadmin

**Comment by palisadoes** [comment]
> This should be ready for review.
> PS: When a Creator/ Event Admin is a USER and tries to open event dashboard they are directed to the 404 page. This should probably be fixed in another issue as it would require changing secure routing.


We allow regular users to create events in Mobile and there is a GSoC idea for event parity. 

After merging this PR please create an issue to allow that. 

Does this mean that the user portal calendar is read only for regular users? I've never verified it as I thought it was OK

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please let me know. We need to fix this behavior

**Comment by Sahi1l-Kumar** [comment]
@palisadoes What I meant was regular users can create event. But when they try to navigate to the event dashboard then they see the 404 page.

**Comment by palisadoes** [comment]
Yes, that needs to be fixed

**Pull request merged**
