### PR TITLE
Updated the CRUD screens for organizations, for implementation of Address param from Location.

### PR DESCRIPTION
**Pull request by Anubhav-2003**
**What kind of change does this PR introduce?**
A feature

**Issue Number:**
#1457 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Screenshot from 2024-01-24 18-43-37
Screenshot from 2024-01-23 19-18-06
Screenshot from 2024-01-23 18-54-21
Screenshot from 2024-01-23 18-42-52
Screenshot from 2024-01-23 14-18-24
Screenshot from 2024-01-23 14-18-00

**If relevant, did you update the documentation?**
No.

**Summary**

This PR changes the CRUD screens for the organizations in the admin portal, to successfully implement the migration from location param to address in the Talawa-API.

**Does this PR introduce a breaking change?**
Yes. This PR must be merged along with the PR for the Talawa-API.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I have created both the PR'S for the ADMIN portal, and the Updated PR for the Talawa-API simultaneously as previously discussed. Both the PR'S must be merged together for the successful implementation of the feature. 

Thank You.

**Comment by Cioppolo14** [comment]
@Anubhav-2003 Please fix the failing tests, or document here why the failed tests are acceptable.  Do not worry about the introspection test failing.

**Comment by palisadoes** [comment]
Please add country code validation

**Comment by Cioppolo14** [comment]
@Anubhav-2003 Please fix the failing codecov tests.

**Comment by Anubhav-2003** [comment]
@Cioppolo14 @palisadoes 
Respected Ma'am/sir, 
Please review, I think the PR is good to merge. 

Thank you.

**Review by noman2002 — COMMENTED** [review]
Changes looks fine but in the last screenshot are 2 location icons, there should be only one. And Also please explain what is sorting code?

**Comment by palisadoes** [comment]
Also fix the failing tests. Introspection needs to pass. You have added coffee that is causing it to fail

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please fix the failing tests. 1. Introspection needs to pass. You have added coffee that is causing it to fail

**Review by palisadoes — APPROVED** [review]

**Comment by Anubhav-2003** [comment]
> Changes looks fine but in the last screenshot are 2 location icons, there should be only one. And Also please explain what is sorting code?

Respected sir, Actually some places have sorting codes, but it is optional, and not mandatory. Thank You.

**Pull request merged**
