### PR TITLE
Events screen and Post Comment Modal for Talawa-user-portal 

### LINKED ISSUE #964: Add Events Screen and Post Comment Modal on user portal
**Is your feature request related to a problem? Please describe.**
Add Events Screen and Post Comment Modal on user portal.

**Additional context**
GSoC'23 follow up issue

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by beingnoble03**
**What kind of change does this PR introduce?**
Adds Events screen for Talawa-user-portal.
Fixes #964 

**Did you add tests for your changes?**
No.

**Snapshots/Videos:**
Screenshot 2023-08-26 at 3 15 25 AM
Screenshot 2023-08-26 at 3 15 39 AM
Screenshot 2023-08-26 at 3 15 52 AM
Screenshot 2023-09-02 at 12 39 38 AM

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by beingnoble03** [comment]
Writing tests is the next target.

**Comment by beingnoble03** [comment]
Note: This events screen PR doesn't contain calendar view. Will add it in the next PR.

**Comment by beingnoble03** [comment]
Writing tests is the next target.

**Comment by palisadoes** [comment]
@beingnoble03 Please create an issue for this PR as request in the CONTRIBUTING.md document

**Comment by palisadoes** [comment]
@evasharma12 @Sagar2366 Please review

**Comment by beingnoble03** [comment]
I had my mid-sems previous week. I'll fix it today.

**Comment by beingnoble03** [comment]
I've also updated `typedoc-plugin-markdown` to the latest version.

**Comment by palisadoes** [comment]
@evasharma12 @Sagar2366 Please review.

**Review by evasharma12 — APPROVED** [review]

**Pull request merged**
