### PR TITLE
MVP Talawa Admin : Hiding Chat Feature from Talawa Web App

### LINKED ISSUE #1069: MVP - Talawa Admin
We need to have an Talawa MVP by the end of the year. The MVP will be the master branch. To do this we will need to remove features that either don’t work or have insufficient functionality. 

The features to remove include:

1. Links to chat
1. Notifications
1. Dynamic linking

Other

1. You need to work on removing these functionalities from this repo and work with the contributors below to make sure the correct functionality occurs in the other repos.
1. Documentation related to configuring these features needs to be removed as they will be no longer valid.
1. Test code coverage needs to be maintained. Coverage for the PR patches needs to be 100%

The plan is to:

- remove these features from the develop branch by commenting out the code.
- merge the develop branch not containing these features into our master branch.
- make the master branch the default

Please work with @Ayush0Chaudhary (Talawa impacts), @EshaanAgg & @xoldyckk (Talawa-API impacts) @beingnoble03 (Talawa-Admin impacts). Ask to be assigned this task by them.

Issues related to this one include:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1069
- https://github.com/PalisadoesFoundation/talawa-api/issues/1427
- https://github.com/PalisadoesFoundation/talawa/issues/2108

### PR DESCRIPTION
**Pull request by duplixx**
What kind of change does this PR introduce?

A feature request.

Issue Number:

Fixes #1069

Did you add tests for your changes?

No

Snapshots/Videos:

If relevant, did you update the documentation?

Summary

Added the talawa-admin MVP changes.

Does this PR introduce a breaking change?

Other information

Have you read the contributing guide?

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@duplixx  can you please fix the failing tests.

**Comment by duplixx** [comment]
@aashimawadhwa i have added the required changes..

**Comment by aashimawadhwa** [comment]
LGTM @beingnoble03 @SiddheshKukade

**Review by aashimawadhwa — APPROVED** [review]

**Comment by palisadoes** [comment]
1. We'll need approvals from more contributors for this
2. We'll also need to discuss how to migrate this repo to default to the master branch.

**Review by SiddheshKukade — COMMENTED** [review]
@duplixx  I couldn't figure out what have you changed here. You've commented some chat import lines. Not sure what are you trying to fix here.

**Comment by duplixx** [comment]
Hey @SiddheshKukade ,

I've followed this plan as mentioned in issue :

1. Remove the specified features from the develop branch by commenting out the code.
2. Merge the develop branch (without these features) into our master branch.
3. Set the master branch as the default.

I have commented out the unnecessary feature, and I'm planning to merge the develop branch into master. I would appreciate your suggestions on this.

**Comment by SiddheshKukade** [comment]
Then make sure to update the description accordingly.

**Comment by duplixx** [comment]
thanks @SiddheshKukade for feedback i wanted to ask how should i proceed further in this issue ,should i proceed merging the develop branch to master ??

**Review by SiddheshKukade — DISMISSED** [review]
Looks fine to me.

**Comment by noman2002** [comment]
@duplixx Please fix the conflicting files. So that we can merge this.

**Comment by duplixx** [comment]
> @duplixx Please fix the conflicting files. So that we can merge this.

Done.. @noman2002

**Comment by palisadoes** [comment]
1. This will be merged into `develop` when you have made the requested updates, and get the approvals.
2. We'll work with the contributors to merge into master and modify all the GitHub actions that are branch dependent. @aashimawadhwa can you manage this item?

**Review by beingnoble03 — APPROVED** [review]
LGTM.

**Review by noman2002 — APPROVED** [review]

**Pull request merged**
