### PR TITLE
fixed the Users/Users.tsx for develop-userTypeFix

### LINKED ISSUE #1684: Fix the `User/Users.tx` Screen in the `develop-userTypeFix` branch
### NOTE

1. This issue will require close coordination with persons assigned issues in the reference section.
1. This work will need to be done on the `develop-userTypeFix` branch

**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.
1. We have created the `develop-userTypeFix` branch from the `develop` branch to fix this.
     1. All remedial work is being done on the `develop-userTypeFix` branch 
     2. When the development work is complete on the `develop-userTypeFix` branch it will be merged back into `develop`
     1. This is planned to be completed shortly
1. This issue was created to apply the desired functionality for the screen in this issue's title
    
This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
1. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
1. All other `userType`s would be on a per organization basis
1. This has already been implemented in the `develop-userTypeFix` branch of Admin and the API. Your role will be to apply the change to the screen in this issue's title to the `develop-userTypeFix` code.
4. **The new functionality of `userType` must be unchanged.**
5. No other features must be affected
6. All tests must be valid and pass

**Screenshots**

The current API schema:

image

The new API schema:

image

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile
1. Research these issues for context with the new `userType` functionality:

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa/issues/2373
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1682
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1683
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1684
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1685
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1686

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kanhaiya04**
**What kind of change does this PR introduce?**

Refactoring

**Issue Number:**

Fixes #1684 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/fc33a8ef-3842-4110-b87f-7948eeba40a0

**If relevant, did you update the documentation?**

**Summary**
Fixed the `Users/Users.tsx` screen to support `develop-userTypeFix` branch of talawa API

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by kanhaiya04** [comment]
@palisadoes The First test failed because more than `600 lines` were changed, the second one because this PR is for the `develop-userType` branch not `develop` and the third one failed has nothing to do with this PR.

**Comment by adi790uu** [comment]
@palisadoes this can be merged.

**Comment by palisadoes** [comment]
Please refactor the file that is to long

**Comment by kanhaiya04** [comment]
@palisadoes Fixed the failing test.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
