### PR TITLE
Add Support for Event Invitees and Registrants

### LINKED ISSUE #1606: Feature Request :  Add Support for Event Invitees and Registrants
**Is your feature request related to a problem? Please describe.**
- Our current process lacks the capability to invite users to events.
- Currently, only users can register and check in to events.
- There is a need to update the registration and check-in process to include user invitation functionality.
- The UI redesign aims to enhance the user experience and streamline event management.

**Describe the solution you'd like**
#### Admin
- Implement a user-friendly interface that seamlessly integrates with the updated Talawa API. Ensure that the interface follows modern design principles and provides a smooth user experience.

- Design a feature-rich UI specifically tailored for Admin and SuperAdmin users. This UI should empower them to perform essential tasks such as inviting, registering, and checking in individuals to events seamlessly.

- Ensure the UI offers clear navigation and intuitive controls for all key functionalities, including inviting and registering users, as well as facilitating event check-ins. 

- Once all components are in place and thoroughly tested, ensure that Admin and SuperAdmin users have the necessary privileges to invite, register, and check in users to events efficiently. 

#### Other

- All tests for this functionality update must be valid
- No other functionality must be altered

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
- Please refer to below issue in talawa-api for more details.
- https://github.com/PalisadoesFoundation/talawa-api/issues/1644

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AdityaRaimec22**
**What kind of change does this PR introduce?**
https://github.com/PalisadoesFoundation/talawa-admin/issues/1606

**Issue Number:**

Fixes #1606

**Did you add tests for your changes?**
Still working on them

**Snapshots/Videos:**
None

**If relevant, did you update the documentation?**
Not relevant

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Olatade** [comment]
@AdityaRaimec22 please fix the conflicts

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 It also doesn't look like all checks ran.

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22 It also doesn't look like all checks ran.

Yes, because of the conflicts once they are removed the tests will run, Currently I am writing tests of this PR, I will push them ASAP and then I will remove the conflicts.

**Comment by palisadoes** [comment]
Please fix the merge conflicts

**Comment by pranshugupta54** [comment]
Hey @AdityaRaimec22, are you facing any issues?

**Comment by Cioppolo14** [comment]
@AdityaRaimec22 Are you still working on this?

**Comment by AdityaRaimec22** [comment]
> @AdityaRaimec22 Are you still working on this?

All the changes are made and PR is created but some of the tests are failing which the PR will pass soon once my exams are over. Thanks.

**Comment by palisadoes** [comment]
Will you be able to revisit this?

**Comment by AdityaRaimec22** [comment]
> Will you be able to revisit this?

Yes, My exams are just over and now I will be able to contribute regularly so I will finish this.

**Pull request closed without merging**
