### PR TITLE
fix(933): refetching in /orgpost after deleting a post

### LINKED ISSUE #933: Improve data update mechanism throughout the application after query/mutation
**Describe the bug**
Currently, the code is using `window.location.reload()` to refresh the page after a query. Hard refreshing does not give the best user experience and is quite annoying.

**To Reproduce**

1. Navigate to the 'orgpost' route
2. Click 'Delete on a Post' (error exists in multiple places in the application)

**Expected behavior**
The data should be refetch the data and update the data instantly without having to reload the entire page. 

**Actual behavior**
The entire page is reloaded creating a bad user experience

**Screenshots**
N/A

### PR DESCRIPTION
**Pull request by ThePiyushAggarwal**
In the /orgpost page, posts are listed but after deleting a post, the page was being reloaded to fetch the latest posts. This was a bad UX.
I have made use of `refetchQueries` method from the hooks provided by `@apollo/client`, it will delete the post and fetch latest data and then complete the process. This actually makes it a lot faster than before.

**What kind of change does this PR introduce?**
Fix

**Issue Number:**

Fixes #933

**Did you add tests for your changes?**
No. Not required.

**Snapshots/Videos:**

[talawa-delete-post-refetching.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/27003616/a3ebf32c-97dc-48c6-ba5c-17429431fd54)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@ThePiyushAggarwal Please write the appropriate tests to verify your work

**Comment by ThePiyushAggarwal** [comment]
Ok. I will write the tests. I have some experience with testing but not much. I plan to complete this by end of this week.

**Comment by ThePiyushAggarwal** [comment]
@palisadoes

There are tests already available for this functionality 
image

I tried to enhance the tests more but I could not do more than what is already done.

**Comment by aashimawadhwa** [comment]
This is already taken care by me . @ThePiyushAggarwal @palisadoes

**Comment by aashimawadhwa** [comment]
This has already been taken care of , under the revamp of newsfeed managament @palisadoes @ThePiyushAggarwal

**Comment by ThePiyushAggarwal** [comment]
@aashimawadhwa Can you please point me to the PR/branch for this resolved issue?

**Comment by ThePiyushAggarwal** [comment]
@palisadoes Shall I close the PR if it is not required?

**Comment by palisadoes** [comment]
@JamaicanFriedChicken @jordan-barrett-jm Pleases review

**Comment by palisadoes** [comment]
Closing as @aashimawadhwa is already working on this

**Pull request closed without merging**
