### PR TITLE
changed color of logout button to red on hover #1201

### PR DESCRIPTION
**Pull request by PriyeshPandey2000**
**What kind of change does this PR introduce?**

bug fix 

**Issue Number:**

#1201 

Fixes #

changed css properties 
Screenshot 2024-01-02 162425

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
This is the third pull request you have made for this simple issue. Why? The value of your contributions to the repository are only realized when the code is merged.

**Comment by palisadoes** [comment]
Let us know when you are finally finished so we can review.

**Comment by PriyeshPandey2000** [comment]
> Let us know when you are finally finished so we can review.

this is my second pr as change was requested ,the other pr was raised by someone else .I think this is fine please review it.

**Comment by PriyeshPandey2000** [comment]
> > Let us know when you are finally finished so we can review.
> 
> this is my second pr as change was requested ,the other pr was raised by someone else .I think this is fine please review it.

@palisadoes

**Comment by aashimawadhwa** [comment]
@PriyeshPandey2000  this is not the ideal behaviour we wanted a red colour button by default not on hover. and the icon and text should have white collar

**Comment by PriyeshPandey2000** [comment]
> @PriyeshPandey2000 this is not the ideal behaviour we wanted a red colour button by default not on hover and the icon and text should have white colour

will change @aashimawadhwa

**Pull request closed without merging**
