### PR TITLE
Merge Develop-postgres into develop

### LINKED ISSUE #3004: Merge develop-postgres into develop
**Is your feature request related to a problem? Please describe.**
Merge develop-postgres into develop

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by im-vedant**
**Issue Number:**

Fixes #3004

### CODE REVIEW

**Comment by palisadoes** [comment]
I just remembered that I have an easier way to do this. Try this

**Comment by palisadoes** [comment]
## Steps - Part 1

cd /path/to/local/repo

git checkout develop
git add --all
git commit --no-verify -am "Saving before reset `date +'%D %T'`"
git fetch upstream
git fetch origin
git reset upstream/develop --hard
git branch --set-upstream-to=origin/develop develop
git push origin --force

git checkout develop-postgres
git add --all
git commit --no-verify -am "Saving before reset `date +'%D %T'`"
git fetch upstream
git fetch origin
git reset upstream/develop-postgres --hard
git branch --set-upstream-to=origin/develop-postgres develop-postgres
git push origin --force

git checkout develop-postgres
tar --exclude='./.git' --exclude='./node_modules' -czvf /tmp/"$(basename $PWD)".tgz .
cd ~/code/GitHub/PalisadoesFoundation
cp -rp repo repo.develop
cd repo.develop
git checkout develop

## Steps - Part 2

Delete all files and subdirectories in the directory. Make sure the only remaining directory is `.git`

Then:

git checkout develop
git branch --set-upstream-to=origin/develop develop
git branch --set-upstream-to=origin/develop-postgres develop-postgres

rm -rf *
git add .
git add --all
git commit --no-verify -am "`date +"%Y%m%d%H%M%S"` Deleted all files in the develop branch in anticipation of merging develop-postgres into develop cleanly"
git push origin --force
tar -xvzf /tmp/repo.tgz
git add .
git add --all
git commit --no-verify -am "`date +"%Y%m%d%H%M%S"` Merge develop-postgres into develop"
git push origin --force

git branch new-develop
git checkout new-develop
git branch --set-upstream-to=origin/new-develop new-develop
git push origin --force

## Finally

Open a PR against `develop-postgres` using `new-develop` as the source

**Comment by palisadoes** [comment]
It's much easier

**Comment by im-vedant** [comment]
> ## Steps - Part 1
> cd /path/to/local/repo
> 
> git checkout develop git add --all git commit --no-verify -am "Saving before reset `date +'%D %T'`" git fetch upstream git fetch origin git reset upstream/develop --hard git branch --set-upstream-to=origin/develop develop git push origin --force
> 
> git checkout develop-postgres git add --all git commit --no-verify -am "Saving before reset `date +'%D %T'`" git fetch upstream git fetch origin git reset upstream/develop-postgres --hard git branch --set-upstream-to=origin/develop-postgres develop-postgres git push origin --force
> 
> git checkout develop-postgres tar --exclude='./.git' --exclude='./node_modules' -czvf /tmp/"$(basename $PWD)".tgz . cd ~/code/GitHub/PalisadoesFoundation cp -rp repo repo.develop cd repo.develop git checkout develop
> 
> ## Steps - Part 2
> Delete all files and subdirectories in the directory. Make sure the only remaining directory is `.git`
> 
> Then:
> 
> git checkout develop git branch --set-upstream-to=origin/develop develop git branch --set-upstream-to=origin/develop-postgres develop-postgres
> 
> rm -rf * git add . git add --all git commit --no-verify -am "`date +"%Y%m%d%H%M%S"` Deleted all files in the develop branch in anticipation of merging develop-postgres into develop cleanly" git push origin --force tar -xvzf /tmp/repo.tgz git add . git add --all git commit --no-verify -am "`date +"%Y%m%d%H%M%S"` Merge develop-postgres into develop" git push origin --force
> 
> git branch new-develop git checkout new-develop git branch --set-upstream-to=origin/new-develop new-develop git push origin --force
> 
> ## Finally
> Open a PR against `develop-postgres` using `new-develop` as the source

@palisadoes  I think pr should be against develop branch. Can you confirm it once?

**Comment by palisadoes** [comment]
Yes the develop branch. There might be typos in the procedure

**Pull request closed without merging**
