### PR TITLE
strict lint and update PR workflow

### LINKED ISSUE #1427: Lint `git` Committed Files & PR Deltas / `no-explicit-any`
We need the ability to selectively adjust our linting rules so that they are eventually applied to our entire code base.

1. Linting rules are managed by the `.eslintrc.json` file.
1. They are applied to the entire code base at once.
1. If we change a rule from `warn` to `error` then every file in the code base will be checked and we have frequently seen our tests fail for dozens of files in hundreds of lines of code.

This is not acceptable.

We have been trying to more strictly lint the entire code base manually, but it has been very slow.

## At the user CLI
We need a way to edit `.eslintrc.json` with increasingly stricter linting rules in such a way that the tests are only applied to the changed files with every `git commit` and `git push` command. 

These `git` commands must fail if the linting fails.

## With Every Pull Request

We are working on a Talawa-API pull request that checks each submitted file for linting compliance. This can be used as an example of how to run the test against individual files.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1677

You must make sure that this functionality applied for all PRs for this repository whenever the  `.eslintrc.json` file is updated

## Other

1. There may be ways to achieve the CLI goals by updating our existing Git Hooks
1. Your solution should preferably work within coding environments such as VScode
1. Please work with @EshaanAgg on this issue

## Screenshots

When complete, you should be able to convert all these  `.eslintrc.json` file lines containing `warn` or `off` to `error` and the tests will only be applied to the changed files in `git`

image

### PR DESCRIPTION
**Pull request by lakshz**
**What kind of change does this PR introduce?**
Stricts the lint config to consider `no-explicit-any` as an error.

Updated PR workflow:
 - Linting Checks in PR, will be done only on changed-files
 
Updated pre-commit script:
 - `lint-staged` configuration was added in `package.json` file, taking help `talawa-api` project.

**Issue Number:**

Fixes #1427 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@lakshz Please fill out the PR template as thoroughly as possible.  In the future, please do not assign reviewers.  We have queue monitors who do an initial check of the PR, and then assign reviewers when it is ready.

**Comment by Cioppolo14** [comment]
@Tajcore @beingnoble03 Can you review this PR?

**Comment by lakshz** [comment]
@Cioppolo14 Got it, I updated the PR comment. 
Apologies for any confusion. I wanted to clarify that my pull request was automatically assigned to Palisadoes for review, as he is the designated code owner.

**Comment by palisadoes** [comment]
1. This PR needs to be closed. The source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
1. Please create a new branch in your local repository with the changes
2. Make sure the branch name is named differently from the target branch (`develop`)
3. Resubmit your PR

You will see that other PRs are using non-develop branch names for this reason

**Pull request closed without merging**
