### PR TITLE
Implement Token Refresh in talawa-admin for Seamless Session Renewal

### LINKED ISSUE #1024: Issue with implementing token refresh functionality
**Describe the bug**
The talawa-admin currently lacks the functionality to fetch a new access token using the refresh token once the existing token has expired. The missing functionalities include fetching new access and refresh tokens and storing them in the local storage. User is logged out automatically in between their session and have to enter their credentials again.

**To Reproduce**

1. Wait for the existing access token to expire.
2. Observe that the talawa-admin fails to automatically fetch a new access token using the refresh token.
3. And the user is logged out automatically.

**Expected behavior**
1. Automatically fetch a new access token using the refresh token once the existing access token has expired.
2. Store the new access and refresh tokens in the local storage.

**Actual behavior**
The current code currently lacks the ability to perform the automatic refresh access token using the refresh token so as to keep the user logged in while still renewing the access token.

**Screenshots**
N/A

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**

Bug fix

**Issue Number:**

Fixes  #1024

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

The present issue in talawa-admin revolves around the absence of functionality to automatically fetch a new access token using the refresh token when the existing token expires. As a consequence, users are involuntarily logged out, disrupting their sessions and requiring manual re-entry of credentials.

To solve the above mentioned issues this PR:
* Implements automatic access and refresh token refresh using provided refresh token upon expiration, when the server throws an error with message "User is not authenticated".
* Prevents automatic logout, ensuring a seamless user experience.
* Stores updated access and refresh tokens in local storage for uninterrupted sessions.
* Addresses the issue of involuntary user logout between sessions.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by chandel-aman** [comment]
@palisadoes @kb-0311 
Can you please review this PR?

**Comment by palisadoes** [comment]
Please fix the failing tests. You need to validate documentation better.
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/6862719862/job/18724627604?pr=1061

**Comment by chandel-aman** [comment]
> Please fix the failing tests. You need to validate documentation better.
> 
>     * https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/6862719862/job/18724627604?pr=1061

@palisadoes 
All the tests for the newly created or modified files have been have been covered and none of them are failing.
Here is the screenshot from codecov of the same
image

And regarding the validation error, this PR in talawa-admin depends on the PR in talawa-api, which is causing the mentioned error. Once the changes in api are merged the validation error will not occur here in talawa-admin.

**Changes in talawa-api that is causing this validation error**

* The schema for revokingRefreshTokenForUser has been changed earlier it required an userid to be passed as argument since it was an unauthenticated route, now we are getting the userid from the access token that is being passed from the client.

**Comment by noman2002** [comment]
@chandel-aman The test is not failing due to code coverage, its failing due to GraphQL formatting. Please check the link shared by @palisadoes .

**Comment by chandel-aman** [comment]
@palisadoes
image
Sir why is this PR workflow failing?

**Comment by chandel-aman** [comment]
@palisadoes @noman2002 
The GraphQL schema error that was causing the test error earlier should have been resolved now, since there was some change made in the schema of revokeRefreshTokenForUser api and the PR has been merged it should work now.

**Comment by chandel-aman** [comment]
@palisadoes 
Sir any update on this issue?

> @palisadoes image Sir why is this PR workflow failing?

**Comment by noman2002** [comment]
> @palisadoes image Sir why is this PR workflow failing?

There is some issue with github actions. Its failing every where.

**Comment by noman2002** [comment]
@aashimawadhwa @EshaanAgg @beingnoble03 @rishav-jha-mech Please review.

**Review by EshaanAgg — APPROVED** [review]
LGTM. Can't comment about the failing actions.

**Comment by palisadoes** [comment]
> LGTM. Can't comment about the failing actions.

The failing action is a known issue:
- https://github.com/actions/first-interaction/issues/286

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
