### PR TITLE
Fix:routing issue for orgdash page

### LINKED ISSUE #540: Rerouting should be done throguh router
**Describe the bug**
Rerouting should be done through the router package instead of a window.
Doing through the window will take time to get to that page and reset the state of react query.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login
2. go to the orglist page
3. click the manage button
4. the page will reload and go there

**Expected behaviour**

https://user-images.githubusercontent.com/67755128/223178937-af842166-5db3-4075-9421-0aa2ddb38a0c.mp4

visit this [link](https://drive.google.com/file/d/1wCxHhXYLEDpj7Szbfx_Hg1B2t9j3c-3O/view?usp=share_link) if the above video not working

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.

https://user-images.githubusercontent.com/67755128/223178089-d91bcbfe-4d6e-477d-b25a-26d76e62f982.mp4

visit this link if the above video is not working

https://drive.google.com/file/d/12gyXcOKyk-vDNRhrq39Jtrp_BNDwYkmB/view?usp=share_link

**Additional details**

Do click on roles , request navlink and see the difference

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by VenomFate-619**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #540 

**Did you add tests for your changes?**

No
**Snapshots/Videos:**

https://user-images.githubusercontent.com/67755128/223808727-06d58308-cd18-4c1d-ae0e-0ae8906e625b.mp4

**Summary**

On previous version it was taking a long time to get to that route as well it is prone to reset the state of the parent component

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by VenomFate-619** [comment]
I will fix this test issue and push

**Review by xoldyckk — DISMISSED** [review]

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by noman2002 — APPROVED** [review]
Looks good to me

**Review by palisadoes — APPROVED** [review]

**Comment by anshgoyalevil** [comment]
@palisadoes 
@VenomFate-619 

I have checked the changes, and a line is removed in this PR which is causing ```People```, ```OrgSettings``` pages fail to load.

The handleClick() function must be
```
  function handleClick() {
    const url = '/orgdash/id=' + props.id;
    window.location.replace(url);
    history.push(url);
  }
```
instead of 
```
  function handleClick() {
    const url = '/orgdash/id=' + props.id;
    history.push(url);
  }
```

**Comment by palisadoes** [comment]
@anshgoyalevil Please add a test for this if possible

**Comment by anshgoyalevil** [comment]
@palisadoes 

These type of things cannot be tested properly using React Testing Library. 

We should go for E2E tests using puppeteer and jest. That way, we can test such things.

I will research more on this topic.

**Comment by palisadoes** [comment]
OK, another GSoC idea

**Comment by VenomFate-619** [comment]
@anshgoyalevil 

```
 window.location.replace(url);
 history.push(url);
```

both statements do the same things, the history way is a preferred way as we need a client-side routing.

failing for People and OrgSetings can be a different issue, it is related to the redux state management.

```
const generateRoutes = (comps: any[]) => {
  return comps
    .filter((comp) => comp.name && comp.name !== '')
    .map((comp) => {
      const entry = comp.comp_id
        ? { name: comp.name, url: `/${comp.comp_id}/id=${currentOrg}` }
        : {
            name: comp.name,
            subTargets: comp.subTargets.map((subTarget: any) => {
              return {
                name: subTarget.name,
                url: `/${subTarget.comp_id}/id=${currentOrg}`,
                icon: subTarget.icon ? subTarget.icon : null,
              };
            }),
          };
      return entry;
    });
};
```

this code is used to generate the routes, initially, the `currentOrg` is undefined because the application opens from the orglist page where the id is not present.


When we use `window.location.replace`  it is like reloading for the page, at that time that `currentOrg` id would be present in the URL and the redux store.

when we use the history one the page is not reload and the routes are also not updated in the redux store but any function, there is a reducer to update the route but it does not use

```
case 'UPDATE_TARGETS': {
      return Object.assign({}, INITIAL_STATE, {
        targets: [...INITIAL_STATE.targets, action.payload],
      });
    }
```

going on the window approach kills the SPA(single page application) feature for client-side routing.

I will suggest that we need to fix the redux logic 

@xoldyckk @palisadoes

**Comment by VenomFate-619** [comment]
using the window approach we would lose the redux state also when moving from one page to another page, it is always reset to initial data

**Comment by anshgoyalevil** [comment]
@VenomFate-619 

Using the history.push way may be good.

But, should we opt for something which is breaking other things, without even fixing those things?

If you still think we should go for this method, please create issues for fixing the broken pages.

**Comment by xoldyckk** [comment]
@VenomFate-619 What you're trying to do is the correct thing, I too agree with that, but I guess the components are highly coupled to that older inefficient approach, so to make this work, you'll have to fix those other instances too.

YES, IT'S RECURSIVE TECHNICAL DEBT.

**Comment by VenomFate-619** [comment]
@xoldyckk @anshgoyalevil thx for the feedback.
I agreed with you, I will create a PR to fix this.

**Pull request merged**
