### PR TITLE
Feature/alert timing

### PR DESCRIPTION
**Pull request by Graycemuthui**
**What kind of change does this PR introduce?**

Feature : I added a timeout for all the toast alerts and managed to reduce the timing once the event occurs.

**Issue Number:**

- #673 

**Did you add tests for your changes?**

- Yes, I did.

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

- Not relevant

**Summary**

- Reduced the time on alerts since they were taking a long time to load.

**Does this PR introduce a breaking change?**

- No it does not. 

**Update**
- Fixed the issue highlighted

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Graycemuthui Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. It greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by Cioppolo14** [comment]
@Graycemuthui Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by EshaanAgg** [comment]
@Graycemuthui 
You have defined an autoClose variable in each of the files. Instead, you should define a constant in one central file (`constants.ts` is a nice candidate) and set the value of the same there.  Then you should import the same in each of the files that you want to use it and supply it to the `toast` method. 

Only considering renaming `autoClose` to `toastAutoCloseTimeout` for better readability and verbosity.

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
@Graycemuthui I'm closing the PR. There are:

1. lots of conflicting files
2. tests that have not been passing

Please resubmit.

**Pull request closed without merging**
