### PR TITLE
Redesign the Event Management's Event Statistics tab for the talawa Admin portal #1752

### LINKED ISSUE #1752: ADMIN REDESIGN: redesign the Event Management's Event Statistics tab for the talawa Admin portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management's Event Statistics Tab for the talawa Admin portal

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:
Screenshot 2024-03-20 at 12 38 51 AM

Desired Result:
Screenshot 2024-03-20 at 12 39 07 AM

Related Issues: 
#1748 

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by sahil-idk**
**What kind of change does this PR introduce?**

Screen Redesign

**Issue Number:**

Fixes #1752 

**Did you add tests for your changes?**

Yes

[Screencast from 2024-05-02 11-54-05.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/141494404/a31309c3-8cdd-4655-a21d-ed9f4945a412)

**If relevant, did you update the documentation?**

**Summary**

-> Removed the earlier modal that was showed 
-> made it a block using rows and columns
-> Creation of Cards for the three sections 
-> Arranging the cards 

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by sahil-idk** [comment]
> Please fix the conflicting file

Fixed those conflicts

**Comment by palisadoes** [comment]
Please fix all the PR checks, except introspection.

**Comment by sahil-idk** [comment]
@palisadoes  Hi  I am really sorry to inform that I am having some merge issue with the fix-1752 branch as i  staged some changes before pulling but the check failing are just formatting issues of proper indentation, can u pls fix them as it is in only 2 files and merge this PR
image

**Comment by palisadoes** [comment]
> @palisadoes Hi I am really sorry to inform that I am having some merge issue with the fix-1752 branch as i staged some changes before pulling but the check failing are just formatting issues of proper indentation, can u pls fix them as it is in only 2 files and merge this PR image

I'm going to close this PR. You can resubmit a new one with the correct changes.

**Pull request closed without merging**
