### PR TITLE
Updated get advertisements query and implemented infinite scroll

### LINKED ISSUE #1663: Update the implementation of advertisements Connection query
**Describe the bug**

advertisementsConnection query needs to be updated as per the new implementation in https://github.com/PalisadoesFoundation/talawa-api/pull/1919

**Additional details**
The implementation of advertisementsConnection query has been updated in https://github.com/PalisadoesFoundation/talawa-api/pull/1919 and it needs to be updated in Talawa admin as well

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**

Fixes #1663 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Updated the implementation of fetching advertisements and implemented infinite scroll.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by disha1202** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/4f0d8084-647c-471d-a39c-d82eba9e2858

**Comment by palisadoes** [comment]
1. Why do some ads look like this?

    image

1. And others look like this? Is it that one has embedded HTML / Markdown and the other doesn't?

    image

Please get the code coverage of the patch to pass

**Comment by disha1202** [comment]
>> Is it that one has embedded HTML / Markdown and the other doesn't?
We only have support for images and videos. 
Both the advertisements contains images and the images are clipped to fit inside the advertisement card. 
This is because of the css rule `object-fit: cover;`

**Comment by palisadoes** [comment]
1. Thanks. We'll see what end users say about having text only ads. That will be for another day.
1. Please try to get the code coverage for the patch higher so we can merge.
    image

**Comment by disha1202** [comment]
> 1. Thanks. We'll see what end users say about having text only ads. That will be for another day.
> 2. Please try to get the code coverage for the patch higher so we can merge.
>    image

Sure, I am working on it. Will try to fix this as soon as possible.

**Review by palisadoes — DISMISSED** [review]

**Comment by disha1202** [comment]
Hi @palisadoes, 

I am working on improving the code coverage. Will update the PR soon.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
