### PR TITLE
USER REDESIGN: Redesign the sidenav for Talawa user portal

### LINKED ISSUE #1510: USER REDESIGN: redesign the sidenav for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the sidenav for the user portal and follow a theme similar to the talawa admin portal.

**Additional context**

1. These are the two side navbars that require modifications.
   Please refer the figma file below : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1
1. Try to split this up into several smaller PRs, possibly 2-3 screens at a time. This will make the reviewing process much faster.

**Screenshots**
Screenshot 2024-01-28 at 10 59 53 PM Screenshot 2024-01-28 at 11 00 02 PM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1510

Redesign the sidenav of talawa user portal with theme similar to admin portal.

Figma: https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

Previous sidebar is removed and two sidebars are added:

1. User: 
    - My Organizations -> /user/organizations
    - Settings -> /user/settings
    - UserInfo Button -> /user/settings
    - Sign out -> /user

2. Organization:
    - OrganizationInfo Button -> /user/organizations
    - Posts -> /user/organization/id={id}
    - Events -> /user/events/id={id} 
    - Donations -> /user/donations/id={id}
    - UserInfo Button -> /user/settings
    - Sign out -> /user

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/66236e39-02ef-4b62-a47b-2fb500d321bf

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@pateldivyesh1323 Can you please fix the failing introspection test? We are working on a fix to this issue.

**Comment by pateldivyesh1323** [comment]
@Cioppolo14 Is there something to be done from my side?

**Comment by Cioppolo14** [comment]
We can move forward without it for now.  I will assign reviewers.

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa I have removed the top navbar.

image


image

**Review by rishav-jha-mech — CHANGES_REQUESTED** [review]
`src/components/UserPortal/OrgLeftDrawer/OrgLeftDrawer.module.css`

The left drawer has same style and classes as the one component we are using in Admin, just the logical part is different, instead of creating new files everywhere for the same component, create a index.css file in `src/assets/css/` folder and import it in `src/index.tsx` file. Also when you do this, make sure to remove the same from all the left drawer and corresponding screen components.

**Comment by pateldivyesh1323** [comment]
> `src/components/UserPortal/OrgLeftDrawer/OrgLeftDrawer.module.css`
> 
> The left drawer has same style and classes as the one component we are using in Admin, just the logical part is different, instead of creating new files everywhere for the same component, create a index.css file in `src/assets/css/` folder and import it in `src/index.tsx` file. Also when you do this, make sure to remove the same from all the left drawer and corresponding screen components.

@rishav-jha-mech I have tried implementing the requested change but it is creating more and more confusion as the styles are slightly different. This is making one part to keep in index.css and other to keep in their respective module.css files. It is getting difficult to track all of them.

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by palisadoes** [comment]
1. You have submitted too many files. 
2. We'll have to close the PR
3. Please resubmit

**Pull request closed without merging**
