### PR TITLE
Modify event visibility for non-admins

### LINKED ISSUE #795: Feature Request: Private Events
**Is your feature request related to a problem? Please describe.**
The participants in all events are publicly visible to everyone. There need to be options for more privacy.

REF : [#354](https://github.com/PalisadoesFoundation/talawa-api/issues/354)

**Describe the solution you'd like**
1. The ability to make events private where only participants can see who is attending
2. The optional ability to make private events invisible to persons not attending

**Describe alternatives you've considered**
This is my thought process:
When a user is added as a participant to an event, the user details are added to the participants' array. We could actually make that happen, for example, after we fetched events, when rendering the event in the admin, we can have a check that filters on event visibility. If the event is private, we will then check if the user id is in the list of participants. If it is present then we add the private event to the calendar, else we don't add it. But if the event visibility is public then we don't need this check. We will just add it to the calendar.

The `SUPERADMIN` will have the right to see both private and public events. The `ADMIN` will see both Private and Public events of the organizations he is in charge of.

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kayceeDev**
**What kind of change does this PR introduce?**
This PR Fixes:
- The ability to make events private where only participants can see who is attending
- The optional ability to make private events invisible to persons not attending

**Issue Number:**
Fixes #795 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
N/A

**If relevant, did you update the documentation?**
N/A

**Summary**
The participants in all events are publicly visible to everyone. There need to be options for more privacy.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by kayceeDev** [comment]
> Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:
> 
> 1) The overall code coverage drops below the target threshold of the repository
> 2) Any file in the pull request has code coverage levels below the repository threshold
> 
> We do this to ensure the overall reliability of the code base is maintained.
> 

I am working on a change

**Comment by kayceeDev** [comment]
@palisadoes everything is tested now.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
