### PR TITLE
feat: manage tags UI (GSoC)

### LINKED ISSUE #2184: ADMIN: Implement Manage Tags UI (GSoC)
### Describe the feature.

Adding support for Managing `Tags` in the admin.

### Describe the solution you'd like

Making the `ManageTags` UI, adding a `Manage` option in the tags list that would take us to that screen.

Organization_ Tag Detail

### Additional context

Previous issue: #2037

### PR DESCRIPTION
**Pull request by meetulr**
### What kind of change does this PR introduce?

Implements Manage Tag Screen.

### Issue Number:

Fixes #2184

### Did you add tests for your changes?

Yes

### Snapshots/Videos:

https://github.com/user-attachments/assets/3800408b-2ad1-4d82-a455-e69f17e3b51c

### Does this PR introduce a breaking change?

No

### Additional Context

Previous PR: #2175

## Summary by CodeRabbit

- **New Features**
	- Introduced a comprehensive tag management interface for adding and unassigning users to tags.
	- Added support for tag management in multiple languages: English, French, Hindi, Spanish, and Chinese.

- **Bug Fixes**
	- Updated routing paths for managing tags, enhancing user navigation and interaction.

- **Documentation**
	- Enhanced user interface with detailed prompts and feedback related to tag management actions.

- **Tests**
	- Implemented unit tests for the new manage tag component to ensure functionality and user interactions.

- **Style**
	- Improved styling for the manage tag interface to enhance usability across devices.

### CODE REVIEW

**Review by rishav-jha-mech — APPROVED** [review]

**Review by Nitya-Pasrija — CHANGES_REQUESTED** [review]
Please update the UI so that all the fields are aligned accordingly
image

**Comment by meetulr** [comment]
> Please update the UI so that all the fields are aligned accordingly

That member profile screen is not associated with this issue, the view profile button just takes us to that existing screen. Do you want me to make changes there as part of this issue?

**Comment by Nitya-Pasrija** [comment]
> > Please update the UI so that all the fields are aligned accordingly
> 
> That member profile screen is not associated with this issue, the view profile button just takes us to that existing screen. Do you want me to make changes there as part of this issue?

Yes, you can create a separate issue and link it up with this PR to address these changes as well

**Comment by Nitya-Pasrija** [comment]
> Please update the UI so that all the fields are aligned accordingly
> image
> 

As discussed via text, let's have this as a separate issue instead to align and rectify the minor UI fixes

**Review by Nitya-Pasrija — APPROVED** [review]

**Pull request merged**
