### PR TITLE
test : adding test for constant.ts

### LINKED ISSUE #399: Code Coverage: Create tests for constant.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/Constant/constant.ts
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by arunavabasu-03**
**What kind of change does this PR introduce?**

This pull request is to include a comprehensive test for the constant.ts  file, which will ensure its proper functionality and performance before it is integrated into the main codebase.

**Issue Number:**

Fixes #399 

**Did you add tests for your changes?**

yes

**Snapshots/Videos:**

Screenshot 2023-01-29 at 1 17 36 PM

**If relevant, did you update the documentation?**

**Summary**

Adding test for constant.ts

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Review by prathamesh-mutkure — APPROVED** [review]
Looks good to me

**Comment by palisadoes** [comment]
@arunavabasu-03 @prathamesh-mutkure Our PR automated workflows and procedures were created to improve our code's reliability.

Valid approvals can only be made by the Palisadoes volunteer team. Approvals by others do not meet our code merging safeguards. Sometimes I override these safeguards but not for situations like these.

Please refrain from this practice. It is not in the spirit of our community.

**Comment by palisadoes** [comment]
I recognize your enthusiasm, but please let's do the right thing.

**Comment by arunavabasu-03** [comment]
yeah !! i dont aware of this thing , although thanks for pointing it out , take care of that from next time !! 😀

**Review by noman2002 — APPROVED** [review]

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, really sorry, I was not aware of that, my bad

I've worked with a few organizations in the past and they encouraged code reviews, I assumed the same with Palisadoe.

Will keep that in mind in the future.

**Comment by palisadoes** [comment]
Thanks for letting me know about other repos. We can revisit it later.

We put the rules in place because during the GSoC period things can get out of control.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
