### PR TITLE
Increased the OrgList Code Coverage

### PR DESCRIPTION
**Pull request by saadabban76**
**What kind of change does this PR introduce?**
testing

**Issue Number:**

Fixes ##429

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
Not Required.

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Kevoniat** [comment]
@saadabban76  the Coverage is still at 90.83%

**Comment by saadabban76** [comment]
> @saadabban76  the Coverage is still at 90.83%

I've added test's for "Superdashlist" and null search value, don't know why the coverage still remain the same

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by saadabban76** [comment]
Hi @palisadoes I've fixed the failing test and also managed to increased the code coverage of orgList component. sorry for any inconvenience.

**Comment by saadabban76** [comment]
Hi @noman2002 can you please review this PR?

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
