### PR TITLE
feat: added validation for links in advertisement

### LINKED ISSUE #1479: No validation for formState.link as URL or String
**Describe the bug**
When creating a new advertisement, there is a missing validation check for the formState.link field. This allows users to input random strings or potentially invalid data.

**To Reproduce**

1. Create an Organization
2. Go to `orgads/id=some_id`.
3. Click on `Create new advertisement`.
4. Now you can eneter any random string in the `Provide a link for content to be displayed` input.

**Expected behavior**
The formState.link should undergo a validation to ensure that the provided input is a legitimate URL, preventing the submission of arbitrary or invalid strings.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/91189139/f3fb4a1c-1050-45f1-b75d-3544cf181424

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
This PR introduces validation of link in the advertisements screen.

**Issue Number:**

Fixes #1479 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/6817aba0-0e9d-4975-8f6a-a22a69b7f05d

**If relevant, did you update the documentation?**
Not relevant

**Summary**
- Implemented validation for the `formState.link` field to ensure that it represents a valid URL.
- Proper The validation checks have been added to prevent users from submitting arbitrary or invalid strings when creating a new advertisement.
- Added tests for the modified code.
- Ensured no other functionality or tests fail after the changes.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar Please fix the failing test.

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar Please fix the failing test.

The failing tests are not a result of the changes I made. However, the error message `Unknown type 'UserToReturn'` is peculiar, as there is no type named `UserToReturn` defined anywhere within the codebase.

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar Ok, we need to get to the cause of the error, to make sure API & Admin work together.  I will ask for help.

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar UsertoReturn is in the API code base, probably from a recent merge. Please add a reference to it in the src/GraphQl directory tree of the Admin code.  See if that clears the error.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14 , please add reviewers even for this PR.
Thank you

**Comment by akhilender-bongirwar** [comment]
@palisadoes , please review.

**Comment by akhilender-bongirwar** [comment]
@noman2002 @SiddheshKukade , Kindly review

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
