### PR TITLE
Few UI bug Fixing.

### LINKED ISSUE #1192: Few very small UI bugs.
**Describe the bug**
Bug 1: On the login page, the mail icon in the email input is overflowing out of the input div.
Bug 2: In the members page, We have 3 radio button, they are very weirdly placed.
Bug 3: The hamburger has a weird line going from top to bottom.

**To Reproduce**
Bug 1:
1. Go to login page
2. Here you can see the email icon is overflowing.
Bug 2:
1. Login 
2. Click on manage on any organization.
3. Click on People tab.
4. Under filter by name and under all the input fields you can see the bug.
Bug 3:
1. Login
2. Click on manage on any organization.
3. Click on People tab or the Events tab.
4. Here you can see the hamburger has that weird line.

**Expected behavior**
Bug 1: The email icon should not overflow out of the input div. It should be contained, just like in the password.
Bug 2: All three buttons should be vertically aligned
Bug 3: There should not be a vertical line across the hamburger.

**Screenshots**
Bug 1:
image
Bug 2:
image
Bug 3:
image

**Additional Details**
Since all these issues are very small, I included them on the same issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
**What kind of change does this PR introduce?**

UI Bug fixing.

**Issue Number:**

Fixes #1192 

**Did you add tests for your changes?**

NO.

**Snapshots/Videos:**
Bug 1 Fix:
Screenshot 2023-12-14 120718
Bug 2 Fix:
Screenshot 2023-12-14 120744
Bug 3 Fix:
Screenshot 2023-12-14 120753

**If relevant, did you update the documentation?**
No.

**Does this PR introduce a breaking change?**

NO.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please merge your code with the latest upstream. More tests will pass

**Comment by Cioppolo14** [comment]
@git-init-priyanshu
 Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
Please merge your code with the latest upstream. This should make the linting tests pass. We had an error in a configuration file

**Comment by palisadoes** [comment]
> Please merge your code with the latest upstream. More tests will pass

Please do this again. We had a configuration error

**Comment by git-init-priyanshu** [comment]
> > Please merge your code with the latest upstream. More tests will pass
> 
> Please do this again. We had a configuration error

You can check now.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
