### PR TITLE
Refactor:src/screens/UserPortal/Events from Jest to Vitest 

### LINKED ISSUE #2574: Refactor:`src/screens/UserPortal/Events` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/UserPortal/Events` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by abbi4code**
**What kind of change does this PR introduce?**
This PR migrates the test cases in src/screens/UserPortal/Events from Jest to Vitest, ensuring compatibility with Vitest .

✅ Replace Jest-specific functions and mocks with Vitest equivalents
✅ Ensure all tests in src/screens/UserPortal/Events pass after migration using npm run test:vitest
✅ Maintain the test coverage for the file as 100% after migration
✅ Upload a video or photo for this specific file coverage is 100% in the PR description

**Issue Number:**

Fixes #2574 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

Screenshot from 2024-12-11 19-50-31

**Other information**

- Replaced hardcoded date strings 
Screenshot from 2024-12-11 19-57-46

- With dynamic dates using new Date().toLocaleDateString() to ensure the test uses the current date.
Screenshot from 2024-12-11 19-52-58

- Updated hardcoded startTime and endTime values from '02:00 PM' and '06:00 PM' to '08:00 AM' and '10:00 AM'
Screenshot from 2024-12-11 20-05-14
Screenshot from 2024-12-11 19-59-47

- To align with the default values set in Events.tsx
Screenshot from 2024-12-11 20-03-31

## Summary by CodeRabbit

- **Tests**
	- Transitioned testing framework from Jest to Vitest for the Events component.
	- Updated mock implementations for various dependencies to improve functionality.
	- Enhanced readability of test functions by changing `test` to `it` and adding clarifying comments.
	- Adjusted date and time handling in tests to reflect current locale-specific formats.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please make sure coderabbit.ai approves your PR
1. Make sure all tests pass (except introspection)
1. Please make sure that the code coverage for your patch reaches at least 95%

**Comment by abbi4code** [comment]
@coderabbit start review

**Comment by abbi4code** [comment]
@coderabbit start review

**Comment by palisadoes** [comment]
Please make the appropriate changes so that coderabbit.ai approves your PR

**Comment by abbi4code** [comment]
@CodeRabbit start review

**Comment by palisadoes** [comment]
1. Please fix the failing tests. We cannot merge failing code into the code base. If a failing test doesn't appear to be related to your changes, it may be. Our contributors don't always test for all possible outcomes and your changes may have triggered the failure. Make valid adjustments to the code to make it fully tested.
1. Please also ensure CodeRabbit.ai approves your changes

**Comment by abbi4code** [comment]
@CodeRabbit review

**Comment by palisadoes** [comment]
1. Please fix the failing tests. Click on the `Details` links for more information.
1. Please make sure that CodeRabbit.ai approves your changes

**Comment by abbi4code** [comment]
> 1. Please fix the failing tests. Click on the `Details` links for more information.
> 2. Please make sure that CodeRabbit.ai approves your changes

1. Failing tests have already been fixed 
2. coderabbit has approves the changes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
