### PR TITLE
[organization action items] updated OrganizationActionItem screen

### LINKED ISSUE #2094: OrganizationActionitems Screen Mobile Redesign: Create Button Out of Bounds
**Describe the bug**
In the OrganizationActionitems Screen on mobile the create button is out of bounds.

**To Reproduce**

1. Access any foundation 
2. Click on Action items within the menu navbar
3. View screen on mobile width

**Expected behavior**
To have the create button and filter buttons within the respected parent container

**Screenshots**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Alfredoeb9**
…fix buttons on mobile screen

updated OrganizationActionItems screen to fix button and dropdown menus on mobile screens as buttons were off screen during tablet - mobile

**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #2094

**Did you add tests for your changes?**

No, not needed only changed css.

**Summary**

updated OrganizationActionItems screen to fix button and dropdown menus on mobile screens as buttons were off screen during tablet - mobile

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Improved button layout and alignment for a better user experience.
	- Buttons are now stacked vertically for enhanced usability.
	- Extended the duration of mock data for pledges to accommodate longer-term goals.

- **Style**
	- Updated CSS for button containers to center and better organize buttons visually.
	- Applied new styling properties to enhance the overall aesthetics of the button blocks.

### CODE REVIEW

**Comment by Alfredoeb9** [comment]
looks like test src/screens/FundCampaignPledge/FundCampaignPledge.test.tsx is failing, not sure why as I only changed css on OrganizationActionItems Screen so this error did not come from this PR.

**Comment by Cioppolo14** [comment]
@Alfredoeb9  Please fix the failing tests.

**Comment by Alfredoeb9** [comment]
@Cioppolo14 looks like last major file changes on these files were from https://github.com/PalisadoesFoundation/talawa-admin/pull/2064/files from user @GlenDsza.

Commit: src/screens/FundCampaignPledge/FundCampaignPledge.tsx

Also seeing a new PR: https://github.com/PalisadoesFoundation/talawa-admin/pull/2163

I suggest teaming up with GlenDsza as this was their task. 

Those changes are my roadblock, my changes on this PR do not affect unit test from errors seeing above in this PR.

**Comment by GlenDsza** [comment]
@Alfredoeb9 the issue could be resolved by changing the year values of endDate on following line
[https://github.com/PalisadoesFoundation/talawa-admin/blob/3d4a87e6f591fcaef973c5398a2c6418e61309ba/src/screens/FundCampaignPledge/PledgesMocks.ts#L25](https://github.com/PalisadoesFoundation/talawa-admin/blob/3d4a87e6f591fcaef973c5398a2c6418e61309ba/src/screens/FundCampaignPledge/PledgesMocks.ts#L25)

Set the endDate to something in far distant future `endDate: "2034-08-08"`. I have changed this in my recent [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2163) but it might take time to get merged as the size of changes is vast

**Comment by Alfredoeb9** [comment]
@GlenDsza copy that! Since changes are made in your PR, I'll wait until your changes have integrated so there is not conflict when my PR is merged. Thank you for the follow up!

@Cioppolo14 We should wait on this PR merge until @GlenDsza is completely merged to avoid any conflict.

**Comment by Alfredoeb9** [comment]
@Cioppolo14 seeing #2163 has been merged. Can we update this PR branch with the latest changes. All tests should be good now.

**Comment by Alfredoeb9** [comment]
@Cioppolo14 @palisadoes PR is ready for review and to be merged 👍.

**Comment by palisadoes** [comment]
1. Please add a video to show how this works.
2. We don't expect users to be running Admin on a mobile phone, but on a tablet where the options will be more usable. This PR may not be suitable for our needs.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please add a video to show how this works.
2. We don't expect users to be running Admin on a mobile phone, but on a tablet where the options will be more usable. This PR may not be suitable for our needs.

**Comment by Alfredoeb9** [comment]
Sure will upload video right now

**Comment by palisadoes** [comment]
Closing. Inactivity.

**Pull request closed without merging**
