### PR TITLE
Configure Automatic Labeling for Issues 

### PR DESCRIPTION
**Pull request by Sumitsh28**
**What kind of change does this PR introduce?**

Feature: Configures automatic labeling for issues.

**Issue Number:** Closes [#2256](https://github.com/PalisadoesFoundation/talawa-admin/issues/2256)

**Did you add tests for your changes?**

No. This change is related to GitHub Actions configuration and does not require unit tests.

**If relevant, did you update the documentation?**

No, documentation update is not required for this change.

**Summary**

This pull request updates the `issue.yml` file to configure automatic labeling of issues using the `Renato66/auto-label` GitHub action. The motivation behind this change is to reduce manual labeling effort and ensure that issues are labeled consistently based on their content. This automation will improve the efficiency of issue management by applying appropriate labels for dependencies, security, and design-related issues.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced issue labeling in GitHub Actions for better categorization of newly opened issues.
- **Refactor**
	- Improved formatting and consistency in the issue greeting message.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Sumitsh28 Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

**Comment by Sumitsh28** [comment]
@Cioppolo14 Done!

**Review by palisadoes — CHANGES_REQUESTED** [review]
@Sumitsh28 

1. You have not followed the approach in the issue. 
2. Please fix

**Comment by Sumitsh28** [comment]
@palisadoes , can you please tell me what I missed?

**Comment by palisadoes** [comment]
Your solution does not follow the recommended configuration by the GitHub Action's team
* https://github.com/marketplace/actions/auto-label

**Comment by noman2002** [comment]
@Sumitsh28 Are you still working on this ?

**Comment by palisadoes** [comment]
Closing. Inactivity

**Pull request closed without merging**
