### PR TITLE
Flawless Installation

### LINKED ISSUE #1463: Admin: Flawless Installation - Write Tests for `setup.ts`
**Is your feature request related to a problem? Please describe.**

1. We frequently add new configuration parameters to our code base.
2. The changes mean that the `setup.ts` file is always being modified.
3. Most PRs that modify this file introduce various types of failure.

PRs related to `setup.ts` require a high degree of manual verification by our reviewers and errors are frequent.

**Describe the solution you'd like**

Your job is to make the execution of the `setup.ts` file be:

1. foolproof
2. intuitive to use
3. easier and simpler to use

A tech novice or new contributor should be able to install the API without issue.

For the successful completion of this issue:

1. Write code to thoroughly test the `setup.ts` file without manually inputting responses to prompts, including:
    1.  all relevant functions, methods and classes where applicable.
    5. all user prompts
6. Ensure that running the tests is a part of our existing PR and Husky `git commit` workflows

This may mean making changes to the `setup.ts` file.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

This issue may require the refactoring of this script file to make it:

1. Easier to test
4. Easier to maintain

Testing must verify that the:

1. Default values for input are correct:
     1. When a parameter is already configured 
     1. When a parameter is not configured 
1. Functionality when parameters are missing from the configuration is maintained
1. Sequencing of the prompts is maintained
1. Configuration parameters that rely on any external APIs (eg. database, mail) must be tested.
    1. The tests don't hang when testing these APIs whether or not the API connectivity is validated
1. Preexisting comments in the test configuration file are maintained when the final configuration is saved
1. Final configuration isn't saved until the last question is answered. In other words, hitting CTRL-C at any point before the last question will not affect the original configuration.
1. Wording of the prompts in all scenarios is unchanged
1. Previously correctly answered questions are not repeated
1. Correct values are echoed when:
    1. entered, 
    1. updated or 
    1. previously found in the configuration
1. Input of mandatory parameters cannot be avoided if they are not previously configured

Plus any other tests that could avoid failure based on the PR comments for the issues below.

Other items to consider include:

1. The test file must be located in the existing `tests/` directory
1. The test file has good readability
1. Not making any changes to files in the `.github` directory
1. Use the `setup.ts` file in the API repo as a guide on how the script functionality should work.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sauradip07**
**Flawless Installation Possible for end User**

**Issue Number:**

Fixes #1463 

**Summary**

- [x] Default values for input are correct: -done
     - 1. When a parameter is already configured 
     - 2. When a parameter is not configured 
- [x] Functionality when parameters are missing from the configuration is maintained -done
- [x] Sequencing of the prompts is maintained -done
- [x] Preexisting comments in the test configuration file are maintained when the final configuration is saved -done
- [x] Final configuration isn't saved until the last question is answered. In other words, hitting CTRL-C at any point before the last question will not affect the original configuration. -done

   - I've introduced a `tempEnv` object to store the configurations, and I check for changes between the existing .env file and the values in `tempEnv` before updating the .env file. If there are changes, the script updates the .env file; otherwise, it informs the user that no changes have been detected. Additionally, a .temp-env file is not mandatory,
   
- [x] Wording of the prompts in all scenarios is unchanged -done
- [x] Correct values are echoed -done
- [x] Input of mandatory parameters cannot be avoided if they are not previously configured -done

**Other information**

- [ ] Configuration parameters that rely on any external APIs (eg. database, mail) must be tested.
The tests don't hang when testing these APIs whether the API connectivity is validated
please explain in details. Need more clarity.  

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

 **Yes**

### CODE REVIEW

**Comment by Sauradip07** [comment]
Do I Need to add the test file for `setup.ts` file or need any kind of modification 
`Please feel free to reach out if there are any modifications or any changes need to be made.`

**Comment by palisadoes** [comment]
The issue states that you need to create tests.

**Comment by Sauradip07** [comment]
> The issue states that you need to create tests.

Now I understand this issue and I work on it, thanks for clarity.

**Comment by Cioppolo14** [comment]
@Sauradip07 Is this ready for reviewers?

**Comment by Sauradip07** [comment]
> @Sauradip07 Is this ready for reviewers?

No, I am Still Working on it. Creating a test for `setup.ts `

**Comment by noman2002** [comment]
@Sauradip07 Any update in this ?

**Pull request closed without merging**
