### PR TITLE
Redesign & Bug Fixes in Organization Venue

### LINKED ISSUE #1840: Unable to create a venue | Bad User Input
**Describe the bug**
As an admin of an organization, I am not able to create a venue.

PFA the error SS
image

image

A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by GlenDsza**
**What kind of change does this PR introduce?**

bugfix, feature, refactoring, redesign

**Issue Number:**

Fixes #1840 & #1879  

**Did you add tests for your changes?**

Yes 

Modified Files:

- OrganizationVenues.tsx
image

- VenueModal.tsx:
image
 

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/90bde418-cbb1-4603-b2f6-18aa15c89140

**Summary**

- Redesigned Organization Venue Screen
- Added Search & Sort Functionality (Client)
- Fix UI layout issues
- Added Delete Venue Functionality
- Added checks to stop sending string capacity (invalid) for creating new venue
- Shifted Venue Mutations to separate file for Modularity
- Shifted Edit/Create Modal to `src/componenets/Venue/VenueModal`
- - Shifted Card to `src/componenets/Venue/VenueCard`

**Additional Details:**
Updated from Table to Card Layout

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Huy1996** [comment]
@ttaylor92 @noman2002 Could you review this PR?

**Comment by aashimawadhwa** [comment]
@GlenDsza 

-please render the image in the table.

Also if  for venue we can implement a layout like post feed, with cards and proper image display. and all other information i the card that would be really informative, please implement that.

**Comment by GlenDsza** [comment]
> @GlenDsza
> 
> -please render the image in the table.
> 
> Also if for venue we can implement a layout like post feed, with cards and proper image display. and all other information i the card that would be really informative, please implement that.

Yes would migrate it to card layout

**Comment by GlenDsza** [comment]
@aashimawadhwa @noman2002 @ttaylor92 PTAL Need Review
Update Venue Screen from Table to Card Layout


https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/c0b2fd1a-02a3-4406-bd2d-c805798f8678

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
