### PR TITLE
fixes graphql-introspection

### LINKED ISSUE #1429: GitHub Action Introspection Test Failure
**Describe the bug**

The introspection GitHub Action checks are failing in our PRs

**To Reproduce**

1. Submit a PR
2. The introspection check fails 
 
This is because the git clone command defaults to cloning the default Talawa-API branch which is `main` instead of `develop`. We are therefore comparing `main` in one repo with `develop` in the other.

**Expected behavior**

1. The introspection check must clone Talawa API using the same branch as that target branch of the  Talawa Admin PR. This must be done automatically using GitHub action variables.
    1. If the PR is merging the contributor's code into the Talawa Admin `XXXXXXX` branch then the `XXXXXXX` branch must be automatically cloned in the GitHub action file.
1. It's been suggested in the comments link below that this command could be used:
```
git clone -b branch_name --single-branch REPO_NAME && ls -a
```
1. All other functionality must be maintained.
1. The above suggested change may require adjustment

**Actual behavior**

- See above

**Screenshots**

image

**Additional details**

Comments from other PRs and issues and failed GitHub actions
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327#issuecomment-1891049919
1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7521006577/job/20472163884

The GitHub Action File that needs editing
1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aialok**
**What kind of change does this PR introduce?**

- It will fix the graph introspection that is currently failing.

**Issue Number:**

Fixes #1429 

**Did you add tests for your changes?**

- No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

- It will fix the graphql-introspection that is currently failing. However, we need to be alert about the fact that whenever we merge the develop branch of talawa-admin into the main branch, we must first merge the develop branch of talawa-api into main.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by aialok** [comment]
Hey @palisadoes,
The branch issue has been resolved, and we are now comparing the develop branches of both repositories. However, a new bug has emerged. The GraphQL introspection is still failing because many mutations and queries in talawa-admin are not present in the develop branch of talawa-api. Instead, these mutations and queries are available in the main branch. This mismatch is causing the GraphQL inspector to fail.

Here are one of the of the example:
1.  See the first error `Cannot query fieldcreateEventProject on type mutation` .

inspector

2. See `createEventProject` exist in mutation .

talawa-admin

3. But there is no such mutation or text in the talawa-api develop branch

talawa-api

4. Look we have `createEventProject` mutations exist in the talawa-api main branch.

talawa-api-create-event-main

Screenshot from 2024-01-15 21-14-40

5. But there is no such file exist in the talawa-api develop branch.

Screenshot from 2024-01-15 21-13-58

- These are the reason why our graphql-inspector is getting failed. I tried checking out the commit history but could not found anything related to the removal of these file.

Thank You : )

**Comment by palisadoes** [comment]
It's failing. You may need to be using $FULL_BRANCH_NAME instead. The echo of $BRANCH_NAME isn't working
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7530385953/job/20496635065?pr=1433

You'll need to do further commits. If it's working the introspection test must pass as part of this PR

**Comment by palisadoes** [comment]
1. That's not entirely true. There was an error with `FULL_BRANCH_NAME` which you seem to have solved. I'll merge this. 
2. Please open an equivalent issue in the API repo to complete this task.

**Comment by palisadoes** [comment]
Also, merge this file into `push.yml` in the API repo. We have been trying to make it easier to troubleshoot events, and this will help. 

- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/inspect.yml

I see the hard coded `develop` in the file. Is that the source of the issue? I can't see why it is now as both repos default to `develop`, but I can see that being an issue in future.

I'll need an answer before I merge this 

Are you sure this is the source of the current problem?

**Comment by aialok** [comment]
> Also, merge this file into `push.yml` in the API repo. We have been trying to make it easier to troubleshoot events, and this will help.
> 
> * https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/inspect.yml
> 
> I see the hard coded `develop` in the file. Is that the source of the issue? I can't see why it is now as both repos default to `develop`, but I can see that being an issue in future.
> 
> I'll need an answer before I merge this
> 
> Are you sure this is the source of the current problem?

- Can you please provide more details about the merge in `push.yml`? Do I need to merge the GraphQL Inspector?

- Regarding the issue in the `inspect.yml` file, I don't believe our current problem is related to inspect.yml file  because in talawa-api we are missing some of the mutation and queries which is present in the main branch of talawa-api but no in the develop. However, after checking the workflow history, I found that it's failing with every push. we need to fix the `inspect.yml` file too and we also need to add dynamic branch so that in future when we doing push to `main` branch. it does not create any issue.

**Comment by aialok** [comment]
> 1. That's not entirely true. There was an error with `FULL_BRANCH_NAME` which you seem to have solved. I'll merge this.
> 2. Please open an equivalent issue in the API repo to complete this task.

Okay I will create issue for the for same.

**Comment by aialok** [comment]
Yeah, got it. It helps us to manage our push workflow more easily. 🚀

**Comment by aialok** [comment]
> 1. In the API repo, the commands in the `inspect.yml` file are invoked with every push.
> 2. We have a separate `push.yml` file that is also invoked with every push.
> 3. We need to move the YAML code in the `inspect.yml`  to the  `push.yml` file and delete the  `inspect.yml` file
> 4. When this is done, the name of the job needs to be changed from `test` to something indicative of doing introspection testing.
> 5. It the migrated YAML code needs to:
>     1. be dependent on the `Push-Workflow` job in the `push.yml` file 
>     2. ensure that the `inspect.yml` file's code automatically adjusts to the branch
> 7. This will mean that developers will only need to edit one file for all push related changes to our GitHub actions
> 
> Does this make sense to you for the long term health of the project? We don't want a solution that we'll need to fix repeatedly. Are these suggestions clear?

Yeah, got it. It helps us to manage our push workflow more easily. 🚀

**Comment by aialok** [comment]
Should I create a new issue for the inspect.yml file merging?

**Comment by palisadoes** [comment]
> Should I create a new issue for the inspect.yml file merging? If this issue get resolved then merge it. I will create new issue for the graph-introspection in talawa-api.

Yes, a single issue to integrate inspect.yml into push.yml and to fix the automatic branch detection that will be required

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Why is this the introspection test failing in this PR if it is supposed to be pulling from the `develop` schema file in the API, and the API is creating a schema file in `develop` with its workflows?

**Comment by aialok** [comment]
> Why is this the introspection test failing in this PR if it is supposed to be pulling from the `develop` schema file in the API, and the API is creating a schema file in `develop` with its workflows?

As I mentioned earlier in the above comment, some queries and mutation files are missing in the API develop branch. When the workflow runs for auto-generation, it only updates or generates files that are present. However, those schema, mutations, and queries exist in talawa-admin. And because of this test are failing. 


Although the test failure related to `isPublic` being changed to `userRegistrationRequired` is resolved, other queries and mutations are causing issues due to their absence in the API."

**Comment by palisadoes** [comment]
OK, thanks for reiterating the rationale. Please open the other issue and ask to be assigned to it

**Comment by aialok** [comment]
@palisadoes, I've reviewed the commit history and discovered that there's no need to create a new issue for this. The mutations and queries were deleted as part of deprecating the task and project features. In talawa-api the issue is resolved already.

For Talawa-Admin, the problem still persists (#1362). Once this issue is resolved, our graphql-introspection tests will pass successfully :tada:

#### Talawa-API
- Resolved: [talawa-api/issues/1617](https://github.com/PalisadoesFoundation/talawa-api/issues/1617#issue-2061738583)

#### Talawa-Admin
- Pending resolution: #1362

**Comment by palisadoes** [comment]
It's not just the mutations. We still need to make sure the GitHub action in the API automatically adjusts for the branch and consolidate the YAML into a single file. Please open an issue to do this.

**Comment by aialok** [comment]
> It's not just the mutations. We still need to make sure the GitHub action in the API automatically adjusts for the branch and consolidate the YAML into a single file. Please open an issue to do this.

- Sure, I will be creating the issue.

- Regarding the graphql-introspection failed, it is only cause by the deprecating the project/task from talawa-api. If in talawa-admin depracating feature project/task got resolved then our graphql-introspection will pass.

**Comment by palisadoes** [comment]
Understood. Please proceed.

**Pull request merged**
