### PR TITLE
Agenda category CRUD operations

### LINKED ISSUE #1676: Add Support for Organization Agenda Item Categories
**Is your feature request related to a problem? Please describe.**

1. Add CRUD support for the newly implemented organization agenda item categories in the API

**Describe the solution you'd like**
1. Add the feature to the current Admin organization settings section
1. Follow the Figma design guide look and feel. This screen has not been designed.
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Related Issues**

- https://github.com/PalisadoesFoundation/talawa-api/issues/1588
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1676

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
CRUD operation for organization agenda category

**Issue Number:**

Fixes #1676 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/60101655-5bd0-4d56-ae48-9346af855952

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
  - Introduced agenda category management for organizations, including creating, updating, and deleting categories.
  - Added support for agenda category details, options, and messages in multiple languages (English, French, Hindi, Spanish, Chinese).
  - Implemented new user interfaces for managing agenda categories, including modals for creation, update, and deletion.
  - Added a new route for organization agenda categories in the application.

- **Bug Fixes**
  - Enhanced error handling and success messages for agenda category operations.

- **Tests**
  - Added comprehensive test cases for agenda category components and their interactions.
  - Introduced mock data for testing GraphQL queries and mutations related to agenda categories.

- **Style**
  - Updated styling for agenda category components to ensure consistent visual presentation.

- **Chores**
  - Updated localization files to include new translations for agenda category management.

### CODE REVIEW

**Comment by gautam-divyanshu** [comment]
@palisadoes @Atharva-Kanherkar Please review

**Comment by palisadoes** [comment]
What happens to pre-existing agendas when a category is deleted?

**Comment by gautam-divyanshu** [comment]
> ?

The agendas might be automatically reassigned to a default category if such a mechanism exists. This ensures that no agenda items are left without a category, maintaining organization and accessibility.

**Comment by gautam-divyanshu** [comment]
@palisadoes or The category could be removed, but the agendas themselves remain intact without any category. This may result in the agendas being listed as "uncategorized" or under a generic label such as "No Category."

**Comment by gautam-divyanshu** [comment]
``

> Which option have you implemented?

Currently, there are none because I didn't implement the UI for agenda items. I will implement these features in the agenda item PR, but I can't implement them with this PR.

**Comment by gautam-divyanshu** [comment]
@palisadoes I plan to implement second one , i.e.  agendas being listed as "uncategorized" or under a generic label such as "No Category."

**Comment by palisadoes** [comment]
Is this covered in your test cases here?

**Comment by gautam-divyanshu** [comment]
@palisadoes test cases only check if deletion is working or not. This agenda category does not depend on the agenda item, but agenda items depend on the category, so I can't write anything related to the feature that you are asking. It will be implemented with agenda item issue #1778,

**Comment by gautam-divyanshu** [comment]
To ensure that pre-existing agenda items remain intact but become "uncategorized" or assigned to a generic label such as "No Category" when their associated category is deleted, I will implement a middleware function in Mongoose. This middleware function should be triggered before the deletion of an AgendaCategory. It will update any AgendaItem that references the category being deleted, setting the category reference to null or replacing it with a reference to a "No Category" category.

**Comment by gautam-divyanshu** [comment]
categoryId will be updated to default using that middleware

image

**Comment by gautam-divyanshu** [comment]
@palisadoes  So can we merge this PR?

**Review by Atharva-Kanherkar — DISMISSED** [review]
It looks good to me!

**Comment by gautam-divyanshu** [comment]
@palisadoes ??

**Comment by palisadoes** [comment]
Please address the code rabbit suggestions and increase the test code coverage for the patch.

**Comment by gautam-divyanshu** [comment]
@palisadoes  you can merge now, code coverage is 98.34%

**Comment by gautam-divyanshu** [comment]
@palisadoes workflow failing because of merging of latest pr from dependabot 
getting this error in latest develop branch 

image

**Comment by gautam-divyanshu** [comment]
@palisadoes And can we merge this PR because I have to update this PR again and again?

**Comment by gautam-divyanshu** [comment]
@Cioppolo14 Please take a look

**Pull request merged**
