### PR TITLE
Fixes #1514 redesign the Posts screen for the talawa user portal

### LINKED ISSUE #1514: USER REDESIGN: redesign the Posts screen for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Posts screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.
current situation :
Screenshot 2024-01-28 at 11 52 42 PM
Desired Result:
Screenshot 2024-01-28 at 11 47 04 PM

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gauravsingh94**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1514 

**Did you add tests for your changes?**

Yes 

**Snapshots/Videos:**

[Screenrecod.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/adc7e2af-a1ce-49dc-8c62-ed1900f64ef3)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by gauravsingh94** [comment]
I am not able to figureout why the graphql test is not passing. it is working locally in my system. I have also fetch the lastest change of the backend.

**Comment by Cioppolo14** [comment]
@gauravsingh94 Can you fix the failing codecov checks?

**Comment by gauravsingh94** [comment]
@Cioppolo14  I have added the tests.

**Comment by Cioppolo14** [comment]
@gauravsingh94 The test application check is still failing.  Can you fix it?

**Comment by varshith257** [comment]
@aashimawadhwa @rishav-jha-mech In redesigning the User Portal, Are we removing the comment functionality on posts? Can clarify this?

**Comment by gauravsingh94** [comment]
@Cioppolo14 

The test error I am encountering is not related to the changes I have made.

In my pull request (PR), the test is failing in the `Event.tsx` file because it is behind the `develop` branch. When I tried to update my PR with the `develop` branch, I discovered that tests were also failing in the `develop` branch. 

I then cloned the entire project again and found that tests were failing in the `talawa-admin` `develop` branch without any changes being made.

The tests started failing in the `EventCalendar.test.tsx` file without any modifications.

 Here's the sequence of steps I followed:

1. I cloned the Talawa Admin repository.
2. I switched to the `develop` branch.
3. I ran the following commands:
   ```
   npm install
   npm run test --watchAll=false --coverage
   ```
   
   
   
   
image

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by gauravsingh94** [comment]
> @gauravsingh94 The test application check is still failing. Can you fix it?

@Cioppolo14 
I have fixed all the tests

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@gauravsingh94 Please fix the conflicting files and failed tests.

**Comment by palisadoes** [comment]
Closing as potentially abandoned. We can reopen it if requested.

**Pull request closed without merging**
