### PR TITLE
Dashboard interactive cards refactored

### LINKED ISSUE #573: Cards in the dashboard are not interactive.
**Is your feature request related to a problem? Please describe.**
The cards are not interactive yet, we have functionalities for four cards right now,
we can link the: 

1. event card with the event section from the navbar, 
2. post card to the post section from the navbar, 
3. members card to the people section from the navbar.
4.  blocked users card to Block/Unblock section from the navbar

**Describe the solution you'd like**
Add a on click functionalities and link cards to the menu from the navbar as explained above
Screenshot 2023-03-08 at 9 12 13 AM

**Additional context**
**This is a good first issue and we welcome newcomers and beginners to  look into them**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by KrutikaBhatt**
**What kind of change does this PR introduce?** 
This PR refactors interactive cards from the organization dashboard that are linked to the navbar

**Issue Number: #573**
This PR fixes #573 

**Did you add tests for your changes?** No extra tests were needed, but all test cases returned successfully after the changes were made. 

**If relevant, did you update the documentation?** No 

**Does this PR introduce a breaking change?** No

**Other information**
The major functionality was covered and fixed in this PR #620. I have just refactored and removed extra variables and function lines.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?** Yes

### CODE REVIEW

**Comment by KrutikaBhatt** [comment]
This  PR passed the tests earlier. I will just check it out properly

**Comment by KrutikaBhatt** [comment]
All the test cases pass but there are specific errors and warning messages in console while performing `yarn test` which is not due to changes in `OrganizationDashboard.tsx`.  <br>
image

Should I create another issue for these or rectify into the same PR ?

**Comment by palisadoes** [comment]
Please fix the code that is causing the tests to fail. We cannot have errors entering the code base. We don't allow failing test cases to be merged, however sometimes unit tests break when a dependency changes.

**Review by Rumone — APPROVED** [review]

**Review by ttaylor92 — CHANGES_REQUESTED** [review]
1. Was the commit histroy sqaushed? I see more changes in commits than insite files changed
2. Test coverage is a priority, please ensure that test cases are passing.

**Comment by palisadoes** [comment]
@KrutikaBhatt Are you still working on this?

**Comment by KrutikaBhatt** [comment]
> @KrutikaBhatt Are you still working on this?

No sir, the functionality is already developed and merged. The failing test cases are not because of this file. We can create separate issues for it. We can close this PR for now

**Pull request closed without merging**
