### PR TITLE
Added folding feature to posts

### LINKED ISSUE #545: Feature Request: Creating a separate page for each Post when clicked on the post
**Is your feature request related to a problem? Please describe.**
We can write an much as content in the description of a post and the whole description is rendered in that post in the posts sections which makes things look uneven

**Describe the solution you'd like**
I suggest to reduce the length of description to 100 letters (or any other limit) and then render it on the main page where all the posts will be there...
Then if a user wants to see the whole post, he can click on that post and a new page with whole post will appear.

The image clears all:

Screenshot from 2023-03-07 17-24-59

and i think it should be something like this where the string is shortened to 100 letters followed by '...' and then if the user wants to see the whole post, he can click on the post:
Screenshot from 2023-03-07 17-22-19

This will make all the postCards to be of the same size and the improve the UI
**Describe alternatives you've considered**
Or we can skip making a new page and instead add a button of readmore at the end after shortening the string and if the user clicks on it, the post should expand.

### PR DESCRIPTION
**Pull request by anurag0006**
**What kind of change does this PR introduce?**
a feature

**Issue Number:**
#545 

Fixes #545 

**Did you add tests for your changes?**

**Snapshots/Videos:**
[Screencast from 09-03-23 01:13:53 AM IST.webm](https://user-images.githubusercontent.com/107215525/223850810-c8784a5b-e254-4b8a-94d9-152e3fa9cb51.webm)

**If relevant, did you update the documentation?**
Not required

**Summary**
The feature closes #545

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@anurag0006 Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

 - The overall code coverage drops below the target threshold of the repository
-   Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by palisadoes** [comment]
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Comment by anurag0006** [comment]
@Cioppolo14  @palisadoes i went through the documentation of testing-library but wasn't to sort this code coverage...Can you please assign me a mentor or someone who knows testing and who can help me sort this code coverage

**Comment by anurag0006** [comment]
improved the code coverage to 100%... please merge this PR so that i could start working on next one @Cioppolo14  @palisadoes

**Comment by anurag0006** [comment]
There are some other bugs that need to be fixed:
1. The recently added post displays at the end, this needs to be fixed so that the most recent post displays at the top.
2. The posts per each page is set to 5 intially which looks bad as a lot of space is left empty...i suggest to change it to 6 so that the symmetry is maintained.

Should i also fix these both bugs along with this PR ?

**Comment by anurag0006** [comment]
Sorry i had made some mistake in the code and had to revert back to the prev. commit....I will solve the above mentioned bugs in another Issue very soon...So can you please merge this PR @palisadoes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
