### PR TITLE
Plugin and  advertisement screen revamp

### LINKED ISSUE #1918: ADMIN REDESIGN: redesign the advertisement and plugin screen in talawa-Admin portal
**Is your feature request related to a problem? Please describe.**
Redesigning the Advertisement and Plugin Screen from existing design
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
Attaching the screenshots for reference

**Current Situation**
Advertisement:
image
Plugin:
image

Redesign:
Organization_ Advertisement (1)

Organization_ Advertisement

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

Redesign

**Issue Number:**

Fixes #1918

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
image
image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Release Notes

- **New Features**
	- Renamed "Add On Store" to "Plugin Store" for clarity.
	- Introduced search functionality in the Advertisements component.
	- Enhanced plugin filtering options in the AddOnStore.

- **Bug Fixes**
	- Improved date validation in Advertisement tests.

- **Documentation**
	- Updated pull request template to clarify branching strategy and contribution guidelines.

- **Style**
	- Adjusted styles for buttons and advertisement entries to improve visual presentation.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please make the suggested code rabbit updates to the code

**Comment by palisadoes** [comment]
Please fix the conflicting files and address the coderabbit suggestions

**Comment by duplixx** [comment]
sorry for late response i'll make the suggested changes

**Comment by palisadoes** [comment]
Please fix the conflicting files.

**Comment by palisadoes** [comment]
Closing. Inactivity and many conflicting files

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by duplixx** [comment]
> Are you still working on this?

revamped has already been done here, i guess there are some conflict after the branch change.. I'll fix it so that it can be merged ASAP

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
