### PR TITLE
fixes: #598 length check for the organization's name

### LINKED ISSUE #598: Adding check for the length of the organization name
**Describe the bug**
As now we are rendering name of the organization on the dashboard, having large name will break the styling 

**To Reproduce**

1.  create an organization
2.  give it a big name
3. open dashboard of that organization
4. see the error

**Expected behavior**
- Either we can check the length or can control the overflow situation at the navbar.

**Actual behavior**
it is overflowing and breaking the styling.

**Screenshots**
Screenshot 2023-03-09 at 6 25 57 PM (2)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
BugFix

**Issue Number:**

Fixes #598 

**Did you add tests for your changes?**
 Not required

**Summary**

Added length check for the organization's name in create organization modal
**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@palisadoes I guess there is an issue with the CI/CD. The changes looks good to me but still the console.warn is there. 
We have to create various issues for each file to fix the console warns and we have to make changes in the CI/CD to make it pass with the warnings

**Comment by aviraldevv** [comment]
@aashimawadhwa I am sorry but I think both of your branches were not synced before submitting PR, try resyncing and submitting the PR it should pass.
Screenshot_391

**Comment by aviraldevv** [comment]
@aashimawadhwa try sync your branch to recent commits , see if it works .

**Comment by beingnoble03** [comment]
I guess the limit needs an improvement. Even `The Palisaodes Foundation` has more than 15 characters.

**Comment by literalEval** [comment]
@beingnoble03 yeah I mean these changes are done on the UI part, like we can truncate the word if that's taking a lot of space. Forcing a small name is a bad idea @palisadoes

**Review by noman2002 — CHANGES_REQUESTED** [review]
Set the MaxLength to 50

**Comment by aviraldevv** [comment]
@noman2002 I feel organization name should not be next to Palisadoes Icon we can place it somewhere below it.What do you think ??

**Comment by aviraldevv** [comment]
Screenshot_394
Also if we still want to display name next to logo we can follow this UI with a dropdown which displays full name.

**Comment by EshaanAgg** [comment]
@aashimawadhwa 
The backend currently has checks implemented for these length validations as well. It is on utmost importance that the constraints between the two are communicated effectively.

Right now, the backend allows the max length for name to be 256, location to be 50 and description to be 500 characters.
Kindly first discuss the appropriate length for all these 3 fields with the mentors, and then make the changes (if needed be) first in backend, and only then in Admin to ensure continuous functionality. The PR should be updated to reflect the same.

**Comment by aashimawadhwa** [comment]
closing this and opening an issue in the API, this doesn't  require any work in the Admin.

**Pull request closed without merging**
