### PR TITLE
update pull-request.yml to ignore actions on ignore-sensitive-files-pr

### LINKED ISSUE #2383: Admin: Create PR GitHub Actions logic for the ignore-protected-files-pr label
**Is your feature request related to a problem? Please describe.**

1. The `pull-request.yml` workflow file has a section called `Check-Sensitive-Files`
1. This GitHub action:
    1. was created to flag PRs that edited sensitive files that we want to protect from unauthorized changes
    1. is run on all PRs except those submitted by `dependabot`
1. There are cases where community members need to edit sensitive files. When this is done, the `Check-Sensitive-Files` test fails. Our formal GitHub contributors can only merge PRs where all tests pass. This means the Repository owners have to merge the PRs. This creates a bottleneck in PR reviews

**Describe the solution you'd like**

1. There is a `ignore-sensitive-files-pr` label in this repository
1. We want only the `Check-Sensitive-Files` GitHub action to be ignored if this label is applied to the PR by any of our GitHub contributors
1. No other functionality must be altered, especially the logic where the  `Check-Sensitive-Files` GitHub action is also not run when the PR author is the `dependabot` user.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by govindsingh3477**
label

**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #2383

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a new validation step to ensure pull requests target the 'develop' branch.
- **Improvements**
	- Enhanced conditions for sensitive file checks to avoid unnecessary validations for specific pull requests.

### CODE REVIEW

**Comment by govindsingh3477** [comment]
@varshith257 can you please help me why this "PR Workflow / Runs Introspection on the GitHub talawa-api repo on the schema.graphql file (pull_req" is failing?

**Comment by palisadoes** [comment]
Please fix the introspection tests. That will be needed to determine whether this PR will cause the desired behavior. 

You should ask to be assigned to this issue too and make the changes a part of this PR.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/2385

**Comment by govindsingh3477** [comment]
@palisadoes  sir , Do you want me to solve  issue #2385 in this pr or i can create a separate pr ?

**Comment by varshith257** [comment]
> @palisadoes  sir , Do you want me to solve  issue #2385 in this pr or i can create a separate pr ?

@govindsingh3477 Your wish but the aim is to make all workflows green

**Comment by govindsingh3477** [comment]
This issue arises due to createGroupChat , createDirectChat ,createMessageChat were removed in commit 2f605f927348dba23978c749ade7d52ff56d2195 , now i should remove these from talwa admin ?

**Comment by varshith257** [comment]
See here 
https://github.com/PalisadoesFoundation/talawa-admin/pull/1500

**Comment by varshith257** [comment]
But I think it is worked by @disha. Let's confirm from her

**Comment by govindsingh3477** [comment]
i think these can be removed as some related functions were removed in 
https://github.com/PalisadoesFoundation/talawa-admin/commit/ca7c569060cc0f4cd16d10458393346aaecc1099

**Pull request closed without merging**
