### PR TITLE
Implemented featurs for Postfeed Management

### LINKED ISSUE #921: Improved Grid view for the post newsfeed dashboard
**Is your feature request related to a problem? Please describe.**

Currently we have various cards to manage the post of an organization which is not up to the design standards .

**Describe the solution you'd like**
I suggest using grid system like Instagram web to provide with a concise and neat view of all the posts.

**Additional context**
Features to be added in this PR:

1. Improved grid view for the dashboard in the post management.
2. A detailed view for post
3.  elimination pagination to introduce infinite scroll.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #921 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

Screenshot 2023-10-06 at 2 44 05 AM
Screenshot 2023-10-06 at 2 43 53 AM
Screenshot 2023-10-06 at 2 44 00 AM
**If relevant, did you update the documentation?**

**Summary**
Implementation of the post feed management for the talawa admin.

**Does this PR introduce a breaking change?**

No
**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by ttaylor92 — DISMISSED** [review]

**Comment by palisadoes** [comment]
@aashimawadhwa Please work on the tests for this. I'll message after the coffee coverage requirement is met

**Comment by aashimawadhwa** [comment]
@palisadoes I think we can merge this as the coverage is only declining by 0.6% and still it's above the acceptable test coverage. I have to submit another PR for people management and it is ready .

**Comment by palisadoes** [comment]
@aashimawadhwa Any updates on this?

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa Any updates on this?

no as of now sir, I texted on group for the same.

**Pull request merged**
