### PR TITLE
Adding count line script and workflow improvement

### LINKED ISSUE #37: Organise github workflow and add script
**Is your feature request related to a problem? Please describe.**
Creation of only two `yml` file, one for issues and one for PR and organise the workflow code.
We can add the countline script here and it will help to make sure the project is structured.

**Describe the solution you'd like**
2 yml files:
1. issues.yml
2. pull-request.yml

**Approach to be followed (optional)**
The current 3 yml files will be updated to two yml files and if allowed the addition of countline script

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Closes #37 

**Did you add tests for your changes?**
Not needed

**If relevant, did you update the documentation?**
Not needed

**Summary**
It will organise workflow and improve code quality

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please complete the tasks before creating the pull request. Too many draft pull requests sometimes cause our workflows to fail. I'll close this.

**Comment by palisadoes** [comment]
@DangaRanga Is there another issue related to this? I thought @yasharth291 had submitted something in the past.

**Comment by yasharth291** [comment]
hello @palisadoes  sir this is another flow which will count the number of line in the pr i just added error and run checking workflows

**Comment by palisadoes** [comment]
@sumitra19jha  Let me know when you are ready to resubmit. Is 300 lines the expected minimum for react? What changes to the script will be required?

**Pull request closed without merging**
