### PR TITLE
Add/ test for OrgPost.tsx

### LINKED ISSUE #271: Code Coverage: Create tests for OrgPost.tsx
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/screens/OrgPost/OrgPost.tsx`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/screens/OrgPost/OrgPost.test.tsx`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/screens/OrgPost/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
## Work in Progress

**What kind of change does this PR introduce?**
Added test cases.
**Issue Number:**

Fixes #271 

**Did you add tests for your changes?**
Yes
**Snapshots/Videos:**
to be Added later
**If relevant, did you update the documentation?**
Not required
**Summary**
Adding the tests
**Does this PR introduce a breaking change?**

No

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by SiddheshKukade** [comment]
> Please also include the issue number. Closing.

Added the issue number #271. Please re-open.

**Comment by palisadoes** [comment]
Please fix the linting error

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the linting errors.

**Comment by SiddheshKukade** [comment]
> Please fix the linting errors.

Sure. Actually this is currently  work in progress I will ping you once its ready.

**Comment by Tajcore** [comment]
Could you remove all unused methods and ensure the code base is properly linted

**Comment by Kevoniat** [comment]
@SiddheshKukade  any update on this?

**Comment by palisadoes** [comment]
@SiddheshKukade I'm closing. There has been no activity for a week

**Pull request closed without merging**
