### PR TITLE
fixed #2505 :Refactor CSS Structure for EventVolunteers: Improved Maintainability and UI Consistency

### LINKED ISSUE #2505: Refactor CSS files in src/screens/EventVolunteers
# Refactor CSS files in src/screens/EventVolunteers

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by gurramkarthiknetha**
**What kind of change does this PR introduce?**

Feature/Refactoring

**Issue Number:**

Fixes #2505 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

N/A 

**If relevant, did you update the documentation?**

No 

**Summary**

This PR refactors the CSS structure for the `EventVolunteers` and its related components. The changes involve merging all CSS files from the subdirectory and related components into the global CSS file. After the merge, the old CSS files were deleted, and the components were updated to reference the global CSS. This improves maintainability and adheres to the updated design patterns.

**Does this PR introduce a breaking change?**

No, these changes only refactor the existing CSS structure.

**Other information**

Testing was completed to ensure no UI regressions. All screens were verified for consistency with the updated global CSS styles.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced new CSS classes for enhanced UI components, including dropdowns, buttons, and modals.

- **Bug Fixes**
	- Improved error handling and logging in the GroupModal component.

- **Documentation**
	- Updated test cases for the OrganizationScreen component to utilize CSS module styles.

- **Refactor**
	- Streamlined styling import paths across various components.
	- Adjusted internal logic in the GroupModal for better clarity and maintainability.
	- Updated class names for consistency across multiple components.

- **Chores**
	- Removed obsolete CSS file for Event Volunteers, affecting its visual presentation.

### CODE REVIEW

**Comment by gurramkarthiknetha** [comment]
image
now all tests are passed

**Comment by gurramkarthiknetha** [comment]
> image now all tests are passed

All tests pass on my local machine, but the [Test Application (pull_request)] is failing.

**Comment by gurramkarthiknetha** [comment]
image
tests are passed in my local machine

**Comment by palisadoes** [comment]
Please fix:

1. Any failing tests (Click on the `details` link for more information)
1. Any conflicting files

Make sure CodeRabbit.ai approves your changes

**Comment by gurramkarthiknetha** [comment]
> Please fix:
> 
> 1. Any failing tests (Click on the `details` link for more information)
> 2. Any conflicting files
> 
> Make sure CodeRabbit.ai approves your changes

now is this ok ??

**Comment by gurramkarthiknetha** [comment]
the codecov is getting 75% due to the setupTests.ts file in that i just increased some time due to the tests are not getting passed due to insufficient time but it's not related to my pr

**Review by palisadoes — CHANGES_REQUESTED** [review]
It appears that the file `src/screens/EventVolunteers/EventVolunteers.module.css` has been truncated to a blank file but not completely deleted as expected. Please verify.

**Comment by Cioppolo14** [comment]
@gurramkarthiknetha Please fix the failing tests.

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha Please fix the failing tests.

All tests are passed except that schema.graphql that is not related to my pr

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please try to get the test code coverage test to pass for your modified files. We need the code coverage to match that of the repository overall to maintain the code's stability

image

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1. The overall code coverage drops below the target threshold of the repository
2. Any file in the pull request has code coverage levels below the repository threshold
3. The code does not comply with our linting check or other related formatting requirements 

Here are some steps to take:

1. Click on the `Details` link for the tests to get an explanation of the cause(s)
2. You may have to fix a test that is not related to this PR as in some rare cases we merge faulty test code. If this is the case, fix the test in this PR. Do not open another issue.

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

Additional notes:

1. Ensure that CodeRabbit.ai approves your work
1. Please fix any conflicting files

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1. The overall code coverage drops below the target threshold of the repository
2. Any file in the pull request has code coverage levels below the repository threshold
3. The code does not comply with our linting check or other related formatting requirements 

Here are some steps to take:

1. Click on the `Details` link for the tests to get an explanation of the cause(s)
2. You may have to fix a test that is not related to this PR as in some rare cases we merge faulty test code. If this is the case, fix the test in this PR. Do not open another issue.

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

Additional notes:

1. Ensure that CodeRabbit.ai approves your work
1. Please fix any conflicting files

**Comment by palisadoes** [comment]
Please improve the code coverage for the patch.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
