### PR TITLE
Script created for github action to check atleast one tsdoc comment

### LINKED ISSUE #2155: Feature Request: Create a github action to check TSDoc comments in .tsx file
**Is your feature request related to a problem? Please describe.**
github action, each file must have atleast one tsdoc comment, 

**Describe the solution you'd like**
Create a script

**Additional context**
Part of Internship phase 1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2155

**Did you add tests for your changes?**

**Snapshots/Videos:**
Screenshot from 2024-08-06 21-33-10

Screenshot from 2024-08-06 17-45-32

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Introduced a utility to validate TSDoc comments in TypeScript React component files.
	- Added a new script command to check for TSDoc comments during the build process.
	- Enhanced the GitHub Actions workflow to include a step for TSDoc comment validation.
	- Updated the mock data to extend the duration of a funding campaign.

- **Bug Fixes**
	- Improved documentation standards by ensuring that files without TSDoc comments are flagged.
	- Temporarily disabled specific test cases related to the rendering of the Campaign Pledge screen.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please take a look at the coderabbit suggestions and implement them where valid

**Comment by GlenDsza** [comment]
@gautam-divyanshu the test application check failing could be resolved by changing the year values of endDate on following line
[https://github.com/PalisadoesFoundation/talawa-admin/blob/3d4a87e6f591fcaef973c5398a2c6418e61309ba/src/screens/FundCampaignPledge/PledgesMocks.ts#L25](https://github.com/PalisadoesFoundation/talawa-admin/blob/3d4a87e6f591fcaef973c5398a2c6418e61309ba/src/screens/FundCampaignPledge/PledgesMocks.ts#L25)

Set the endDate to something in far distant future `endDate: "2034-08-08"`. I have changed this in my recent [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2163) but it might take time to get merged as the size of changes in other files is vast

**Comment by gautam-divyanshu** [comment]
@GlenDsza 
Ok, Thanks for informing.

**Comment by gautam-divyanshu** [comment]
@GlenDsza getting this error after changing the date, 
image

**Comment by gautam-divyanshu** [comment]
I can comment out the failing test case for this PR, and when your PR will merge then it will be fixed, so what do you think?

**Comment by GlenDsza** [comment]
> I can comment out the failing test case for this PR, and when your PR will merge then it will be fixed, so what do you think?

Yes works

**Comment by gautam-divyanshu** [comment]
@GlenDsza I have commented out 3-4 test cases, but after commenting a test case, the next test case fails.

**Comment by gautam-divyanshu** [comment]
image

**Comment by gautam-divyanshu** [comment]
@GlenDsza  If test cases for this file are failing, then how did they get merged?

**Comment by GlenDsza** [comment]
> @GlenDsza If test cases for this file are failing, then how did they get merged?

Dont know why its failing for you but it is not failing in my local (develop) 
image

neither it failed in my latest [UI PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2163) (have made some changes to code though)

**Comment by GlenDsza** [comment]
> @GlenDsza I have commented out 3-4 test cases, but after commenting a test case, the next test case fails.

the cascading failing of test case is due to memory leak somewhere in previous test case, which is causing next following test case to fail. You'll have to identify which test case is causing subsequent one to fail, once you comment those rest are good to go

**Comment by gautam-divyanshu** [comment]
> > @GlenDsza If test cases for this file are failing, then how did they get merged?
> 
> Dont know why its failing for you but it is not failing in my local (develop) image
> 
> neither it failed in my latest [UI PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2163) (have made some changes to code though)

Test cases are failing locally also.

**Comment by gautam-divyanshu** [comment]
@GlenDsza Memory leak is in these 2 test cases, 
image
image
image

**Comment by gautam-divyanshu** [comment]
@palisadoes Please merge this PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please put the script in the .github/workflows directory as it is related to github actions

**Pull request closed without merging**
