### PR TITLE
Fix user profile buttons layout and added form validation

### LINKED ISSUE #1060: Bug Report:User profile and editing funcationality is not working correctly.
**Describe the bug**
There are a lot of problem in the user profile page.

1. On side navbar when we click on the profile page it says `profile page coming soon`. As it is already made so we should add that page to that button.

 image

3. `Edit` and `add admin`  button style issue. They design of the `edit` and `add admin` button is not looking good.

image

5. Form validation is not working properly in the edit profile page.

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/760d6856-6634-4f81-a8e8-a6a6227060b2

The form can also be submitted using white spaces.

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/e170d8cf-fe24-47cf-b26f-ab73f7a4f1b2

**To Reproduce**

1.Go to the Talawa members page.
3.Click on users.
5.Click on anybody's profile.
6.See the design of the edit and add admin button.
7.Click on edit button it will open your profile, no matter whose profile you are watching at that time.
8.Submit the form using blank values or white spaces in the first name and last name. You see the form gets submitted without any errors. 

**Expected behavior**
Profile button should redirect the user to the profile page.
Design of edit and add admin button should be corrected.
Form validation should be there in the edit profile page.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by skbhagat0502**
**What kind of change does this PR introduce?**

A bug fix and UI/UX

**Issue Number:**

Fixes #1060 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/ab23570a-8ca5-402b-a1e9-2ca3334761ec

**If relevant, did you update the documentation?**

**Summary**

I linked the profile to the buttons on the left drawer. Also I corrected the layout of the Add admin and Edit profile button. Added the required validation in the userUpdate form.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by skbhagat0502** [comment]
@palisadoes @noman2002 Please review.

**Comment by skbhagat0502** [comment]
@palisadoes @noman2002 Please review.

**Comment by palisadoes** [comment]
1. Please fix the code test coverage on the patch. We need to get it to 100%
2. We have allowed our coverage to drop and we need to get it back up

**Comment by skbhagat0502** [comment]
> 1. Please fix the code test coverage on the patch. We need to get it to 100%
> 2. We have allowed our coverage to drop and we need to get it back up

Ok @palisadoes

**Review by noman2002 — APPROVED** [review]
Looks good to me. 
@aashimawadhwa @rishav-jha-mech @EshaanAgg Please review.

**Comment by noman2002** [comment]
@skbhagat0502 Pull the latest code and push it to the current branch.

**Comment by skbhagat0502** [comment]
> @skbhagat0502 Pull the latest code and push it to the current branch.

Ok @noman2002

**Review by aashimawadhwa — APPROVED** [review]

**Pull request merged**
