### PR TITLE
Fix plugin errors and made the filter working.

### LINKED ISSUE #1009: Bug Report: Installed Plugins are not fetched correctly and showing errors.
**Describe the bug**
When I click on the installed plugins button available at the plugin store page, it shows plugins does not exists even if there are plugins installed. Also after a few milisecond the following error is shown.

Screenshot 2023-10-26 091859
Screenshot 2023-10-26 091826
Screenshot 2023-10-26 092228

**To Reproduce**

1.Login
2.Go to your organisation dashboard.
3.Click on plugin and then plugin store.
4.Click on installed button to see installed plugins.

**Expected behavior**
All installed plugins should be there.

**Actual behavior**
Throwing an error as shown in picture.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by skbhagat0502**
**What kind of change does this PR introduce?**

A bug fix and feature.

**Issue Number:**

Fixes #1009 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/4592ca5c-b804-4c0b-9b31-c61bd91e4519

**If relevant, did you update the documentation?**

**Summary**

When trying to see the installed plugin in talawa admin it throws error. Which is now resolved. There was a lot unnecessary code which I have removed now. The code now looks clear and is working fine now. I have made some changes in the filter also. 
Now all filters is working fine.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by skbhagat0502** [comment]
@palisadoes  I haven't added the tests yet for the changes made in this PR. Since there are many alterations in the AddOnStore.tsx file, I'd like to get it reviewed first to ensure that the changes align with your expectations. Once this review is done, I'll proceed with writing tests. As there are already open issues for writing tests for AddOnEntry.tsx and AddOnStore.tsx, my plan is to merge this first and then write tests, referring to those issues. Your feedback is essential in maintaining a cohesive and well-tested codebase.

**Comment by noman2002** [comment]
@skbhagat0502 Please fix the failing test.

**Comment by skbhagat0502** [comment]
> @skbhagat0502 Please fix the failing test.

@noman2002 I've made significant changes to the code in the file, and the previous version didn't have proper tests, resulting in a coverage of around 20 to 25 percent. Before investing time in writing tests, I want to ensure that the new code aligns with expectations and functions correctly. Once the code is reviewed and confirmed to be in good shape, I'll proceed with writing tests for it. This approach ensures that testing efforts are focused on stable and intended behavior.

**Comment by noman2002** [comment]
@skbhagat0502 Please write the tests firsts then only someone will able to review it and merge it in one go. Otherwise the reviewer have to iterate it again and again. I would suggest you to please write the tests to make sure all the tests are passing.

**Comment by skbhagat0502** [comment]
> @skbhagat0502 Please write the tests firsts then only someone will able to review it and merge it in one go. Otherwise the reviewer have to iterate it again and again. I would suggest you to please write the tests to make sure all the tests are passing.

ok @noman2002

**Pull request closed without merging**
