### PR TITLE
Refactoring CSS files: merged PageNotFound styles into global app.module.css

### LINKED ISSUE #2524: Refactor CSS files in src/screens/PageNotFound
# Refactor CSS files in src/screens/PageNotFound

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by mandeepnh5**
**What kind of change does this PR introduce?**

Refactoring CSS files: merged PageNotFound styles into global app.module.css

**Issue Number:**

Fixes #2524 

**Did you add tests for your changes?**

Yes

**Summary**

It is my first PR on Palisadoes Foundation and I am looking forward to contribute more to this organization.
This PR solves the problem of having a single global CSS file instead of having many CSS files in sub directories.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the "Page Not Found" component, ensuring a visually distinct and responsive design across various devices.
- **Bug Fixes**
	- Updated the import of styles for the "Page Not Found" component to reference a new CSS module, improving consistency in styling.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

Also ensure that CodeRabbit.ai approves your work

**Comment by mandeepnh5** [comment]
The checks which were not successful were out the scope of this PR I think because the I followed all linting rules and other and as it was only a CSS file I don't think there is issue in the talawa-api check.

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by mandeepnh5** [comment]
@palisadoes  But why is it conflicting the task was to put pagenotfound css code to global css file right

**Comment by varshith257** [comment]
@mandeepnh5 The conflicts occur because multiple people change this global file from different PRs, just need to take care of them

**Comment by palisadoes** [comment]
Yes

**Comment by mandeepnh5** [comment]
@palisadoes Now all the checks are passing except the talawa api. I am not why is it an issue or can be skipped

**Comment by palisadoes** [comment]
@AVtheking @varshith257 PTAL

**Comment by mandeepnh5** [comment]
@varshith257 is there an issue still ?

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix:

1. Any failing tests (Click on the `details` link for more information)
1. Any conflicting files

Make sure CodeRabbit.ai approves your changes

**Comment by mandeepnh5** [comment]
> Please fix:
> 
> 1. Any failing tests (Click on the `details` link for more information)
> 2. Any conflicting files
> 
> Make sure CodeRabbit.ai approves your changes

I dont know what happened suddenly many files have changed but i just pulled the changes and tried to fix the issue

**Comment by palisadoes** [comment]
This PR has too many submitted files that are out of scope of the original issue. 

Please ensure the following:

1. Fetch the latest `upstream/develop-postgres` files
2. Make your PR modifications based on the local copy of this `develop-postgres` branch
3. Submit your PRs against our `develop-postgres` branch.
4. Your source branch in your local repository must not be the same as the target branch

Closing

**Pull request closed without merging**
