### PR TITLE
Removed all eslint-disable lines and added workflow for checking.

### LINKED ISSUE #1460: Admin: GitHub Action Required: Fail on detection of eslint-ignore statements
**Is your feature request related to a problem? Please describe.**

The quality of our code is paramount to us. This includes:

1. Functionality
2. Consistency of coding style for improved readability
3. Following best practice coding standards

To achieve the last 2 points, we have been gradually increasing the linting rules enforced in the repository to maintain a consistency of our code style. We have implemented `githooks` to try to enforce this linting best practice.

Even so, we have seen contributors adding statements to ignore our linting rules.

**Describe the solution you'd like**

1. Remove the typescript linting ignore statements to reveal the original linting errors
1. Fix the causes of the linting errors without affecting functionality
1. Add a test to our pull request GitHub action file to fail if any files submitted in the PR:
    1. under the `src/` directory have ignore statements
    2. the `setup.ts` script in the root directory
1. There may be cases in test files where linting is required, but this should not be the case in non-test typescript files.
1. The GitHub action file is:
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- Evidence of the use of the ignore statements in the `src/` directory

image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

This PR does 2 things:
1. Removes all eslint-disable lines and fixes the underlying errors that were causing the placement of these lines.
2. Adds a github workflow to check if any new PR contains an eslint-disable comment.

**Issue Number:**

Fixes #1460 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

Eslint-disable statements are used for ignoring the below violations of the linting rules. This PR ensures that the tests fail if there is an eslint-disable statement.

**Does this PR introduce a breaking change?**
No

**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@aarishshahmohsin Please fix the failing code patch test.

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin Please fix the failing code patch test.

The test for src/components/AddOn/core/AddOnStore/AddOnStore.tsx is not complete. It only has a temporary test. [Link](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx )
I will have to make a complete test on my own. Should I do it?

**Comment by aarishshahmohsin** [comment]
@palisadoes @Cioppolo14 Is there any update?

**Comment by palisadoes** [comment]
> > @aarishshahmohsin Please fix the failing code patch test.
> 
> @palisadoes  @Cioppolo14 The test for src/components/AddOn/core/AddOnStore/AddOnStore.tsx is not complete. It only has a temporary test. [Link](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx )
> I will have to make a complete test on my own. Should I do it?

Please rectify it

**Comment by aarishshahmohsin** [comment]
> > > @aarishshahmohsin Please fix the failing code patch test.
> > 
> > 
> > @palisadoes  @Cioppolo14 The test for src/components/AddOn/core/AddOnStore/AddOnStore.tsx is not complete. It only has a temporary test. [Link](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx)
> > I will have to make a complete test on my own. Should I do it?
> 
> Please rectify it

@palisadoes There is an error in the ```/src/components/AddOn/core/AddOnStore/AddOnStore.tsx/```
In this file 
```
 const { data, loading } = useQuery(PLUGIN_GET);
```
query is being used to get plugins, but this query does not contain the pluginInstallStatus attribute, which makes the installed plugins not show altogether.

adding this line in the query increases the test coverage from 67.85 % to 100 %. However, this change breaks the 
```src/components/Advertisements/Advertisements.tsx ``` file. This would require a change in the PLUGIN_GET query or a new query for the AddonStore file. Should I make a issue on it?

**Comment by aarishshahmohsin** [comment]
@palisadoes I have made the necessary changes.

**Comment by aarishshahmohsin** [comment]
@palisadoes, please review the submitted PR or close it.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
