### PR TITLE
 Upgrade Yarn to NPM in Talawa Admin Project

### LINKED ISSUE #546: Convert Talawa-Admin to use the NPM package manager
**Describe the bug**

1. Talawa-Admin currently uses Yarn v1. This is end of life.
1. We need to upgrade the package manager to a current product
1. For the sake of consistency, we want to use NPM like Talawa-API

This has caused problems with developing new code like this:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/493#issuecomment-1458162310

**To Reproduce**

1. Update packages
2. Incompatibility errors

**Expected behavior**

When updating packages:

1. No deprecation warnings. 
1. No package incompatibilities 

**Actual behavior**

1. Deprecation warnings. 
1. Package incompatibilities 

**Screenshots**

image

**Additional details**

- See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
This PR changes the current project's package manager from yarn to npm.

**Issue Number:**

Fixes #546 

**Did you add tests for your changes?**
Not Required

**Snapshots/Videos:**
Not Required

**If relevant, did you update the documentation?**
Yes

**Does this PR introduce a breaking change?**
Maybe yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anshgoyalevil** [comment]
@palisadoes @xoldyckk 

Please review.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Is using `--legacy-peer-deps` in the spirit of what we want to achieve? The aim was to use `npm` because the version of Yarn we were using was outdated. Now we will be encouraging the use of legacy dependencies? What would be your plan to remedy this?

**Comment by anshgoyalevil** [comment]
@palisadoes 

Here are some points which we need to consider as of now.

- The project contains a lot of outdated packages, upgrading which could cause several errors. As described in the comment https://github.com/PalisadoesFoundation/talawa-admin/issues/546#issuecomment-1483833671
- I have used the flag ```--legacy-peer-deps``` to fallback to legacy dependencies. What that basically means is the peerDependencies of the project would now be installed as a standalone package even if the required peer dependency version mismatches.
- Every new package installation would now require the ```--legacy-peer-deps``` flag to be added to the ```npm install``` script. For example, if we now want to install ```lodash```, we would have to write ```npm install lodash --legacy-peer-deps```, since ```npm install lodash``` won't work.
  - This can be resolved by adding a new script ```install: npm install --legacy-peer-deps```

We would need to upgrade the packages to latest version which could match the npm version. This would break many things.

The remedy for this would be to upgrade the packages, and fix the source code too. That would take time.

I am not sure if I am doing the right thing by following this approach. @xoldyckk What's your opinion on this?

**Comment by anshgoyalevil** [comment]
@noman2002 Could you please review this PR.

**Comment by anshgoyalevil** [comment]
@xoldyckk Could you please review this PR

**Comment by xoldyckk** [comment]
@palisadoes @anshgoyalevil The primary focus was getting rid of yarn, as contributers were getting confused regarding its installation. Now the latest version of npm present on their systems will be used.

I had hoped some stuff related to packages could be fixed but it's not possible probably. Fixing/replacing the outdated packages requires a great deal of work, it's almost like building the project from scratch. It's a direct consequence of there being no automated dependency updates system. Normally you'd have to update stuff in small parts, but now all those updates have accumulated.

So, I think the PR can be merged.

**Comment by xoldyckk** [comment]
@anshgoyalevil If there are unused packages in the project you can get rid of them, and also update the docs to remove mentions of yarn.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil If there are unused packages in the project you can get rid of them, and also update the docs to remove mentions of yarn.

Yes, I updated the docs to use instances of npm in place of yarn.

I would post a message on Talawa Admin Slack channel regarding the changes, and how to shift the local environment safely with this PR.

For unused packages, I didn't stepped into it. Will create another issue if I found any such dependency.

**Comment by anshgoyalevil** [comment]
@palisadoes 

This PR can now be merged.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
