### PR TITLE
Renamed Private Organisation to userRegistrationRequired

### LINKED ISSUE #1327: Admin - Remove Support for Private Organizations
**Is your feature request related to a problem? Please describe.**
We need to reduce and simplify some of the Talawa features. 

The concept of private organizations is unlikely given that most organizations using Talawa will be non-profits where transparency will be important.

Therefore not just must the organizations be always public. They must also always be visible.

**Describe the solution you'd like**

Remove all support for private organizations in:
1. Sections of screens that contain references this feature
1. Any screens completely dedicated to this feature
1. All supporting code

Other:

1. All tests must be valid and pass
1. No other functionality must be affected.

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1604
2. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327
3. https://github.com/PalisadoesFoundation/talawa/issues/2287

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aialok**
**What kind of change does this PR introduce?**

- Renamed `isPublic` to `userRegistrationRequired`.

**Issue Number:**

close #1327 

**Did you add tests for your changes?**

**Snapshots/Videos:**
- Before :

ispublic

- Removed isPublic and isVisible checked button.

Screenshot from 2024-01-06 14-46-37

Screenshot from 2024-01-06 14-45-17

- We need to change in the backend accordingly.

Screenshot from 2024-01-06 14-47-38

**If relevant, did you update the documentation?**

**Summary**

- Renamed `isPublic` to `userRegistrationRequired` because it is more meaningful and help in developer and user understading.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
@rishav-jha-mech @noman2002 @beingnoble03 

1. Please review
2. The introspection test is going to fail because the PR to remove private organizations from the API hasn't been merged yet.

**Comment by noman2002** [comment]
@palisadoes I think we should not remove it all. we should just make it inaccessible for now but just removing the toggle buttons and keep the rest. We might need it in future.

**Comment by palisadoes** [comment]
@noman2002 

It's being removed in the API too. How do you propose we handle it there?

**Comment by palisadoes** [comment]
Please refer to this discussion before proceeding
- https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274

**Comment by aialok** [comment]
> Please refer to this discussion before proceeding
> 
> * [Feat/remove private org talawa-api#1643 (comment)](https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274)

@palisadoes, I find it more reasonable than removing the whole feature; it also provides more flexibility to the organization. Should I rollback the changes and rename the `isPublic` to  `userRegistrationRequired`  only ?

**Comment by palisadoes** [comment]
Yes

**Comment by aialok** [comment]
- Here is an example :

[cinnamon-2024-01-07T233503+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/9a61858e-c7d7-4eb2-9a59-a8df40ee7550)

- I have not changed anything in the mutations, queires, and apis stuff because we have to changed in backend accordingly.

**Comment by aialok** [comment]
@palisadoes, please review the changes.

**Comment by aialok** [comment]
[cinnamon-2024-01-12T104245+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/cad701bb-df7e-46a3-850c-5fc33bf7e312)

Hi @noman2002, @beingnoble03, @rishav-jha-mech,

I've made all the needed changes. Please check. The test is failing because `schema.graphql ` in ` talawa-api ` hasn't been updated as required.

- Check this out in type organisation, isPublic is still there.

Screenshot from 2024-01-12 11-38-30


Thank You : )

**Comment by aialok** [comment]
@palisadoes please review this change as because of this PR, contributor are facing problem creating an Organisation.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
