### PR TITLE
USER REDESIGN: Redesign the sidenav for Talawa user portal

### LINKED ISSUE #1510: USER REDESIGN: redesign the sidenav for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the sidenav for the user portal and follow a theme similar to the talawa admin portal.

**Additional context**

1. These are the two side navbars that require modifications.
   Please refer the figma file below : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1
1. Try to split this up into several smaller PRs, possibly 2-3 screens at a time. This will make the reviewing process much faster.

**Screenshots**
Screenshot 2024-01-28 at 10 59 53 PM Screenshot 2024-01-28 at 11 00 02 PM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1510
- #1510

Redesign the sidenav of talawa user portal with theme similar to admin portal.

Figma: https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

Top Navbar and Previous sidebar is removed and two sidebars are added:

1. User: 
    - My Organizations -> /user/organizations
    - Settings -> /user/settings
    - UserInfo Button -> /user/settings
    - Sign out -> /user

2. Organization:

    - OrganizationInfo Button -> /user/organizations
    - Posts -> /user/organization/id={id}
    - Events -> /user/events/id={id}
    - Donations -> /user/donations/id={id}
    - UserInfo Button -> /user/settings
    - Sign out -> /user

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/41bd122a-cbb4-49c0-9126-7db4ac46b1a3

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by rishav-jha-mech — COMMENTED** [review]
@pateldivyesh1323 
```
OrgLeftDrawer.module.css
OrgScreen.module.css
UserLeftDrawer.css
```
CSS is being repeated in these files and some files in admin components as well, so you should create a common css file and import it in `src/index.ts`, so that we can prevent code duplicacy.

**Review by rishav-jha-mech — COMMENTED** [review]
@pateldivyesh1323 change the background colour from light grey to the light blue one, which we are using in Admin Screens, the User Screens look inconsistent right now.

**Review by beingnoble03 — COMMENTED** [review]
@pateldivyesh1323 I can see a light blue div in the bottom of every screen in the video. Can you please fix that?

**Comment by pateldivyesh1323** [comment]
@rishav-jha-mech @beingnoble03 I have merged common css, changed background to light blue and fixed extra div at bottom of screen

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/e4f237b7-b75e-4df2-a0d8-e6b25e0e83a0

**Comment by palisadoes** [comment]
Please fix the merge conflicts. 

We cannot review if they are there

**Comment by palisadoes** [comment]
Please close the PR and open smaller ones that are easier to review.

**Comment by palisadoes** [comment]
Closing for the previously stated reason

**Pull request closed without merging**
