### PR TITLE
feat: setup script for .env configuration file

### LINKED ISSUE #1233: Create a Setup Script for the `.env` configuration file
**Is your feature request related to a problem? Please describe.**

1. The current `INSTALLATION.md` file describes how to manually setup the `.env` file
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/main/INSTALLATION.md#creating-env-file 
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file

**Describe the solution you'd like**
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file
1. It should validate the parameters entered and that any services related to the parameters are working correctly
1. The `INSTALLATION.md` file must be updated with the new procedure
1. The table of contents must be regenerated with a link to the new instructions visible

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1233 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by disha1202** [comment]
@palisadoes 
Created a new PR for #1233 
Please take a look

**Comment by palisadoes** [comment]
1. Closing. You have submitted too many files. 184
2. Please resubmit

**Comment by disha1202** [comment]
@palisadoes 

Whenever I push, it automatically creates an `Update documentation` commit. 

I even tried to revert it you can check the commit history but that does not work.

**Comment by palisadoes** [comment]
1. You need rebase against the `develop` branch and add your changes there.
2. Usually when we see so many files submitted it is because the `main` branch was used at some point.

**Comment by disha1202** [comment]
> * You need rebase against the `develop` branch and add your changes there.
> * Usually when we see so many files submitted it is because the `main` branch was used at some point.

The changes in this PR are not because `main` branch is involved but because of the automated commit that updates the documentation.

This is the initial commit that includes changes related to the setup script https://github.com/PalisadoesFoundation/talawa-admin/pull/1459/commits/eed3bdc4536abea1183ec84a650fec61cc2747c8

And then there's this automated commit which updates the documentation https://github.com/PalisadoesFoundation/talawa-admin/pull/1459/commits/2879860830fc50f0005f6f9af4a88c97edd052af and also because of this commit there are so many files changed.

Even if I resubmit the PR this issue will most probably arise again.

**Pull request closed without merging**
