### PR TITLE
[userTypeFix] Fixed Undefined User in Sidebar & Refactoring

### LINKED ISSUE #1772: [userTypeFix] Undefined User in Sidebar in UserPortal & Apollo Error in Console
**Describe the bug**
- On logging in Talawa Admin  in the Sidebar the User Details are undefined. 
- GraphQL query is also failing due to missing variables.

**To Reproduce**

1. Log in as user
2. View The sidebar
3. See the console for error related to query

**Expected behavior**
Below User Avatar Image user First Name, Last name and Email should be present

**Actual behavior**
Instead of user Details undefined is shown

**Screenshots**
image

image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by GlenDsza**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1772 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/1e1b0fe1-1316-4425-8ac1-28424d586ba5

**Summary**

- Fixed the undefined user by resolving failing user apollo query. 
- For user changed `getItem('id')` (which lead to null value) to `getItem('userId')`.
- Added Test cases for partially covered line.
- Refactored `UserSidebar.tsx` and `UserSidebar.test.tsx`

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by GlenDsza** [comment]
@palisadoes need PR Reviewers.

The Files changed in above PR have complete code coverage with all passing tests
image
 
The failing Test Application check is due to failing tests in following Screens: `Donate.test.tsx` , `Chat.test.tsx`, 'Events.test.tsx' and few more which are unrelated to above PR and changes. These failing tests are bound to be solved in their separate Test issues.

**Comment by Cioppolo14** [comment]
@GlenDsza Please fix the Test application check.

**Comment by GlenDsza** [comment]
> @GlenDsza Please fix the Test application check.

Please Check [Comment](https://github.com/PalisadoesFoundation/talawa-admin/pull/1791#issuecomment-2016769918)

@Cioppolo14 The test application check is failing due to issues in files which are unrelated to this PR. Solving all of failing tests of these files seems infeasible as the no of files and tests is large. Rather there are individual issues created for these files which require solving failing tests and increase code coverage e.g.  #1769 #1770 and there are other files as well whose issue regarding failing tests is still to be created.

**Comment by GlenDsza** [comment]
Test Application Check Results:
image

@palisadoes @Cioppolo14  Would be beneficial if PR/Bugs/Features unrelated to above failing test files are continued with merging process as Around 38 failed tests and 9 failed test suites (9 test files) would take time to be fixed even in individual issues.

**Comment by palisadoes** [comment]
Please merge with the latest upstream. We just merged a PR where all the tests were passing.

**Comment by GlenDsza** [comment]
Test Application passed
@palisadoes @Cioppolo14 Sorry for trouble, the error was on my part.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
