### PR TITLE
Added the Filtering Functionality

### LINKED ISSUE #1196: Implement filter functionality for the users list in users page.
**Is your feature request related to a problem? Please describe.**
Currently the filter option is present in the UI, but not implemented.

**Describe the solution you'd like**
I want to implement the filter functionality.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Filter by role of the user 
image

**Additional context**
I really want to work on this feature, please assign this to me.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

this PR adds the filtering functionality in the Users Component.

**Issue Number:**

Fixes #1196 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
[www_screencapture_com_2023-12-25_15_59.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/ce911459-fac2-4a4c-9414-b9c2a20c5cad)

**If relevant, did you update the documentation?**

**Summary**

I have added the filter functionality that was missing from the user component

**Does this PR introduce a breaking change?**

No

**Other information**
I think more can be added, because I saw somethings missing. Should I make an issue? Please also tell if I have to make tests for this PR.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by aarishshahmohsin** [comment]
These tests are failing for all the past few PRs. There must be some error in the  main branch.

**Comment by palisadoes** [comment]
It's related to this issue

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1157

**Comment by palisadoes** [comment]
The offending PR has been reverted. Please merge with the latest upstream

**Comment by aashimawadhwa** [comment]
@aarishshahmohsin can you fix the failing test @aarishshahmohsin

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin can you fix the failing test @aarishshahmohsin

I have fixed them.

**Review by aashimawadhwa — APPROVED** [review]
LGTM 👍🏼

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
