### PR TITLE
GitHub Action: Unauthorized-changes-detection action

### LINKED ISSUE #1526: GitHub Action: Fix `authorized-changes-detection`
**Is your feature request related to a problem? Please describe.**

1. We have a GitHub action file `authorized-changes-detection.yml` that, during pull requests, detects when sensitive files are modified and exits with an error.
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/authorized-changes-detection.yml
1. Unfortunately, as seen in the example PR  below, it does not mention the file(s) that is modifed. This would be very helpful
   1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1488

**Describe the solution you'd like**

1. Migrate the functionality of the `authorized-changes-detection.yml` file to:
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml
1. The action must:
    1.  Identify when one or more configured directories and files are modified during a PR
    2. List the file(s) in this list that were modified
    3. Exit with failure code.
1. The configuration of the list of sensitive files and directories must be done only once in the file. 
1. Do not use the `paths:` statement. It was suitable for a standalone file, but not for `pull-requests.yml` where other jobs run
1. The `authorized-changes-detection.yml` file must be deleted.
1. The new action must not depend on any other job in the YAML file.

**Describe alternatives you've considered**

We think that this GitHub action could be used
- https://github.com/tj-actions/changed-files

**Approach to be followed (optional)**

- See above

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1526 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Have you tested this?
2. Is it possible to do so within this PR?

**Comment by duplixx** [comment]
yeah i can test it in forked repo

**Comment by palisadoes** [comment]
1. Let us know when the testing is complete
2. I'd prefer to see some tests against this PR too

**Comment by duplixx** [comment]
@palisadoes test fails 
also i have tried running using python3 but that also doesn't seems working
here's
https://github.com/duplixx/talawa-admin/actions/runs/7951290497/job/21704540958?pr=18

**Comment by palisadoes** [comment]
Try running it in verbose mode and see whether it's reaching the various steps.

The popen communicate may not be working as expected

**Comment by duplixx** [comment]
Popen isn't working ,popen works on local but isn't working in actions 
image

**Comment by palisadoes** [comment]
What's in the the popen communicate output?

You introspection may be incorrect

**Comment by palisadoes** [comment]
1. I noticed in the GitHub actions that some of the actions were out of date and in some cases deprecated.
2. I updated them. That may be part of the issue. You need to make sure you're using the latest versions in your YAML

**Comment by duplixx** [comment]
After adding Exception handling in Popen communicate output I am getting this Error @palisadoes sir
similar issue like this stackoverflow one
https://stackoverflow.com/questions/45096755/fatal-ambiguous-argument-origin-unknown-revision-or-path-not-in-the-working
image

same code works fine in my local 

image

**Comment by palisadoes** [comment]
Are you still working on this?
I'd prefer someone else to take a look as you already have 3 assigned issues

image

image

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
