### PR TITLE
fix: fixed events lists visibility in desktop and table view in event calendar

### LINKED ISSUE #1746: Bug: Events beyond the first two not visible in desktop and tablet view
**Describe the bug**
Events beyond the first two are not visible in the desktop/laptop and tablet views of our application. However, they are visible in the mobile view.

**To Reproduce**

1. Navigate to any organization dashboard.
2. Go to `Events` screen.
3. Add more than 2 events on the same day.
4. Observe that only the first two events are visible, while the rest are not displayed.

**Expected behavior**
All added events to be visible in the desktop/laptop and tablet views, similar to the mobile view when the number of events created is more than 2.

**Actual behavior**
In the desktop/laptop and tablet views, only the first two events are visible, and the rest are not displayed.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/43c09065-9342-434d-9d0b-7863b3e91a94

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by MahendraDani**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1746 

**Did you add tests for your changes?**

Tests are already covered

**Snapshots/Videos:**

[screen-capture (1).webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/64dc6c52-5bb8-45cc-89f3-6bb3a73dd9d5)

**If relevant, did you update the documentation?**

**Summary**

- If number of events on a day > 2 then `view all` button is visible. Else events are shown in list view

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
You need to write tests for this so that it doesn't happen again

**Comment by MahendraDani** [comment]
@palisadoes I think the changes are already covered with tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by MahendraDani** [comment]
@palisadoes please check

**Comment by palisadoes** [comment]
Your tests are failing

**Comment by palisadoes** [comment]
Closing as potentially abandoned. No recent commits. You can ask to have it reopened

**Pull request closed without merging**
