### PR TITLE
fixed the error while editing admin profile

### LINKED ISSUE #1924: Error when editing Super Admin profile
**Describe the bug**
Error when editing Super Admin profile

**To Reproduce**

1. Start at the Super Admin organization screen:
1. Navigate to the view profile screen
1. Error is visible:

**Expected behavior**

1. No visible error
2. Tests must be created for this fix. All tests must be valid and pass

**Actual behavior**

- See above

**Screenshots**

1. Start at the Super Admin organization screen:

    image

1. Navigate to the view profile screen

    image

1. Error is visible:

    image

**Additional details**

- See above

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by ARYANSHAH1567**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1924 

It does not give error as CreatorId is being passed to the talawa-api so i will have to change a file in the api also so that it handles it correctly and then it will not throw error
Screenshot 2024-09-21 004048

## Summary by CodeRabbit

- **New Features**
	- Added a new query to retrieve organizations based on the creator's ID, enhancing data specificity.
	- Renamed existing queries for improved clarity, shifting focus from organizations to members where applicable.

- **Bug Fixes**
	- Updated variable naming in the component to align with the new query, ensuring accurate data retrieval based on creator ID.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by ARYANSHAH1567** [comment]
Fixed the liniting errors now it shall pass the failing test

**Comment by ARYANSHAH1567** [comment]
@coderabbitai review

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by ARYANSHAH1567** [comment]
> Please fix the failing test

@palisadoes to fix the failing tests i need to change a file in the Talawa-api so that i can define the creator id in the types and it can be handled properly.

**Comment by palisadoes** [comment]
Thanks,

1. Please focus on the failed Test Application test, not the Introspection. 
2. We can address Introspection later

**Comment by ARYANSHAH1567** [comment]
> Thanks,
> 
> 1. Please focus on the failed Test Application test, not the Introspection.
> 2. We can address Introspection later

Without the change in API i cant fix the tests or issue

**Comment by ARYANSHAH1567** [comment]
> > Thanks,
> > 
> > 1. Please focus on the failed Test Application test, not the Introspection.
> > 2. We can address Introspection later
> 
> Without the change in API i cant fix the tests or issue

Can i create a issue in api and fix that first? i guess that would help

**Comment by palisadoes** [comment]
> > > Thanks,
> > > 
> > > 1. Please focus on the failed Test Application test, not the Introspection.
> > > 2. We can address Introspection later
> > 
> > 
> > Without the change in API i cant fix the tests or issue
> 
> Can i create a issue in api and fix that first? i guess that would help

OK

**Comment by ARYANSHAH1567** [comment]
> > > > Thanks,
> > > > 
> > > > 1. Please focus on the failed Test Application test, not the Introspection.
> > > > 2. We can address Introspection later
> > > 
> > > 
> > > Without the change in API i cant fix the tests or issue
> > 
> > 
> > Can i create a issue in api and fix that first? i guess that would help
> 
> OK

Created the issue can you please assign it to me

**Comment by palisadoes** [comment]
1. What is the new issue number?
2. This PR is still failing the application tests

**Comment by ARYANSHAH1567** [comment]
> 1. What is the new issue number?
> 2. This PR is still failing the application tests

1) The issue number is 2555 in Talawa-API
2) In the admin, it is actually sending creatorId to retrieve the organisation from talawa-api but the variable name is orgId and talawa-api is treating it is orgId. So it is unable to fetxh the org data and hence we get error while editing the profile.
Fixes: In api i will change the files so that it can handle the creatorId and can successfully fetch the organisations and send to the admin

**Comment by noman2002** [comment]
@ARYANSHAH1567 Are you still working on this ??

**Comment by ARYANSHAH1567** [comment]
> @ARYANSHAH1567 Are you still working on this ??

Yes, I have created a issue in api regarding this, once that  pr gets merged this issue will automatically be solved

**Comment by ARYANSHAH1567** [comment]
@palisadoes fixed all the issues and all tests are successful. So can you please review the pr and merge it

**Comment by palisadoes** [comment]
Please fix the failing tests

**Pull request closed without merging**
