### PR TITLE
Implemented manage functionality for admin and super admin after login

### LINKED ISSUE #493: Implement login for Admin and Super-Admin
**Is your feature request related to a problem? Please describe.**
Admins of several organizations may control the personnel and operations of their own organizations using talawa-admin. Presently, when you attempt to connect into talawa-admin, you are logged in as super-admin and are able to access information for other organizations in addition to your own.
You can refer to the image below.

**Describe the solution you'd like**
The login screen should stay the same, but when a user enters their credentials, it should automatically determine if they are an admin or a super-admin. Although the super admin might travel down through all the organizations, the admin should only be allowed access to their specific organization.

**Describe alternatives you've considered**
The contributor can come up with her/ his own ideas.

**Approach to be followed**
- We want to minimize changes to the existing design. Keep the current design.
- Code coverage for all files editor must be 100%

**Additional context**
 - API calls may have to be modified and the relevant issues created

### PR DESCRIPTION
**Pull request by Manoramsharma**
**What kind of change does this PR introduce?**

Its kind of feature where right after the login the super admin can access/manage all the provided organisations where the admin can manage only its own organisation other options will be disabled.

**Issue Number:**

Fixes #493 

**Did you add tests for your changes?**
Yes 

**Summary**

https://github.com/PalisadoesFoundation/talawa-admin/issues/493

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Manoramsharma** [comment]
@xoldyckk @noman2002 kindly approve the workflow to run for this PR.

**Comment by Kevoniat** [comment]
@Manoramsharma  no test coverage was generated

**Comment by palisadoes** [comment]
@Kevoniat 
@xoldyckk 
@Tajcore 

Please review

**Review by noman2002 — CHANGES_REQUESTED** [review]
Attach a screenshot/ video after changes.

**Comment by Manoramsharma** [comment]
> Attack a screenshot/ video after changes.

https://drive.google.com/file/d/1vnHKCUIcR0ei2u9O2te4y7vEPvomWE-9/view?usp=sharing  
Here is the attached link of the video, what exactly is done that the manage functionality for SUPERADMIN is not restricted to any organisation whereas for ADMIN I only the manage button corresponding to his/her organisation is active other buttons are disabled for him.
Ideally not even other Organizations must be fetched  in the list for admin of particular organisation but for its implementation the different route would be required after login(i.e 2 separate routes after login as SUPERADMIN and other as ADMIN fetching different /orglist corresponding to each). So presently as mentioned in the issue with minimum change I proceeded this way just disabling the manage action according to the userType. I can go for the described approach if asked to.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
