### PR TITLE
Feature : Replaced Favicon with original Palisadoes Icon 

### LINKED ISSUE #166: Feature : LOGO REPLACEMENT
**Is your feature request related to a problem? Please describe.**
The Talawa Admin website , still shows the default React Icon in the title . 

**Describe the solution you'd like**
The default react icon should be replaced with the Original Palisadoes Foundation icon .

**Describe alternatives you've considered**
Replacing the icon with original Palisadoes icon .

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
image

### PR DESCRIPTION
**Pull request by reachaadrika**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #166 

**Did you add tests for your changes?**

Not needed 

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**

Not Needed 

**Summary**

An the original Talawa admin page , the title bar had default React Favicon in it , this PR fixes this issue and thus replaces the default logo with the original Talawa Logo . 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
@reachaadrika, why are there so many commits in your PR? Some of them are not done by you. Please fix this. You probably didn't sync your repo properly before submitting the PR.

**Comment by yasharth291** [comment]
don't add ```package-lock.json ``` this file here @reachaadrika

**Comment by palisadoes** [comment]
> don't add `package-lock.json` this file here @reachaadrika

@reachaadrika please add the `package-lock.json` file to `.gitignore`

**Comment by reachaadrika** [comment]
Yes sure @palisadoes and @yasharth291  , I will do that , I will probably open a new PR with the commits I have done . Making changes to this when would be a bit clumsy . Sorry for this .

**Pull request closed without merging**
