### PR TITLE
Added Event Attendance Feature in Admin and User Portal

### LINKED ISSUE #2351: GSoC: Added Event Attendance Feature and UI Enhancements in User Portal
**Is your feature request related to a problem? Please describe.**
The current user portal lacks a streamlined way to manage and display event attendance statistics. This makes it difficult for users to track their participation and for admins to efficiently view attendance records. Additionally, certain UI elements related to event tracking and member details are outdated or non-intuitive, leading to a suboptimal user experience. Specifically, there is no support for on-spot event registration, limiting flexibility for participants.

**Describe the solution you'd like**
I would like to introduce an enhanced event attendance feature in the user portal that allows users and admins to easily track events attended. This solution includes:

- A new UI for viewing event attendance statistics with bar charts and modal filtering.
- Revamped member details section to improve usability and access to information.
- Bug fixes related to recurring events and chart rendering.
- Support for on-spot registration, allowing users to register for events directly at the venue or during the event.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

Feature of Event Attendance and Statistics

**Issue Number:** 

Fixes #2351 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

This PR introduces an enhanced event attendance feature in the user portal, addressing the need for a streamlined way to manage and display event attendance statistics. Currently, users face challenges in tracking their participation, and admins find it difficult to view attendance records efficiently. The existing UI elements related to event tracking and member details are outdated, leading to a suboptimal user experience. This solution aims to improve usability and provide greater flexibility for participants.

Key improvements include:

1. A new user interface for viewing event attendance statistics with interactive bar charts and modal filtering options.
2. A revamped member details section for improved usability and easier access to information.
3. Bug fixes related to recurring events and chart rendering, ensuring accurate and reliable data display.
4. Support for on-spot registration, allowing users to register for events directly at the venue or during the event, enhancing flexibility for participants.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Release Notes

- **New Features**
	- Added support for event attendance tracking, including new fields in user and event data.
	- Introduced a new "Attendance" tab in the event management interface.
	- Enhanced localization with new keys for gender across multiple languages.
	- Added a new component for displaying events attended by users.
	- Introduced mock data for testing event attendees.
	- Modified GraphQL queries to support new attendance-related features.
	- Implemented CSV export functionality for attendance trends and demographics.

- **Bug Fixes**
	- Improved error handling for GraphQL queries related to event attendees and user interactions.
	- Enhanced handling of scenarios with no organization members in the event registrants modal.

- **Tests**
	- Expanded test coverage for components related to event attendance, ensuring proper rendering and error handling.
	- Updated assertions in existing tests for consistency and clarity.
	- Introduced new test files for components handling event attendance and user address fields.
	- Added tests for autocomplete functionality in the event registrants modal.
	- Enhanced tests for the EventsAttendedByMember component to cover loading, error handling, and successful data rendering.
	- Refined mock data structures in tests to include attendees and specific event dates.

- **Documentation**
	- Updated localization files for various languages to include new keys for gender.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please make sure coderabbit approves your PR

**Comment by palisadoes** [comment]
1. Please fix the conflicting files.
2. Please also make sure that CodeRabbit approves your PR
3. Please fix the failing linting test

**Comment by palisadoes** [comment]
Please fix the conflicting files and make sure code rabbit approves your PR.

**Comment by duplixx** [comment]
> Please fix the conflicting files and make sure code rabbit approves your PR.

@palisadoes I am working on fixing errors that came after merging recent pr's..working on fixes

**Comment by palisadoes** [comment]
Please get the test code coverage higher.

**Comment by palisadoes** [comment]
@duplixx I'm going to merge this on good faith as we need to get as many GSoC features in `develop` before the code freeze tomorrow

**Pull request merged**
