### PR TITLE
Test src test store

### LINKED ISSUE #277: Code Coverage: Create tests for store.ts
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/state/store.ts`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/state/store.test.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/state/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
Note: this repeated PR from #299 due to some technical problems (you can visit #299 for more information)

What kind of change does this PR introduce?
Added Testcases for src/state/index.ts file

Issue Number:

#277 

Fixes #277 

Did you add tests for your changes?
Yes I have added a testfile

Summary
I have added a store.test.tsx file required for issue #277  for Gsoc2022

Does this PR introduce a breaking change?
No

SnapShots
image

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
@yasharth291  can you check now ?

**Review by DangaRanga — CHANGES_REQUESTED** [review]
Good job so far!

Please create separate tests/assertions for each property you're testing. As if the schema changes it could become difficult to pinpoint exactly what could  be causing the tests to fail.

You could achieve this by setting up the state object to be global to this test suite before the tests, and then separating each test as follows:

**Test for checking if the state has the required properties**
```
test('State should contain the properties appRoutes and plugins',  () => {
....

}
```
**Test to ensure that the appRoute's schema is as intended**
```
test('appRoutes schema should contain targets, configUrl and components',  () => {
...

}
```

**Test to ensure that the plugin's schema is as intended**
```
test('plugins schema should contain installed, addOnStore and extras',  () => {
...

}
```

This would be an essential pattern to adopt as the size of the redux store increases, and more functionality to be tested gets added

**Comment by SiddheshKukade** [comment]
> Good job so far!
> 
> Please create separate tests/assertions for each property you're testing. As if the schema changes it could become difficult to pinpoint exactly what could  be causing the tests to fail.
> 
> You could achieve this by setting up the state object to be global to this test suite before the tests, and then separating each test as follows:
> 
> **Test for checking if the state has the required properties**
> ```
> test('State should contain the properties appRoutes and plugins',  () => {
> ....
> 
> }
> ```
> **Test to ensure that the appRoute's schema is as intended**
> ```
> test('appRoutes schema should contain targets, configUrl and components',  () => {
> ...
> 
> }
> ```
> 
> **Test to ensure that the plugin's schema is as intended**
> ```
> test('plugins schema should contain installed, addOnStore and extras',  () => {
> ...
> 
> }
> ```
> 
> This would be an essential pattern to adopt as the size of the redux store increases, and as more functionality to be tested gets added

Thank you sir for the response. I will apply assertions to test cases in a few minutes

**Comment by SiddheshKukade** [comment]
@DangaRanga Sir Is this Ok ?

**Review by DangaRanga — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
@SiddheshKukade What is the level of code coverage for the file. It's not visible in the CodeCov report. Please paste an image of the reporting of this value. We need to get to 100%

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade What is the level of code coverage for the file. It's not visible in the CodeCov report. Please paste an image of the reporting of this value. We need to get to 100%

Ok :+1:

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
