### PR TITLE
Workflow Updates and Countline script

### LINKED ISSUE #37: Organise github workflow and add script
**Is your feature request related to a problem? Please describe.**
Creation of only two `yml` file, one for issues and one for PR and organise the workflow code.
We can add the countline script here and it will help to make sure the project is structured.

**Describe the solution you'd like**
2 yml files:
1. issues.yml
2. pull-request.yml

**Approach to be followed (optional)**
The current 3 yml files will be updated to two yml files and if allowed the addition of countline script

### PR DESCRIPTION
**Pull request by sumitra19jha**
**What kind of change does this PR introduce?**
Closes #37 

**Did you add tests for your changes?**
Not needed

**If relevant, did you update the documentation?**
Not needed

**Summary**
It will organise the workflow and improve code quality

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
What is the desired number of lines of code for node.js that other mentors have requested? That will need to be the default.

Add a README.md in the `.github` directory like the one that now exists in `talawa`

**Comment by sumitra19jha** [comment]
Sure working on it

**Comment by palisadoes** [comment]
@sumitra19jha  is this done?

**Comment by sumitra19jha** [comment]
It will be done today

**Comment by sumitra19jha** [comment]
@palisadoes Done

**Review by palisadoes — CHANGES_REQUESTED** [review]
@sumitra19jha please resolve the merge conflicts and then we can merge this PR into the code base.

**Pull request closed without merging**
