### PR TITLE
Redesigning the post dialog of user portal

### LINKED ISSUE #1198: Post dialog needs to be modified like linkedin
**Describe the bug**
The post dialog in the home screen in the user portal which can be accessed here `http://localhost:3000/user` needs to be modified like linked in

**To Reproduce**
Steps to reproduce the behaviour:

1. run the talawa admin
2. access the user login form and log in as a user
3. click on any organisation
4. access the issues

**Expected behaviour**
Something similar to linked-in, have attached the image below for reference.
Screenshot 2023-12-15 at 3 18 54 AM

**Actual behaviour**
A basic post dialog
Screenshot 2023-12-15 at 3 14 21 AM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by chandel-aman**
**What kind of change does this PR introduce?**
Feature request

**Issue Number:**

Fixes #1198 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image

image

https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/1994e573-493a-4602-abeb-923686e43f57

Test Covered
image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by chandel-aman** [comment]
@Cioppolo14 Can you review this PR?

**Comment by aashimawadhwa** [comment]
LGTM 👍🏼

**Review by aashimawadhwa — APPROVED** [review]

**Comment by aashimawadhwa** [comment]
@beingnoble03 please look into it.

**Comment by chandel-aman** [comment]
@rishav-jha-mech 
Could you please review this PR and provide your feedback?

**Comment by chandel-aman** [comment]
@palisadoes
Could you please provide your review for this PR?
Thanks!

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
