### PR TITLE
fix: user profile page details responsive for mobile screen

### LINKED ISSUE #1083: Bug Report : User profile page is not responsive for mobile screens
**Describe the bug**
- The `user details` page is not responsive for mobile screens.
- The profile details overflow with the profile image icon
- The `main`, `organizations`, `events` sections are not readable.

**To Reproduce**

1. Login as admin
2. Go to organization dashboard
3. Click on user details by scrolling to bottom of sidebar
4. Inspect the website for responsive viewports. 

**Expected behavior**
- The user details page should be responsive and readable.

**Actual behavior**
- The user details page is not responsive for mobile view and the details overflow over profile image

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/4c788d8c-3184-460e-a09c-3195b7ff7d9a

**Additional details**
I would like to work on this issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by MahendraDani**
**What kind of change does this PR introduce?**

bugfix
**Issue Number:**

Fixes #1083 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

## Before

https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/44f24ae8-dfd6-48d3-87a7-20bb31e96e9b

## After

https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/c9ece189-2e6d-4d7e-8167-c075b6438d75

**If relevant, did you update the documentation?**

**Summary**

Fixed the responsiveness of user details section

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@rishav-jha-mech  please review this.

**Review by noman2002 — COMMENTED** [review]
Pull the latest code into this branch.

**Comment by MahendraDani** [comment]
> Pull the latest code into this branch.

Done

**Comment by palisadoes** [comment]
The pull request target GitHub workflow has suddenly started to fail in this and other repos. The GitHub action hasn't been updated since September. A dependency has changed and the authors will need to fix it. We'll have to ignore it for now.

- https://github.com/actions/first-interaction

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
