### PR TITLE
Fixes #1767 Eventdetail Id

### LINKED ISSUE #1767: [userTypeFix] Error encountered in Settings page (MemberDetail file) as superadmin.
**Describe the bug**
When logged in as a superadmin and clicking on the User option (Avatar and username) from the left side panel in the Settings page (MemberDetail file), a blank screen is encountered.

**To Reproduce**
1. Log in as a superadmin.
2. Navigate to the Settings page (MemberDetail file).
3. Click on the "Username" option from the left side panel.

**Expected behavior**
Clicking on the "Username" option should display relevant user details or allow for user management actions.

**Actual behavior**
Clicking on the "Username" option results in a blank screen, preventing access to user-specific details or management options.

**Additional details**

image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1767

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by varshith257 — COMMENTED** [review]
@duplixx Can provide scr of it's working? So that can be merged quickly

**Comment by duplixx** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/57519459-0464-4c7b-9f36-a6672c5092ae

the screen error is now fixed.but seems like talawa API error also needs to fixed

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by palisadoes** [comment]
The linked issue is incorrect

**Comment by duplixx** [comment]
@palisadoes the error is coming from API
image

**Comment by varshith257** [comment]
@duplixx If you feel any errors from API. Please feel free to open a issue there and work on it

**Comment by palisadoes** [comment]
Open an issue in the API

**Comment by pranshugupta54** [comment]
This is irrelevant now, re-designed page for the left side panel is merged. 
User card is shifted to top right now.

**Pull request closed without merging**
