### PR TITLE
Chore/css changes

### PR DESCRIPTION
**Pull request by AVtheking**
What kind of change does this PR introduce?

refactoring color schemes for color blind people

Issue Number:

Fixes #
Does this PR introduce a breaking change?

NO

## Release Notes

- **New Features**
	- Introduced new CSS variables for consistent styling across components.
	- Added new classes for buttons and layout enhancements in various screens.
	- Enhanced layout and styling for organization events and funds interfaces.

- **Bug Fixes**
	- Improved button styling and hover effects for better user interaction feedback.
	- Enhanced validation and error handling for event creation.

- **Documentation**
	- Updated import paths for styles to a centralized CSS module, enhancing maintainability.

- **Refactor**
	- Streamlined class names and structure in multiple components for improved readability and consistency.

- **Style**
	- Enhanced visual presentation of buttons, modals, and input fields across the application.
	- Updated styles for dropdowns, tables, and other UI elements to improve responsiveness and maintainability.
	- Adjusted button colors and hover effects to enhance visual feedback based on active states.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by Cioppolo14** [comment]
@AVtheking first comment so that each issue listed automatically closes & the failed tests.

**Comment by palisadoes** [comment]
@AVtheking Please ask the other maintainers for assistance. Sometimes fresh eyes are necessary. I think it's something small that's causing the failure.

**Comment by palisadoes** [comment]
@varshith257 Do you have any insights as to why this may be failing?

**Comment by varshith257** [comment]
@palisadoes dev-postgres the check will fail until we migrate all files into vitest and configure coverage for vitest.

I tried merging both coverages not to break any but the conflicts are applying.


So from now if any tests files are included in PR just make sure author of PR needs to provide screenshot of the  coverage of test files included in PR.


Other thing we can do it to disable the step that currently failing of acceptable  test coverage and reintroduce once migration is done

**Comment by palisadoes** [comment]
I'll set the coverage value in the workflow to zero

**Comment by palisadoes** [comment]
Then we can raise it over time

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
