### PR TITLE
Refactoring CSS files: merged CommunityProfile styles into global app.module.css

### LINKED ISSUE #2503: Refactor CSS files in src/screens/CommunityProfile
# Refactor CSS files in src/screens/CommunityProfile

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by mandeepnh5**
**What kind of change does this PR introduce?**

Refactoring CSS files: merged CommunityProfile styles into global app.module.css

**Issue Number:**

Fixes #2503 

**Did you add tests for your changes?**

No

**Summary**

It is my third PR on Palisadoes Foundation and I am looking forward to contribute more to this organization.
This PR solves the problem of having a single global CSS file instead of having many CSS files in sub directories.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Updated styling for the Community Profile component to enhance visual structure and responsiveness.
	- Introduced new CSS classes for card components and form elements in the global style file.

- **Bug Fixes**
	- Improved layout and presentation of UI elements, particularly for mobile devices.

- **Chores**
	- Removed the local CSS module for the Community Profile and transitioned to a global style file.

### CODE REVIEW

**Comment by mandeepnh5** [comment]
@palisadoes all checks has passed please check

**Comment by palisadoes** [comment]
Please make sure coderabbit.ai approves your changes

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please make sure coderabbit.ai approves your changes

**Comment by mandeepnh5** [comment]
@palisadoes coderabbit.ai approved the changes please check

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
