### PR TITLE
Added scrollbar for scrolling post, upcoming events 

### LINKED ISSUE #1736: Feature Request: - Add a scrollbar to latest post where only 3 or 4 post are shown
**Is your feature request related to a problem? Please describe.**
Currently, the latest posts section displays all posts without a scrollbar, leading to a cluttered interface when numerous posts are present. Users may find it challenging to navigate through the posts efficiently.

Screenshot 2024-03-17 at 5 11 32 PM

**Describe the solution you'd like**
I would like to see a scrollbar added to the latest post section, limiting the display to only three or four posts at a time. This would streamline the interface, making it easier for users to navigate through recent posts without overwhelming them with excessive information.

**Describe alternatives you've considered**
One alternative could be implementing pagination for the latest posts, allowing users to navigate through multiple pages to view older posts. However, this may not provide an optimal user experience as users would need to click through several pages to find the post they are looking for.
 
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**

Feature- added scrollbar for scrolling post, upcoming events etc.

**Issue Number:**

Fixes #1736 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by krishna619** [comment]
@palisadoes please review

**Comment by Cioppolo14** [comment]
@krishna619 Please fix the test application check.

**Comment by krishna619** [comment]
@Cioppolo14 https://github.com/PalisadoesFoundation/talawa-admin/pull/1844 This PR has now fixed the failing test.

Credits: @disha1202

**Comment by krishna619** [comment]
@palisadoes 
Please review.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
