### PR TITLE
Refactor: Added Vitest To Requests Screen

### LINKED ISSUE #2569: Refactor: `src/screens/Requests` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/Requests` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by shivasankaran18**
**What kind of change does this PR introduce?**

Added Vitest to Requests Screen

**Issue Number: 2569**

Fixes #2569 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Screenshot 2024-12-13 175144

**If relevant, did you update the documentation?**

**Summary**

Migrated the testing framework to Vitest.
Updated all test files and configurations to be compatible with Vitest's syntax and features.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Tests**
	- Enhanced testing framework by integrating `vitest` for improved mocking of `localStorage` and `window.location`.
	- Introduced a new utility function `wait` to facilitate asynchronous testing.
	- Maintained existing test structure while improving reliability and isolation of tests.

### CODE REVIEW

**Comment by shivasankaran18** [comment]
@coderabbitai review

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

Unfortunately, if this continues we will have to close the offending PR and unassign you from the issue.

image

**Comment by shivasankaran18** [comment]
@palisadoes Extremely sorry for the act..the only reason for closing of PRs is that it fails many CI tests..Hence , to make the PR pass the CI tests, I have chose to close my PRs and open new one so that it is ready to be merged..this PR is ready to be merged..And i strictly make sure this won't happen again

**Review by palisadoes — APPROVED** [review]

**Comment by shivasankaran18** [comment]
yeah got it @palisadoes ..just learnt that after this..thanks for your time sir..!

**Pull request merged**
