### PR TITLE
Avatar migration to vitest

### PR DESCRIPTION
**Pull request by NishantSinghhhhh**
What kind of change does this PR introduce?
Feature/Refactoring Avatar component

Issue Number : #2492

Did you add tests for your changes?
Yes

Snapshots/Videos:

[Screencast from 2024-12-02 18-44-06.webm](https://github.com/user-attachments/assets/4c18fc7b-1bfc-4e88-bc0b-a4cb97bf47da)

Summary

Does this PR introduce a breaking change?
NO

Migrated the testing framework to Vitest.
Updated all test files and configurations to be compatible with Vitest's syntax and features.
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

## Release Notes

- **New Features**
  - Enhanced `Avatar` component with optional `name` and `customUrl` properties for greater flexibility.
  - Introduced new testing scripts for the Vitest framework to improve testing capabilities.

- **Bug Fixes**
  - Improved error handling in the `Avatar` component to gracefully manage invalid inputs.

- **Documentation**
  - Updated configuration files for TypeScript and Vitest to streamline the development and testing processes.

- **Chores**
  - Updated various dependencies to their latest versions for improved performance and security.

### CODE REVIEW

**Comment by NishantSinghhhhh** [comment]
@palisadoes

**Comment by palisadoes** [comment]
PTAL
- https://github.com/PalisadoesFoundation/talawa-admin/pull/2589#issuecomment-2511517716

**Comment by NishantSinghhhhh** [comment]
@palisadoes  , can you please tell me how can I remove the linting issue , the npm run lint:fix is not working in my case

**Comment by palisadoes** [comment]
Closing. You need to be making your changes using the  most current version of the `develop-postgres` branch.

**Pull request closed without merging**
