### PR TITLE
Fixed: #504 implemented translation on the plugin tab

### LINKED ISSUE #504: Translation is not working for Plugin tab
**Describe the bug**
Many entities in the plugin section are not translating during the toggle in languages.
 

**To Reproduce**

1. run talawa API locally
2. run talawa admin in your local machine
3.  login to the admin
4.  from the dashboard of the organization, reach plugins
5.  see the issue.

**Expected behavior**
All the translations should work properly in the plugin section

**Actual behavior**
some text is not being translated.

**Screenshots**

Screenshot 2023-02-25 at 3 02 37 AM (2)
Screenshot 2023-02-25 at 3 02 48 AM (2)

**Additional details**
That might be some hard-coded text which needs to be passed from the predefined translation function.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #504 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

Screenshot 2023-02-26 at 12 55 45 AM (2)

**If relevant, did you update the documentation?**
not any

**Summary**
Implemented translation in plugin tab

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by aashimawadhwa** [comment]
> Please fix the failing tests

there is a separate PR for these tests. I have made no changes in AddOnStore files @palisaodes

**Comment by palisadoes** [comment]
It's probably due to the changes you made to the other files in that directory.

Please update the tests.

It seems that codecov is now testing the diffs too. I'll research it some more, but in the meantime please update the tests

**Comment by Kevoniat** [comment]
@palisadoes  should I approve the failing test?

**Comment by palisadoes** [comment]
You can approve requesting changes. There is an option there.

**Comment by palisadoes** [comment]
I want to understand what is happening in this case. It may affect us in the typescript repositories

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing tests. 
It claims that the three edits in this file need to coverage work 
- `src/components/AddOn/core/AddOnStore/AddOnStore.tsx`
- https://github.com/PalisadoesFoundation/talawa-admin/pull/510/files#diff-197b88421ba4c4e0ec3e7fe17a3b267ca4a77cb0c7c5739db571996c0a74fdeb

**Pull request merged**
