### PR TITLE
User - People UI - Redesign

### LINKED ISSUE #1607: USER REDESIGN: redesign the People screen for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the People screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation:
Screenshot 2024-02-21 at 1 04 25 AM

Desired Result:
Screenshot 2024-02-21 at 12 58 59 AM

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranshugupta54**
SAME AS #1654 

**What kind of change does this PR introduce?**

User -> People -> Redesigning

**Issue Number:**

Fixes #1607 

**Did you add tests for your changes?**

**Snapshots/Videos:**

image

**Tests:**
image
image

**Other information**

- The left side panel (according to Figma) should be fixed in another issue to match the design.
- Added extra Avatar (as per current codebase, `no avatar was there in new design`)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
can you remove the pagination we don't have it in the new designs we follow infinite scroll now across the talawa admin portal. @pranshugupta54

**Comment by pranshugupta54** [comment]
> can you remove the pagination we don't have it in the new designs we follow infinite scroll now across the talawa admin portal. @pranshugupta54

Hey @aashimawadhwa, can you please clarify over this. I see pagination everywhere across Talawa. Can you refer some infinite scroll? Do you want me to list all the users at once or do you want them to load depending on user scroll event? (In my opinion, pagination would be a better choice here. Infinite scroll is preferred when there is no definite end point or count, like scrolling feed section with endless posts. But user list is a finite number so pagination should be preferred.)

**Comment by noman2002** [comment]
@pranshugupta54 Please fix the introspection issue.

**Comment by pranshugupta54** [comment]
Hey @noman2002, the problem you're referencing isn't specific to this PR. It's occurring across all other PRs and is being addressed in a separate issue.

**Comment by aashimawadhwa** [comment]
> Hey @aashimawadhwa, can you please clarify over this. I see pagination everywhere across Talawa. Can you refer some infinite scroll? Do you want me to list all the users at once or do


please check other tables, i am talking about pagination implemented in front end that I  can see in the video you have attached below your table.
image

**Review by aashimawadhwa — COMMENTED** [review]
remove the suggested changes and provide with a new commit.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
