### PR TITLE
Upgrade @pdfme/generator to 5.0.0

### LINKED ISSUE #2317: Upgrade @pdfme/generator from 4.5.2 to 5.0.0
## Rationale
1. This was previously attempted by the automated dependabot job but the PR tests failed.
1. This issue has been created to fix the issue as there may be multiple dependency requirements that need updating

This is a major revision upgrade and many files may need to be updated to the new syntax, functions, methods and classes

## Task
1. Upgrade the package
1. Remove this package if it is: 
    1. unused
    3. unnecessary. For example:
        1. the functionality can be maintained by using another package we are already using, 
        3. If we are using only one function or class in the package you can consider replacing it with code that resides in this repository
        4. It is used by a feature that the end user is unlikely to ever use

## Background Failing PRs and Tests
- https://github.com/PalisadoesFoundation/talawa-admin/pull/2313
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/11097331491/job/30828434661?pr=2313

### PR DESCRIPTION
**Pull request by Kunalpal216**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #2317 

**Did you add tests for your changes?**

Not required.

**Summary**

1. Upgraded @pdfme/generator to 5.0.0.
2. Added mock function for generate import from @pdfme/generator because jest couldn't map a package's internal dependency(node_modules/@pdfme/schemas/src/utils.ts) leading to test cases involving imports from @pdfme/generator to failing.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a mock `generate` function for testing, returning a data array as expected from the original generate utility from `@pdfme/generator`.
	- Added a new test case to the `TableRow` component to verify appropriate error handling when PDF generation fails.

- **Dependencies**
	- Upgraded `@pdfme/generator` package to version `5.0.0`, potentially introducing new features and improvements.

- **Configuration Updates**
	- Updated Jest configuration to include module name mapping for improved testing capabilities.
	- Cleaned up comments in the Jest configuration for better organization.
	- Ensured the fetch API is available in the testing environment by explicitly including `whatwg-fetch`.

### CODE REVIEW

**Comment by Kunalpal216** [comment]
@pranshugupta54 I have added tests for my additions but still the code coverage seems to not meet. Can you help ?

**Comment by pranshugupta54** [comment]
> @pranshugupta54 I have added tests for my additions but still the codecov test seems to not meet. Can you help ?

https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/2413/indirect-changes
I think your changes will require some modifications for `src/components/CheckIn/TableRow.tsx`

**Comment by Kunalpal216** [comment]
@pranshugupta54 Seems like `src/components/CheckIn/TableRow.tsx` needs some more test additions for those error cases to also get covered. I will check.

**Comment by Kunalpal216** [comment]
@pranshugupta54 Can you review this PR ? The test coverage issue has been resolved.

**Review by pranshugupta54 — APPROVED** [review]

**Comment by pranshugupta54** [comment]
LGTM

**Comment by pranshugupta54** [comment]
PTAL @varshith257

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
