### PR TITLE
[Fixes] Code Coverage: Testing Render.helper.ts

### LINKED ISSUE #260: Code Coverage: Create tests for Render.helper.ts
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/components/AddOn/support/services/Render.helper.ts`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/components/AddOn/support/services/Render.helper.test.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/components/AddOn/support/services/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
Test Cases Added 

**Issue Number:** #260 

Fixes #260 
**Did you add tests for your changes?**
Yes 
   
**Summary**
Ignore the file
`src/components/AddOn/support/services/Render.helper.ts`
 because it was containing just an empty class definition and a export statement :arrow_down: 
```js
class RenderHelper {}

export default RenderHelper;
```
**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
IS there anything to improve on here ?

**Comment by palisadoes** [comment]
@yasharth291 @DangaRanga Please review

**Comment by yasharth291** [comment]
No increase in the percent of test so can't merge

**Comment by palisadoes** [comment]
@yasharth291 please read the explanation of the PR. Review again.

**Comment by SiddheshKukade** [comment]
@yasharth291  @DangaRanga  do you have any suggestions to improve onto this ?

**Review by Devesh21700Kumar — COMMENTED** [review]
@SiddheshKukade, The test coverage of the version of your code in your PR is  61.42% which is less than the min_coverage of 63.42%.
This is primarily because your PR is 4-5 days old and more test coverage increment PRs might have been merged in this period of time.
I would recommend that either you pull the latest changes and commit it 
or
delete this branch and make another branch and make another PR regarding the same (by pulling the latest code)

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade, The test coverage of the version of your code in your PR is 61.42% which is less than the min_coverage of 63.42%. This is primarily because your PR is 4-5 days old and more test coverage increment PRs might have been merged in this period of time. I would recommend that either you pull the latest changes and commit it or delete this branch and make another branch and make another PR regarding the same (by pulling the latest code)

ok @Devesh21700Kumar  thanks :+1:

**Comment by palisadoes** [comment]
@yasharth291 please comment

**Comment by yasharth291** [comment]
there is nothing wrong in ignoring this line

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
