### PR TITLE
orgSettings: UI refactor with locale

### LINKED ISSUE #396: Code Coverage: Create tests for OrgSettings.tsx
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/screens/OrgSettings/OrgSettings.tsx
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by bigBrain1901**
## What kind of change does this PR introduce?

UI Refactor and bugfix for OrgSettings.tsx

## Issue Number

Referenced from GH-396 - [link to thread](https://github.com/PalisadoesFoundation/talawa-admin/issues/396#issuecomment-1457867253)

Partially Fixes #396 
Fixes GH-559

## Did you add tests for your changes?
Not yet, that would be the next step if the current changes are reviewed and alright.

## Snapshots/Videos

[Screencast from 2023-03-07 22-48-19.webm](https://user-images.githubusercontent.com/55971005/223499207-49d92d99-38f2-493e-b884-2c9d1c12b428.webm)

## If relevant, did you update the documentation?

There was no need to update the documentation. No API changes occur in this PR.

## Summary

The UI buttons for the various sections on the Settings page were not working. This was because of bad mapping of the div with their caller hrefs. I was assigned the issue #396 to write tests for this file, but I saw these bugs. Hence, decided to fix them while I was at it anyways. After describing the issue on the linked issue, and when prompted, I worked on this PR.

There were a few hard-coded values for member-locations and images on the admin panel for this page. Made those fields dynamic as well.

I also added locale translations for the required fields by copy-pasting from existing keywords.

## Does this PR introduce a breaking change?

No

## Other information

This PR enables admins to see the `member.location`, `member.image` and `member.join_date` for every `membershipRequest` to an organisation. Need to check if it is okay to reveal this metadata on the users. Else, I will revert my changes here.

## Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@bigBrain1901 Could you create a new issue that references the one partially fixed here, then tag your PR to the new issue?

**Comment by bigBrain1901** [comment]
Sure! I will do it now.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix the failing test by updating the tests for the files you have changed.

**Comment by bigBrain1901** [comment]
Hi, an issue GH-559 was created out of the observations from this MR with a UX redesign for the page.

This PR will depend on the completion of that issue, which is underway.  
Marked this PR as a draft for now :v:

**Comment by palisadoes** [comment]
Thanks for submitting your PR, but we must close it.

1. We get notified of every event in the queue, and draft PRs like these, and their updates that require no action can be a distraction. We need our reviewers to focus on updates that are ready. 
1.  Don't be discouraged, we are just trying to keep our workloads to a manageable level.

Please resubmit when you are ready.

**Pull request closed without merging**
