### PR TITLE
fix: Fixed more button disappearing on calendar on small screens

### LINKED ISSUE #1389: Bug Report: `More` button disappears on event calendar
**Describe the bug**

`More` button disappears on event calendar, on small screens, if there are less than or equal to two events. This disables access to events for that particular data.

This case was missed in PR #1178

**To Reproduce**

1. Go to events
2. Create two or less than two events for same date
3. Reduce the screen size to less than 700px
4. Notice that events disappear

**Expected behavior**
`More` button should be there on smaller screens if there are events.

**Actual behavior**
`More` button disappears if there are less than or equal to two events.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/fbb16d8d-ae32-4d81-8c14-48a041ff789c

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**What kind of change does this PR introduce?**

Fixed disappearing of `more` button on events calendar page on small screens if there are less than or equal to 2 events. 

**Issue Number:**

Fixes #1389

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/782aee93-2da2-4aa0-afd2-1ab59089ab5c

**If relevant, did you update the documentation?**

No

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by rishav-jha-mech** [comment]
@pateldivyesh1323 the text should not be "More", instead put View All over there and also highlight that date

**Comment by pateldivyesh1323** [comment]
@rishav-jha-mech Which date should I highlight, all dates with events or the date with expanded events?

**Comment by aashimawadhwa** [comment]
@pateldivyesh1323  all the dates which have events created in them.

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa @rishav-jha-mech 
I have made the changes.

image

image

**Review by aashimawadhwa — APPROVED** [review]
lgtm

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
