### PR TITLE
fixed:#1887 Event and Holiday Calendar View

### LINKED ISSUE #1887: ADMIN & USER REDESIGN - List of events and holidays in calender view of events.
**Is your feature request related to a problem? Please describe.**
Currently, the event calendar does not provides the list of events and holidays.

**Describe the solution you'd like**

1. Adding a list of holidays, and
2. adding list events below the event calendar.
3. Using color coding for events

**Describe alternatives you've considered**
NA

**Additional context**

**Current**
Talawa-User
Screenshot from 2024-04-07 06-03-11
Talawa-Admin
Screenshot from 2024-04-07 05-45-06

We already figma design made for this.

Screenshot from 2024-04-07 05-46-34

Figma link: https://www.figma.com/file/dTGr5CnGHvkilU5nwnRXg2/Talawa-Admin-UI-Redesign?type=design&node-id=910-355&mode=design&t=EVDV5SZ2cKnOAc2R-0

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gurramkarthiknetha**
This feature displays an interactive calendar view for tracking events and holidays. The calendar highlights holidays and user/organization-created events for the selected month, with color-coded markers for easy identification

**What kind of change does this PR introduce?**
This PR introduces a new feature for displaying an interactive event calendar with a list of holidays and user/organization-created events.

**Issue Number:**

Fixes #1887 

**Did you add tests for your changes?**
Yes, unit tests have been added to ensure the functionality works as expected.

**Snapshots/Videos:**
Snapshots and a short demonstration video showcasing the feature have been attached for better understanding.
image

**If relevant, did you update the documentation?**
Yes, the relevant sections in the [Talawa-Docs](https://github.com/PalisadoesFoundation/talawa-docs) have been updated to include details about the new feature.
**Summary**

This feature addresses the need for a more user-friendly and comprehensive event calendar.

Problem: The existing calendar lacked the ability to display a list of holidays and events in an organized manner.
Solution:
A list of holidays and events is now displayed below the calendar.
Color-coding has been implemented to distinguish between holidays and events for improved usability.
The UI aligns with the Figma design shared by the team.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Other information**

The Figma design used for this implementation can be found [here](https://www.figma.com/file/dTGr5CnGHvkilU5nwnRXg2/Talawa-Admin-UI-Redesign?type=design&node-id=910-355&mode=design&t=EVDV5SZ2cKnOAc2R-0).
This PR follows the project’s contribution guidelines and is submitted against the develop branch, as recommended.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the EventCalendar component with new CSS classes and improved layout for informational cards.
	- Improved accessibility and performance in the EventCalendar display logic, including better handling of holiday data.

- **Bug Fixes**
	- Streamlined tests for the Posts component, ensuring correct rendering when organization ID is invalid.

- **Chores**
	- Increased Jest test timeout to accommodate longer-running tests.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@gurramkarthiknetha Please fix the failed tests.

**Comment by gurramkarthiknetha** [comment]
image
all tests are passed

**Comment by Cioppolo14** [comment]
@gurramkarthiknetha Please fix the failed tests and coderabbit comments.

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha Please fix the failed tests and coderabbit comments.

Is ok now ??

**Comment by palisadoes** [comment]
Please fix:

1. Any failing tests
1. Any conflicting files

Make sure CodeRabbit.ai approves your changes

image

**Comment by Cioppolo14** [comment]
@gurramkarthiknetha Please fix the failed tests.

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha Please fix the failed tests.

all tests are passed

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha can you remove the space in between to have consistency in design? 

expected:
image

your is 
image

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha can you remove the space in between to have consistency in design?
> 
> expected: image
> 
> your is image

ok i will

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha and update the branch with upstream

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha can you remove the space in between to have consistency in design?
> 
> expected: image
> 
> your is image

image
@gautam-divyanshu  is this ok ?

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha 
divide holidays and events in two equal parts, 
image

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha divide holidays and events in two equal parts, image

image
now ??

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha great, and please update the branch

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha great, and please update the branch

ok @gautam-divyanshu

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha great, and please update the branch

now i updated the branch

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha 
image

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha image

what i should do now @gautam-divyanshu

**Comment by gautam-divyanshu** [comment]
@gurramkarthiknetha update and remove the merging conflicts

**Comment by palisadoes** [comment]
Please:

1. Fix the conflicting file
2. Ensure that coderabbit.ai approves your changes

**Comment by gurramkarthiknetha** [comment]
> Please:
> 
> 1. Fix the conflicting file
> 2. Ensure that coderabbit.ai approves your changes

@palisadoes  fixed

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
