### PR TITLE
Fixed the empty space in the OrgList

### PR DESCRIPTION
**Pull request by saadabban76**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #744

**Did you add tests for your changes?**
Not Required

**Snapshots/Videos:**
Before : 
orglist

After : 
fixx

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by saadabban76** [comment]
Hi @noman2002 , can you please review this PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
Remove these files. Why were they created and how can we prevent them from being created again?

1. [dfsdf](https://github.com/PalisadoesFoundation/talawa-admin/pull/751/files#diff-7f51f2cf3fce1c3ecbb01b8a9c374c8ab5f9c48035620aebf87650d35ed5b27b)
2. [er](https://github.com/PalisadoesFoundation/talawa-admin/pull/751/files#diff-cc7e4412564ba8a761bd32ab4cc6086bac3c2c9e580367e0b0eb32a4316f9154)

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1. The overall code coverage drops below the target threshold of the repository
2. Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by saadabban76** [comment]
> Remove these files. Why were they created and how can we prevent them from being created again?
> 
> 1. [dfsdf](https://github.com/PalisadoesFoundation/talawa-admin/pull/751/files#diff-7f51f2cf3fce1c3ecbb01b8a9c374c8ab5f9c48035620aebf87650d35ed5b27b)
> 2. [er](https://github.com/PalisadoesFoundation/talawa-admin/pull/751/files#diff-cc7e4412564ba8a761bd32ab4cc6086bac3c2c9e580367e0b0eb32a4316f9154)

The Files generate on running git config command before the pushing the git commit in the branch.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
