### PR TITLE
Feat : User can leave the org by clicking on button

### LINKED ISSUE #1873: Feature: An option for users to leave the Organization
**Is your feature request related to a problem? Please describe.**
There is no way for the user to exit/leave the Organization.

**Describe the solution you'd like**
An option on the left panel for users to leave the Organization.

**Describe alternatives you've considered**
Can discuss on design

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AnshulKahar2729**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1873

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced a "Leave" button in the user interface, allowing users to leave their current organization.
	- Added a confirmation modal for users to confirm their intention to leave an organization.
	- Enhanced localization with new and updated entries across multiple languages, including English, French, Hindi, Spanish, and Chinese.

- **Bug Fixes**
	- Corrected translation errors in various localization files.

- **Style**
	- Updated styles for the new "Leave" button and confirmation modal to improve user experience.
	- Enhanced visual styling for the organization leave interface components.

### CODE REVIEW

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729 Can you post a video of changes to speed up reviews? And also increase some test coverage too

Sure, I am just working on them.

**Comment by palisadoes** [comment]
Please apply the coderabbit.ai suggestions

**Comment by AnshulKahar2729** [comment]
> Please apply the coderabbit.ai suggestions

ok, sorry for the delay in between, got busy with some stuff, but I am back to track

**Comment by AnshulKahar2729** [comment]
@palisadoes PTAL, changed the code according to the relevant reviews.

**Review by noman2002 — CHANGES_REQUESTED** [review]
@AnshulKahar2729 Please make the suggested changes and resolve conflicting files.

**Comment by AnshulKahar2729** [comment]
@palisadoes done with everything, PTAL.

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please add a video showing the new functionality in action
1. Please fix the conflicting files

**Comment by palisadoes** [comment]
Please also make sure that code rabbit approves your changes

**Comment by AnshulKahar2729** [comment]
I am closing this PR, as this was very old. I am getting stuck in some test cases again nd again. I'll try to contribute to some different issues. Sorry for the inconvenience.

**Pull request closed without merging**
