### PR TITLE
Corrected Admin button functionality

### LINKED ISSUE #1507: Add Admin button for Orgs not working
**Describe the bug**
1. Whenever the Superadmin clicks on 'Add Admin' button in the organization, it displays 'organization not found'.
2. Also, same behavior is observed even if the role of the member is Admin or Superadmin. In this case, the button should be disabled as the member is already an Admin or a Superadmin.

**To Reproduce**

1. Navigate to 'People' section of an organization where list of members is displayed.
2. Go to the profile of a member.
3. Click on Add Admin button

**Expected behavior**
1. Add admin should change the role of member to Admin if the role is User.
2. If the current role is Admin/ Superadmin, this button must be disabled.

**Actual behavior**
For every role after clicking on 'Add Admin' button 'Organization not found' is shown.

**Video**
[Screencast from 27-01-24 07:05:56 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/20cd1dc6-7d0c-42cf-a9b2-4f2039183599)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #1507 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**
[Screencast from 28-01-24 07:08:08 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/d62be54d-5087-4d6c-96e5-f2782b417e19)

**Summary**

a. For Superadmin role:
1. Add Admin button was not working correctly. Now it is adding the admin for an org correctly.
2. The button was clickable although the current role was Admin. Now if the role is admin or superadmin, the button get disabled.
b. For Admin role:
1. The UI is same hence all the changes are replicated.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Anvita0305** [comment]
Here for Admin role, the admin is not permitted to update the role of other member in same organization. This needs to be changed in talawa-api repo. So should I open a new issue there for the same?
image

**Comment by palisadoes** [comment]
Yes, create the issue. Org Admins must be able to edit member information for their organizations

**Comment by palisadoes** [comment]
Please fix the failing tests

1. Code coverage
2. Introspection

**Comment by Anvita0305** [comment]
Hello @palisadoes sir, I have updated the failing tests however the introspection test is failing even after fetching the latest code. Can you please give suggestions for rectifying it?

**Comment by palisadoes** [comment]
1. When you click on the link of the failing test you see that `UserToReturn` is missing. This is in the API repo, but Admin doesn't have code to recognize it.
1. This is probably due to a recent API merge
2. You'll need to add the code

image

**Comment by Anvita0305** [comment]
Ok will add the code. Thanks!

**Comment by Anvita0305** [comment]
Hello @palisadoes sir, the introspection test which was failing due to 'UserToReturn' was fixed by merging the latest code. However now, it is failing because fields 'id' and 'applangcode' is not defined by type UpdateUserInput. However this issue will get fixed in #1762.

**Comment by Cioppolo14** [comment]
@rishav-jha-mech @Kevoniat Can you review this PR?

**Comment by aashimawadhwa** [comment]
I think if the introspection workflow failure is related to the api issue, then this can be merged @palisadoes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
