### PR TITLE
feat: Add Action Items to Event Dashboard

### LINKED ISSUE #1462: Admin - Add support for Action Items
**Is your feature request related to a problem? Please describe.**
Adding support for Action Items in talawa-admin.

**Describe the solution you'd like**
1. A screen for action item categories on the org leftDrawer, through which we could create, edit and view all the categories.
2. A screen for action items on the org leftDrawer, for similar crud functionalities. We could also add custom filter and search functionality for getting action items for a single category, assigned to a certain user, etc.
3. A screen on the event dashboard for action items associated with that event (as was previously the case for event projects). Here also, aside from the basic crud, we could add filter search functionality like the one described above.

**Additional context**
It's a companion issue for [this](https://github.com/PalisadoesFoundation/talawa-api/issues/1595) one in the api.

### PR DESCRIPTION
**Pull request by meetulr**
### What kind of change does this PR introduce?

Adds support for action items associated with an event.

### Issue Number:

Fixes #1462 

### Did you add tests for your changes?

Yes

### Demo:

> **Some design adjustments were made since the last PR.**

1. **Event Dashboard**:

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/1b5bd962-2295-4f4b-a353-4fdeffc4a3d0

2. **Organization Action Items (Since the same component is being used).**:

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/eaa71db9-a68b-4d7b-83b5-1461c0b0c23a

### Additional Context

This is the 3rd and final PR in the series for this issue.

**Previous PR**: #1596

### CODE REVIEW

**Comment by meetulr** [comment]
@palisadoes @aashimawadhwa 
Apart from the added feature, I've made some design adjustments as suggested. Please take a look.

**Comment by Cioppolo14** [comment]
@aashimawadhwa @noman2002 Can you review this PR?

**Comment by palisadoes** [comment]
Please change the Event action items left drawer text from "Action Items" to "Event Action Items" to distinguish it more from the org action items

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
Is this ready for review now?

**Comment by meetulr** [comment]
Yes this is ready

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
