### PR TITLE
Feature : Added Delete Button on Dashboard

### LINKED ISSUE #195: Feature request : Button on Dashboard Page of Organization
**Is your feature request related to a problem? Please describe.**
On the dashboard of organization , the delete organization button looks weird and a bit absurd .

**Describe the solution you'd like**
Change the way the button looks like (according to the theme , like other buttons in the web app ) 
For eg : Create organization 
I propose to create a delete organization button with a bin icon .

**Describe alternatives you've considered**
Change the way the button looks like (according to the theme , like other buttons in the web app ) 
For eg : Create organization 
I propose to create a delete organization button with a bin icon .

**Approach to be followed (optional)**
Change the styles and add a dustbin icon .

**Additional context**
image

### PR DESCRIPTION
**Pull request by reachaadrika**
**What kind of change does this PR introduce?**

BugFIX , FEATURE 

**Issue Number:**

Fixes #195 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:*

Screenshot (230)

**Summary**

The delete Organization button on the dashboard page looked a bit weird and absurd , I have created a better looking button with an icon to it also .

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by yasharth291 — APPROVED** [review]

**Comment by palisadoes** [comment]
@reachaadrika @yasharth291 This is an action that should be done with caution.

- Do you prompt the user with an "Are you sure?" message?
- How does the API interact with Talawa Admin for this? Is this capability available? In other words does the addition of this button do anything? If not, then we are creating the illusion of functionality.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@reachaadrika @yasharth291 This is an action that should be done with caution.

- Do you prompt the user with an "Are you sure?" message?
- How does the API interact with Talawa Admin for this? Is this capability available? In other words does the addition of this button do anything? If not, then we are creating the illusion of functionality.

**Comment by reachaadrika** [comment]
@palisadoes This button , deletes the organization that has been created by the user.

**Comment by palisadoes** [comment]
> @palisadoes This button , deletes the organization that has been created by the user.

Deleting an organization is a major event. Calendars, chats, news feeds, groups could all be deleted. This could severely impact an organization by removing relationships between members.

- Do you prompt the user asking them whether they are sure they want to do this?
- Does the API offer this capability?
- Are you aware of what the API does when an organization is deleted?

Please define the consequences of this action and explain how you will address this with the design of your changes. Providing the ability to delete, and deleting responsibly are very different things.

@yasharth291 What do you think?

**Comment by yasharth291** [comment]
yeah it is a major thing that we should think about we have to revamper the current flow and ask the admin to confirm before he/she is deleting @palisadoes  @reachaadrika

**Comment by reachaadrika** [comment]
@yasharth291 Agreed , I was thinking of creating a popup , where admin is asked if he/she really wants to delete the organization, basically a confirmation , if yes then org is deleted if no he stays on the same page. 
With a small note with consequences one will face if organization is deleted. 
What do you say? @palisadoes @yasharth291

**Comment by yasharth291** [comment]
@palisadoes

**Comment by palisadoes** [comment]
> @yasharth291 Agreed , I was thinking of creating a popup , where admin is asked if he/she really wants to delete the organization, basically a confirmation , if yes then org is deleted if no he stays on the same page. With a small note with consequences one will face if organization is deleted. What do you say? @palisadoes @yasharth291

Yes, please implement that.

**Comment by Lord-Aman** [comment]
Is this feature still not added ?? If not, then I would like to work on implementing the popup feature to ask the admin whether he/she is sure to delete an Organization.

**Comment by palisadoes** [comment]
@Lord-Aman How are you going to address the other issues discussed in the conversation above? It's not just a question of adding a button.

**Comment by Lord-Aman** [comment]
Yeah, I have checked the talawa-api to find the feature for deleting an Organization. And the good part is it's already having it.

So, Here's what the procedure will look like :

* Only the Creator of an Organization can delete it (according to the api) : So whenever the creator will click on the delete button, We can prompt them with all the consequences of deleting an Organization. And if he's sure to delete it then we will ask again for his password and the organization username to be manually typed. (Similar to as github does while deleting a repository ).

* Secondly, we will send a notification to all the members and admins of that organizations that it the organization has been deleted.

**Comment by Lord-Aman** [comment]
@palisadoes I have suggested the approach. Now, if it's good then Can I start working on it ??

**Comment by palisadoes** [comment]
Yes, that is OK.

@Lord-Aman Please comment on https://github.com/PalisadoesFoundation/talawa-admin/issues/195 so that I can assign it to you. I'm closing this PR.

**Pull request closed without merging**
