### PR TITLE
Manage Button UI Fixed

### LINKED ISSUE #1374: Inconsistent Organisation Cards Manage Button
**Describe the bug**
There is an inconsistency in the Orglist Cards Manage Button. When creating a sample organization by following these steps:

**To Reproduce**

1. Click on Create Organisation
2. Click on Create Sample Organisation

**Expected behavior**
The Manage Button on Orglist Cards should maintain consistency throughout the UI.

**Actual behavior**
Some buttons contain only text, while the Manage Button on the sample organization created by clicking "Create Sample Organisation" includes icons, causing a break in the consistent UI.

**Screenshots**
image
image

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

   Bugfix

**Issue Number:**

Fixes #1374 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/f23ba6cf-60d9-457b-af81-dacfc3088605

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by rishav-jha-mech — CHANGES_REQUESTED** [review]
@duplixx if i am not wrong, creating sample organization is just for Testing purposes, that is why it had a Flask icon, you should fix the Manage Button layout without removing the flask icon

**Comment by duplixx** [comment]
> @duplixx if i am not wrong, creating sample organization is just for Testing purposes, that is why it had a Flask icon, you should fix the Manage Button layout without removing the flask icon

yeah @rishav-jha-mech  previous implementation using conditional rendering 
`<Button
          onClick={handleClick}
          data-testid="manageBtn"
          className={styles.manageBtn}
        >
          {data && data?.isSampleOrganization && (
            <FlaskIcon
              fill="var(--bs-white)"
              width={20}
              title={t('sampleOrganization')}
            />
          )}
          {'  '}
          {t('manage')}
        </Button>`

If you insist on fixing the styling by adding the Flask icon, I can proceed with this approach. Should I proceed this way?

**Comment by rishav-jha-mech** [comment]
@duplixx yes you have to add that flask icon, or it will be difficult for the developers to differentiate b/w sample organizations and the ones created by them

**Comment by duplixx** [comment]
@rishav-jha-mech Yeah, totally agreed! Thanks. I'll make the changes.

**Comment by duplixx** [comment]
image

@rishav-jha-mech does this layout looks good??

**Comment by duplixx** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/28d28cf1-0ad2-4911-87cd-7ae99295102c

here is the final preview @rishav-jha-mech

**Comment by rishav-jha-mech** [comment]
@duplixx the flask icon should be almost the same size of manage text, and on smaller screens the button should be of full width

**Comment by duplixx** [comment]
image
@rishav-jha-mech have a look !!

**Comment by rishav-jha-mech** [comment]
@duplixx push the changes for code review

**Comment by duplixx** [comment]
@rishav-jha-mech added changes !!

**Comment by duplixx** [comment]
issues resolved @rishav-jha-mech !!

**Review by rishav-jha-mech — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
