### PR TITLE
Update documentation workflow

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**

### CODE REVIEW

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar Please review

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar Should we close this?

**Comment by palisadoes** [comment]
@anwersayeed @tasneemkoushar Should this be closed or should it be merged?

**Comment by noman2002** [comment]
@anwersayeed @tasneemkoushar Should this be closed ??

**Comment by Nitya-Pasrija** [comment]
This one changes the token name but as the Talawa Admin docs were failing previously, maybe this was the PR that we missed merging.

**Comment by palisadoes** [comment]
@Nitya-Pasrija Can you fix the failing tests for this so that we can get it workflow operational? It does not look like a lot of work.

**Comment by anwersayeed** [comment]
> @Nitya-Pasrija Can you fix the failing tests for this so that we can get it workflow operational? It does not look like a lot of work.

We may close this for now.

**Comment by palisadoes** [comment]
@anwersayeed There is no issue for this PR

Please create an issue for this so that we can track it, then close this PR.

**Comment by Nitya-Pasrija** [comment]
> @Nitya-Pasrija Can you fix the failing tests for this so that we can get it workflow operational? It does not look like a lot of work.

Sure, I'm looking into this one

**Comment by palisadoes** [comment]
@Nitya-Pasrija This is causing the Talawa-Admin documentation to be missing from docs.talawa.io. How is your progress?

**Comment by palisadoes** [comment]
@Nitya-Pasrija This is causing the Talawa-Admin documentation to be missing from docs.talawa.io. 

1. How is your progress?
1. When do you estimate that you'll be able to complete this?

**Comment by tasneemkoushar** [comment]
@Nitya-Pasrija any progress on this PR?

**Comment by Nitya-Pasrija** [comment]
I have started looking into it, will resolve it max to max by first week of December

**Comment by palisadoes** [comment]
> I have started looking into it, will resolve it max to max by first week of December

@Nitya-Pasrija Are you still on track to complete this by next week?

**Comment by palisadoes** [comment]
@Nitya-Pasrija Are you still on track to complete this?

**Comment by Nitya-Pasrija** [comment]
Yep. I'll be creating a PR by Sunday evening

**Comment by palisadoes** [comment]
@Nitya-Pasrija Why was this closed?

**Comment by Nitya-Pasrija** [comment]
A recent PR 968 on Talawa docs, has created major changes and resolves the linking errors as well. Thus, it would have created confusion to have two different PRs referencing different workflows

**Comment by palisadoes** [comment]
@Nitya-Pasrija there is no PR 968.

What is the PR you are referencing?

**Comment by Nitya-Pasrija** [comment]
There is ons under the talawa-docs repository, cuz of the version updates the workflows were activated and hence, they are all working out now.

**Comment by palisadoes** [comment]
Do you mean this PR? And if so, is everything working in the documentation workflow for Talawa Admin and Talawa API?
- https://github.com/PalisadoesFoundation/talawa-docs/pull/690

**Pull request closed without merging**
