### PR TITLE
Talawa admin installer

### LINKED ISSUE #18: Create `Talawa-Admin` Installer
# Introduction

1. We need a single CLI script or program to install Talawa Admin.
1. It must be 100% intuitive and worry free.
1. Must be able to run on Linux or Windows

# General Requirements

1. It is highly preferred that the user does not have to install any additional script interpreter other than those used to run Talawa-Admin.
1. Any failing OS commands must be logged to STDIO, STDERR and .
1. The script must fail if any underlying OS command fails.

The script must:

1. Not require the installation of any prerequisite packages for the script itself to run.
    1. This could be achieved by it installing any missing prerequisite packages for itself to run as part of its operation.
1. Install all required prerequisite packages for `Talawa-Admin` to operate
1. Activate `Talawa-Admin` upon completion of the script
1. Be a part of the `Talawa-Admin` code base
1. Be documented as part of the `Talawa-Admin` installation guide

# Installer Operation
The installation process must:

1. Prompt for:
    1. The API keys required to communicate with the `Talawa-API` server.
    1. The URL to use for communicating with the `Talawa-API` server.
1. Insert all information prompts in a configuration file.
1. Provide the web URL to use to access `Talawa-Admin`

# Post Installer Operation
1. The script (or a second script) must be able to be run to show the status of `Talawa-Admin`.
    1. This must display whether the connection to `Talawa-API` correctly operational
    1. This must display whether `Talawa-Admin` correctly operational

# Related Issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/241

The ability to create organizations in the app must be removed.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

This pull request adds an express installation setup for the Talawa-admin.

**Issue Number:**

Fixes #18 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image
image
image
image

**If relevant, did you update the documentation?**

Yes, I have added the section of Automated Installation in the README.md file, this section redirects to the INSTALLATION.md file which contains the documentation for the same.

**Summary**

The initial setup required several steps to go through in order to install and start the Talawa Admin. Now, it needs just to clone the code, and run a single command. The rest of the installation process will be taken care of by the setup module itself. More information is available at issue #18

**Does this PR introduce a breaking change?**

No

**Other information**

I have gone through the conversation of PalisadoesFoundation/talawa-api#241, and tried to cover all the points mentioned in that conversation.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@asmitsirohi Your linting is failing. Please fix

**Comment by asmitsirohi** [comment]
> @asmitsirohi Your linting is failing. Please fix

Fixed lining errors.

**Comment by yasharth291** [comment]
I have one doubt regarding this why are we using python and making it dependent like if someone wants to install it first he has to make sure that python is working on his computer @asmitsirohi @palisadoes . Why are we not using ```make file```

**Comment by palisadoes** [comment]
@yasharth291 I figured that python would be universally available for Mac, Windows and Linux. Would your makefile solution work for all three? Is there another way to meet this general goal?

**Comment by yasharth291** [comment]
@palisadoes  makefile is just all the required commands in that file and when we run that executable  makefile it automatically do it without even downloading python

**Comment by Devesh21700Kumar** [comment]
> @yasharth291 I figured that python would be universally available for Mac, Windows and Linux. Would your makefile solution work for all three? Is there another way to meet this general goal?


make command runs in mac, windows and Linux successfully.
using `chocolatey` one can use also make freely in windows environment and the installation is simple as well.
https://docs.chocolatey.org/en-us/choco/setup

**Comment by asmitsirohi** [comment]
> I have one doubt regarding this why are we using python and making it dependent like if someone wants to install it first he has to make sure that python is working on his computer @asmitsirohi @palisadoes . Why are we not using `make file`

Is it possible to meet the requirements that are mentioned in PalisadoesFoundation/talawa-admin#18 using MakeFile? I am not sure about that.

**Comment by asmitsirohi** [comment]
> > @yasharth291 I figured that python would be universally available for Mac, Windows and Linux. Would your makefile solution work for all three? Is there another way to meet this general goal?
> 
> make command runs in mac, windows and Linux successfully. and in my opinion, using `chocolatey` one can also use make freely in windows environment and the installation is simple as well. https://docs.chocolatey.org/en-us/choco/setup

But using `chocolatey`, also makes it dependent on `chocolatey` just like python.

**Comment by yasharth291** [comment]
we can make .msi file

**Comment by palisadoes** [comment]
@yasharth291 Make files are for compiling code. I think you are referring to a shell script.

We could use a shell script for Mac / Linux and something else for Windows.

**Comment by palisadoes** [comment]
@yasharth291 @asmitsirohi I merged this by accident and had to revert. Please resubmit. Let's continue the discussion here:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/18

We need to figure out a way to make installation as painless as possible, preferrably without installing additional software as a prerequisite of installation.

**Comment by asmitsirohi** [comment]
@palisadoes  @yasharth291  We can use JavaScript itself as a command-line utility to install or set up the project, this way we are able to resolve the problem of python dependency and cross-platform problems. 

Any suggestions for this?

**Comment by yasharth291** [comment]
that could be done, using python was not at all right as it would be an additional weight on the project. @asmitsirohi

**Comment by palisadoes** [comment]
> that could be done, using python was not at all right as it would be an additional weight on the project. @asmitsirohi

OK, let's pursue this new approach.

**Comment by Devesh21700Kumar** [comment]
Hey @palisadoes . I had some doubts regarding #18  .I feel that key features #18 might not go hand in hand at all the times as:-

(also in reference to #208 )
1). We nee  package installation for talawa-admin installation that means the should have been 
print_console('yarn add yarn add --exact react\n', '#00FF00');
 some where in this PR #208 
but it wont be so cause creating any kind of CLI in any language or framework would require a separate package in itself whether it be chalk/prompt or anything.

2). Even if we manage to run both of them (in a hypothetical case) we can't predict when the yarn installation would end and when yarn serve has to start

3). Another key feature facing a shortcoming might be that it can't be verified from a CLI whether the credetials and token taken from user are correct or not (a graphql query can't be made using this)

And whatever solution I can think of, In the end it only reduces to a feature which takes in credentials and runs yarn serve and the project and probably same number of steps would be needed for installation.
This renders the feature ineffective.

**Comment by palisadoes** [comment]
@Devesh21700Kumar 

- What strategy would you suggest to create an easy to use installer that works and requires the least amount of pre-requisites? 
- Would a simple web based option work like the one WordPress or Mediawiki uses?

It's really important to resolve this.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar
> 
> * What strategy would you suggest to create an easy to use installer that works and requires the least amount of pre-requisites?
> * Would a simple web based option work like the one WordPress or Mediawiki uses?
> 
> It's really important to resolve this.

What I think is that https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#standard-installation

This standard installation procedure here is very well presented and can be used by anyone.

We won't need dockeriztion here , and neither MongoURL parameters in talawa-admin .

Also , in out project we are running the talawa-admin  and talawa-api on port 4000 as well which means that that has to be configured as well or one can just replace the hosted link of talawa-api here

image

In this way if a sequence of steps is mentioned than it would be better and less complex for a new contributor in my opinion.

Using a script/CLI one would still have to do a lot of installations so it does not make any difference in the number of steps.

**Comment by palisadoes** [comment]
We are going to have to host the API and Admin on different ports to make sure they both work if they are both installed on the same server.

If the standard installation process is used, how can we guarantee that the application will restart automatically after a reboot?

I understand the steps are similar with the manual and installer approach. The difference is that with the installer, the user doesn't have to know how to edit files. This may seem trivial to an experienced IT person. But the app may be installed by a junior member of the main organization who has little training.

**Pull request merged**
