### PR TITLE
Updated and optimized Home.test.tsx

### LINKED ISSUE #1131: Code Coverage: Create tests for src/screens/UserPortal/Home/Home.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by vivekBoii**
**What kind of change does this PR introduce?**

Update and optimization of code 

**Issue Number:**

Fixes #1131 

**Did you add tests for your changes?**

This is unittest itself

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Update and optimization of code in Home.test.tsx

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the linting errors.

**Comment by vivekBoii** [comment]
@noman2002 thank you sir for pointing me out , I will not repeat it next time

**Comment by palisadoes** [comment]
Why hasn't the code coverage increased in this PR? The issue was created to increase it to 100%

**Comment by palisadoes** [comment]
The test code coverage is dropping significantly with this PR. Please get to at least 95% coverage for all your edited files. Though there may be issues to increase the coverage for the file, the aim is for them to reach 100% coverage

Please post the screenshot with your coverage when complete

**Comment by palisadoes** [comment]
@vivekBoii are you still working on this?

**Comment by Cioppolo14** [comment]
I am closing this as there hasn't been any activity in 3 weeks.

**Pull request closed without merging**
