### PR TITLE
Fixed #1473: Unexpected behavior when updation of talawa admin members profile.

### LINKED ISSUE #1473: Encountering unexpected behavior when attempting to update Talawa Members' profiles.
**Describe the bug**
1. When attempting to update a member's profile, it seems to require changing the email ID. If this behavior is by design then its fine, else it should also update when the member's name is modified.
2. Despite updating the profile, the member's actual profile remains unchanged. Instead, the user's (your) profile credentials are updated to match the member's credentials.

**To Reproduce**

1. Open Talawa Admin website
2. Click on your profile at the bottom left  
3. Click People Tab on the sidebar
4. Press users checkbox and update a members profile

**Expected behavior**
1. When a user updates a member's profile, the member's profile should get updated even if only the name is edited.
2. After updating the member's profile, it should not affect the user's (your) profile.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/76838871/b72d2ea3-a0d6-4eca-891e-51c2e12a7988

**Additional details**
@palisadoes @aashimawadhwa , If these issues are valid, can I work on it?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Devesh326**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #1473 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/76838871/ee4be25e-0c2c-443c-80f8-3d32f536a13d

**Summary**

Solves the following issues:
1. When attempting to update a member's profile, it required changing the email ID.
2. Despite updating the profile, the member's actual profile remained unchanged. Instead, the user's (your) profile credentials w were updated to match the member's credentials.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by nitishkumar333** [comment]
@Devesh326  If the user edits his own profile then how will leftDrawer update as you have removed localStorage ?

**Comment by Cioppolo14** [comment]
@noman2002  @anwersayeed Can you review this PR?

**Comment by Devesh326** [comment]
> @Devesh326 If the user edits his own profile then how will leftDrawer update as you have removed localStorage ?

Yes, I've addressed that in the latest commit. Now, the system checks if the member's ID matches the root user's ID stored in the localStorage during login. Only under this condition, it utilizes localStorage to update the profile of the root user.

**Comment by palisadoes** [comment]
You will need to pay attention to this PR where we are getting rid of using localstorage that was causing serious difficulties.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1466

**Comment by Devesh326** [comment]
Okay sir, will do the necessary changes

**Comment by Devesh326** [comment]
Hey @palisadoes @noman2002 @anwersayeed ,

This Bug also involves a few changes in the Talawa-Api. I've already implemented the necessary changes. Should I open a new issue in the Talawa API repository and create a corresponding pull request to address this issue?

**Comment by palisadoes** [comment]
Yes

**Review by noman2002 — APPROVED** [review]
Changes looks fine to me.

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing test. The your code doesn't match the schema in some ways. That is why introspection is failing.

**Comment by noman2002** [comment]
> Please fix the failing test. The your code doesn't match the schema in some ways. That is why introspection is failing.

Is the introspection issue fixed now ?

**Comment by palisadoes** [comment]
Yes

**Comment by Devesh326** [comment]
Okay, will check and push a commit to see if the test passes.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
