### PR TITLE
fix: improve code coverage for src/components/EventStats/Statistics/F…

### LINKED ISSUE #1036: Code Coverage: Create tests for src/components/EventStats/Statistics/Feedback.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
**What kind of change does this PR introduce?**

Improve code coverage

**Issue Number:**

Fixes #1036 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by meetulr** [comment]
Recently... a change was made to .eslintrc.json:
Screenshot (1)

Due to which the test is failing because it's encountering "any" in many components:
Screenshot (2)

The purpose of this pr, which is issue #1036, is completed. The coverage has been achieved:
Screenshot (3)

**Comment by palisadoes** [comment]
We reverted the culprit PR. Please merge your submitted code with the upstream.

**Comment by palisadoes** [comment]
@tasneemkoushar Please take a look

**Comment by palisadoes** [comment]
The linting config file has been reverted. Please merge with your upstream and make an updating commit.

**Comment by meetulr** [comment]
Alright! All tests have passed.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
