### PR TITLE
Added tests for MemberDetail.tsx

### LINKED ISSUE #1028: Code Coverage: Create tests for src/screens/MemberDetail/MemberDetail.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by bupd**
**What kind of change does this PR introduce?**
Tests

**Issue Number:**

Fixes #1028 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
achieved100%test

**If relevant, did you update the documentation?**

**Summary**
Achieved 100% test coverage on MemberDetail.tsx

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please watch this video. The cause(s) of your failed code coverage tests may be explained.
- https://www.youtube.com/watch?v=dQuEKpsy1vM

**Comment by noman2002** [comment]
@bupd Merge the latest code into this branch. It will be fixed.

**Comment by bupd** [comment]
@noman2002 I based my branch with the main and changing the base from main to develop for my feature branch will introduce lots of commits. I would like to open another PR with my feature branch based on develop since it removes the error. Should I continue with this approach?

**Comment by palisadoes** [comment]
Yes this has to be closed it's the wrong branch

**Pull request closed without merging**
