### PR TITLE
[FEATURE] Secured Routes implemented and 404 Not Found added

### LINKED ISSUE #341: [Feature Request] Secured Routes and 404 Not Found
**Is your feature request related to a problem? Please describe.**

Currently, in Talawa-admin, the routes are insecure and the authentication of the user is checked only at login. Also, the title for every screen is the same instead of dynamic ones. The 404 not found page is required for the incorrect route.

**Describe the solution you'd like**

The preferable solution is as follows:

* Query to check whether the user is authenticated or not is added.
* Secured route is implemented, so only an authorized user can access the particular screen and unauthenticated users are not able to visit any screen, they have immediately thrown out.
* Title for every component is added and ensures that the user does not explicitly alter the organization ID.
* Not found page added, If any incorrect endpoint is opened then this will be shown.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

feature

Issue Number:

Fixes #341

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

* Unauthorized user tries to access the application
   ezgif com-gif-maker(1)

* User tries to alter the organization ID
   ezgif com-gif-maker

* 404 Not Found Page   
   image

**If relevant, did you update the documentation?**

No

**Summary**

This pull request includes patches of security vulnerabilities and fixes for routing. The complete info is as follows:
* Application loader is added globally, instead of repeated for every component.
* Query to check whether the user is authenticated or not is added.
* Secured route is implemented, so only an authorized user can access the particular screen and unauthenticated users are not able to visit any screen, they have immediately thrown out.
* Title for every component is added and ensures that the user does not explicitly alter the organization ID.
* Not found page added, If any incorrect endpoint is opened then this will be shown.

**Does this PR introduce a breaking change?**

No

**Other information**

This pull request is under GSoC'22.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Asmit, please create an issue for this and configure the PR to automatically close the issue. This requirement is still required.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Asmit, please create an issue for this and configure the PR to automatically close the issue. This requirement is still required.

**Comment by asmitsirohi** [comment]
> Asmit, please create an issue for this and configure the PR to automatically close the issue. This requirement is still required.

Okay

> Asmit, please create an issue for this and configure the PR to automatically close the issue. This requirement is still required.

Okay, I have created an issue.

**Comment by yasharth291** [comment]
Query to check whether the user is authenticated or not is added.
i have question regarding this now is it a session based application?

**Comment by asmitsirohi** [comment]
> Query to check whether the user is authenticated or not is added. i have question regarding this now is it a session based application? @asmitsirohi i will suggest make it like a session based application

Yes, Now it is session-based, As soon as access token expires, user will be logged out.

**Comment by yasharth291** [comment]
> > Query to check whether the user is authenticated or not is added. i have question regarding this now is it a session based application? @asmitsirohi i will suggest make it like a session based application
> 
> Yes, Now it is session-based, As soon as access token expires, user will be logged out.

also add a timely check like after every 20 minutes and update the status of the session as well and please use cookies instead of local storage

**Comment by asmitsirohi** [comment]
Actually, there is no need for timely checks, because it is already done on the server-side. For e.g. If the user is on a dashboard page, then he/she navigates to another page. If the token expires then he/she will automatically be logged out. Also, sessions will last until users log out themselves.

I was thinking of using cookies, but there is no such difference in our case because the token is in the hashed form if the user alters it then it will be not authenticated.

**Comment by asmitsirohi** [comment]
Okay, Can I implement cookies in another issue or pull request because the changes in this pull request are quite large. Till then, the local storage version is also stable.

**Comment by yasharth291** [comment]
> Okay, Can I implement cookies in another issue or pull request because the changes in this pull request are quite large. Till then, the local storage version is also stable.

ok

**Review by yasharth291 — APPROVED** [review]

**Comment by yasharth291** [comment]
@palisadoes  please merge it

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
