### PR TITLE
Feature: Event Agenda Items CRUD operations

### LINKED ISSUE #1778: Feature Request : Add support for Event agenda Items
**Is your feature request related to a problem? Please describe.**
 The app needs to support the API's newly implemented ability to make events have agendas.
Agenda item needs all of these features which are already implemented on the API : 
1. Title
2.Description
3.Agenda item type (See "Note" type below)
4. Agenda item type information (For example if an organization creates a type called "Song, they may want to make this track the key of the music)
5.Duration of the agenda item
6.Multiple Attachments stored on the system
7.Multiple URL links
8.Agenda item "User" to indicate a speaker, performer or similar party

**Describe the solution you'd like**
 1. Admin should be able to see all the agenda items for an event. 
 2. Admin should be able to add, remove or update an agenda item within his reach and ease of accesibilty.
 3. Admin should be able to make a note agenda item 
 4. He should be able to see which category the item belongs to.
 5. And other agenda item features must be implemented on the admin 
 
 
 Related parent issue : 
  Create support for event agenda items [Creating suppport for Event agendas](https://github.com/PalisadoesFoundation/talawa-admin/issues/1677) #1677 
 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by gautam-divyanshu**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1778 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/22520a59-89c5-44df-96c9-dd726a53fc82

**update button:-**

https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/0953fa70-5ead-4bcb-8e33-729f5cf2517a

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
  - Implemented agenda item management with features to create, update, delete, and preview agenda items.
  - Added drag-and-drop functionality for reordering agenda items.

- **Bug Fixes**
  - Improved error handling and validation for URLs and file attachments in agenda items.

- **Localization**
  - Added translations for agenda item-related messages and fields in English, French, Hindi, Spanish, and Chinese.

- **Style**
  - Introduced comprehensive styling for agenda items, including modals, buttons, icons, tables, and drag-and-drop elements.

- **Tests**
  - Added extensive tests for agenda items management components, including creation, updating, deletion, and error handling.

### CODE REVIEW

**Comment by gautam-divyanshu** [comment]
@palisadoes I am trying to improve the code coverage but facing some difficulty for writing test cases such as drag and drop for sequence

I will resolve the changes requested by codeRabbit.

**Comment by gautam-divyanshu** [comment]
@palisadoes I tried improving code coverage as much as possible, but there are some lines for which I can't write a test case.

I tried writing a test case for drag and drop but did not get success.
so can we merge this PR?

**Comment by gautam-divyanshu** [comment]
I tried a lot, but code coverage is not going up.

**Review by palisadoes — APPROVED** [review]

**Comment by gautam-divyanshu** [comment]
@palisadoes  No, I tried almost everything.
and low code coverage is due to src code only; I have checked coverage for single files locally.

**Comment by palisadoes** [comment]
Thanks

**Pull request merged**
