### PR TITLE
fixed people screen filter

### LINKED ISSUE #1852: Admin - Org - People filters don't work
**Describe the bug**
Selection by role doesn't work on Org > People.

**To Reproduce**

1. Login via super admin
2. Select any Org
3. Goto People from left side bar
4. Try to change "Search by role"
image

**Expected behavior**
Should filter according to role

**Actual behavior**
- Users - shows undefined
- Members and Admins show same

**References:**
1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1568

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by kanhaiya04**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #1852 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/b44c30fc-8f54-4286-a6c4-0958c20a4dba

**If relevant, did you update the documentation?**

**Summary**
People screen filter is now working properly and also removed the `UPDATE_USERTYPE_MUTATION` 

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks. 

- Please try to increase the code coverage of the patch. It's only 76%. 
    image
 
- This file was affected noticeably
    image

**Comment by pranshugupta54** [comment]
@kanhaiya04, did you fix this?

**Comment by kanhaiya04** [comment]
@pranshugupta54 Working on it.
Got some issue in tests.

**Comment by kanhaiya04** [comment]
@palisadoes, I have increased the code coverage.
Have a look.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
