### PR TITLE
fix: Improved events calendar page

### LINKED ISSUE #1175: Improved calendar view for events screen
**Is your feature request related to a problem? Please describe.**
The calendar screen does not provide with a good user expereince

**Describe the solution you'd like**
A new calendar view to match the User interface of talawa admin

**Additional context**
we can make something like this with colors and themes similar to what  used in talawa 
Screenshot 2023-12-10 at 10 16 53 PM

Note: Do fix the placement of add event button and remove the small calendar

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pateldivyesh1323**
**What kind of change does this PR introduce?**

Improved calendar view of events page

**Issue Number:**

Fixes #1175

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

- Before

image

- After

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/700ca33b-560a-4eab-8fb2-1082d2e20075

**If relevant, did you update the documentation?**

No

**Summary**

- Matched colors 
- Removed small calendar
- Improved borders
- Moved add events button to right top
- Added previous and next icons

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@pateldivyesh1323 
Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
We had to revert a PR that was causing tests to fail incorrectly. Please submit a minor commit to trigger an update of the GitHub workflow

**Comment by aashimawadhwa** [comment]
@pateldivyesh1323 the calendar looks good but can we work more on fixed tile sizes and making it visible in a view-port and is this calendar responsive?

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa The events will not fit in fixed tile sizes, so I will have to add "more" button to display the events of that date, Is that ok?
image

**Comment by aashimawadhwa** [comment]
Yes please do that on small screen sizes and for the rest show the events as in the tailadmin calendar.

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa The events are not fitting on single tile on larger screens also, a single tile can handle one or two events not more than that, it will break after it, so should I add "more" button on larger screens similarly?

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa The events are not fitting on single tile on larger screens also, a single tile can handle one or two events not more than that, it will break after it, so should I add "more" button on larger screens similarly?

this will not accelerate the user experience, please follow the designs as similar to https://demo.tailadmin.com/calendar this demo.

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa In demo it does shows only single event, but in our case we have multiple events which are not fitting in fixed tile size.

**Comment by aashimawadhwa** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/60996af6-c006-4d52-8a4b-52f274313733

you can show 2 events by default in ascending order and then show a more button, to fit 2 events decrease the width of event tile and handle rest case as it is handled in google calendar. @pateldivyesh1323

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa Does this look good?

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/2a7b30e3-5214-4595-9f31-21db02f23920

**Review by aashimawadhwa — CHANGES_REQUESTED** [review]
Merge the latest code into this branch, this maybe the cause of of your failed code coverage tests .

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa I have pushed the latest code

There is no use of these file `src\screens\OrganizationEvents\calendar.css` and `react-calendar` package now as we removed the small calendar

**Should I remove them?**

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa I have pushed the latest code
> 
> There is no use of these file `src\screens\OrganizationEvents\calendar.css` and `react-calendar` package now as we removed the small calendar
> 
> **Should I remove them?**

Yes sure you can clean the code.

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa Done👍

**Comment by aashimawadhwa** [comment]
can you fix this? @pateldivyesh1323 
Screenshot 2023-12-15 at 11 34 42 PM

**Comment by pateldivyesh1323** [comment]
@aashimawadhwa Done

**Review by aashimawadhwa — APPROVED** [review]
LGTM 👍🏼 @rishav-jha-mech  please have a look.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
