### PR TITLE
Updated Twitter to X links and references

### LINKED ISSUE #2147: Change Twitter to X links
**Describe the bug**

In social column it should be X instead of twitter.
**To Reproduce**

1. Scroll down to footer
2. Check socials

**Expected behavior**
Should show "https://x.com/palisadoesorg?lang=en"
**Actual behavior**
the link shows "https://twitter.com/palisadoesorg?lang=en" 

**Screenshots**
image
**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by BishalJena**
What kind of change does this PR introduce?

This PR introduces a visual update to replace the Twitter link with the new X link.

Issue Number:

Fixes #2147 

Did you add tests for your changes?

No

Snapshots/Videos:

If relevant, did you update the documentation?

Not applicable

Summary

This pull request updates the Twitter links to the new X links.

Does this PR introduce a breaking change?

No

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

Yes

## Summary by CodeRabbit

- **New Features**
	- Updated social media branding from Twitter to X across the application, including logo and links.
  
- **Bug Fixes**
	- Adjusted references in the Community Profile and Login Page tests to maintain functionality with the new identifier "X".

- **Documentation**
	- Enhanced clarity in the handling and representation of social media links in the application.

- **Chores**
	- Updated constants and exported entities to reflect rebranding changes in the codebase.

### CODE REVIEW

**Comment by BishalJena** [comment]
@palisadoes kindly merge this PR if all checks pass.

**Comment by Cioppolo14** [comment]
@BishalJena Please fix the failed checks.

**Comment by varshith257** [comment]
@BishalJena You can always create a branch with upstream develop and raise PR against develop branch too. Could you mind submitting new PR against develop branch?

**Comment by BishalJena** [comment]
@varshith257 sure i'll raise same PR from develop branch, can you check and tell me if there's any other change i gotta do?

**Comment by varshith257** [comment]
It looks fine to me

**Pull request closed without merging**
