### PR TITLE
Fixed postion of 'All Organizations' button and changed its name

### PR DESCRIPTION
**Pull request by adi790uu**
What kind of change does this PR introduce?

This PR renames the "All Organizations" button to "My Organizations" and fixes its postion as specified in the issue.

Issue Number: #1123 

Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1123

Did you add tests for your changes?

No

Snapshots/Videos:

https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/d7d35876-8f97-4bc9-84d6-7757f0fa7979

If relevant, did you update the documentation?

No

Summary

This pull request addresses the specified issue by renaming the "All Organizations" button to "My Organizations" and adjusting its position to enhance the UI/UX.

Does this PR introduce a breaking change?

No

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by adi790uu** [comment]
@noman2002 @aashimawadhwa created this pr for develop branch

**Comment by palisadoes** [comment]
This screen should say "My Organizations" for consistency. That was one of the goals of creating the issue

image

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. This screen should say "My Organizations" for consistency. That was one of the goals of creating the issue
1. The text should already be part of the JSON language translation files. Make sure the text changes according to the language selected. We don't want hard coded text.
1. You'll need to update the JSON language translation files

image

**Comment by adi790uu** [comment]
@palisadoes in the original issue I had to change the postion of All organization's button and change its name to My organisation which is present in left sidebar and this pr introduces those changes!

**Comment by palisadoes** [comment]
> @palisadoes in the original issue I had to change the postion of All organization's button and change its name to My organisation which is present in left sidebar and this pr introduces those changes!

That may be true, but the overall objective is to have a better UI/UX. By going the extra mile, we achieve that goal. We all want a better product, and you revealed a need that must be addressed

**Comment by adi790uu** [comment]
@palisadoes will fix it for sure and cover all the changes requested!

**Comment by aashimawadhwa** [comment]
@adi790uu  any updates on this?

**Comment by adi790uu** [comment]
@aashimawadhwa will complete it by tomorrow

**Comment by adi790uu** [comment]
@aashimawadhwa will complete it today

**Comment by palisadoes** [comment]
Please provide the video that shows that the changes have been implemented, with proof of automatic changing of all the menu items when the language is changed.

**Comment by adi790uu** [comment]
Uploading f3bcd311-3ab7-4888-90cb-dcb2dbaa49a9.mp4…

@palisadoes

**Comment by adi790uu** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/a344d91d-bf08-4c40-ae22-87e2816d01bc

@palisadoes

**Comment by palisadoes** [comment]
@aashimawadhwa @beingnoble03 @rishav-jha-mech please review

**Review by aashimawadhwa — APPROVED** [review]
LGTM, can be merged. we have a different issue that covers test for orglist.tsx rest tests are covered.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
