### PR TITLE
Feature Request: Adding a dialog to go to plugin store after an organization is created by the admin

### LINKED ISSUE #948: Feature Request: Adding a dialog to go to plugin store after an organization  is created by the admin
**Is your feature request related to a problem? Please describe.**
To understand the context please refer to this video: https://youtu.be/9rBc9sdpLjM?t=513
As the plugin would be installed by default the admins should be prompted that they would be using everything or they can visit the store to disable no required features. 
**Describe the solution you'd like**
Adding a dialog:
image

**Describe alternatives you've considered**
N/A
**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**

Rectoring and new feature addition

**Issue Number:**

Fixes #948  & #952 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
 #### Youtube video ⬇️ 

[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=klDNSYXnCno)
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=5GOGf-C3WEo)

**If relevant, did you update the documentation?**
Will do in future
**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
1. @SiddheshKukade Please update the first comment so that both issues will be closed automatically when this PR is merged.
2. Please also add the required tests for the failing GitHub actions.

**Comment by SiddheshKukade** [comment]
Yes, sir, I'm fixing the merge conflicts. The recent merged has change the my OrgList.tsx file again. I'll make sure everything works again

**Comment by SiddheshKukade** [comment]
Hello @tasneemkoushar @DMills27, I've managed to get everything to work again. You can review it now.

**Review by DMills27 — DISMISSED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@SiddheshKukade One of the files doesn't meet the code coverage number. Please fix this.

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comments in PR

**Review by tasneemkoushar — APPROVED** [review]

**Comment by SiddheshKukade** [comment]
Hello @palisadoes Sir, Now the PR is ready to be merged.  
I've tried to add some tests to increase code coverage.
The Line numbers [listed here](https://github.com/PalisadoesFoundation/talawa-admin/pull/951/checks?check_run_id=16202981698) were actually mostly internal logic part that contained some asynchronous functions. 
I've been trying to cover them up in different ways for the past 4 hours, but facing errors in tests.
The OrgList.test.tsx is almost fully covered & UI tests for AddOnEntry tests are added.

Please review and merge,
Thanks

**Pull request merged**
