### PR TITLE
Upgrade react-router-dom and setup layout in routes

### LINKED ISSUE #1407: Upgrade React-router-dom to latest version and setup layouts
**Is your feature request related to a problem? Please describe.**

We are rendering the LeftDrawer (sidebar) component on every endpoint, which is a major performance issue, sidebar should be made common is all endpoints.

Newer version of react-router-dom allows us to setup layouts for common component to improve performance.

Currently Talawa-admin uses react-router-dom v5.2.0 which was released in 2020.
They have introduced many changes since then like,
useHistory hook is changed to useNavigate
Switch is changed to Routes

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by nitishkumar333**
**What kind of change does this PR introduce?**
Refactoring

Fixes #1407 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/d404c017-fc75-4b77-ae44-7975ac8463a2

**Summary**
Upgraded react-router-dom to latest version and refactored the code by setting up layout for routes in App.tsx.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@nitishkumar333 Please fix the PR Workflow linting related tests errors.

**Comment by Cioppolo14** [comment]
@nitishkumar333 Please fix the codecov failing tests.

**Comment by nitishkumar333** [comment]
@Cioppolo14 

The only file which is giving codecov error now is AddOnStore, I can't write tests for it because most part of the file is commented ( I think someone is working on it ). It will be a different issue to cover that file.

All of my changes have 100% coverage, as a result code coverage is up by +0.45%

Please review the PR.

**Comment by Cioppolo14** [comment]
@beingnoble03 @Kevoniat Can you review this PR?

**Comment by Cioppolo14** [comment]
@nitishkumar333 Please fix the conflicting files.

**Comment by palisadoes** [comment]
Please fix the failing tests
- Code coverage is declining. The tests for the files you have submitted are not complete

**Comment by nitishkumar333** [comment]
@palisadoes all the files changes by me have 100% coverage and code coverage is increased by +0.45% from this PR.

The only file which is giving codecov error now is AddOnStore, I can't write tests for it because most part of the file is commented ( I think someone is working on it ). It will be a different issue to cover that file.

**Comment by palisadoes** [comment]
1. Please fix the failing introspection test
2. The API was recently updated and you'll need to update your code to match

**Comment by noman2002** [comment]
Closing due to inactivity.

**Comment by nitishkumar333** [comment]
Hi @noman2002, sorry for the delay was having my exams, please reopen this PR i would like to complete it.

**Pull request closed without merging**
