### PR TITLE
CONTRIBUTING.md file 

### PR DESCRIPTION
**Pull request by XshubhamX**
If you find any typo in the file ,please fix it  :)

### CODE REVIEW

**Comment by XshubhamX** [comment]
@palisadoes I have made contributing.md file Please have a look.

**Review by XshubhamX — COMMENTED** [review]
resolves #2

**Comment by heyjordn** [comment]
Thanks @XshubhamX , this looks good, merging

**Comment by XshubhamX** [comment]
Your welcome sir,
I have also made a pull request on talawa-api sir can you please check,so that I can start making further advancements

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by XshubhamX** [comment]
Your welcome sir @heyjordn ,
I have also made a pull request on talawa-api sir can you please check,so that I can start making further advancements

**Pull request merged**
