### PR TITLE
Strict lint and update PR workflow

### LINKED ISSUE #1427: Lint `git` Committed Files & PR Deltas / `no-explicit-any`
We need the ability to selectively adjust our linting rules so that they are eventually applied to our entire code base.

1. Linting rules are managed by the `.eslintrc.json` file.
1. They are applied to the entire code base at once.
1. If we change a rule from `warn` to `error` then every file in the code base will be checked and we have frequently seen our tests fail for dozens of files in hundreds of lines of code.

This is not acceptable.

We have been trying to more strictly lint the entire code base manually, but it has been very slow.

## At the user CLI
We need a way to edit `.eslintrc.json` with increasingly stricter linting rules in such a way that the tests are only applied to the changed files with every `git commit` and `git push` command. 

These `git` commands must fail if the linting fails.

## With Every Pull Request

We are working on a Talawa-API pull request that checks each submitted file for linting compliance. This can be used as an example of how to run the test against individual files.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1677

You must make sure that this functionality applied for all PRs for this repository whenever the  `.eslintrc.json` file is updated

## Other

1. There may be ways to achieve the CLI goals by updating our existing Git Hooks
1. Your solution should preferably work within coding environments such as VScode
1. Please work with @EshaanAgg on this issue

## Screenshots

When complete, you should be able to convert all these  `.eslintrc.json` file lines containing `warn` or `off` to `error` and the tests will only be applied to the changed files in `git`

image

### PR DESCRIPTION
**Pull request by lakshz**
**What kind of change does this PR introduce?**
Stricts the lint config to consider `no-explicit-any` as an error.

Updated PR workflow:
 - Linting Checks in PR, will be done only on changed-files
 
Updated pre-commit script:
 - `lint-staged` configuration was added in `package.json` file, taking help `talawa-api` project.

**Issue Number:**

Fixes #1427 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by lakshz** [comment]
Screenshot 2024-03-06 at 18 03 59

I want to highlight that, if we strict the lint of `no-explicit-any`, the project will be functionally same, but it will show lint errors on running. 

Solution to this, would be to first migrate the codebase with no `any`, and then strict the lint.

**Comment by Cioppolo14** [comment]
@anwersayeed @tasneemkoushar Can you review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
