### PR TITLE
 Fix: Change ID from query parameter to path segment

### LINKED ISSUE #2017: URL Issue: ID Passed as Query Parameter Instead of Path Segment
**Describe the bug**

The URL currently uses a query parameter to pass the ID (e.g., url/id=343434) instead of including the ID as part of the path (e.g., url/343434). This format does not adhere to the expected RESTful URL structure.

**To Reproduce**

1. Login as a the user 
2. go the donation page 
3. click on "view all" on the right
4. you will see not any members because of the invalid url but if you remove " id=" from the url , you will see all members. 

**Expected behavior**
All members should be visible. 

**Actual behavior**
Members are not visible .

**Screenshots**

image

https://github.com/PalisadoesFoundation/talawa-admin/assets/71646466/e7df0612-30e5-4c59-8a23-6df88fc0da79

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by lokeshsingh3721**
What kind of change does this PR introduce?

This PR introduces a bug fix that changes the way IDs are passed in the URL. Previously, IDs were passed as query parameters, and now they will be passed as path segments. This change improves the readability and structure of the URLs.

Issue Number:

Fixes #2017 

Snapshots/Videos:

https://github.com/PalisadoesFoundation/talawa-admin/assets/71646466/85780595-6a03-41de-a6d0-2dd9a19a729e

Does this PR introduce a breaking change?

NO

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

YES

## Summary by CodeRabbit

- **Bug Fixes**
  - Updated URL structures across the application by removing the `id=` parameter for more streamlined and readable paths.
  - Corrected navigation links in the Organization Sidebar and Add Member screens to ensure proper redirection.

- **Refactor**
  - Enhanced type safety and rendering logic in the Organization Sidebar component for better performance and reliability.
  
- **Tests**
  - Adjusted test cases to align with the new URL format, ensuring consistent and accurate testing of navigation functionality.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please fix the failing tests. 
2. Make your changes to your local branch and make a commit
3. Do not close this PR. It is not necessary

**Comment by lokeshsingh3721** [comment]
> 1. Please fix the failing tests.
> 
>     2. Make your changes to your local branch and make a commit
> 
>     3. Do not close this PR. It is not necessary

okay

**Review by Nitya-Pasrija — APPROVED** [review]

**Comment by lokeshsingh3721** [comment]
image

when i am running this command its showing everything is fine,  but having issues in CI. @palisadoes can you please help me. i was having the same issue with tests in my previous pr.

**Comment by palisadoes** [comment]
Please ask the #talawa-admin slack channel for guidance on the tests

**Comment by lokeshsingh3721** [comment]
> Please ask the #talawa-admin slack channel for guidance on the tests

all checks are passed.

**Comment by lokeshsingh3721** [comment]
@palisadoes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
