### PR TITLE
Simulated Test Database

### LINKED ISSUE #983: Frontend Interface for Sample Organization
**Is your feature request related to a problem? Please describe.**
In order to load data to use for demo and testing purposes the user needs to run a command

**Describe the solution you'd like**
Add a button to the "Create Organization Form" that would allow admins to click and create a sample organization
Include some indicator that can mark organizations as sample
Provide some way to use the sample org amongst real data with the option of removing it without affecting real data.

**Describe alternatives you've considered**
N/A

**Additional context**
This pull request is related to the backend che

### PR DESCRIPTION
**Pull request by JamarTG**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**
fixes #983

**Did you add tests for your changes?**

N/A

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/71823011/0a9e96ac-322b-41e7-b00c-aa4b9b2051d1

**Does this PR introduce a breaking change?**

No

**Other information**

The related backend changes can be found here https://github.com/PalisadoesFoundation/talawa-api/pull/1369(must be merged before this PR)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@jordan-barrett-jm @JamaicanFriedChicken Please review. I'd like to get this merged into the code base soon

**Comment by beingnoble03** [comment]
@JamarTG please update the PR description.
"What kind of change does this PR introduce?"
It should clearly explain what changes the PR brings. This is very important for other contributors.

**Comment by rishav-jha-mech** [comment]
@JamarTG 
1. Remove the border above the Create Organization Button
2. Remove the cancel button
3. Remove `backdrop="static"` from Create Organization Modal
4. Make sure the layout looks like the image I provided, `Create Organization button` with full width then `Create Sample Organization` Button with full width.

image

**Comment by palisadoes** [comment]
@JamarTG Please fix the conflicting files so that we can have this work with your API PR that was just merged.

**Review by jordan-barrett-jm — APPROVED** [review]
Approving PR

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
