### PR TITLE
Code Coverage: Increased coverage for src/components/UserPortal/Login/Login.tsx to 100%

### LINKED ISSUE #1032: Code Coverage: Create tests for src/components/UserPortal/Login/Login.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by karthxk07**
**What kind of change does this PR introduce?**

This PR introduces improvements to increase code coverage to 100% in src/components/UserPortal/Login/Login.tsx file.

**Issue Number:**

Fixes #1032 

**Did you add tests for your changes?**

Yes.

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No documentation update required

**Summary**

This PR enhances the code coverage of src/components/UserPortal/Login/Login.tsx file to 100%. By achieving full code coverage, we ensure that all code paths are tested, thus improving the reliability and maintainability of the codebase. This aligns with our goal of delivering high-quality software to our users.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Review by Sauradip07 — COMMENTED** [review]
Don't Remove this 
`if (data) {`
`
else {
          /* istanbul ignore next */
          toast.warn(t('notAuthorised'));
        }
`
this is the Essential Part of Code
Rather than remove this, you have to write the test So that Branch test is covered 100 %

**Comment by Sauradip07** [comment]
@karthxk07 
Testing the else branch of `handleLogin` function:

Currently, you have tests for when `loginVariables.email` or `loginVariables.password` is empty. You also need to test the case when both are not empty.
You also need to test the else branch of the if (data) condition.
Currently, The tests are covered for the login mutation fails` (catch block).` You also need to test the case when the login mutation is successful, but data is null.

As of my Google search, I found some Good Resource that can he;p You to make this PR Successful 

I provide the Approach here :
```
test('Login is unsuccessful', async () => {
  const formData = {
    email: 'invalid@gmail.com',
    password: 'anything',
  };

  render(
    <MockedProvider addTypename={false} link={link}>
      <BrowserRouter>
        <Provider store={store}>
          <I18nextProvider i18n={i18nForTest}>
            <Login {...props} />
          </I18nextProvider>
        </Provider>
      </BrowserRouter>
    </MockedProvider>
  );

  await wait();

  userEvent.type(
    screen.getByPlaceholderText(/Enter your email address/i),
    formData.email
  );

  userEvent.type(
    screen.getByPlaceholderText(/Enter your password/i),
    formData.password
  );

  userEvent.click(screen.getByTestId('loginBtn'));

  await wait();

  // Verify toast.warn is called
  expect(toast.warn).toHaveBeenCalledWith('notAuthorised');
});
```
Please Look into it and Modify it,
Rather than change the `Login.tsx`  Create the test in 'Login.test.tsx'

**Comment by karthxk07** [comment]
@Sauradip07 I had already tried using this approach. I found out that  in the Mocked query since there was no result, it throws an error and the control is shifted to the catch block immediately, which makes the `else { /* istanbul ignore next */ toast.warn(t('notAuthorised')); }` block never accessible.

**Comment by karthxk07** [comment]
@Sauradip07 So, I thought editing the code might be the solution (I agree, this might be only good for a mocked environment and not for the final deployment) . How should I proceed about it then.

**Comment by Cioppolo14** [comment]
Please fix the linting errors.

**Comment by Sauradip07** [comment]
> @Sauradip07 So, I thought editing the code might be the solution (I agree, this might be only good for a mocked environment and not for the final deployment) . How should I proceed about it then.

@karthxk07 
I understand the problem, but I can’t find any solution. 😢

Maybe then, removal is the only option left.

Could the maintainer please assist with this issue

**Review by rishav-jha-mech — CHANGES_REQUESTED** [review]
@karthxk07 what are you trying to achieve here ?, you have just changed the email in tests and expecting the code coverage to go up ?, Also the data can be undefined as well that's why there is an if condition over there, you will have to write the test case for it.

If you are having any issues with that, please use jest-preview and check how the UI looks like with the test env you are trying to create.

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by noman2002** [comment]
@karthxk07 Are you still working on this ?

**Comment by karthxk07** [comment]
@noman2002 I had been trying things , but for some reason the uncovered line is always bypassed with every combination of test cases. I might not be able to complete the PR maybe :confused:

**Comment by palisadoes** [comment]
I'm going to close this and see whether someone else can find a solution.

**Pull request closed without merging**
