### PR TITLE
fix: #601 modal responsive width

### LINKED ISSUE #601: Styling issues - Modals are not responsive
**Describe the bug**
Modals like the login modal, create post modal, create organization modals are not responsive on screens between 600px and 960px.

**To Reproduce**

 On a screen or device with a width within the range 600px and 960px; 
1. Click on the "Login" button
2. Click on "Create Organization" button
3. Click on "Post" navlink on the navbar

**Expected behavior**
The modal that contains the form is supposed to be responsive to provide a better UI/UX.

**Actual behavior**
The modal is not responsive enough.

**Screenshots**

postmodal-bug

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Phyya**
**What kind of change does this PR introduce?**

This change fixes login, create post and create organization modals responsive issues.

**Issue Number:**

Fixes #601 

**Did you add tests for your changes?**
Not required. Css style edits.

**Summary**

I have removed the set width for the modals allowing them to be more responsive for the indicated screen sizes.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by noman2002 — COMMENTED** [review]
Add a video to show the responsiveness.

**Comment by palisadoes** [comment]
Screen shots would work too.

**Comment by Phyya** [comment]
Okay. Please find the video showing the responsiveness below. 

https://user-images.githubusercontent.com/80838239/224482134-c279130f-61a7-4dcd-a4c7-563d0524ca7b.mp4

**Comment by Kevoniat** [comment]
> Okay. Please find the video showing the responsiveness below.

@palisadoes is this the expected behaviour

**Review by Kevoniat — COMMENTED** [review]
so you just removed the default width and didn't add any media query?

**Review by Kevoniat — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
