### PR TITLE
Changed event date and time picker

### LINKED ISSUE #1239: Calendar Times Must be Dropdown or Clock Motif
**Is your feature request related to a problem? Please describe.**

1. The user has to enter the start and stop times for an event, while the dates are entered using the mouse
2. This is an inconsistent user experience

**Describe the solution you'd like**
1. Create a suitable interface
1. The solution must accommodate the mandatory use of seconds in the calendar timing
1. Work with @aashimawadhwa or @rishav-jha-mech for the desired interface selection
1. 100% test code coverage for the solution

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

1. Talawa image
image
1. Google image
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

This PR changes the event Time Picker and Date Picker to Material UI ones.

**Issue Number:**

Fixes #1239 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/1f52197d-2695-44ac-bef5-89f6192c1a8d

**If relevant, did you update the documentation?**

**Summary**

This PR modernizes and makes the Date Picker and Time Picker more user friendly. 

**Does this PR introduce a breaking change?**

No

**Other information**

I have added a global Material UI Theme in the index.ts file as well

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by aarishshahmohsin** [comment]
@rishav-jha-mech @aashimawadhwa Is there any update?

**Comment by aarishshahmohsin** [comment]
@rishav-jha-mech @aashimawadhwa Is there any update?

**Comment by aarishshahmohsin** [comment]
@Cioppolo14 Is there any update with regards to the PR. I am not able to move on to other issues.

**Review by beingnoble03 — APPROVED** [review]
lgtm. thanks @aarishshahmohsin

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
