### PR TITLE
Configurable Session timeout for Community

### LINKED ISSUE #2151: Enhancements For Session Management in Both User And Admin Portal
Is your feature request related to a problem? Please describe.
The lack of admin-configurable session timeouts, absence of pre-timeout
warnings, and inadequate logout messaging disrupt user experience and can lead to frustration
among users.

Describe the solution you'd like
Solution focuses on overcoming these challenges by introducing configurable
session timeouts, warning notifications before session expiry, and seamless redirection to the
login screen upon logout

Describe alternatives you've considered
n/a

Approach to be followed (optional)
The project involves researching session management solutions and planning the implementation strategy, followed by creating detailed design documents and UI mockups, and reviewing these with stakeholders. Configuration settings will be developed in the Talawa-Admin Portal and backend logic will be implemented in Talawa-API. Pre-timeout notifications will be developed in the Talawa mobile app, and logout messaging will be enhanced. Testing will include writing and executing test cases, conducting peer reviews, and integrating feedback. Documentation will be updated and new guides will be written and approved. User feedback will be gathered, bugs identified, and necessary improvements made to finalize features. Finally, features will be deployed to production, followed by final testing to ensure smooth operation.

### PR DESCRIPTION
**Pull request by JordanCampbell1**
**What kind of change does this PR introduce?**

Feature: Session Timeout

**Issue Number:**

Fixes #2151

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

image
image
image

**Summary**

Making the change to include a session timeout, hence creating sessions for the application, ensures that there is a layer of security when users use the application. These changes to Talawa Admin will allow configurable logout that affects the community as well as automatic logout when the user is inactive for the selected session timeout period

https://github.com/PalisadoesFoundation/talawa-admin/issues/2151

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Added new localization strings for "Completed" in English, French, Hindi, Spanish, and Chinese to enhance user experience.
	- Improved clarity in terminology related to action items and organization settings across multiple languages.
	- Introduced new icons for "Agenda Items Category" and "Event Stats" for better visual representation.
	- Enhanced the structure and functionality of the Event Management component with new SVG icons and streamlined tab selection.
	- Added `redux-thunk` for improved management of asynchronous actions in the application.
	- Introduced a new `Community` type and updated mutations in the GraphQL schema for enhanced functionality.

- **Bug Fixes**
	- Improved tooltip functionality with the latest version of the `react-tooltip` dependency.
	- Refined error handling in the Forgot Password process for better user feedback.

- **Chores**
	- Updated project dependencies to ensure the latest features and improvements are utilized.
	- Removed outdated linting rules and added new ones to enhance type safety in TypeScript code.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@JordanCampbell1 Can you fix the failed test application test?

**Comment by JordanCampbell1** [comment]
> @JordanCampbell1 Can you fix the failed test application test?

sure I will take a look

**Comment by JordanCampbell1** [comment]
finished up on the fixes, waiting for review

**Comment by JordanCampbell1** [comment]
@Cioppolo14

**Comment by varshith257** [comment]
@JordanCampbell1 Can you fix merge conflicts?

**Comment by JordanCampbell1** [comment]
just fixed it @varshith257

**Comment by palisadoes** [comment]
@DMills27 @aashimawadhwa Please review

**Comment by aashimawadhwa** [comment]
Hey @JordanCampbell1  can you fix the issues, will begin review shortly after that.

**Comment by JordanCampbell1** [comment]
> Hey @JordanCampbell1 can you fix the issues, will begin review shortly after that.

working on it now

**Comment by JordanCampbell1** [comment]
just finished up @aashimawadhwa @DMills27

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review, updated the code

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by JordanCampbell1** [comment]
fixed the issue

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review please

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review?

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 fixed the lint issues from previous merge,  could you review?

**Comment by aashimawadhwa** [comment]
Screenshot 2024-09-22 at 10 09 21 PM

@DMills27  @JordanCampbell1

**Comment by JordanCampbell1** [comment]
> Screenshot 2024-09-22 at 10 09 21 PM
> @DMills27 @JordanCampbell1

once the API is merged into the codebase then this will be resolved

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by JordanCampbell1** [comment]
@aashimawadhwa @DMills27 could you review?

**Comment by JordanCampbell1** [comment]
@palisadoes made the PR for the develop branch for the admin as well

**Comment by palisadoes** [comment]
@DMills27 @aashimawadhwa Please review

**Comment by DMills27** [comment]
@JordanCampbell1 please fix the conflicts and the failing tests.

**Comment by JordanCampbell1** [comment]
@palisadoes @DMills27 @aashimawadhwa fixed all issues, should be ready for merge now

**Review by DMills27 — APPROVED** [review]

**Pull request merged**
