### PR TITLE
Redesign of Posts screen for talawa user portal.

### LINKED ISSUE #1514: USER REDESIGN: redesign the Posts screen for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Posts screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.
current situation :
Screenshot 2024-01-28 at 11 52 42 PM
Desired Result:
Screenshot 2024-01-28 at 11 47 04 PM

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
**What kind of change does this PR introduce?**
UI redesign.

**Issue Number:**

Fixes #1514 

**Did you add tests for your changes?**
Not yet.

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/fd3fe77f-dcf1-4a56-b427-44c369cd5cf3
image

image

**If relevant, did you update the documentation?**
No.

**Summary**

**Does this PR introduce a breaking change?**
No.

**Other information**
This PR is still in progress.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@git-init-priyanshu Please fix the linting issue.

**Comment by beingnoble03** [comment]
@git-init-priyanshu i think the design doesn't matches with the figma design. Also, looks like the `View Post` button doesn't actually work here.

**Comment by git-init-priyanshu** [comment]
> @git-init-priyanshu i think the design doesn't matches with the figma design. Also, looks like the `View Post` button doesn't actually work here.

Yes. In the figma design I could not understand why is there a 'Browse File' button next to the input area in the Figma design. Where will the title and description be placed? And for the 'View Post' button, I am working on it.

**Comment by git-init-priyanshu** [comment]
Hey @aashimawadhwa, I have made `View Post` modal UI. It is not included in the Figma file so I created one. I would like to know your opinion. Thanks.
image

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by git-init-priyanshu** [comment]
I finally understood the Figma design and made the designs accordingly.
image

**Comment by palisadoes** [comment]
Please fix the conflicting files. It looks good otherwise.

**Comment by git-init-priyanshu** [comment]
> Please fix the conflicting files. It looks good otherwise.

Yes sir. I have my exams next week so I am trying to finish this before that. I will try to finish this ASAP.

**Comment by palisadoes** [comment]
Good luck with your exams. Thanks

**Comment by git-init-priyanshu** [comment]
Should I also add functionality to these dropdown items?
image

**Comment by palisadoes** [comment]
Don't have the share, and pin post icons. 

1. Pinned posts are only for Admins via the Admin portal. 
2. We can add sharing at a later stage.

**Comment by pranshugupta54** [comment]
Please fix type errors

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by git-init-priyanshu** [comment]
Please do not merge this PR right now. I am adding edit post and delete post functionalities.

**Comment by git-init-priyanshu** [comment]
This PR is ready to merge now If everything seems fine.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
