### PR TITLE
fix: improve code coverage for src/screens/OrgPost/OrgPost.test.tsx

### LINKED ISSUE #1029: Code Coverage: Create tests for src/components/OrgPostCard/OrgPostCard.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### LINKED ISSUE #1136: Code Coverage: Create tests for src/screens/OrgPost/OrgPost.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
**What kind of change does this PR introduce?**

Added code coverage for src/screens/OrgPost/OrgPost.test.tsx

**Issue Number:**

Fixes #1136 
Fixes #1029

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by meetulr** [comment]
> Thanks.
> 
> Please also get the test code coverage for the typescript files you edited up to 100%
> 
> We are trying to get back up to 95% coverage overall to ensure the reliability of our code. @meetulr

A test is failing because of incomplete code coverage in components outside the scope of this issue. 
The coverage of src/screens/OrgPost/OrgPost.test.tsx (which is the file related to the assigned issue) is now 100%, after i made the necessary changes. I didn't change any other component or it's test file.
I've had this problem with another pull request too #1150. That pr has been merged.

**Comment by aashimawadhwa** [comment]
The test are failling due to the code in this file itself, you can check the report [here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1165/blob/src/components/OrgPostCard/OrgPostCard.tsx)

**Comment by meetulr** [comment]
> The test are failling due to the code in this file itself, you can check the report [here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1165/blob/src/components/OrgPostCard/OrgPostCard.tsx) @meetulr

Yes, that's what i meant. The file mentioned in the above report is src/components/OrgPostCard/OrgPostCard.tsx, and the file associated with this issue is src/screens/OrgPost/OrgPost.tsx #1136. The test is failing because of incomplete coverage in other component files. Those components have their separate issues open which are assigned to someone else.
Same case with my last pr #1150, which was merged despite that one test failing.
What should I do?

**Comment by palisadoes** [comment]
> > The test are failling due to the code in this file itself, you can check the report [here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1165/blob/src/components/OrgPostCard/OrgPostCard.tsx) @meetulr
> 
> Yes, that's what i meant. The file in the linked report is src/components/OrgPostCard/OrgPostCard.tsx, and the file associated with this issue is src/screens/OrgPost/OrgPost.tsx #1136. The test is failing because of incomplete coverage in other component files. Those components have their separate issues open which are assigned to other contributors. Same case with my last pr #1150, which was merged despite that one test failing. What should I do?

Comment on this issue for that file so that we can assign it to you. Fix both issues with this PR.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1029

**Comment by palisadoes** [comment]
According to the code coverage report this PR will get us over 95% coverage which will stop the errors in future.

image

This PR was supposed to get us over 95% which is why it was merged with the error failure. 95% coverage is our goal.
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1150

Why do you think the coverage isn't crossing the threshold?

**Comment by meetulr** [comment]
> > > The test are failling due to the code in this file itself, you can check the report [here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1165/blob/src/components/OrgPostCard/OrgPostCard.tsx) @meetulr
> > 
> > 
> > Yes, that's what i meant. The file in the linked report is src/components/OrgPostCard/OrgPostCard.tsx, and the file associated with this issue is src/screens/OrgPost/OrgPost.tsx #1136. The test is failing because of incomplete coverage in other component files. Those components have their separate issues open which are assigned to other contributors. Same case with my last pr #1150, which was merged despite that one test failing. What should I do?
> 
> Comment on this issue for that file so that we can assign it to you. Fix both issues with this PR.
> 
> * [Code Coverage: Create tests for src/components/OrgPostCard/OrgPostCard.tsx #1029](https://github.com/PalisadoesFoundation/talawa-admin/issues/1029)

I have commented on that issue, but the test that is failing here is checking some other files too [report](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1165?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
Some of those files have their own open issues assigned.
Would it still not fail the test until all of them are 100% covered?

**Comment by palisadoes** [comment]
I spoke too soon. I wasn't paying sufficient attention.

1. Yes, the patch is may have 100% coverage but the overall code base has 94.7% coverage.
2. The behaviour of CodeCov seems to have changed. The GitHub pull request CodeCov report passes with tick marks, but fails in the testing workflow.
3. It also seems that the reporting is incorrect in other ways, because this is not the first time I've seen that the PR would improve the code coverage by an amount to get us over our 95% target, with the coverage not exceeding 95% afterwards.

In the past CodeCov has been similarly temperamental, so we have been merging test PRs for the sake of speed expecting the overall coverage to be under 95% We will be more stringent after we reach this goal.

**Comment by palisadoes** [comment]
1. Please post the code coverage for the file you are testing in the PR to prove you have reached 100%.
2. Based on the online report it looks like it is only 95.08%

**Comment by meetulr** [comment]
> 1. Please post the code coverage for the file you are testing in the PR to prove you have reached 100%.
> 2. Based on the online report it looks like it is only 95.08%

Sure, if we look at the details of the test that has failed [here](https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7142865262/job/19457103603?pr=1165) it shows us exactly what lines were missing coverage and in what components, at the time I committed.
As we can see, it shows no missing lines for src/screens/OrgPost/OrgPost.tsx.

As for the 95.08% coverage, I think it's covering multiple files between the two commits. The change of +1.94% is because of the file I changed.

**Comment by palisadoes** [comment]
I've asked some others to review this and merge if acceptable.

**Comment by meetulr** [comment]
Ok, now it's passing all the tests, the coverage is 100% for both the files (issues #1136 & #1029).

**Review by noman2002 — APPROVED** [review]
LGTM

**Comment by meetulr** [comment]
Oops!!, I accidentally clicked the refresh button which sent out another review request to you @noman2002. Please ignore it. My apologies for the confusion.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
