### PR TITLE
Fixed tests for src/screens/OrganizationEvents/OrganizationEvents.tsx

### LINKED ISSUE #1786: Test: Create tests for src/screens/OrganizationEvents/OrganizationEvents.tsx v4
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

This PR adds tests for src/screens/OrganizationEvents/OrganizationEvents.tsx

**Issue Number:**

Fixes #1786 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

This PR adds tests for src/screens/OrganizationEvents/OrganizationEvents.tsx

**Does this PR introduce a breaking change?**

NA

**Other information**

I have added ignore statements in the file because of the non-null assertions failing the lint test. I think there should be a revamp for this problem.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by pranshugupta54** [comment]
@aarishshahmohsin, we need to improve the tests. This PR is decreasing the coverage
image

**Comment by Cioppolo14** [comment]
@aarishshahmohsin Please fix the failing tests.

**Comment by pranshugupta54** [comment]
@Cioppolo14, this file already has 100% coverage and PR is decreasing it
image

**Comment by aarishshahmohsin** [comment]
> @Cioppolo14, this file already has 100% coverage and PR is decreasing it image

I think this PR [link](https://github.com/PalisadoesFoundation/talawa-admin/pull/1817) increased the coverage.

**Comment by aarishshahmohsin** [comment]
> @Cioppolo14, this file already has 100% coverage and PR is decreasing it image

About the decrease,
the coverage says that the PR indirectly affected the src/screens/OrgList/OrganizationModal.tsx file [(link)](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1820/indirect-changes). 

There is already an issue created for this file [(link)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1785).

**Comment by palisadoes** [comment]
Closing. The coverage is already at 100%

**Pull request closed without merging**
