### PR TITLE
fix: Ensure Full Visibility of Logo on 404 Error Page

### LINKED ISSUE #1016: 404 Error Page Logo Partially Covered
**Describe the bug**
The bug pertains to the 404 error page where the logo is partially covered, making it not fully visible as expected.

**To Reproduce**

1. Navigate to any endpoint which is not defined
2. There opens a 404 - Page Not Found
3. Observe the position and visibility of the logo.

**Expected behavior**
 The logo should be fully visible and not covered, ensuring it is displayed correctly.

**Actual behavior**
The logo is partially covered, affecting its visibility and not meeting the expected display.

**Screenshots**
404_page_logo_align

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
- Adjusted the positioning of the logo on the 404 error page to ensure full visibility.
- Implemented CSS modifications to prevent the logo from being covered or cut off.
- Tested the changes by navigating to various undefined endpoints, confirming that the logo is now displayed correctly on the 404    error page.

**Issue Number:**

Fixes #1016 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
 Fixed the 404 page
404_corrected_logo

**If relevant, did you update the documentation?**

**Summary**
Previously the 404 error page was experiencing an issue where the logo was partially covered, resulting in incomplete visibility.
This commit addresses the bug by ensuring the proper display of the logo on the 404 error page, enhancing the user experience.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Is this an issue that only affects some screen sizes? You have only lowered the image by a few pixels. It would seem that a better solution would be to show content relative to the top vs the bottom.

**Comment by beingnoble03** [comment]
@akhilender-bongirwar I don't think reducing the image size here solves the issue. I think this would be some problem related to padding or margin.

**Comment by akhilender-bongirwar** [comment]
> Is this an issue that only affects some screen sizes? You have only lowered the image by a few pixels. It would seem that a better solution would be to show content relative to the top vs the bottom.

Thank you for the review.

**Previously**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/f33ade2b-4207-4f14-825c-1722995141f5

- The problem is present on all the screen sizes as shown in the above video.

**Currently**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/022cc99a-11f0-4465-9295-0eaa61e45ae4

- Currently after this change the logo is visible properly on all the screen sizes as I shown in the above video.

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar I don't think reducing the image size here solves the issue. I think this would be some problem related to padding or margin.

Thank you for the review. 
@beingnoble03, I did not reduce the image size here, but I have decreased the bottom CSS property for the whole 404 page because it was pushing the logo above, making it not visible properly.

**Comment by beingnoble03** [comment]
@akhilender-bongirwar what happen's if we reduce the height of the screen? Is this page scrollable?

**Comment by akhilender-bongirwar** [comment]
**Before**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/2ffe7aee-40c6-452b-8c9f-aed42a9b1eec

**After**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/e6cf8b63-ccba-453e-9f9d-aa429653d47f

Yeah ,@beingnoble03 the page is scrollable on reducing the height of the screen.

**Review by beingnoble03 — APPROVED** [review]
LGTM.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
