### PR TITLE
Standardized and Added UTC conversion for Date and Time

### LINKED ISSUE #1888: Standardizing the date and time format
**Describe the bug**
Throughout the repository, It can be seen that dates and times are differently formatted.

**To Reproduce**
Search for date and time.

**Expected behavior**
A standardized way of storing dates and time. The best way is to create types for them. 

**Actual behavior**
Different formats of time and date.

**Screenshots**

320226032-65ebbd40-100c-4acf-8710-c6ecdf00bbc8

**Additional details**
The dependent issue is being currently worked on by me: https://github.com/PalisadoesFoundation/talawa-admin/issues/1813

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

This PR standardizes and adds UTC conversion for Date and Time.

**Issue Number:**

Fixes #1888

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

Conversion of date and time to and from UTC ensures they remain same irrespective of the location of the user

**Does this PR introduce a breaking change?**

No

**Other information**

This PR also adds functions for https://github.com/PalisadoesFoundation/talawa-admin/issues/1813

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin why are you changing the formatting and conversion of dates this way? Did you test the functionalities with these changes? They'll break stuff and cause wierd results due to time zone discrepancies.

I refrained from changing the date formats for this very reason. I only changed the time format.

**Comment by aarishshahmohsin** [comment]
@meetulr I have only converted the date and time when any mutation and query is called. Can you please specify how would it break and what should I do to fix it?

**Comment by meetulr** [comment]
Sorry for not being clear... I was referring to the conversion of dates mainly. It'll cause discrepancies. Did you thoroughly test the functionalities manually?

**Comment by aarishshahmohsin** [comment]
> Sorry for not being clear... I was referring to the conversion of dates mainly. It'll cause discrepancies. Did you thoroughly test the functionalities manually?

Yes, I have tested them by console logging and checking the conversions. Can you further brief me about the discrepancies that could occur?

**Comment by meetulr** [comment]
The conversion is not required at all, at the end, the dates are passed in the format `YYYY-MM-DD`, which was correctly formatted according to the local date. The way you're doing it will overcompensate for time zone discrepancies and cause weird behaviour.

**Comment by meetulr** [comment]
> > Sorry for not being clear... I was referring to the conversion of dates mainly. It'll cause discrepancies. Did you thoroughly test the functionalities manually?
> 
> Yes, I have tested them by console logging and checking the conversions. Can you further brief me about the discrepancies that could occur?

I meant did you call the mutations? Are the results as expected?

**Comment by aarishshahmohsin** [comment]
> The conversion is not required at all, at the end, the dates are passed in the format `YYYY-MM-DD`, which was correctly formatted according to the local date. The way you're doing it will overcompensate for time zone discrepancies and cause weird behaviour.

the conversion is actually for the parent issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/1813

**Comment by meetulr** [comment]
> > The conversion is not required at all, at the end, the dates are passed in the format `YYYY-MM-DD`, which was correctly formatted according to the local date. The way you're doing it will overcompensate for time zone discrepancies and cause weird behaviour.
> 
> the conversion is actually for the parent issue: #1813

Yes i know but this conversion is pointless don't you think? Because of the reason i mentioned above.

I think it'll break things and produce weird results. I'll test things with your code from my side too😅.

**Comment by aarishshahmohsin** [comment]
> > the conversion is actually for the parent issue: #1813
> 
> Yes i know but this conversion is pointless don't you think? Because of the reason i mentioned above.
> 
> I think it'll break things and produce weird results. I'll test things with your code from my side too, and confirm if that's the case😅.

The conversion if for edge cases where the timezone difference may cause change in dates. However, the severity of the issue is questionable.

**Comment by meetulr** [comment]
> The conversion if for edge cases where the timezone difference may cause change in dates. 

What I'm saying is, the dates are already correctly formatted according to local time zones, as they are right now, they'll cause no discrepancies. 
But the changes you've made will most likely cause these discrepancies. As I said the dates are being sent in the format `YYYY-MM-DD`, dayjs would correctly format it, but unnecessarily adjusting the hours could easily case discrepancies.

**Comment by meetulr** [comment]
I'll test things tomorrow from my side too.
But if you're still working, try creating an event between 12:00AM - 5:30AM tonight, see if it works as expected.

**Comment by palisadoes** [comment]
@meetulr 

The rationale in sending all dates to the API as UTC and then converting them back to the local timezone in the client is stated here.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1813

Let me know if you still have concerns after evaluating the reasoning.

**Comment by meetulr** [comment]
> @meetulr
> 
> The rationale in sending all dates to the API as UTC and then converting them back to the local timezone in the client is stated here.
> 
> * [Admin: Store all dates in the database in UTC #1813](https://github.com/PalisadoesFoundation/talawa-admin/issues/1813)

Yes sir, I'm aware of the issue. I was talking about this specific implementation, and how dates are handled currently in the codebase.
I just tested this code. Yes, it's breaking things and causing weird behavior.

What I was saying earlier is that, the dates are being passed in the format `YYYY-MM-DD` to the backend, and are extracted in the same format. i.e. **we're dealing with only the date part, and not the time part**. What this code does is just alter this date part unnecessarily (and it's also formatting it incorrectly), which would only serve to cause discrepancies, and there would be no way of converting it back to the appropriate date when we get it back from the backend.

This issue would require some planning first, and corresponding changes in the api. To work with UTC conversions, we would need the **time part** in our date too, and for that, we would need to change the graphql type of our dates from `Date` to `DateTime` in the backend. i.e. we may need to revise our strategy of handling dates.

**Comment by palisadoes** [comment]
The sequence of events seems to be:

1. Merge this PR
2. Merge a PR for the mobile issue to convert that client's times to UTC
    1. https://github.com/PalisadoesFoundation/talawa/issues/2446
4. Create issues for the API, Admin and Mobile to convert all times to date-time.

@meetulr @aarishshahmohsin @Azad99-9 - Please confirm

**Comment by meetulr** [comment]
> > @meetulr
> > The rationale in sending all dates to the API as UTC and then converting them back to the local timezone in the client is stated here.
> > 
> > * [Admin: Store all dates in the database in UTC #1813](https://github.com/PalisadoesFoundation/talawa-admin/issues/1813)
> 
> Yes sir, I'm aware of the issue. I was talking about this specific implementation, and how dates are handled currently in the codebase. I just tested this code. Yes, it's breaking things and causing weird behavior.
> 
> What I was saying earlier is that, the dates are being passed in the format `YYYY-MM-DD` to the backend, and are extracted in the same format. i.e. **we're dealing with only the date part, and not the time part**. What this code does is just alter this date part unnecessarily (and it's also formatting it incorrectly), which would only serve to break things and cause discrepancies, and there would be no way of properly converting it back to the appropriate date when we get it back from the backend.
> 
> This issue would require some planning first, and corresponding changes in the api. To work with UTC conversions, we would need the **time part** in our date too, and for that, we would need to change the graphql type of our dates from `Date` to `DateTime` in the backend. i.e. we would need to revise our strategy of handling dates throughout the codebase.
> 
> btw do we need to convert the dates? e.g. with the current implementation, if there's an event scheduled at `2024-04-13`. It will show the event on that date only (13), regardless of what time zone we're in. But for hourly accuracy, we would need the time part as I've mentioned.
> 
> Please let me know if there's been some discussion on this😅

Sir, as I've said, **this PR is breaking things**.
1. Date conversion done in this PR is just wrong.😅
2. Time conversion done in this PR seems to be doing nothing, i.e. it's giving the same output as before. @aarishshahmohsin?

**Comment by palisadoes** [comment]
@meetulr 

I see what you are saying. Yes we need more date precision. 

However, the database doesn't store all dates and times in DateTime format. 

We'll need to change that too for consistency and the removal of any doubt about timing in general. 

This would mean creating an issue in the API possibly as a separate branch. 

What do you think?

**Comment by meetulr** [comment]
> @meetulr
> 
> I see what you are saying. Yes we need more date precision.
> 
> However, the database doesn't store all dates and times in DateTime format.
> 
> We'll need to change that too for consistency and the removal of any doubt about timing in general.
> 
> This would mean creating an issue in the API possibly as a separate branch.
> 
> What do you think?

That is what I'm saying, first we need to convert the types to `DateTime`. Then write the code for conversion.

Yes definitely in a separate branch for thorough testing and ensuring that nothing's broken.

Maybe maintainers would suggest a good approach here.

**Comment by Azad99-9** [comment]
> The sequence of events seems to be:
> 
>     1. Merge this PR
> 
>     2. Merge a PR for the mobile issue to convert that client's times to UTC
>        
>        1. [Mobile: Store all dates in the database in UTC talawa#2446](https://github.com/PalisadoesFoundation/talawa/issues/2446)
> 
>     3. Create issues for the API, Admin and Mobile to convert all times to date-time.
> 
> 
> @meetulr @aarishshahmohsin @Azad99-9 - Please confirm

@palisadoes I agree with what @meetulr said. 

It's better to follow this approach.

1. Create a separate branch to fix the DateTime type.
2. Work on making the entire code base DateTime consistent.
3. Make sure that nothing breaks and everything works as expected.
4. Merge the DateTime branch into develop.
5. Raise issues to accommodate UTC conversions.

**Comment by palisadoes** [comment]
Closing. We can continue the discussion here:

- https://github.com/PalisadoesFoundation/talawa-api/discussions/2222

**Pull request closed without merging**
