### PR TITLE
Bug Fix: Resolve linting errors

### PR DESCRIPTION
**Pull request by karan2704**
**What kind of change does this PR introduce?**

Fixes linting errors

**Issue Number:**

#186 

**Did you add tests for your changes?**

Not needed

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

Not needed

**Summary**

ESlint github action fails when a PR is generated. This issue will probably fix it.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by karan2704** [comment]
I've replaced empty functions with dummy functions as instructed it still fails. Could it be a problem with GitHub actions? @yasharth291

**Comment by yasharth291** [comment]
@karan2704  I am not able to get time to see this we will be solving this tomorrow

**Comment by palisadoes** [comment]
@karan2704 We are still seeing linting issues. Please fix and submit your code.

This is holding us up. Other PRs cannot be run until this is fixed.

image

**Comment by karan2704** [comment]
Yes I was seeing errors and discussed with @yasharth291 as well didn't have the idea as to how to proceed ... As you suggested we can revert the original PR that introduced the error I'll generate another one for that enhancement issue soon @palisadoes

**Comment by palisadoes** [comment]
@karan2704  There have been significant changes to the code base in recent days. Please merge your code with the current `upstream/develop` branch, fix the conflicting files (if any), and push the result to your repo. The PR will be automatically updated.

**Pull request closed without merging**
