### PR TITLE
Enabling editing an advertisement

### LINKED ISSUE #1157: Enabling editing an advertisement
**Is your feature request related to a problem? Please describe.**
We have ensured CRUD operations throughout the talawa( wherever necessary). We require an edit ad modal in the Advertisement section on all the created ads.

**Describe the solution you'd like**
An editing ad modal on all created ads, ensuring fields similar to create ads modal.

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Vaishali054**
**What kind of change does this PR introduce?**

Enabling editing an advertisement

**Issue Number:**

Closes #1157  

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

-Edit advertisement modal
 
Screenshot 2023-12-09 132506

-Edit button in the card
image

**If relevant, did you update the documentation?**

NA

**Summary**

Adding edit advertisement modal

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by rishav-jha-mech** [comment]
@Vaishali054, please follow this layout while rendering advertisement cards. 
This same layout will be followed in Posts Card soon, so both screens would look similar.

Add the edit advertisement and delete option at the top where there is ellipsis icon with a dropdown, and the place where you have kept Edit button, it can be replaced with View button.

Also change the header of the Edit Modal of Advertisement with Theme coloured Bg and white text. And change the text from `Close the Window` to `Edit Advertisement`.

image

**Comment by Vaishali054** [comment]
@rishav-jha-mech I updated the code with the changes mentioned above.

**Comment by palisadoes** [comment]
Please fix the failing tests. Some may be fixed by updating your branch with the lastest upstream

**Comment by palisadoes** [comment]
Please try to get the test code coverage up to 100% for each of the files you edited.

**Comment by Vaishali054** [comment]
Okay @palisadoes

**Comment by palisadoes** [comment]
Please merge your code with the latest upstream in the API and Admin repos and test again. That should fix the introspection PR error.

**Comment by Vaishali054** [comment]
@palisadoes ,I am not sure but I think updateAdvertisement function is not yet added in the talawa-api, it was a new feature request
image

**Comment by palisadoes** [comment]
@SiddheshKukade Please comment on this as you created the advertising feature

**Comment by palisadoes** [comment]
@Vaishali054 If the feature isn't available in the API, are you able to add it?

**Comment by Vaishali054** [comment]
I will create an issue and add it to the talawa-api, if that's okay, I coded most of it on my local but it is not yet complete.

**Comment by palisadoes** [comment]
> I will create an issue and add it to the talawa-api, if that's okay, I coded most of it on my local but it is not yet complete.

OK. Please ask one of the queue monitors mentioned in our #general slack channel to assign you the issue as you create it.

**Comment by Vaishali054** [comment]
Okay!!

**Comment by SiddheshKukade** [comment]
@Vaishali054 you can check from the API Files I think I've added that function in backend already.

**Comment by Vaishali054** [comment]
@SiddheshKukade I went through the repository, and I think I missed it, could you please give the function or file name if possible?

**Comment by palisadoes** [comment]
The test code coverage is dropping significantly with this PR. Please get to at least 95% coverage for all your edited files. Though there may be issues to increase the coverage for the file, the aim is for them to reach 100% coverage

Please post the screenshot with your coverage when complete

**Comment by SiddheshKukade** [comment]
Okay, let me check if it's not there I'll add it.

**Comment by Vaishali054** [comment]
@SiddheshKukade thank you.
@palisadoes waiting for updates from @SiddheshKukade on update advertisement. Once that is done, I will add tests to increase coverage as those 6 missing lines are api call to update advertisement. Getting update advertisement on backend will fix introspection error and adding test cases will fix the rest of the checks.

**Comment by palisadoes** [comment]
> @SiddheshKukade thank you. @palisadoes waiting for updates from @SiddheshKukade on update advertisement. Once that is done, I will add tests to increase coverage as those 6 missing lines are api call to update advertisement. Getting update advertisement on backend will fix introspection error and adding test cases will fix the rest of the checks.

OK. In the mean time try some other issues. This is an important feature to add.

**Review by SiddheshKukade — DISMISSED** [review]
Looks good

**Comment by palisadoes** [comment]
Please fix the confllcting files

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
