### PR TITLE
Fixes multiple add members screen layout issues #2232

### LINKED ISSUE #2232: Multiple `Add Member` Screen Layout Issues
**Describe the bug**

1. Most of the headings are not translated
1. The heading isn't translated. The layout should reflect the key elements of the screen behind. For example, there are no icons beside the member names. 

**To Reproduce**

1. Login as an Admin or Super Admin
2. Select an organization
3. Select the people page
4. Attempt to add a new or an existing member

**Expected behavior**

**Actual behavior**

- A better user experience with the mentioned issues corrected 

**Screenshots**

1. Most of the headings are not translated
    image

1. The heading isn't translated. The layout should reflect the key elements of the screen behind. For example, there are no icons beside the member names. 
image

**Additional details**
- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Nandika-A**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2232 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

1. Translated the headings
Screenshot (100)

2. Translated the headings and added icons beside the member names.
image

**If relevant, did you update the documentation?**

Not relevant here

**Summary**

This PR fixes the screen layout issues in 'Add Member' functionality in organisations as mentioned in the issue #2232 .  The translations are added in translation.json and to add the icons, a new column named 'profile' is created in the modal, which displays the avatar if present, otherwise creates a new avatar for the user.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced localization support with new translations for user information fields and account management functionalities in English, French, Hindi, Spanish, and Chinese.
	- Improved `Add Member` interface by adding a profile image column for better visual representation of users.

- **Bug Fixes**
	- Updated the invalid details message to provide clearer guidance on required information.

- **Tests**
	- Expanded test coverage for the `OrganizationPeople` component, including validations for displaying user profile images.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Please get the test code coverage for the patch up to 100%. The reliability of our code depends on it.
    image
1. Make sure you have translations for all languages and that they work

**Comment by Nandika-A** [comment]
> 1. Please get the test code coverage for the patch up to 100%. The reliability of our code depends on it.
>    image
> 2. Make sure you have translations for all languages and that they work

Thanks for the review. I will make these changes.

**Comment by Nandika-A** [comment]
Hi @palisadoes , I have added translations for all languages and tests for displaying profile icon in add existing users modal. Could you check if further changes are required?

**Comment by palisadoes** [comment]
> Please work on getting the test code coverage for the patch up to 100%
> 
> image

Please work on this. We need the test coverage to be better. Our code can only be reliable if it's properly tested.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please increase the test code coverage for the typescript files you edited up to 100%. Ask our slack community for guidance

**Comment by Nandika-A** [comment]
> Please increase the test code coverage for the typescript files you edited up to 100%. Ask our slack community for guidance

Hi @palisadoes! I have added the new test cases. However, I encountered some issues running Codecov for this repository and couldn't verify the test coverage myself. Could you please check if these test cases bring the patch's test coverage to 100%? Thank you for your help.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
