### PR TITLE
fixes - [#597] - Navbar navlinks hover and button styles 

### LINKED ISSUE #597: Styling Issue - Hovering on the navlinks breaks navbar styles
**Describe the bug**
Upon hovering on the navlinks on the navbar, the "All Organizations" button style breaks which is not good for the UI.

**To Reproduce**

1. Login the admin portal
2. Click on Manage to view an organization
3. Hover over any of the navlinks (Dashboard, People, Events...etc).

**Expected behavior**
The "All Organizations" button is not supposed to move. The navbar style is not supposed to be shaky.

**Actual behavior**
The "All Organizations" button becomes bigger and out of styles. The navbar moves about upon hovering on the navlinks.

**Screenshots**
talawa-bug-header

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Phyya**
**What kind of change does this PR introduce?**

This change improves the UI/UX of the navbar. It stops the navbar navlinks hover styles from disrupting the main UI.

**Issue Number:**
#597 

Fixes #597 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

talawa-navbar-fixed

**Summary**

This PR solves the issue of a distracting user experience that occurs upon hovering on a navlink on the navbar by adding a "white-space: nowrap" style to the button to prevent the text from splitting unto a new line thereby increasing the height of the button. 

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by jadeharr** [comment]
@Phyya Thank your for your contribution. This PR will be closed due to lack of documentation of what this PR is.

**Comment by Phyya** [comment]
Hi @jadeharr, I'm sorry. I clicked on the "Submit button" by mistake. I have updated the documentation. Please reopen. Thanks

**Comment by palisadoes** [comment]
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix the conflicting files. Pull the latest code it will be resolved.

**Comment by Phyya** [comment]
@noman2002, thank you very much. I have learnt to pull from upstream before pushing. All checks pass now.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
