### PR TITLE
fixes codeQL warning

### PR DESCRIPTION
**Pull request by Devesh21700Kumar**
@palisadoes This will fix this 
https://github.com/PalisadoesFoundation/talawa-admin/issues/108#issuecomment-1003540452
push hook also had to be specified that's why that warning was caused.

### CODE REVIEW

**Review by Devesh21700Kumar — COMMENTED** [review]
Since I changed a file in the .github/ path it shows unauthorized file change error

image

**Comment by palisadoes** [comment]
@Devesh21700Kumar 

1. You have edited the pull request file. For pushes we'd need to create a `push.yml` file in keeping with the spirit of the [README.md](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/.github/workflows) in that directory.  
1. Your solution would make us run all the tests (not just CodeQL) on a periodic basis, after each push or pull. We need to have the evaluation done immediately, not as a `cron` job. 

Based on the CodeQL documentation, it looks like we will need a separate CodeQL workflow file, with the CodeQL section in the `pull-request.yml` file moved to the new CodeQL file. Please investigate if this is so, and create PR that fixes #108 for that.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar
> 
> 1. You have edited the pull request file. For pushes we'd need to create a `push.yml` file in keeping with the spirit of the [README.md](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/.github/workflows) in that directory.
> 2. Your solution would make us run all the tests (not just CodeQL) on a periodic basis, after each push or pull. We need to have the evaluation done immediately, not as a `cron` job.
> 
> Based on the CodeQL documentation, it looks like we will need a separate CodeQL workflow file, with the CodeQL section in the `pull-request.yml` file moved to the new CodeQL file. Please investigate if this is so, and update this PR to automatically fix #108.

Sure will fix this

**Review by Devesh21700Kumar — COMMENTED** [review]
@palisadoes do check this one out.

**Comment by palisadoes** [comment]
@Devesh21700Kumar Have you tested this on a  repo under your account to verify this works? Please add the link to a successful GitHub Actions run in the repo. 

[Looking at the original file](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml), there is a  continuous integration section included to install dependencies. Is that needed for your solution?

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar Have you tested this on a repo under your account to verify this works? Please add the link to a successful GitHub Actions run in the repo.
> 
> [Looking at the original file](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml), there is a continuous integration section included to install dependencies. Is that needed for your solution?

1).Yes I have tested it https://github.com/Devesh21700Kumar/talawa-admin/runs/4684748064?check_suite_focus=true

image

no warning here

2). No CI was not added as a dependency by me in the `.github/workflows/codeql-analysis.yml`
file as it was in a different file altogether.

**Comment by palisadoes** [comment]
@Devesh21700Kumar Thanks. I really prefer to have the pushes and pull requests in separate files unless it is absolutely necessary to have them together. Your most recent solution doesn't have the cron schedule, so we won't be re-running the GitHub actions repeatedly. Based on this we should: 

- Add your modified CodeQL solution to `pull-requests.yml` for pull requests only.
- Create a `push.yml` file that includes your CodeQL modifications. 

I know the CodeQL sections in both files will be very similar with duplication, but doing it this way allows us to govern the order of the checks which will be important in future. Make sure the line `needs: Continuous-Integration` is included in `pull-requests.yml` to make sure it runs in sequence.

Thanks for your patience. We are both learning from this.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar Thanks. I really prefer to have the pushes and pull requests in separate files unless it is absolutely necessary to have them together. Your most recent solution doesn't have the cron schedule, so we won't be re-running the GitHub actions repeatedly. Based on this we should:
> 
> * Add your modified CodeQL solution to `pull-requests.yml` for pull requests only.
> * Create a `push.yml` file that includes your CodeQL modifications.
> 
> I know the CodeQL sections in both files will be very similar with duplication, but doing it this way allows us to govern the order of the checks which will be important in future. Make sure the line `needs: Continuous-Integration` is included in `pull-requests.yml` to make sure it runs in sequence.
> 
> Thanks for your patience. We are both learning from this.

Sure will do that

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar Thanks. I really prefer to have the pushes and pull requests in separate files unless it is absolutely necessary to have them together. Your most recent solution doesn't have the cron schedule, so we won't be re-running the GitHub actions repeatedly. Based on this we should:
> 
> * Add your modified CodeQL solution to `pull-requests.yml` for pull requests only.
> * Create a `push.yml` file that includes your CodeQL modifications.
> 
> I know the CodeQL sections in both files will be very similar with duplication, but doing it this way allows us to govern the order of the checks which will be important in future. Make sure the line `needs: Continuous-Integration` is included in `pull-requests.yml` to make sure it runs in sequence.
> 
> Thanks for your patience. We are both learning from this.

Justt Tried this out and the warning popped back in.
Seems like an on.push event is quite necessary whenever we work with codeQL or it will keep popping up.

So, I think an on.push in `pull-requests.yml` is needed as well along with a separate `push.yml` that works only on push

**Comment by Devesh21700Kumar** [comment]
> > @Devesh21700Kumar Thanks. I really prefer to have the pushes and pull requests in separate files unless it is absolutely necessary to have them together. Your most recent solution doesn't have the cron schedule, so we won't be re-running the GitHub actions repeatedly. Based on this we should:
> > 
> > * Add your modified CodeQL solution to `pull-requests.yml` for pull requests only.
> > * Create a `push.yml` file that includes your CodeQL modifications.
> > 
> > I know the CodeQL sections in both files will be very similar with duplication, but doing it this way allows us to govern the order of the checks which will be important in future. Make sure the line `needs: Continuous-Integration` is included in `pull-requests.yml` to make sure it runs in sequence.
> > Thanks for your patience. We are both learning from this.
> 
> Justt Tried this out and the warning popped back in. Seems like an on.push event is quite necessary whenever we work with codeQL or it will keep popping up.
> 
> So, I think an on.push in `pull-requests.yml` is needed as well along with a separate `push.yml` that works only on push

made the change and there's no warning

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
