### PR TITLE
fix: Fixed custom field submission on Enter key press

### LINKED ISSUE #1395: [Bug] Error Triggered When Pressing "Enter" Instead of Clicking "Submit" Button When Adding Custom Field in Settings
## Describe the bug
When attempting to add a custom field in the settings, an error occurs if the "Enter" key is pressed instead of clicking on the "Submit" button.

## To Reproduce

* Navigate to the settings section.
* Look for the option to add a custom field.
* Fill in the necessary details for the custom field.
* Instead of clicking on the "Submit" button, press the "Enter" key.

## Expected behavior
The custom field should be added successfully, regardless of whether the "Submit" button is clicked or the "Enter" key is pressed.

## Actual behavior
An error is triggered when the "Enter" key is pressed as the method of submission.

## Screenshots
[Screencast from 2024-01-07 09-10-37.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/16f57433-b83a-4e4a-bb30-a55d24b55ba7)

## Potential internship candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
BugFix: - Resolves an issue where pressing the "Enter" key while adding a custom field in the settings was triggering an error.

**Issue Number:**

Fixes #1395 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/f3d1371b-8cc7-43ed-96db-acbe791cc136

**If relevant, did you update the documentation?**
No

**Summary**

- Modified the handling of form submission to ensure that the custom field is added successfully whether the "Submit" button is clicked or the "Enter" key is pressed.
- Ensured all the modified lines are covered by tests and no other functionality is affected.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar Please fix the failing test.

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar We are working on a fix, for now can you update the schema file to address UpdateUserInput.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14 , the failing GraphQL schema introspection workflow is due to the merged #1499  where `applang` and `id` was added to the UpdateUserInput input in the schema in`talawa- admin` portal. However, there are no corresponding changes in `talawa-api`, which is causing the workflow to fail.

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar We are working on a fix, for now can you update the schema file to address UpdateUserInput.

Ma'am, there is no need to change the schema in `talawa-admin` as it has already been added in schema. We need to add it to talawa-api instead, which is being fixed in PR [#1762]( https://github.com/PalisadoesFoundation/talawa-api/pull/1762.)

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar I understand.  Thanks for being patient with this.

**Comment by Cioppolo14** [comment]
@Kevoniat @tasneemkoushar Can you review this PR?

**Review by noman2002 — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
