### PR TITLE
update packages and test environment for "Upgrade deprecated sane library #1225"

### LINKED ISSUE #1225: Upgrade deprecated `sane` library
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Shubh152**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1225 
Fixes PR #1425 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Upgraded package.json and package-lock.json to install the correct version of dependencies
Also made suitable changes to custom-test-env.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Shubh152** [comment]
The introspection test fails because it validates updated GraphQL documents in this repo to the outdated schema.graphql file in main branch of talawa-api repo

**Comment by Shubh152** [comment]
@palisadoes As you mentioned in the PR #1425  I made for this issue, changes in the package.json leads to failure of some specific tests as the whole testing infrastructure needs to be updated to the latest jest and @testing-library dependencies, which seems out of scope for the current issue. As of now, the best solution should be to upgrade specifically the "sane" package in the lock-file. Your thoughts on this?

**Comment by palisadoes** [comment]
The lock file will be overwritten when the package.json file is updated. We need a long term solution.

**Comment by Shubh152** [comment]
The long-term solution will be updating @testing-library and jest followed by making appropriate changes in the tests. Should this be done here? Please help if you have any other idea.

**Comment by palisadoes** [comment]
Yes

**Comment by Shubh152** [comment]
Closing PR as it got messed

**Pull request closed without merging**
