### PR TITLE
fix: Fixed likes and comments not working with User Posts

### LINKED ISSUE #1688: Bug: Likes and Comments for User Posts not working
**Describe the bug**
The likes and Comments card which shows comment for specific post in User is not working because `ORGANIZATION_POST_LIST` query is missing `likedBy` and `comments` array which are responsible for above features in UI.

In [`src/Screen/UserPortal/Home/Home.tsx`](https://github.com/PalisadoesFoundation/talawa-admin/blob/e04abf34a2924c4680d4bc81d59fe85afa618ed6/src/screens/UserPortal/Home/Home.tsx#L333-L366) when we we look at code for rendering posts we require `likedBy` and `comments` array to be returned by `ORGANIZATION_POST_LIST` results which is not being returned as a result above features don't work.

**To Reproduce**

1. Sign in as user
2. Open an organization page
3. Like Or Add comment
4. Reload the Page the changes would be reset

**Expected behavior**
On liking or commenting the posts (in user's Organization Dashboard) the changes made should be persistent and be able to render on screen even after reload

**Actual behavior**
On liking or commenting the posts (in user's Organization Dashboard) the changes made are wiped out. as on reload the new data is not being fetched due to missing attribute in query.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/17522da5-c243-47f5-8325-07e50fc27928

### PR DESCRIPTION
**Pull request by Doraemon012**
**What kind of change does this PR introduce?**

- This PR is a **bug fix**.

**Issue Number:**
- Fixes #1688

**Did you add tests for your changes?**
No.

**Snapshots/Videos:**

[likes_and comments.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/ed11c9e3-4d38-49e4-ba71-5ab4b3b6864d)

**If relevant, did you update the documentation?**
No.

**Summary**

- This PR addresses a bug related to the likes and comments functionality for user posts.
- The bug caused the likes and comments not to persist after reloading the page, and the likes on comments rendering only after reloading the page.
- This was caused by the `ORGANIZATION_POST_LIST` query not returning the required `likedBy` and `comments` arrays, and the fact that the `likedBy` array was not changed immidiately when the user liked a comment.`

**Does this PR introduce a breaking change?**

No.

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Doraemon012 Please fix the failing tests.

**Comment by Doraemon012** [comment]
@Cioppolo14 , I've fixed the failing tests. Please take a look.

There were two failing checks :
1. Because of unused variables
2. Runs Introspection on the GitHub talawa-api repo on the schema.graphql file
I've fixed the first one.
However the second one there's already an open issue (#1162).

**Comment by Cioppolo14** [comment]
@Kevoniat @noman2002 Can you review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@Doraemon012 Please fix the conflicting files and failed codecov tests.

**Comment by Doraemon012** [comment]
@Cioppolo14, I'm unable to resolve the conflicting files at the moment due to posts not being visible on the Organization Posts page.
I've opened an issue for the same ( #1796 ). Once the issue is resolved, I'll update the code accordingly.

**Comment by palisadoes** [comment]
@Doraemon012 The blocking issue has been fixed

**Comment by palisadoes** [comment]
@Doraemon012 

1. The blocking issue has been fixed.
2. You can resume work on this PR.
3. Please fix the conflicting files

**Comment by palisadoes** [comment]
Please fix the conflicts

**Comment by Doraemon012** [comment]
@palisadoes  I will fix it ASAP

**Comment by Doraemon012** [comment]
Or will it be better if I open a new PR ? Please suggest.

**Comment by palisadoes** [comment]
Resubmit. It looks like it'll be easier. I'll close this one.

**Pull request closed without merging**
