### PR TITLE
Refactor: jest to vitest: Fixes #2485

### LINKED ISSUE #2485: Refactor : `src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from test.tsx to spec.tsx
2. Ensure all tests in `src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
 https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93

- Vitest documentation: 
https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by bandhan-majumder**
**What kind of change does this PR introduce?**

Refractor from jest to vitest

**Issue Number:**

Fixes #2485 

**Snapshots/Videos:**

image

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

## Summary by CodeRabbit

- **Tests**
	- Transitioned testing framework from Jest to Vitest for improved performance and maintainability.
	- Streamlined test cases for the `AdvertisementRegister` component, enhancing readability and efficiency.
	- Updated mocking and timer methods for consistency with Vitest standards.

### CODE REVIEW

**Comment by bandhan-majumder** [comment]
Here is the PR that is unable to mock `create` and `update` mutation response. Please look at it @varshith257

**Comment by bandhan-majumder** [comment]
I had one global usefake and usereal for all. I removed them and added individually for the ones which needed and were suggested. But the issue persists. It still is unable to get response from apollo client.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by bandhan-majumder** [comment]
Closing the PR as it got solved by a duplicate issue. Thanks.

**Pull request closed without merging**
