### PR TITLE
Preventing default action when pressing Enter key to add custom fields in Settings  - Fixes #1395

### LINKED ISSUE #1395: [Bug] Error Triggered When Pressing "Enter" Instead of Clicking "Submit" Button When Adding Custom Field in Settings
## Describe the bug
When attempting to add a custom field in the settings, an error occurs if the "Enter" key is pressed instead of clicking on the "Submit" button.

## To Reproduce

* Navigate to the settings section.
* Look for the option to add a custom field.
* Fill in the necessary details for the custom field.
* Instead of clicking on the "Submit" button, press the "Enter" key.

## Expected behavior
The custom field should be added successfully, regardless of whether the "Submit" button is clicked or the "Enter" key is pressed.

## Actual behavior
An error is triggered when the "Enter" key is pressed as the method of submission.

## Screenshots
[Screencast from 2024-01-07 09-10-37.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/16f57433-b83a-4e4a-bb30-a55d24b55ba7)

## Potential internship candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by karthxk07**
## What kind of change does this PR introduce?
Bugfix

## Issue Number:
Fixes #1395 

## Did you add tests for your changes?
Yes

## Snapshots/Videos:
[Screencast from 2024-01-10 23-25-28.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/adcacde9-6ff9-440c-b013-a7e6eca8074b)

## If relevant, did you update the documentation?
No, No documentation changes were needed

## Summary
This pull request addresses an issue where an error was triggered when clicking "Enter" instead of the submit button for adding new custom fields in the settings page. The root cause was that the form was being submitted when pressing "Enter," resulting in unexpected behavior. To fix this, I added a preventDefault action to the form submission and then called the handleSave function.

## Does this PR introduce a breaking change?
No, this PR does not introduce any breaking changes.

## Other information

[x] I've tested this fix thoroughly on various browsers to ensure compatibility.
[x] The code follows the coding standards and guidelines outlined in the contributing guide.
[x] This change has been made against the develop branch.

## Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
`src/components/OrgProfileFieldSettings/OrgProfileFieldSettings.tsx` can you run prettier and check why the PR workflow is failing.

**Comment by karthxk07** [comment]
@aashimawadhwa umm, ok

**Comment by karthxk07** [comment]
@aashimawadhwa I have updated the file in question, can you please review this now

**Comment by karthxk07** [comment]
@aashimawadhwa How do i get codecov to pass, Do i have to add any tests anywhere?

**Pull request closed without merging**
