### PR TITLE
Configure Automatic Labeling for Issues

### PR DESCRIPTION
**Pull request by Sumitsh28**
**What kind of change does this PR introduce?**

Feature: Configures automatic labeling for issues.

**Issue Number:** [2256](https://github.com/PalisadoesFoundation/talawa-admin/issues/2256)

**Did you add tests for your changes?**

No. This change is related to GitHub Actions configuration and does not require unit tests.

**If relevant, did you update the documentation?**

No, documentation update is not required for this change.

**Summary**

This pull request updates the `issue.yml` file to configure automatic labeling of issues using the `Renato66/auto-label` GitHub action. The motivation behind this change is to reduce manual labeling effort and ensure that issues are labeled consistently based on their content. This automation will improve the efficiency of issue management by applying appropriate labels for dependencies, security, and design-related issues.

**Does this PR introduce a breaking change?**

No, this PR does not introduce any breaking changes.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced detailed label configurations for categorizing issues (e.g., "dependencies," "security," "ui/ux").
  
- **Improvements**
	- Enhanced organization and categorization of incoming issues through granular labeling.
	- Reformatted the greeting message for new issues for consistency.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Sumitsh28 Please fix the failed checks

**Comment by Sumitsh28** [comment]
@Cioppolo14

The failed checks are: 
1) Unauthorised File changed (issue.yml), for the issue [2256](https://github.com/PalisadoesFoundation/talawa-admin/issues/2256) i have to change the issue.yml file
2) Source branch is develop and target branch is also develop (its saying branches should be different)

How to fix these. Please help

**Comment by palisadoes** [comment]
@Sumitsh28 Have you tested this on a repository in your GitHub account to make sure it works?

**Comment by Sumitsh28** [comment]
@palisadoes Yes, I have tested this

**Comment by palisadoes** [comment]
1. This PR needs to be closed. The source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
1. Please create a new branch in your local repository with the changes
2. Make sure the branch name is named differently from the target branch (`develop`)
3. Resubmit your PR

You will see that other PRs are using non-develop branch names for this reason

**Pull request closed without merging**
