### PR TITLE
[Fixes] Code Coverage: Create tests for src/index.ts 

### LINKED ISSUE #278: Code Coverage: Create tests for index.ts
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/state/index.ts`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/state/index.test.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/state/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
   Added Testcases for src/state/index.ts file

**Issue Number:**
#278 

Fixes #278 

**Did you add tests for your changes?**
   Yes I have added a testfile

**Summary**
   I have added a index.test.ts. file required for the issue #278 for Gsoc2022

**Does this PR introduce a breaking change?**
   No

**SnapShots**

image

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
  Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please make sure the issue is assigned to you before making the pull request.

**Review by palisadoes — CHANGES_REQUESTED** [review]
You will need to get to 100% coverage for the review to be done.

**Comment by SiddheshKukade** [comment]
> Please make sure the issue is assigned to you before making the pull request. We may close PRs for which there is no assigned issue.

I am sorry sir , I'll keep that in mind next time

**Comment by yasharth291** [comment]
> Please make sure the issue is assigned to you before making the pull request. We may close PRs for which there is no assigned issue.

the thing doesn't work like this it shows the percent of whole code coverage if it is a + then it is okay

**Review by yasharth291 — CHANGES_REQUESTED** [review]
explain the test like which things they are doing and what is the expected result for the same

**Comment by SiddheshKukade** [comment]
@palisadoes  @yasharth291  sir I am very confused currently,

#278  Issue is asking to test the src/state/index.ts file which contains the following code (there is only 1 line in the file)
```javascript
export * as actionCreators from './action-creators/index';
``` 
I thought I have to test the actionCreators object to have truth values so I added the below code 
```javascript
test('Testing Index File of "src/state/"', () => {
    expect(actionCreators.installPlugin).toBeTruthy();
    expect(actionCreators.removePlugin).toBeTruthy();
    expect(actionCreators.updateInstalled).toBeTruthy();
    expect(actionCreators.updatePluginLinks).toBeTruthy();
    })
```
still I am getting coverage of 33% only.... help me @palisadoes  @SiddheshKukade

**Comment by yasharth291** [comment]
try asking @asmitsirohi  he will tell you

**Comment by Devesh21700Kumar** [comment]
> @palisadoes @yasharth291 sir I am very confused currently,
> 
> #278 Issue is asking to test the src/state/index.ts file which contains the following code (there is only 1 line in the file)
> 
> ```js
> export * as actionCreators from './action-creators/index';
> ```
> 
> I thought I have to test the actionCreators object to have truth values so I added the below code
> 
> ```js
> test('Testing Index File of "src/state/"', () => {
>     expect(actionCreators.installPlugin).toBeTruthy();
>     expect(actionCreators.removePlugin).toBeTruthy();
>     expect(actionCreators.updateInstalled).toBeTruthy();
>     expect(actionCreators.updatePluginLinks).toBeTruthy();
>     })
> ```
> 
> still I am getting coverage of 33% only.... Is there anything I am missing ?? help me @palisadoes @yasharth291

You'll have to probably mock the state data and check the dispatch actions by using isEqualTo method.

**Comment by palisadoes** [comment]
Thanks @Devesh21700Kumar. Can you provide an example in an existing test suite in the repo?

**Comment by Devesh21700Kumar** [comment]
> Thanks @Devesh21700Kumar. Can you provide an example in an existing test suite in the repo?

Mocks have been created in children files of screen subFolder 

https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx

but they are Mocks for graphql queries and therefore are in a bit different format from what is needed.
Exact snippet that can be referred to for this case is not present right now i guess

**Comment by asmitsirohi** [comment]
@SiddheshKukade, You are trying to test an actionCreaters by importing it, instead of the index file. Leave it for actionCreaters tests, for this, you have to mock the data.

image

Actually, the src/state/index file has only one export statement, which is not necessary to test. Just to get 100% code coverage we can exclude it from code coverage, by referring to this article https://stackoverflow.com/questions/43044696/test-a-create-react-app-index-js-file.

What's your view on this @yasharth291 @palisadoes.

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade, You are trying to test an actionCreaters by importing it, instead of the index file. Leave it for actionCreaters tests, for this, you have to mock the data.
> 
> image
> 
> Actually, the src/state/index file has only one export statement, which is not necessary to test. Just to get 100% code coverage we can exclude it from code coverage, by referring to this article https://stackoverflow.com/questions/43044696/test-a-create-react-app-index-js-file.
> 
> What's your view on this @yasharth291 @palisadoes.

OK @asmitsirohi  sir I will try this one

**Comment by SiddheshKukade** [comment]
@asmitsirohi @palisadoes  @yasharth291 @Devesh21700Kumar  what do you guys think about this change

**Comment by SiddheshKukade** [comment]
Guys please at least tell me if i'm moving in right direction or not or should I close this PR and should work on another issue 👍

**Review by DangaRanga — APPROVED** [review]
I apologize for the delayed review. This is good actually since the `index.ts` file only contains an import statement

**Comment by SiddheshKukade** [comment]
thank you @DangaRanga  sir, @palisadoes @yasharth291 are the changes ok?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
