### PR TITLE
Adding Plugin Logic to the Talawa Mobile Web App

### LINKED ISSUE #975: Feature Request: Adding Plugin Logic to the Talawa Mobile Web App
**_Note:  More details to be added soon_**

**Is your feature request related to a problem? Please describe.**
Adding the UI toggling logic to the talawa user app on "/user"
**Describe the solution you'd like**
- Setting Up socket connections 
- Adding the toggling logic
- Finding a way to store and handle that data.

**Describe alternatives you've considered**
n/a

**Approach to be followed (optional)**
A clear and concise description of the approach to be followed.

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by SiddheshKukade**
**What kind of change does this PR introduce?**
Adding Plugin Logic to the Talawa Mobile Web App

**Issue Number:**

Fixes #975

**Did you add tests for your changes?**

**Snapshots/Videos:**
 #### Youtube video ⬇️ 

### Talawa Plugin working demo on web version | GSoC 2023 Sept Work Report | Siddhesh Kukade Palisadoes
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=iUd5zbpEAdI)

### Plugin Demo on Web app with Multiple features removal and additions | GSoC Work Report | Palisadoes
[IMAGE ALT TEXT HERE](https://www.youtube.com/watch?v=zpV-P7El_qk)

**If relevant, did you update the documentation?**
Not required.

**Summary**

Explained the process in the video. have added socket listeners and handled data logic to display appropriate features based on their statues. 

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
@SiddheshKukade Please fix the failing tests and ask your mentors to review your work

**Comment by SiddheshKukade** [comment]
@DMills27 , @tasneemkoushar Please take a look.

**Review by DMills27 — APPROVED** [review]

**Comment by palisadoes** [comment]
@SiddheshKukade Please address the code coverage

**Review by tasneemkoushar — DISMISSED** [review]
This looks good me

**Comment by palisadoes** [comment]
@SiddheshKukade Please fix the conflicting files and the code coverage decline

**Comment by SiddheshKukade** [comment]
@palisadoes Actually, I researched on it. 
The coverage is mostly reduced on the `OrganiationNavbar.tsx` file and I couldn't find a way to test toggling UI with websocket listeners as a **unit test**. 
IThis is because the User Interface of the mobile app is changing based on operations performed by the admin app. So I'm unable to test that flow as a unit test in `react-testing-library`. That's why I am unable to add tests.
Please merge this pull request.

**Comment by palisadoes** [comment]
Thanks.

1. Please fix the failing test, and then we can merge.
2. Consider ways to ignore just that file in the codecov app as part of this PR.

**Comment by SiddheshKukade** [comment]
@palisadoes Sir,
Fixed the failing tests. Now ready to be merged.

**Pull request merged**
