### PR TITLE
Refactored  src/screens/OrganizationEvents.tsx from Jest to Vitest #2559

### PR DESCRIPTION
**Pull request by Ramneet04**
Refactored src/screens/OrganizationEvents/OrganizationEvents.test.tsx  to
src/screens/OrganizationEvents/OrganizationEvents.spec.tsx

Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/2559: https://github.com/PalisadoesFoundation/talawa-admin/issues/2559

Changes Implemented:

Refactored the testing framework from Jest to Vitest in src/screens/OrganizationEvents/OrganizationEvents.test.tsx.
Updated import statements, mocking methods, and assertions to align with Vitest conventions.
Verified compatibility with the existing codebase using Vitest.
- Renamed the test file:
OrganizationEvents.test.tsx → OrganizationEvents.spec.tsx   to follow the naming convention for Vitest.
- Ran all tests successfully under the Vitest environment.
https://github.com/PalisadoesFoundation/talawa-admin/issues/2559

issue8 1

Other information
I have read the previous refactor PR and tried to keep things as uniform as possible.
Please suggest any other changes if required.

## Summary by CodeRabbit

- **Chores**
	- Migrated test suite from Jest to Vitest testing framework.
	- Updated mocking and assertion methods to align with Vitest.
	- Refined `window.location` and global alert function mocking techniques.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Merge your local branch with the latest upstream
1. Commit and push to your origin
1. It should fix some of the PR check failures
1. We merged some recent updates that may have been after you initially submitted your PR

**Comment by palisadoes** [comment]
Please merge your local branch with the latest upstream, commit and then push to your origin.

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by Ramneet04** [comment]
hey @palisadoes could you please help me out a bit how to address this issue, can u refer me some resources for this.

**Comment by palisadoes** [comment]
Please click on the error link. It's explained there

**Comment by Ramneet04** [comment]
> Please click on the error link. It's explained there

yeah I finally found a way to do it.

**Pull request merged**
