### PR TITLE
Fixed the issue of overlapping of user's info on the organizations section.

### LINKED ISSUE #442: Bug :In case of long emails, the info section is overlapping the organization's section and the bottom section is not center alligned
**Describe the bug**
Many times, the users have long emails which tend to overlapp the orgnaization's section when we shift to smaller screeens like laptops or tablets.

**To Reproduce**

1.login to talawa-admin portal
2.Reduce the screen width to about tablet's width
3.U will the email of the user is overlapping the organizations

**Expected behavior**
There should be no overlapping.

**Actual behavior**
There is overlapping and the UI doesnt looks good due to it 

**Screenshots**
For the ovelapping:
Screenshot from 2023-02-05 03-43-35

For the center allignment issue of the bottom section("the rows per page" text is not alligned properly)
Screenshot from 2023-02-05 03-51-10

### PR DESCRIPTION
**Pull request by anurag0006**
**What kind of change does this PR introduce?**
a bugfix

**Issue Number:**
#442 
Fixes #

**Did you add tests for your changes?**
Not required

**Snapshots/Videos:**
Now:

image

Earlier:

image

**If relevant, did you update the documentation?**
Not Needed

**Summary**
The issue of overlapping of user's info over the organizations has been fixed in this PR and hence it closes #442 ...
Along with that , i also added some margins and padding at some places makign the UI better.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by anurag0006** [comment]
Sorry, i forgot to lint the code...will lint the code right now

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please try to get the coverage to 100% for OrgList.tsx

**Comment by anurag0006** [comment]
@noman2002 , i went through the issue list and found that there are people already working on making code coverage 100% for the orglist.tsx...issue no #429 and that issue is already assigned to someone else. So should i try to make code coverge for orglist.tsx 100% or leave it for them?

**Comment by palisadoes** [comment]
> @noman2002 , i went through the issue list and found that there are people already working on making code coverage 100% for the orglist.tsx...issue no #429 and that issue is already assigned to someone else. So should i try to make code coverge for orglist.tsx 100% or leave it for them?

In that case we'll wait for https://github.com/PalisadoesFoundation/talawa-admin/issues/429 to be completed. @noman2002 Please review again

**Review by noman2002 — APPROVED** [review]
Looks good to me

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
