### PR TITLE
Create tests for OrganizationDashboard.tsx

### LINKED ISSUE #1132: Code Coverage: Create tests for src/screens/OrganizationDashboard/OrganizationDashboard.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sauradip07**
**Create tests for src/screens/OrganizationDashboard/OrganizationDashboard.tsx**

**Issue Number:**

Fixes #1132

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

Screenshot from 2024-02-06 15-20-51

Screenshot from 2024-02-06 15-21-11

**Summary**

Lines 86-94 & Lines 239-241 weren't covered by the tests It seems that Upcoming Events are mainly not covered
which introduce in Last PR of this File 

**Other information**

I try to cover the entire useEffect hook 
for Line 86 to 94 
```
  // UseEffect to update upcomingEvents array
  useEffect(() => {
    if (eventData && eventData?.eventsByOrganizationConnection.length > 0) {
      const tempUpcomingEvents: InterfaceQueryOrganizationEventListItem[] = [];
      eventData?.eventsByOrganizationConnection.map((event: any) => {
        const startDate = new Date(event.startDate);
        const now = new Date();
        if (startDate > now) {
          tempUpcomingEvents.push(event);
        }
      });
      setUpcomingEvents(tempUpcomingEvents);
    }
  }, [eventData?.eventsByOrganizationConnection]);
```
The 239 to 241 is already Covered but not showed in Codecov
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

`Please feel free to reach out if there are any modifications or any changes need to be made.`

### CODE REVIEW

**Comment by Sauradip07** [comment]
@palisadoes Please Check I create a Fresh PR

**Comment by noman2002** [comment]
@Sauradip07 Why the coverage has not increased?

**Comment by Sauradip07** [comment]
@noman2002 
The Test is Wait for useEffect: wait() is called to ensure any useEffect hooks inside the `Organization Dashboard `component have executed and also the test checks whether certain elements (`Upcoming Events`and` Latest Posts`) are rendered, indicating that the state has been updated properly.
Overall, this test suite checks for the `OrganizationDashboard` component, including state updates, logic execution.It ensures that the component behaves correctly under different conditions and renders the expected content.

`I don't know why the coverage has not increased. `
I google it but not found any relevent Informatation about it if Possible please suggest what's i need to do.

**Comment by rishav-jha-mech** [comment]
@Sauradip07 have you tried using jest preview and checked the code coverage from the html file that gets updated everytime you make a change to your tests ?

**Comment by Sauradip07** [comment]
@rishav-jha-mech 
Yes, I used jest preview and checked the code coverage from the HTML file
I try to cover the entire useEffect hook and after all changes I don't know why this coverage has not increased
if you find any mistake in my code changes, please point it out, and I am continuously research on it why coverage is not increased.
`If you have any suggestion, Please feel free to suggest.`
Screenshot from 2024-02-13 18-53-59

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by rishav-jha-mech** [comment]
@Sauradip07 for some reason, the code under the if condition is not getting executed, you need to check if the mocks are correct or not

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
