### PR TITLE
Corrected placeholder text, added missing inputs(video,images)  and their tests to edit post feature present in Admin role. 

### LINKED ISSUE #1477: Missing fields and improper placeholder values in Edit Post Modal.
**Describe the bug**
While editing a post(Admin Role), the placeholders have OrgPostCard.postTitle1 instead of a proper text and fields image and video which are present in Create post modal, are missing in Edit post modal.

**To Reproduce**

1. Role: Admin
2. Create a post in your organization
3. Now if you want to edit it, for editing only 2 fields- title and information are present, not fields for editing image and video are present. 
4. Also, the placeholder values are OrgPostCard.postTitle1 and OrgPostCard.information respectively for currently available fields.

**Expected behavior**
1. Placeholders must have text which can be easily understood by the user instead of OrgPostCard.postTitle1 and OrgPostCard.information.
2. User must also be able to edit image and video

**Actual behavior**
1. Unclear placeholder values
2. Missing fields in edit option

**Video**
[Screencast from 22-01-24 07:45:27 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/621b4d58-9a9c-491b-953c-d1191e4a69dd)

**Additional details**
Trying to replicate create post modal for edit post modal.
This is create post modal.
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**

Fixes #1477 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[Screencast from 23-01-24 07:39:47 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/d39e8bbd-090a-4076-9a87-57caa4ff74fd)

**Summary**

1. Initially the placeholder values were OrgPostCard.postTitle1 and OrgPostCard.information respectively. Corrected those in all the languages.
2. Initially there was no option for editing image and video after the post was created, add it.
3. Added relevant testing code

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@noman2002 @tasneemkoushar Can you review this PR?

**Review by noman2002 — COMMENTED** [review]
Changes looks fine to me. Merge the latest code into this.

**Comment by palisadoes** [comment]
Please merge the latest upstream into this PR.

The tests should then all pass

**Comment by Anvita0305** [comment]
Hello @noman2002 @palisadoes I have merged the latest upstream in this PR. Can you please review it? Thanks!

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
