### PR TITLE
Add chat screen to talawa-user-portal

### LINKED ISSUE #985: Add Chat Screen for Talawa-User-Portal
**Is your feature request related to a problem? Please describe.**
Add Chat Screen for user portal.

**Additional context**
GSoC'23 follow up issue

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by beingnoble03**
**What kind of change does this PR introduce?**
GSoC'23 follow-up PR: Add chat screen to talawa-user-portal

**Issue Number:**
Fixes #985 

**Did you add tests for your changes?**
No. Working on tests.

**Snapshots/Videos:**

Screenshot 2023-10-09 at 12 30 25 PM
Screenshot 2023-10-09 at 12 30 39 PM

**If relevant, did you update the documentation?**
Not required.

**Summary**

**Does this PR introduce a breaking change?**
No.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by beingnoble03** [comment]
Working on tests. Will add required tests soon.

**Comment by beingnoble03** [comment]
Unauthorized file changes test is failing due to addition of a package.

**Comment by beingnoble03** [comment]
- Working on tests. Will add required tests soon.
- Unauthorized file changes test is failing due to addition of a package `@mui/system`.

**Comment by beingnoble03** [comment]
- Working on tests. Will add required tests soon.
- Unauthorized file changes test is failing due to addition of a package `@mui/system`.

**Comment by beingnoble03** [comment]
@palisadoes @evasharma12 please review I have added the required tests with 100% coverage.
Unauthorized file changes test is failing due to addition of a package `@mui/system` and `@mui/private-theming`

**Review by evasharma12 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
