### PR TITLE
Navbar made fully functional for all the screens.

### LINKED ISSUE #383: Bug : Navbar not properly functional for screens with width less than 1200px
**Describe the bug**
The navbar on the login page as well as on the dashboard is not fully responsive and is overlapping on the other components my on smaller screens like tablets...
Also the button and the the website logo are not fitting in the given space making it look odd...

**To Reproduce**

1.Go to the website.
2.Make your screen width less than 1200px so that the navbar transforms into a button to be functional in vertical direction
3.You will notice that the the button and the logo are not properly alligned and are are coming out of the navbar.
4.Along with that , on clicking the button to open vertical navbar, the elements of the navbar overlapp on the elements on the screen making it look odd.

**Expected behavior**
The navbar should be totally resposive and should not overlapp on the other elements in any case

**Actual behavior**
Overlapping the other elements as well as the logo and button are not properly alligned.

**Screenshots**
[Screencast from 19-01-23 12:07:38 AM IST.webm](https://user-images.githubusercontent.com/107215525/213371647-048bb5e7-3df0-41e8-8e95-122643d328eb.webm)

Screenshot from 2023-01-19 00-18-06

**Additional details**
The navbar is functioning properly for the full screen as well as for the screen with width less than 600px.
And the bug is applicable to all the pages of the websites.(login page as well as the dashboard page)

### PR DESCRIPTION
**Pull request by anurag0006**
**What kind of change does this PR introduce?**
A bugfix.

**Issue Number:**

Fixes #383 

**Did you add tests for your changes?**
No 

**Snapshots/Videos:**
Screenshot from 2023-01-19 22-44-11

**If relevant, did you update the documentation?**
Not required

**Summary**
The Navbar initially was overlapping on the other elements and the logo and the button of navbar were overflowing the navbar...the Motivation was to make better UI for a better user experience.

**Does this PR introduce a breaking change?**
No

**Other information**
No extra information required.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please lint the code correctly. This should be outlined in the CONTRIBUTING.md file or you can look at the commands that was run for the failing test.

**Comment by anurag0006** [comment]
@palisadoes , i think i linted the code correctly now, there was a small error while is resolved

**Comment by anurag0006** [comment]
@palisadoes , i guess all the checks have been passed, so can u please approve the PR

**Review by palisadoes — CHANGES_REQUESTED** [review]
Are there any tests that you can add to make sure that this doesn't happen again? That would be very helpful. Please take a look at other examples as a guide.

**Comment by anurag0006** [comment]
But this was a minor front end issue caused because the elements were inheriting all the css properties from the bootstrap which sometimes is dangerous as in this case, i just added a class to that element and changed its css and i actually don't know how to write the tests for them...So Should i DM a mentor to learn about writing tests?

**Comment by palisadoes** [comment]
Yes, try to see whether this can be tested in any way. This is not the first time that we have had issues with screen size responsiveness. It keeps coming up and we need to make sure it doesn't repeat itself.

**Comment by anurag0006** [comment]
@palisadoes , i have written some tests using jest snapshots for the navbar. Please have a look

**Comment by anurag0006** [comment]
@palisadoes , i have made the necessary changes for this PR to be commited...As told by kevonia sir, the tests for the css aren't required which were giving errors so i have removed them and resubmitted the PR...So please merge this PR

**Comment by noman2002** [comment]
@anurag0006 Why `height ` is removed from everywhere ?? Doesn't this break the UI?

**Comment by anurag0006** [comment]
> @anurag0006 Why `height ` is removed from everywhere ?? Doesn't this break the UI?

Nope, earlier the height was fixed to 60px which makes the components to overflow in some cases....now as the height is removed, it will inherit its property of height:auto which means it will automatically adjust the height...

**Comment by noman2002** [comment]
I can see an empty folder named talawa-admin is created, please remove it. Rest everything looks good to me.

**Comment by anurag0006** [comment]
@noman2002 , the mistakenly added talawa-admin folder has been removed...I guess now everything is alright...Please merge this PR

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
