### PR TITLE
merged develop-userTypeFix in develop

### PR DESCRIPTION
**Pull request by AVtheking**
What kind of change does this PR introduce?

Feature

Issue Number:

Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Did you add tests for your changes?

Yes

Summary

Merging the develop-userTypeFix  branch in develop.

Does this PR introduce a breaking change?
Yes

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by varshith257** [comment]
Merge Conflicts arrived here in the PR

**Comment by palisadoes** [comment]
@varshith257 Can you resolve them?

**Comment by palisadoes** [comment]
@varshith257 

1. We have to approve the GitHub action because you've never merged a PR before. This is going to be time consuming and cause delays. 
2. Can you create a trivial PR in Admin that I can merge so that I don't have to approve subsequent workflows for you? For example add a space to a file

**Comment by varshith257** [comment]
> @varshith257
> 
> 1. We have to approve the GitHub action because you've never merged a PR before. This is going to be time consuming and cause delays.
> 2. Can you create a trivial PR in Admin that I can merge so that I don't have to approve subsequent workflows for you? For example add a space to a file

Sure . I will edit a small typo in INSTALLATION.md and make a PR

**Comment by varshith257** [comment]
@AVtheking What happened?

**Comment by AVtheking** [comment]
I was renamining branch because of that failed error ,it deleted it

**Comment by palisadoes** [comment]
1. Create another PR 
2. Have we lost all the changes?

**Comment by varshith257** [comment]
@AVtheking No need to worry about that

**Pull request closed without merging**
