### PR TITLE
feat: implemented support to upload media while creating and updating advertisements

### LINKED ISSUE #1158: Enabling media support to the create ad action
**Is your feature request related to a problem? Please describe.**
We need media support on create ad action (both photo and video)

**Describe the solution you'd like**
An method to upload media in the create ad modal (you can refer the create post modal in the posts section from the menu).

**Additional context**
Please discuss your approach before starting with the solution and refer to this issue as well #1127 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1158 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
Yes

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@disha1202 Please fix the failing tests.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
This is a repeat of this PR that was merged prematurely. 
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1248

We need to wait for the API PR to be merged first.
- https://github.com/PalisadoesFoundation/talawa-api/pull/1585

**Comment by aashimawadhwa** [comment]
@disha1202 can you please resolve the conflicting files?

**Comment by disha1202** [comment]
> @disha1202 Why have you updated 152 files?

It's because of the updated documentation. 

This is the same issue that we faced during the setup script PR 
https://github.com/PalisadoesFoundation/talawa-admin/pull/1350
https://github.com/PalisadoesFoundation/talawa-admin/pull/1461

Also I have just updated my PR with the latest upstream

**Comment by palisadoes** [comment]
Is this ready for review?

**Comment by disha1202** [comment]
> Is this ready for review?



> Is this ready for review?

Hi 

This is not ready for review yet. I am currently working on the api part and it will require changes in Talawa Admin as well. 
Sorry for the delay. I'll try to wrap this up as soon as possible.

**Comment by palisadoes** [comment]
_**NOTE**_ Read very carefully

1. We just merged this PR which upgraded the prettier package. 
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1599
1. It reformatted over 150 files. 

This will put your PR at risk of extensive merge conflicts. Do the following **IN THIS ORDER**:

1. upgrade your `prettier` in your local branch to the same version
1. run `prettier` on your local branch
1. update your local branch with the latest upstream
    
This will help to reduce the number of **existing** and **future** merge conflicts for your PR.

**Comment by noman2002** [comment]
@disha1202 Any update on this one ?

**Comment by palisadoes** [comment]
1. You now have 152 files to review. This isn't a manageable amount
2. Try this to remove the newly added documentation. 
    1.  https://stackoverflow.com/questions/12481639/remove-file-from-latest-commit

**Comment by disha1202** [comment]
Hi 
This PR is ready for review.

**Comment by disha1202** [comment]
Also currently we are fetching all the advertisements and filtering them on the basis of organizationId. 

This has been fixed in Talawa-API. we have updated the organization schema so that it contains advertisements and also implemented pagination. 

Need to update the query for fetching advertisements in Talawa admin and also implement infinite scroll similar to what we have on organizations screen. 

Can we have a separate issue for that?

**Comment by noman2002** [comment]
Yes, create a separate issue for that. 
And also pull the latest code into this branch.

**Comment by disha1202** [comment]
> Yes, create a separate issue for that.
> And also pull the latest code into this branch.

Okay, Thanks!!

**Review by noman2002 — APPROVED** [review]
LGTM.
@SiddheshKukade @aashimawadhwa  Please have a look.

**Comment by disha1202** [comment]
> @disha1202
> 
> Is there an API PR that needs to be merged before this one?

Yes, This PR in Talawa API needs to be merged first.
https://github.com/PalisadoesFoundation/talawa-api/pull/1585

**Comment by disha1202** [comment]
Here's the working demo

https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/7faa0bcd-3c1f-45ac-ba31-78e0a1cee4d4

https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/6ae4eb57-7182-43bb-9b4c-17eb693715f2

**Review by SiddheshKukade — APPROVED** [review]
LGTM

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by disha1202** [comment]
> Please fix the failing tests

Fixed the failing tests

**Pull request merged**
