### PR TITLE
Talawa admin installer in JavaScript

### LINKED ISSUE #18: Create `Talawa-Admin` Installer
# Introduction

1. We need a single CLI script or program to install Talawa Admin.
1. It must be 100% intuitive and worry free.
1. Must be able to run on Linux or Windows

# General Requirements

1. It is highly preferred that the user does not have to install any additional script interpreter other than those used to run Talawa-Admin.
1. Any failing OS commands must be logged to STDIO, STDERR and .
1. The script must fail if any underlying OS command fails.

The script must:

1. Not require the installation of any prerequisite packages for the script itself to run.
    1. This could be achieved by it installing any missing prerequisite packages for itself to run as part of its operation.
1. Install all required prerequisite packages for `Talawa-Admin` to operate
1. Activate `Talawa-Admin` upon completion of the script
1. Be a part of the `Talawa-Admin` code base
1. Be documented as part of the `Talawa-Admin` installation guide

# Installer Operation
The installation process must:

1. Prompt for:
    1. The API keys required to communicate with the `Talawa-API` server.
    1. The URL to use for communicating with the `Talawa-API` server.
1. Insert all information prompts in a configuration file.
1. Provide the web URL to use to access `Talawa-Admin`

# Post Installer Operation
1. The script (or a second script) must be able to be run to show the status of `Talawa-Admin`.
    1. This must display whether the connection to `Talawa-API` correctly operational
    1. This must display whether `Talawa-Admin` correctly operational

# Related Issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/241

The ability to create organizations in the app must be removed.

### PR DESCRIPTION
**Pull request by asmitsirohi**
**What kind of change does this PR introduce?**

This pull request adds an express installation setup for the Talawa-admin.

**Issue Number:**

Fixes #18 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image
image

**If relevant, did you update the documentation?**

Yes, I have added the section of Express Installation in the README.md file, this section redirects to the INSTALLATION.md file which contains the documentation for the same.

**Summary**

The initial setup required several steps to go through in order to install and start the Talawa Admin. Now, it needs just to clone the code, and run a single command. The rest of the installation process will be taken care of by the setup module itself. More information is available at issue #18

**Does this PR introduce a breaking change?**

No

**Other information**

This PR is the continuation of #202 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by yasharth291 — DISMISSED** [review]

**Comment by palisadoes** [comment]
@asmitsirohi  Please resolve your conflicting files before we can merge

**Comment by palisadoes** [comment]
@asmitsirohi Can you figure out what is causing the CodeQL GitHub action to fail?

**Comment by asmitsirohi** [comment]
@palisadoes I have resolved the conflicts.

**Comment by asmitsirohi** [comment]
image

I think it is caused because issue #18 is closed and it is not able to find a reference for this pull request. But I'm not sure about that.

**Comment by palisadoes** [comment]
I think it was occurring because:

- CodeQL needs to run with a matching PR and push GitHub action.
- Our implementation had our PR GitHub action YAML configuration file configured for both PRs and pushes
- We had another push YAML file configured for pushes.
- This meant that for every merged PR (which is a PR, followed by a push) we had two pushes being run. 
- The second run would fail because there was no matching PR run.

I've made the adjustments and will monitor the progress

**Comment by Devesh21700Kumar** [comment]
> @asmitsirohi Please resolve your conflicting files before we can merge

But will this do the function of an installer?
because to run this one has to run `yarn install anyways` and this only makes a config file and also `asks the user` to run `yarn serve` and does not do that automatically.
Basically one has to do the installation and running on his/her own only.

**Comment by Devesh21700Kumar** [comment]
> > @asmitsirohi Please resolve your conflicting files before we can merge
> 
> @yasharth291 @palisadoes
> 
> But will this do the function of an installer? because to run this one has to run `yarn install` anyways and this only makes a config file and also `asks the user` to run `yarn serve` on his/her own and does not do that automatically. Basically one has to do the installation and running on his/her own only.

**Comment by asmitsirohi** [comment]
I think @Devesh21700Kumar is right in some aspects because to set up talawa-admin, we need the talawa-API project well setup as APIs used in talawa-admin is from talawa-API.

Also, the API keys are set up in talawa-API with that project itself and API keys are not required in talawa-admin as mentioned in #18.
The only thing  required in talawa-admin configuration is API URL, which is actually hardcoded in the project currently

image

The API URL could be present in the .env file, which makes sense for automated installation.


I think the correct way to set up talawa-admin is:
* Clone Talawa-admin
* Clone Talawa-API
* Setup Talawa-API {API keys, MongoDB connection url}
* Setup Talawa-admin {API URL}

### After cloning Talawa-admin, all the other things need to be done using the command line.

Any suggestions on this @palisadoes  @yasharth291 .

**Comment by yasharth291** [comment]
@palisadoes  what @asmitsirohi  is saying is kind of true we have to take this into the consideration.

**Comment by Devesh21700Kumar** [comment]
> I think @Devesh21700Kumar is right in some aspects because to set up talawa-admin, we need the talawa-API project well setup as APIs used in talawa-admin is from talawa-API.
> 
> Also, the API keys are set up in talawa-API with that project itself and API keys are not required in talawa-admin as mentioned in #18. The only thing required in talawa-admin configuration is API URL, which is actually hardcoded in the project currently
> 
> image
> 
> The API URL could be present in the .env file, which makes sense for automated installation.
> 
> I think the correct way to set up talawa-admin is:
> 
> * Clone Talawa-admin
> * Clone Talawa-API
> * Setup Talawa-API {API keys, MongoDB connection url}
> * Setup Talawa-admin {API URL}
> 
> ### After cloning Talawa-admin, all the other things need to be done using the command line.
> Any suggestions on this @palisadoes @yasharth291 .

Yeah, I had mentioned concerns on similar lines here https://github.com/PalisadoesFoundation/talawa-admin/pull/202#issuecomment-1004811672

**Comment by palisadoes** [comment]
I agree, we need to remove the hard coding of URLs from the code and place them in configuration files. We will need to coordinate these efforts with @kailash360 who is working on a JavaScript installer for the API. The Admin instructions will need to include the series of steps mentioned above.

- https://github.com/PalisadoesFoundation/talawa-api/pull/387

Please work on this assuming that we prompt for the URL.

**Comment by palisadoes** [comment]
Was the code updated to prompt for the URL?

**Comment by asmitsirohi** [comment]
I was waiting for PalisadoesFoundation/talawa-api#241 to be fixed because before setup talawa admin a number of steps need to be done.

* Clone talawa-API
* Run automated setup of talawa-API
* Automated installing of talawa-admin will begin now onwards.

Apart from it, code for prompt can be ready at any time.

**Comment by palisadoes** [comment]
The API installer shouldn't be a pre-requisite. Talawa-Admin may be installed on a completely different server, we therefore would only need the URL to the API to be created. The cloning of the API and installation of the API shouldn't be a factor. 

Let me know if you think we need to consider other factors. I'd really like to get this completed soon.

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
