### PR TITLE
Fix: Improve Code Coverage for src/screens/Users/Users.tsx

### LINKED ISSUE #1035: Code Coverage: Create tests for src/screens/Users/Users.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by shivansh-bhatnagar18**
This improves the code coverage for the Users Component by adding more tests

**Issue Number:**

Fixes #1035 

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@shivansh-bhatnagar18  can you add the snapshot of 100% test coverage report.

**Comment by shivansh-bhatnagar18** [comment]
image
I am constantly trying to add more tests in the Users.test.tsx but I am unable to understand why isn't the code coverage not more than 88.88%. Could you help me out. I also did try to add tests to lines mentioned in the coverage

**Comment by Cioppolo14** [comment]
@shivansh-bhatnagar18  Are you still working on it?

**Comment by shivansh-bhatnagar18** [comment]
Yes @Cioppolo14 , I am still working on this

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by SiddheshKukade** [comment]
Please fix the conflict

**Pull request closed without merging**
