### PR TITLE
fix md_mpx_format_adjuster.py script

### PR DESCRIPTION
**Pull request by dhiraj0911**
**What kind of change does this PR introduce?**

- Bugfix for the automated documentation GitHub action PUSH workflow.
- Standardizes package manager to `npm` for both `talawa-api` and `talawa-admin`.
- Adds a Python script (`md_mpx_format_adjuster.py`) to ensure Markdown files are MPX compatible.
- Fixed a Python script for  excessive `/`

**Issue Number:** #1279 

---

**Did you add tests for your changes?**

- No new tests added. The changes pertain to the GitHub Actions workflow and documentation updates.
- Manual testing was conducted to ensure functionality and MPX compatibility.

---

**If relevant, did you update the documentation?**

- Documentation updated to reflect the shift from npm to yarn and the integration of `script.py`.
- Details on workflow changes and MPX compatibility considerations with Docusaurus v3 included.

---

**Summary**

- Addresses issues with GitHub action for automated documentation generation.
- Resolves inconsistencies in package managers and non-compliance with Docusaurus v3's MPX standards.
- Includes transition to yarn and introduction of `script.py` for Typedoc-generated Markdown files.

---

**Does this PR introduce a breaking change?**

- No breaking changes introduced.
- Focuses on resolving workflow issues and enhancing compatibility, not affecting core software functionality.

---

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**

- Yes, the contributing guidelines have been followed.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
See comment.

**Comment by palisadoes** [comment]
Please work with @noman2002 on this. He'll be taking over the review of this PR

**Comment by palisadoes** [comment]
@Nitya-Pasrija Please be aware of this PR

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@noman2002 please review

**Review by palisadoes — COMMENTED** [review]
See comment

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
