### PR TITLE
Refactor: Migrated src/components/CurrentHourIndicator/CurrentHourIndicator.test.tsx from Jest to Vitest

### LINKED ISSUE #2840: Refactor `src/components/CurrentHourIndicator/CurrentHourIndicator.test.tsx` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor the file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

1. Refer to the merged PR for the base Vitest configuration:
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
1. Vitest reference site:
    1. https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by subrajeet-maharana**
**What kind of change does this PR introduce?**

This PR will migrate the src/components/CurrentHourIndicator/CurrentHourIndicator.test.tsx from Jest to Vitest.

**Issue Number:**

Fixes #2840 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**
N/A

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**
N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Tests**
	- Updated testing framework import for `CurrentHourIndicator` component tests
	- Maintained existing test case for component rendering

### CODE REVIEW

**Comment by palisadoes** [comment]
Please merge your local branch with the latest upstream. That should fix the error

**Comment by duplixx** [comment]
@subrajeet-maharana please fix the conflicting file changes

**Comment by palisadoes** [comment]
1. Why was this closed?
2. If tests fail or there are file conflicts, merge your local branch with the latest upstream, fix the files, merge, commit to your origin. The PR will automatically be updated
3. Reopening

**Comment by subrajeet-maharana** [comment]
Hello! Apologies for closing the issue.
1. Branch name same hence tests were failing.. 
image
2. Was unable to figure out how to connect commit from different branch. so closed this and created a new PR #3092 
3. But it seems same issue with the new PR also. 

Can you help me with this?

**Comment by palisadoes** [comment]
In that case, it needs to be closed

**Pull request closed without merging**
