### PR TITLE
Change the Scalar Types [Provides relevant client side changes for #1085 in Talawa-API]

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Bugfix: Updates the relevant Scalar types for the parameters of mutations and queries (if any) to the newly added Graphql-scalars introduced by this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1085)

**Issue Number:**

Fixes [#1085 of Talawa API](https://github.com/PalisadoesFoundation/talawa-api/pull/1085)

**Did you add tests for your changes?**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
This PR must be merged with the corresponding PR in the Talawa-API repository to ensure that the implementation of the same doesn't break the client.

**Does this PR introduce a breaking change?**
YES

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

**Additional Minor Change**
Added .vscode directory to the `.gitignore` because it is a common directory that should be included most .gitignores (as already done in Talawa-API)

### CODE REVIEW

**Comment by EshaanAgg** [comment]
I have identified another breaking client side change in terms of date objects. Earlier we were storing dates as numbers (UNIX timestamps), but now due to introduction of Date and Time scalars, they are being stored as proper date and time objects (in ISO 8601 format). 
Thus we must update the calls to `dayjs` library to handle the same. 

Should I add these changes to this PR itself?

**Comment by xoldyckk** [comment]
> I have identified another breaking client side change in terms of date objects. Earlier we were storing dates as numbers (UNIX timestamps), but now due to introduction of Date and Time scalars, they are being stored as proper date and time objects (in ISO 8601 format). Thus we must update the calls to `dayjs` library to handle the same.
> 
> Should I add these changes to this PR itself?

Yes

**Comment by Kevoniat** [comment]
can you fix the failing test?

**Comment by Kevoniat** [comment]
the Code looks good but the 68.81% Coverage  test  is concerning

**Comment by palisadoes** [comment]
Please add tests for the modified files, especially [OrganizationPeople.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/500?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3NjcmVlbnMvT3JnYW5pemF0aW9uUGVvcGxlL09yZ2FuaXphdGlvblBlb3BsZS50c3g=)

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please add tests for the modified files, especially [OrganizationPeople.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/500?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3NjcmVlbnMvT3JnYW5pemF0aW9uUGVvcGxlL09yZ2FuaXphdGlvblBlb3BsZS50c3g=)

**Comment by EshaanAgg** [comment]
@Kevoniat @palisadoes Writing tests for the same seems out of scope for this PR, as this PR doesn't deal with the UI, but rather provides patches for the changes in Talawa-API due to migration to GraphQL-scalars.

There are separate issues that are already open for increasing the coverage of files, like [this](https://github.com/PalisadoesFoundation/talawa-admin/issues/480) for increasing the coverage of `OrganizationPeople.tsx`

**Comment by palisadoes** [comment]
1. We are really trying to keep our code coverage up. And one way of doing that is ensuring that we get it for all submitted files.
1. We haven't made an announcement so I'll let this one go.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@Kevoniat please take a look

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by xoldyckk** [comment]
@palisadoes revert this commit. Unless talawa mobile, admin and api all are in sync with the schema changes this can't be merged.

**Comment by palisadoes** [comment]
I'm getting a message stating that an automatic revert is impossible.
Please approve with changes requested with an explanation of the merging concerns. That way I  get a red flag. I am weighing the need for speed to get things fixed against the risks of this happening. I need the right signals.

**Comment by xoldyckk** [comment]
@palisadoes https://github.com/PalisadoesFoundation/talawa-api/pull/1085#issuecomment-1445276284
Talawa mobile will get the relevant changes by today, so I guess you don't need to revert.

**Pull request merged**
