### PR TITLE
feat: Implemented Sorting Functionality for Users Screen

### LINKED ISSUE #1074: Implement sorting on the users screen
**Describe the bug**
Currently sorting is not implemented in the users screen, the aim is to implement the sort functionality with latest first, oldest first etc. options, you can refer from the posts screen.

**To Reproduce**

1. login into the talawa admin dashboard 
2. from the menu navigate to the users option
3. navigate to the sort button

**Expected behavior**
sorting of users on the basis of defined and selected attributes.

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
This PR introduces the sorting functionality in the Users screen.

Changes Made:
- Implemented sorting functionality for the users screen.
- Added options for sorting users by latest first and oldest first.
- Wrote corresponding tests to ensure the sorting behavior is accurate.
- Tested the sorting feature by logging into the Talawa admin dashboard, navigating to the users option, and checking the sort button.

**Issue Number:**

Fixes #1074 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/494f0224-9fe5-4735-8735-ef56d4719f36

**If relevant, did you update the documentation?**
No

**Summary**
This commit addresses the reported issue regarding the lack of sorting functionality on the Users screen.
The objective was to allow users to sort users based on creation date.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@DMills27 @noman2002 @palisadoes 
I reviewed it, LGTM.

**Comment by DMills27** [comment]
I suggest changing the word "latest" to "newest" as that sounds more natural. Otherwise it looks good to me.

**Comment by palisadoes** [comment]
@akhilender-bongirwar Please make the requested change

**Comment by akhilender-bongirwar** [comment]
> I suggest changing the word "latest" to "newest" as that sounds more natural. Otherwise it looks good to me.

Sure @DMills27. Newest sounds good.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
