### PR TITLE
Fix Password validation on the Login/Signup Page [Fixes #720]

### LINKED ISSUE #720: Unmatched password filed validation between Talawal mobile app &  Talwal admin
when i tried to register a new account `on the admin `portal i was able to register an account with a password which has the following validation **(at least 8 characters long ),** but when i tried to use the same password to login `using the mobile app` it gave me the error **(password must have at least 8 char, one upper Case , one number ,one special characters)**

**To Reproduce**

1. first choice is to edit the validation on the `mobile app` to (**at least 8 characters )**
2.second choice is to edit the validation on the `admin portal` to (**password must have at least 8 char, one upper Case , one number ,one special characters)**
 i am ready to be assigned for this issue

**Expected behavior**
matched password validation between mobile app & admin portal

**Actual behavior**
unmatched password validation between mobile app & admin portal

**Screenshots**
WhatsApp Image 2023-03-15 at 8 53 01 PM (1)
WhatsApp Image 2023-03-15 at 8 53 01 PM (2)
WhatsApp Image 2023-03-15 at 8 53 01 PM
WhatsApp Image 2023-03-15 at 8 53 02 PM

### PR DESCRIPTION
**Pull request by BhuvanAde**
**What kind of change does this PR introduce?** 
It is a bug fix; the password validation during the signup only constrain the password on being non-empty but now it will ensure that it is at least 8 characters long and has at least one capital letter, one number and one special character.

**Issue Number:**
#720 

Fixes #720 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by BhuvanAde** [comment]
https://user-images.githubusercontent.com/81461629/230124288-f7257b07-f8a9-475e-9cd5-b7bc7f1e4e55.mov

**Comment by aviraldevv** [comment]
@BhuvanAde please try adding locales for all languages.

**Review by aviraldevv — COMMENTED** [review]
@BhuvanAde

Helper functions like this can be used to segregate the logic and make it more understandable.

`const hasUppercase = (password) => /[A-Z]/.test(password);`
`const hasNumber = (password) => /[0-9]/.test(password);`
`const hasSpecialChar = (password) => /[^A-Za-z0-9]/.test(password);`

**Comment by palisadoes** [comment]
Will this work in all the supported languages?

**Comment by BhuvanAde** [comment]
Currently, It supports English. If required, I will also add to all the languages available.

**Comment by palisadoes** [comment]
It will need to support all supported languages. European language rules are not going to be universally available. Please research the best strategies for this.

**Comment by BhuvanAde** [comment]
Ok sure! @palisadoes

**Review by palisadoes — CHANGES_REQUESTED** [review]
The validation method needs to be consistent across all the supported languages.

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Review by palisadoes — CHANGES_REQUESTED** [review]
You have not thoroughly considered the implications on all languages.

1. Do all the languages have the concept of capital letters?
    1. How are you testing this?
1. Do all the languages use A-Z characters in their alphabets? 
1. Do all the languages use the same special characters you have selected? 
1. How are you letting people in all languages know what the expected special characters should be?
    1. How are you testing this?
1. Do all the languages we support use Arabic numerals? Are these numerals available on their keyboards?

You need to have a solution that truly is multilingual. Please research this some more.

**Comment by BhuvanAde** [comment]
Ok @palisadoes! I would do a bit more research. Does the mobile app currently have multilingual support?

**Comment by palisadoes** [comment]
> Ok @palisadoes! I would do a bit more research. Does the mobile app currently have multilingual support?

Yes. It probably suffers the same deficiencies as this app

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by BhuvanAde** [comment]
Because of my end-of-term exams, I am currently unable to work on this issue. I intend to continue my research as soon as possible and am looking to learn more about the mobile app and admin portal issues. As a result, it would allow for a solution for both. @palisadoes

**Pull request closed without merging**
