### PR TITLE
Fix #488 Removed carousel and added Palisadoes logo

### LINKED ISSUE #488: Image not visible on orglist page
**Describe the bug**
The image is not being displayed on the orgist page,despite the the image is selected while creating the org

I think it is happening because of image is not being sent in payload while creating an organization

**To Reproduce**

1. Create an organization with a display image

**Expected behaviour**

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AjayMaheshwari23**
I have removed the carousel from the home page and added Palisadoes logo in place of that.

Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/448
Here's a snapshot for that :
Before:
Screenshot 2023-02-08 at 2 44 38 PM

After:
Screenshot 2023-02-08 at 8 12 46 PM

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Remove the line `This is Talawa Admin Management Portal` etc. We already have the `Talawa Portal` text in the top left hand corner
1. Replace `FROM PALISADOES` with `An open source application by Palisadoes Foundation volunteers`

**Review by noman2002 — DISMISSED** [review]

**Comment by palisadoes** [comment]
@AjayMaheshwari23 Please make the requested changes.

**Comment by AjayMaheshwari23** [comment]
Done

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
@noman2002 please review again

**Comment by AjayMaheshwari23** [comment]
Why is it not performing the 7 checks ?

**Comment by AjayMaheshwari23** [comment]
@noman2002 and @Kevoniat can you please review the changes

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
