### PR TITLE
fix: solved issue #551

### LINKED ISSUE #551: Updated user role doesn't change until page refresh
*** Describe the bug ***
User role remains the same even after updating the role

*** To Reproduce ***

1. Log in as a superadmin
2. Navigate to /roles
3. Change a users Role/User-Type
4. Navigate out of /roles
5. Navigate back to roles

*** Expected behavior ***
I expect the ui to display the updated users role

*** Actual behavior ***
What displays is rather a previous user role, and this behavior fixes only after refreshing the page

*** Solution ***
include refetch after the update mutation has occured

Pls assign this task to me

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sedoid**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #551 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Summarily,  whenever an user role update was performed by the superadmin, the role displayed remained the same whenever the he navigates out and back to the page,  the replication procedure is detailed on issue #551

To solve this, i just added a refetch() expression after the  success toast

**Does this PR introduce a breaking change?**
No

**Other information**

I noticed that i unintentionally committed the solution to issue #544 concerning a repeating row of pagination.
i had realized the issue was just duplicated code, i commented one block of it and that solved the issue

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1. The overall code coverage drops below the target threshold of the repository
1. Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by Sedoid** [comment]
Alright, can i close this pull request,  fix the failing tests and try opening another one pr again?

**Comment by palisadoes** [comment]
No, that's not necessary. Each new commit push you make to your repository should automatically update the PR. The report will be generated each time.

**Review by noman2002 — CHANGES_REQUESTED** [review]
restore .env.example .

**Comment by Sedoid** [comment]
Yes yes ... i did not notice

**Review by noman2002 — CHANGES_REQUESTED** [review]
pull the latest code to this PR. There is a huge drop in codecov.

**Pull request closed without merging**
