### PR TITLE
Added dropdown for Applanguage in UserUpdation form

### LINKED ISSUE #485: changes in the Setting feature of Update Organization
**Is your feature request related to a problem? Please describe.**
We have a setting page to update Organization details. In that, there is an Option to fill App Language Code.
Screenshot from 2023-02-19 14-30-51
We want to have a dropdown for the language option just like this one.
Screenshot from 2023-02-19 14-36-19

**Describe the solution you'd like**
Add a DropDown to choose the App Language Code.

**Approach to be followed (optional)**
we want to minimize changes to the existing design. Hence no new CSS, no new responsive design, just the enabling of previously disabled or incorrectly implemented features.

### PR DESCRIPTION
**Pull request by rishav-jha-mech**
**What kind of change does this PR introduce?**

Bug fix, dropdown of app languages in user updation form 

**Issue Number:**
#485 

Fixes #485

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
Talawa Setting - Google Chrome 23-02-2023 05_25_40

**If relevant, did you update the documentation?**

No necessary.

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by noman2002** [comment]
@rishav-jha-mech Attach a screenshot of dropdown.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Change App Language code to Default language.

**Comment by rishav-jha-mech** [comment]
> Change App Language code to Default language. and display English as the default language rather than showing " - ".

I have made the necessary changes @noman2002, please let me know if there is something missing.

**Comment by noman2002** [comment]
> > Change App Language code to Default language. and display English as the default language rather than showing " - ".
> 
> I have made the necessary changes @noman2002, please let me know if there is something missing.

Please add a latest screenshot

**Comment by rishav-jha-mech** [comment]
## Screenshots

Dropdown select

Dropdown

**Review by noman2002 — APPROVED** [review]
Good Work

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
