### PR TITLE
Refactor styles: move SubTags.module.css styles to app.module.css

### LINKED ISSUE #2526: Refactor CSS files in src/screens/SubTags
# Refactor CSS files in src/screens/SubTags

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by amitb0ra**
**What kind of change does this PR introduce?**

refactoring

**Issue Number:**

Fixes #2526

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

There are some issues like: "Cannot find module '@testing-library/dom' from 'node_modules/@testing-library/react/dist/pure.js'" but that is not relevant here.

**If relevant, did you update the documentation?**

No

**Summary**

The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern.

**Does this PR introduce a breaking change?**

No

**Other information**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced error message display and styling for better visibility.

- **New Features**
	- Introduced new styles for improved button and input layouts.
	- Added responsive design adjustments for better usability on mobile devices.
	- Implemented new CSS variables for better color contrast and accessibility.

- **Style**
	- Updated various CSS classes for improved visual consistency and interactivity.
	- Enhanced scrollbar styles for scrollable areas.
	- Modified button and layout properties for better control and spacing.
	- Improved hover effects and layout stability for links and breadcrumbs.
	- Refined media queries for better adaptability on smaller screens.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
You haven't updated the code files that will use the updated app.module.css

**Comment by amitb0ra** [comment]
> You haven't updated the code files that will use the updated app.module.css

It was already there in src/screens/SubTags/SubTags.tsx

`import styles from '../../style/app.module.css';`

**Comment by palisadoes** [comment]
Thanks. Please fix the failing tests

**Comment by amitb0ra** [comment]
> Thanks. Please fix the failing tests

the failing tests are due to some modules missing, which is out of scope of this PR. Do you want me to include it?

There are some issues like: "Cannot find module '@testing-library/dom' from 'node_modules/@testing-library/react/dist/pure.js'" so to fix failiing tests i have to install this.

**Comment by palisadoes** [comment]
> > Thanks. Please fix the failing tests
> 
> the failing tests are due to some modules missing, which is out of scope of this PR. Do you want me to include it?
> 
> There are some issues like: "Cannot find module '@testing-library/dom' from 'node_modules/@testing-library/react/dist/pure.js'" so to fix failiing tests i have to install this.

Yes. @AVtheking will provide further guidance

**Comment by amitb0ra** [comment]
any updates? @AVtheking @palisadoes

**Comment by palisadoes** [comment]
Please fix the tests that need to be updated because of your changes

**Comment by amitb0ra** [comment]
> Please fix the tests that need to be updated because of your changes

which failing tests?

**Comment by VanshikaSabharwal** [comment]
@amitb0ra you must fix this test. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/12215418229/job/34077354372?pr=2538

**Comment by Cioppolo14** [comment]
@amitb0ra  Please fix the failed tests.

**Comment by amitb0ra** [comment]
> @amitb0ra Please fix the failed tests.

The logs indicate that the following CSS files have issues with parsing:

src/screens/OrganizationPeople/OrganizationPeople.module.css
src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.module.css
src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.module.css
src/screens/OrganizationEvents/OrganizationEvents.module.css
src/screens/OrgPost/OrgPost.module.css
src/screens/OrganizationVenues/OrganizationVenues.module.css
src/screens/OrganizationFunds/OrganizationFunds.module.css
src/screens/OrganizationTags/OrganizationTags.module.css
src/screens/Requests/Requests.module.css

which is irrelvant to this pr. do you want me to go out of scope and fix all?

**Comment by palisadoes** [comment]
1. Please merge you code with the latest develop-postgres code.
2. Please isolate the PR that may have caused the issue

**Comment by amitb0ra** [comment]
> 1. Please merge you code with the latest develop-postgres code.
> 2. Please isolate the PR that may have caused the issue

1. this pr is already in latest develop-postgres branch.
2. none of the css code caused the error, i have checked even without changing anything these test cases are getting failed.

**Comment by palisadoes** [comment]
1. We cannot merge the PR with failing tests.
2. Please fix the tests or suggest the PR that caused it to be reverted. If it cannot be reverted, then you'll need to fix the tests

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
1. Please fix the failing tests. 
    1. You may have to fix a test that is not related to this PR as in some rare cases we merge faulty test code. If this is the case, fix the test in this PR. Do not open another issue.
1. Please make sure that CodeRabbit.ai approves the PR.

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by amitb0ra** [comment]
@palisadoes any updates?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
