### PR TITLE
[userTypeFix] Bugfix 1832

### LINKED ISSUE #1832: [userTypeFix]: Privilege Escalation through login mutation Response Interception
**Describe the bug**
refer to https://github.com/PalisadoesFoundation/talawa-api/issues/2103

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

@palisadoes assign this to me.

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**

BugFix

For the time being, we should restrict critical fields like `isSuperAdmin` from being even displayed and changed from the front end.

**Issue Number:**

Fixes #1832 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by pranshugupta54** [comment]
This will create too many unknown bugs

**Comment by Cioppolo14** [comment]
@ttaylor92 @anwersayeed Can you review this PR?

**Comment by pranshugupta54** [comment]
Reference, 
This is a part of [discussion](https://github.com/PalisadoesFoundation/talawa-api/discussions/1997) for implementing some authorization (maybe Supabase).

**Comment by Cioppolo14** [comment]
@krishna619  This isn't actually addressing the bug right? Does this make sense to do? Are we making another issue to track the security issue in this case?

**Review by palisadoes — CHANGES_REQUESTED** [review]
This seems short sighted. Wouldn't changing this single line of code also disable SuperAdmin functionality in the app?

**Comment by palisadoes** [comment]
I'm going to close this based on the slack discussion
- https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1711622494491939

**Pull request closed without merging**
