### PR TITLE
First PR | Email verification for signup

### LINKED ISSUE #492: Improve registration validation
**Describe the bug**
Currently the registration form has following fields:-
+ Your Name
+ Your Email
+ Your Password
but it fails to validate the input taken from the user.

**Expected behavior**
Before registering a user, confirm the user's identity, such as sending a confirmation email to the provided email address. There should be limit to the minimum number of characters allowed for password etc.

**Actual behavior**
The website currently accepts any user without confirming the user's identity.

**Additional details**
We want to minimize changes to the existing design. Keep the current design.

### PR DESCRIPTION
**Pull request by KhushiTayal**
**What kind of change does this PR introduce?**

Adds the email otp verification to Login Page , while signing up . 

**Issue Number:**

Fixed #492 Improve registration validation. 

**Did you add tests for your changes?**

Nope . Could you please help with this?

**Snapshots/Videos:**

Okay

**If relevant, did you update the documentation?**

Not relevant

**Summary**

Email needs to be verified before signing up . This functionality has been enabled by the new changes

**Does this PR introduce a breaking change?**

No.

**Other information**

Nope

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by KhushiTayal** [comment]
@palisadoes I have made the required changes. Please review it.

**Comment by KhushiTayal** [comment]
@anshgoyalevil please review the changes suggested by you.

**Comment by anshgoyalevil** [comment]
@KhushiTayal 

- Please fix the failing tests.
- Write/update unit tests for the files you have modified
- Your PR on the Talawa API is closed because you have incorrectly linked this issue to that PR. You can reference issues between repositories by mentioning user/repository#number in an issue. Example ```palisadoes/talawa-admn#492```

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please fix the failing tests.

**Comment by palisadoes** [comment]
Please fix the failing tests and the conflicting files. You will need to merge with your upstream

**Comment by palisadoes** [comment]
Closing due to inactivity

**Pull request closed without merging**
