### PR TITLE
Minor tweaks in admin

### LINKED ISSUE #1737: Feature Request: Minor tweaks in admin
**Is your feature request related to a problem? Please describe.**
The current labeling and organization within the admin interface are causing confusion and inefficiency. Users are having difficulty navigating and understanding the functions due to unclear and inconsistent terminology.

**Describe the solution you'd like**

- [ ] Rename “Talawa Posts” to “Posts” to simplify and generalize the label, making it more intuitive for users.

- [ ] Rename “Talawa Block /Unblock” to “Block / Unblock” for clarity and consistency with action verbs.
- [ ] Remove the "manage ads" sub-heading from the advertisement page to declutter and streamline the interface.
- [ ] Remove the “events” subheading from the events page to simplify and unify the page structure.
- [ ] Rename “Talawa Settings” to “Settings” for consistency and clarity.
- [ ] On the Settings page, for the “Action Item categories” button, remove the hover effect to enhance usability and prevent confusion.
 

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by adi790uu**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1737 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

Screenshot 2024-03-21 at 1 37 42 AM
Screenshot 2024-03-21 at 1 38 04 AM
Screenshot 2024-03-21 at 1 38 08 AM
Screenshot 2024-03-21 at 1 38 17 AM
Screenshot 2024-03-21 at 1 41 51 AM

https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/286fb6e8-352f-42da-b7d0-40c1a2c368a5

**Summary**

Some minor tweaks related to UI/UX.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by adi790uu** [comment]
@SiddheshKukade have implemented every task and have only changed headings in en.json.

**Comment by Cioppolo14** [comment]
@adi790uu  Please fix the failing test application check.

**Comment by adi790uu** [comment]
@Cioppolo14 its fixed now.

**Comment by adi790uu** [comment]
@Cioppolo14 can you assign reviewers to this.

**Comment by Huy1996** [comment]
@noman2002 @anwersayeed Could you review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Pull request merged**
