### PR TITLE
Refactor: src/screens/UserPortal/Volunteer/UpcomingEvents from Jest to Vitest

### LINKED ISSUE #2582: Refactor: `src/screens/UserPortal/Volunteer/UpcomingEvents`  from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/UserPortal/Volunteer/UpcomingEvents` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by abbi4code**
**What kind of change does this PR introduce?**
This PR migrates the test cases in src/screens/UserPortal/Volunteer/UpcomingEvents from Jest to Vitest, ensuring compatibility with Vitest .

✅ Replace Jest-specific functions and mocks with Vitest equivalents
✅ Ensure all tests in src/screens/UserPortal/Volunteer/UpcomingEvents pass after migration using npm run test:vitest
✅ Maintain the test coverage for the file as 100% after migration
✅ Upload a video or photo for this specific file coverage is 100% in the PR description

**Issue Number:**

Fixes #2582 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

Screenshot from 2024-12-09 03-29-00

## Summary by CodeRabbit

- **Tests**
	- Updated testing framework from Jest to Vitest for the UpcomingEvents component.
	- Modified mocking methods for `react-toastify` and `react-router-dom` to align with Vitest standards.
	- Added documentation comments to clarify the purpose of the unit tests for the UpcomingEvents component.

### CODE REVIEW

**Comment by abbi4code** [comment]
> For TS doc check fail you have to add some comments on the top of file. Check merged PR linked in issue for reference

Done @varshith257

**Comment by abbi4code** [comment]
What else can I do to make this PR mergeable? @varshith257

**Comment by palisadoes** [comment]
1. Please make sure coderabbit.ai approves your PR
1. Make sure all tests pass (except introspection)
1. Please make sure that the code coverage for your patch reaches at least 95%. It is at 83% now.

**Comment by abbi4code** [comment]
> 1. Please make sure coderabbit.ai approves your PR
> 2. Make sure all tests pass (except introspection)
> 3. Please make sure that the code coverage for your patch reaches at least 95%. It is at 83% now.

1. CodeRabbit review has been completed and approved.
2. All tests have passed successfully (except introspection).
3. changes in the current pull request (patch) did not affect the coverage
Screenshot from 2024-12-13 10-14-16

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
