### PR TITLE
New Event Calendars for Admin and User Portals with working functionalities

### LINKED ISSUE #1608: USER REDESIGN: redesign the Event screen for the talawa user portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Event screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation :
Screenshot 2024-02-21 at 1 14 52 AM

Desired Result:
Screenshot 2024-02-21 at 1 10 01 AM

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : 
- #1510 (sidenavbar is covered in this issue)

**Additional context**

1. **_NOTE:_** This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1608 #1850 #1851

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/c32a6932-6d0d-4e60-a229-a20a5d0e6a81

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
Please remove the console log statement from `src/screens/OrgList/OrgList.test.tsx` it's giving too much output

image

**Comment by duplixx** [comment]
@palisadoes sir there isn't any console log present in the file
image

**Comment by duplixx** [comment]
@palisadoes yes sir I am on it

**Comment by duplixx** [comment]
@palisadoes this PR is ready

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
