### PR TITLE
feat: added dependabot

### LINKED ISSUE #1104: Configure Automated Dependabot Updates
We need to make sure our code is constantly up to date especially for our `develop` branch. To do this we need to implement automated updates using dependabot. This has already been done with the Talawa repo, but we also need it done for this one.

Requirements

1. Weekly updates
1. Run against the `default` branch
1. Use the appropriate package system
1. Use the appropriate root directory

Other information

1. Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
1. Talawa Example: https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/dependabot.yaml

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**
feature

**Issue Number:** 

Fixes #1104 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

Added Dependabot for weekly automated dependency updates
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please take a look at this for standardization
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/dependabot.yaml

**Review by EshaanAgg — CHANGES_REQUESTED** [review]
@disha1202 Please add the comments and the same `prefix` for dependabot PRs as done in the linked file by Peter. Please re-request a review after you do so.

**Comment by disha1202** [comment]
Hi @EshaanAgg 

I have updated the PR. 

Please take a look.

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
1. I have to revert this. The file is in the wrong directory and is causing other merges to fail.
2. @disha1202 refer to this
    - https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github

**Pull request merged**
