### PR TITLE
Upgraded prettier from 2.3.2 to 3.2.5

### LINKED ISSUE #1591: Upgrade prettier from 2.3.2 to 3.2.5
**Is your feature request related to a problem? Please describe.**

We need the the default formatting for Talawa-Admin to match that of Talawa-API

**Describe the solution you'd like**

1. Upgrade [prettier](https://github.com/prettier/prettier) from 2.3.2 to 3.2.5.
1. Format the code base according to the new default prettier rules
1. Submit PR. The prettier pull request check must pass. The check can be found here
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-request.yml
    2. This file must not be edited
1. All tests must pass
1. No other functionality must be affected 

**Describe alternatives you've considered**

- N/A 

**Approach to be followed (optional)**

- N/A 

**Additional context**

The upgrade will cause many files to be modified to meet the new prettier defaults. Refer to these items for guidance.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1814
- https://github.com/PalisadoesFoundation/talawa-api/pull/1840

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
Upgraded prettier to 3.2.5

**Issue Number:**

Fixes #1591 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
- Upgraded prettier to latest version and matched the version to that of talawa-api
- Ensured all the tests are passing
- Ensured no other functionality got affected

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
@palisadoes, the PR Workflow, which performs linting, formatting, and type-checking checks, is successful.

**Comment by akhilender-bongirwar** [comment]
prettier-eslint-issue
- I have faced the above error when I ran `npm run serve`

eslint-prettier

- Even the lint:check didn't work as you can see in the above screen shot.


Hence to resolve this issue and make sure the linting worked properly I have upgraded `eslint-plugin-prettier` to `5.1.3`.

**Comment by palisadoes** [comment]
Is this ready for review now?

**Comment by akhilender-bongirwar** [comment]
> Is this ready for review now?

yes sir : )

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
