### PR TITLE
Refactor CSS Structure for EventVolunteers: Improved Maintainability and UI Consistency

### LINKED ISSUE #2505: Refactor CSS files in src/screens/EventVolunteers
# Refactor CSS files in src/screens/EventVolunteers

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by gurramkarthiknetha**
**What kind of change does this PR introduce?**

Feature/Refactoring

**Issue Number:**

Fixes #2505 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

N/A 

**If relevant, did you update the documentation?**

No 

**Summary**

This PR refactors the CSS structure for the `EventVolunteers` and its related components. The changes involve merging all CSS files from the subdirectory and related components into the global CSS file. After the merge, the old CSS files were deleted, and the components were updated to reference the global CSS. This improves maintainability and adheres to the updated design patterns.

**Does this PR introduce a breaking change?**

No, these changes only refactor the existing CSS structure.

**Other information**

Testing was completed to ensure no UI regressions. All screens were verified for consistency with the updated global CSS styles.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for various components, including buttons, containers, and modals.
	- Improved search functionality with debounced input for better performance.

- **Bug Fixes**
	- Adjusted styling for error icons and input fields.

- **Documentation**
	- Updated CSS styles to reflect new class definitions and improvements.

- **Chores**
	- Reorganized CSS import paths for better structure and maintainability.

- **Style**
	- Removed outdated styles from the Event Volunteers screen and introduced new styles for improved UI presentation.
	- Added new classes for dropdowns and modals, enhancing interactivity and visual presentation.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@gurramkarthiknetha Please fix the title of the PR to reflect what the PR is doing.  Something doesn't seem right here, as its only running one check.  Please make sure all the tests run, pass their tests,  and there are not conflicting files.

**Comment by palisadoes** [comment]
Please resolve the conflicting files. Hopefully if that gets resolved the rest of the tests will run

**Comment by gurramkarthiknetha** [comment]
> @gurramkarthiknetha Please fix the title of the PR to reflect what the PR is doing. Something doesn't seem right here, as its only running one check. Please make sure all the tests run, pass their tests, and there are not conflicting files.

thank you for you suggestion @Cioppolo14 
Now i changed to "Refactor CSS Structure for EventVolunteers: Improved Maintainability and UI Consistency" is this ok .

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by gurramkarthiknetha** [comment]
> Please fix the conflicting file

Ok @palisadoes I will fix tonight

**Comment by palisadoes** [comment]
Thanks for submitting your PR, but we must close it.

1. We get notified of every event in the queue, and draft PRs like these, and their updates that require no action can be a distraction. We need our reviewers to focus on updates that are ready. 
1.  Don't be discouraged, we are just trying to keep our workloads to a manageable level.

Please resubmit when you are ready.

**Pull request closed without merging**
