### PR TITLE
Refactor: src/screens/UserPortal/Posts from Jest to Vitest

### LINKED ISSUE #2578: Refactor: `src/screens/UserPortal/Posts` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/UserPortal/Posts` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Niyatijain-9**
**What kind of change does this PR introduce?**
It is a refactor of changing the test case migration of jest to vitest.

**Issue Number:**

Fixes #2578 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
Screenshot (5)

Screenshot (4)

**If relevant, did you update the documentation?**

**Summary**
This code is tested with vitest and all the tests are run and passed.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

## Summary by CodeRabbit

- **Bug Fixes**
	- Enhanced tests for the `Posts` component to ensure correct functionality, including post deletion and comment display.
	- Updated the like button test to confirm the increment of likes after interaction.

- **New Features**
	- Added tests for new functionalities such as pagination and post creation, including user interaction checks.

- **Refactor**
	- Simplified the `renderHomeScreen` function signature.
	- Restructured and renamed several tests for clarity and focus on component functionality.

- **Chores**
	- Removed the stale issue management workflow from the repository.
	- Removed the ESLint ignore entry for a specific file, allowing it to be subject to linting checks.
	- Deleted ESLint configuration file, streamlining linting processes.

### CODE REVIEW

**Comment by Niyatijain-9** [comment]
Hi @palisadoes, kindly review. I have made the changes.

**Comment by Niyatijain-9** [comment]
Kindly review @palisadoes. I have made the required changes.

**Comment by palisadoes** [comment]
This PR has too many submitted files that are out of scope of the original issue. 

Please ensure the following:

1. Fetch the latest upstream/develop-postgres files
2. Make your PR modifications based on the local copy of this `develop-postgres` branch
3. Submit your PRs against our `develop-postgres` branch.
4. Your source branch in your local repository must not be the same as the target branch

Closing

**Comment by Niyatijain-9** [comment]
> This PR has too many submitted files that are out of scope of the original issue.
> 
> Please ensure the following:
> 
> 1. Fetch the latest upstream/develop-postgres files
> 2. Make your PR modifications based on the local copy of this `develop-postgres` branch
> 3. Submit your PRs against our `develop-postgres` branch.
> 4. Your source branch in your local repository must not be the same as the target branch
> 
> Closing

Hi, I had actually made changes to one file only  but as I had changed the base branch to develop-postgres it automatically took in the file changed count to 49. Could you please help me in providing insights for the same.

**Comment by palisadoes** [comment]
You are merging from develop into develop-postgres. All work must be done in the develop-postgres branch for this repo at this time.

**Pull request closed without merging**
