### PR TITLE
added OrgName to the Navbar

### LINKED ISSUE #503: Include the name of the organization on all pages for the admin.
**Is your feature request related to a problem? Please describe.**
To prevent admins from losing track of where they are and the group they are making changes for.

- Refer to this video for context: https://youtu.be/ix3eSReJj2k

**Describe the solution you'd like**
For admins to keep track of where they are and the group they are making changes for, the organization name should show on every page.

**Approach to be followed**
- We want to minimize changes to the existing design. Keep the current design.
- Code coverage for all files editor must be 100%

### PR DESCRIPTION
**Pull request by anurag0006**
**What kind of change does this PR introduce?**
A  bugfix

**Issue Number:**
#503 
Fixes #

**Did you add tests for your changes?**
not required

**Snapshots/Videos:**
image

**If relevant, did you update the documentation?**
not req.

**Summary**
The pr closes #503 

**Does this PR introduce a breaking change?**
no

### CODE REVIEW

**Comment by palisadoes** [comment]
What does the screen look like after a Super Admin selects an individual organization and then returns to the main Super Admin screen? Does the Talawa logo return, because that would be the desired behavior?

**Comment by anurag0006** [comment]
@palisadoes , it does returns to talawa-logo, i made all the changes keeping that in mind...(screencast shows it)
[Screencast from 02-03-23 01:14:26 PM IST.webm](https://user-images.githubusercontent.com/107215525/222363812-42e3344c-606f-4ffd-8394-b043c75e988d.webm)

**Comment by anurag0006** [comment]
@palisadoes  , it does returns to talawa-logo, i made all the changes keeping that in mind...(screencast shows it)
[Screencast from 02-03-23 01:14:26 PM IST.webm](https://user-images.githubusercontent.com/107215525/222696122-8de03c0b-ad25-4fe0-a79e-d5e5980d7805.webm)

**Comment by palisadoes** [comment]
The tests are failing because the code coverage has declined. You will need to write tests for you changes.

**Pull request closed without merging**
