### PR TITLE
Better naming of results of fetched queries [Fixes #829]

### LINKED ISSUE #829: Refactor: Better naming for results of fetched queries
**Describe the bug**
Across the codebase, we are using multiple queries, whose results are fetched and then stored in variables named like `data-1`, `data-2` and `data-3` which makes it very difficult to understand what data has been fetched. These objects should be named according to the queries they are results of.

**To Reproduce**
NA

**Expected behavior**
Clear and descriptive names.

**Actual behavior**
Redundant and anti-pattern names.

**Screenshots**
NA

**Additional details**
NA

### PR DESCRIPTION
**Pull request by EshaanAgg**
**What kind of change does this PR introduce?**
Bugfix

**Issue Number:**
Fixes #829 

**Did you add tests for your changes?**
NA

**Snapshots/Videos:**
NA

**If relevant, did you update the documentation?**
NA

**Summary**
Renamed the `data` variables to move understandable names wherever multiple of them being consumed in the same component.

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by EshaanAgg** [comment]
Only the calender test is failing, which would be fixed by the PR #772.

**Comment by aashimawadhwa** [comment]
@EshaanAgg  please take a pull the failing test will pass .

**Comment by palisadoes** [comment]
@EshaanAgg merge with the upstream and commit those changes to this PR.

**Comment by EshaanAgg** [comment]
@palisadoes Done.

**Comment by EshaanAgg** [comment]
@palisadoes Can you please re-run the jobs? The `Continuous-Integration` job used to run the tests is passing, but the `Code Coverage` job is failing unexpectedly.

**Comment by palisadoes** [comment]
Please fix the failing test. I have noticed this intermittent failure before. Please troubleshoot it.

image

**Comment by EshaanAgg** [comment]
Sure @palisadoes. I will give it a shot.

**Comment by EshaanAgg** [comment]
@palisadoes I have fixed the intermittent failing test, too in this PR as a new commit :)

**Comment by palisadoes** [comment]
@EshaanAgg 

1. Please close this PR and reopen it.
2. The `pull-requests.yml` tests are not being run.  You can use the new PR to troubleshoot it.

**Comment by anshgoyalevil** [comment]
@EshaanAgg 

Try closing this PR and opening a new PR. The tests are running with the updated Workflow: https://github.com/anshgoyalevil/talawa-admin/actions/runs/4586698745/jobs/8099720649#logs

**Comment by EshaanAgg** [comment]
Thanks @anshgoyalevil. Will do.

**Pull request closed without merging**
