### PR TITLE
add eslint rules and plugins for "Apply Linting Only to Files Updated in git #1270"

### LINKED ISSUE #1270: Apply Linting Only to Files Updated in `git`
We need the ability to selectively adjust our linting rules so that they are eventually applied to our entire code base.

1. Linting rules are managed by the `.eslintrc.json` file.
1. They are applied to the entire code base at once.
1. If we change a rule from `warn` to `error` then every file in the code base will be checked and we have frequently seen our tests fail for dozens of files in hundreds of lines of code.

This is not acceptable.

We have been trying to more strictly lint the entire code base manually, but it has been very slow.

## At the user CLI
We need a way to edit `.eslintrc.json` with increasingly stricter linting rules in such a way that the tests are only applied to the changed files with every `git commit` and `git push` command. 

These `git` commands must fail if the linting fails.

## With Every Pull Request

We recently merged a Talawa-API pull request that checks each submitted file for linting compliance. This can be used as an example of how to run the test against individual files.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1242

You must make sure that this functionality applied for all PRs for this repository whenever the  `.eslintrc.json` file is updated

## Other

1. There may be ways to achieve the CLI goals by updating our existing Git Hooks
1. Your solution should preferably work within coding environments such as VScode
1. Please work with @anwersayeed and @tasneemkoushar on this issue
1. Related issues:
    - https://github.com/PalisadoesFoundation/talawa-api/issues/1548

## Screenshots

When complete, you should be able to convert all these  `.eslintrc.json` file lines containing `warn` to `error` and the tests will only be applied to the changed files in `git`

image

### PR DESCRIPTION
**Pull request by Shubh152**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1270 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
added eslint rules and plugins as requested in ISSUE#1270 and PR#1353

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Are the linting errors expected for only this PR and will work satisfactorily from the CLI?

**Comment by Shubh152** [comment]
No. These errors are due to the new rules added and will be there even for the CLI

**Review by palisadoes — CHANGES_REQUESTED** [review]
> No. These errors are due to the new rules added and will be there even for the CLI


That is not the goal as stated in the issue. We only want linting to be done against files committed in git. Now the next person submitting a PR will have to fix hundreds of linting errors for the remaining tests to pass.

Please contact the author of this PR for assistance
- https://github.com/PalisadoesFoundation/talawa-api/pull/1635

DO NOT CLOSE THIS PR.

Make any adjustments to your branch and do the follow up in this PR

**Comment by Shubh152** [comment]
The linting errors are due to the old scripts in the PR workflow. These scripts probably check linting for the whole of the repository and the errors arise due to new linting errors added. We will have to update the PR workflow to check for linting in committed files.
The changes I made will check staged files before linting in the CLI, not in the PR workflow. If you want I can try to change the PR workflow. Please guide @palisadoes .

**Comment by palisadoes** [comment]
Please make the changes so that it works as expected
The PR workflow scripts were supposed to cycle through each file submitted on the PR

You may have repurposed the script names so they are not failing

You'll need to restore the functionality, possibly with a new script name

**Comment by Shubh152** [comment]
From what I can see in the PR workflows, the linting is performed for the whole repo and not only files submitted in the PR. Do you want me to change the PR workflow to check only submitted files? @palisadoes

**Comment by Shubh152** [comment]
The errors we see are due to new rules like tsdoc/syntax, import/no-duplicates, and @typescript-eslint/no-explicit-any which were not fixed in old files. Its better we fix them somehow like advised in the PR you mentioned or remove these rules. Please advice @palisadoes

**Comment by palisadoes** [comment]
1. I know it will be a lot of work, but we need to fix them, preferably in this PR because that was the goal
2. Can you facilitate that? Or is there a better approach that will guarantee this will be completed faster?

**Comment by EshaanAgg** [comment]
@palisadoes We should revert the rules and open a new PR for each rule. It must be ensured that whenever any change to linting and formatting configurations are made, they must be added to the codebase completely in that PR itself. Bloating this PR with eslint changes is not wise IMO as then we are delaying this PR when it is ready. Also it would allow us to test these changes concerned with `staged-lint` in isolation.

**Comment by Shubh152** [comment]
@palisadoes 
The majority of errors are due to "no-explicit-any".

1. One easy approach is to convert all "any" types we have encountered until now to "unknown"  type using an inbuilt auto-fixer in eslint, We will be able to do it much faster without compromising much on the type safety as "unknown" is more typesafe than "any". After that, we can turn this auto-fixer off for future type-safety. I can do it if you want.

2. Otherwise we will have to change each file separately maybe directory-wise, which will be tedious but ensure more type safety.

Error due to rules other than "no-explicit-any" can be fixed by hand as they are not much in number. I can assist you with that.

**Comment by EshaanAgg** [comment]
@Shubh152 As a middle ground, we can do the following
- Fix the errors due to the other rules in this PR, expect `no-explicit-any`
- Turn the rule `no-explicit-any` off and open a new PR. I am advising the same as while using `unknown` is safer than `any`, it would still require the use of type guards to narrow the types safely, and that would make this PR longer and harder to review. I also believe if we are going to put in manhours into this job, we might as well do it with stricter types, and using unknown also when we actually can't be sure about the types of the values returned.

**Comment by Shubh152** [comment]
I agree with you @EshaanAgg . I'll be happy to help with that.

**Comment by palisadoes** [comment]
> I agree with you @EshaanAgg . I'll be happy to help with that. I will do as you advice and then open another PR for the planned changes .Should we @palisadoes ?

Yes. this is long overdue.

**Comment by palisadoes** [comment]
Would it be easier to split this up into multiple issues each handling a different linting rule? That way we could split up the workload.

**Comment by Shubh152** [comment]
> Would it be easier to split this up into multiple issues each handling a different linting rule? That way we could split up the workload.

There is only one linting rule "no-explicit-any" which is a problem. Rest I will fix in this PR. I think file or directory-wise approach will be good.

**Comment by palisadoes** [comment]
@NamitBhutani Could this approach be used in your case?

**Comment by palisadoes** [comment]
> > @NamitBhutani Could this approach be used in your case?
> 
> For the admin repo, there are a lot of other errors too, other than the ones related to "typescript-eslint/no-explicit-any". It is definitely possible to fix all but would require a lot of changes and reviews, especially for "@typescript-eslint/no-non-null-assertion".

What about the approach of linting only the committed files and those submitted in the PR? That will assist greatly.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@Shubh152 This has been merged. Create another PR for the remaining linting errors and use the same original issue as a reference.

**Pull request merged**
