### PR TITLE
feat: Redesigned Funds Screen for Talawa Admin Portal

### LINKED ISSUE #1717: ADMIN REDESIGN: redesign the Funds screen for the talawa Admin portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Funds screen for the talawa Admin portal

**Screenshots**
- Attaching the screenshots for reference.

Desired Result:
Screenshot 2024-03-12 at 5 03 53 PM

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
This PR introduces a redesign of the funds screen.

**Issue Number:**

Fixes #1717 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/a2511a3e-a2bd-4b76-b7f3-3b36c7c8c782

**If relevant, did you update the documentation?**

N/A

**Summary**

- Redesigned the funds screen as per the figma design.
- Except the button to archive/ unarchive funds in the update fund modal I have modified it to switch.
- Ensured create and delete funds are working properly.
- Modified the update handler to update the fundId for the fund.
- Ensured search by fund name also works by adding a new query.
- added a new query for fundbyOrganization to retrieve all the funds also to help to sort by name easily.
- Ensured the page is responsive for all screens.
- Covered all the modified code by tests.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar Please fix the code coverage tests.

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar Please fix the code coverage tests.

@Cioppolo14 Done :octocat:

**Comment by palisadoes** [comment]
This is dependent on your API PR correct?

**Comment by akhilender-bongirwar** [comment]
Yes @palisadoes

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the merge conflicts

**Comment by akhilender-bongirwar** [comment]
Actually I have merged my branch with upstream and resolved conflicts but git is not alllowing me to commit due to all eslint errors from the merged changes.

image

**Comment by akhilender-bongirwar** [comment]
This PR also solves the issue #1781 

image

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
