### PR TITLE
search bar functionality fixed

### PR DESCRIPTION
**Pull request by rv602**
### What kind of change does this PR introduce?
The functionality of the search bar was broken, if some text is typed in the search bar then it shows organisations matching with that text, but if the text is cleared from the search bar, then no organisations are displayed, instead of displaying all organisations.

### Did you add tests for your changes?
No
Since solving this issue only dealt with modifying the ```onChange``` function of the search bar, I didn’t add any additional tests.

### Video of the desired functionality working : -

https://user-images.githubusercontent.com/92572013/215123923-d6591131-d10f-44ad-823b-adb27f217b66.mp4

### If relevant, did you update the documentation?
No

### Does this PR introduce a breaking change?
No

### Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please try to get the code coverage up to 100% for the files you have changed, currently it is at 96%

**Comment by rv602** [comment]
@palisadoes @noman2002 codecov report isn’t being generated for my latest commit 😅

**Comment by noman2002** [comment]
@rv602 now its generated, please have a look at it. And also if the codecov report is not generated you can check it locally on you machine.

**Comment by rv602** [comment]
okay I'll do that. Thank you.

**Comment by palisadoes** [comment]
@Kevoniat please review

**Review by Kevoniat — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
