### PR TITLE
Implement GraphQL Error Handling: Resolver user

### PR DESCRIPTION
**Pull request by Sivam2313**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes [This issue](https://github.com/PalisadoesFoundation/talawa-api/issues/1474) from talawa-api

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

taskerror

**If relevant, did you update the documentation?**

**Summary**

Added support for the new schemas for User resolver and added error handling in the required components.

**Does this PR introduce a breaking change?**

Changes the schema for User resolver

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
We had to revert a PR that was causing tests to fail incorrectly. Please submit a minor commit to trigger an update of the GitHub workflow

**Comment by EshaanAgg** [comment]
@Sivam2313 Please fix the failing test and then request a review.

**Comment by Sivam2313** [comment]
I think one of the tests is failing due to changes made in the schema

**Comment by EshaanAgg** [comment]
It's showing that it can't validate the documents, which is an error I have never heard of before. Any explanations as to what might be happening?

**Comment by palisadoes** [comment]
@xoldyckk could you comment on this? It seems related to the API

**Comment by Sivam2313** [comment]
> It's showing that it can't validate the documents, which is an error I have never heard of before. Any explanations as to what might be happening?

I think its because the schemas in graphql in this pr does not match the schemas in the api.

**Comment by xoldyckk** [comment]
@Sivam2313 It seems the `UserNotFoundError` type neither exists on the client nor on the server side schema. Anyways like i had suggested, get rid of it, simply handle errors the old way.

**Pull request closed without merging**
