### PR TITLE
test: SecuredRouteForUser component 100% Test Coverage and fixed uncovered lines

### LINKED ISSUE #1037: Code Coverage: Create tests for src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by duplixx**
## Description

This PR aims to achieve 100% test coverage for the `SecuredRouteForUser` component by adding tests that cover various scenarios.

## Changes Made

- Added tests to ensure the `SecuredRouteForUser` component behaves as expected when the user is not logged in.
- Verified that all tests pass successfully and that the component functions as intended.

## Issue Number:
Issue Number:

Fixes #1037 

## Did you add tests for your changes?
Yes

## Test Coverage

- [x] Covered scenarios where the user is not logged in.
- [x] Covered scenarios where the user is logged in.

## Checklist

- [x] I have tested these changes thoroughly.
- [x] All existing tests have passed.
- [x] I have added new tests that cover the changes in this PR.

## Snapshots/Videos:
Before:
image

After:
image
image

## If relevant, did you update the documentation?
No

## Summary
With these new tests, I now have 100% test coverage, and there are no more uncovered lines. The  the `SecuredRouteForUser` component component is thoroughly tested for different size scenarios, and all tests pass successfully.

## Does this PR introduce a breaking change?
No

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@duplixx you need to fix the linting errors for this PR.

**Comment by duplixx** [comment]
hey @aashimawadhwa @palisadoes I have fixed linting errors

**Comment by palisadoes** [comment]
@Ayush0Chaudhary will be managing the PR process.

**Comment by Ayush0Chaudhary** [comment]
> ## [Codecov](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1048?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> > Merging [#1048](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1048?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) (19a7f97) into [develop](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/commit/09803268d9919d0b591094ccff873a2d094d5c3b?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) (0980326) will **increase** coverage by `0.13%`.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop    #1048      +/-   ##
> ===========================================
> + Coverage    93.66%   93.79%   +0.13%     
> ===========================================
>   Files          129      129              
>   Lines         3014     3014              
>   Branches       837      837              
> ===========================================
> + Hits          2823     2827       +4     
> + Misses         181      177       -4     
>   Partials        10       10              
> ```
> 
> 
> [see 1 file with indirect coverage changes](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1048/indirect-changes?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)
> 
> :mega: Codecov offers a browser extension for seamless coverage viewing on GitHub. Try it in [Chrome](https://chrome.google.com/webstore/detail/codecov/gedikamndpbemklijjkncpnolildpbgo) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/codecov/) today!
> 

You still have 4 misses, can you write the test from them?

**Comment by duplixx** [comment]
Okay i'll be updating that...

**Comment by duplixx** [comment]
Hey @Ayush0Chaudhary  @palisadoes ,
in Codecov, I'm seeing a 100% coverage for our file. I suspect we might have shared the entire branch coverage. Could you take a moment to check and confirm?
image

**Comment by palisadoes** [comment]
Thanks for your work.

1. Please fix the failing tests
1. The test coverage fails for two reasons. 
    1. The patch does not meet the code coverage level
    2. The branch does not meet the code coverage level
 
We realize that the branch hasn't reached the desired coverage which is why we created the per file coverage issues. The patch needs to meet the desired coverage level.

**Comment by duplixx** [comment]
hey please check now, I have fixed workflow errors @Ayush0Chaudhary @palisadoes

**Comment by palisadoes** [comment]
Please fix the failing tests. You will need to lint your code properly.

**Comment by palisadoes** [comment]
1. Please add the `prettier` linter to your IDE to make it automatically lint on saving your files. 
2. Please fix the failing lint tests

**Comment by duplixx** [comment]
Thanks for the tips! 🙌 I've followed your guidance, fixed the linting error, and would appreciate a recheck.

**Comment by noman2002** [comment]
@duplixx Pull the latest code from develop.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
