### PR TITLE
Added Implement an inactivity timer

### LINKED ISSUE #899: Automatic logout
**Describe the bug**
The admin automatically logouts in some time

**To Reproduce**

1. login to the admin
2. leave for little time
3. the admin will logout on it's own

**Expected behavior**
Normally the website should remain logged in until admin logout , or until no event is detected for a decided time.

**Actual behavior**
Automatic logout

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**
Fixes #899 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

[www_screencapture_com_2023-4-29_01_18.webm](https://user-images.githubusercontent.com/73706697/235245870-f91442b3-b55b-4b37-a05b-4070bc3da13c.webm)

**Summary**
Implementing automatic logout  after inactivity of 1 hour with an popup to notify the user

**Does this PR introduce a breaking change?**
No

**Other information**
NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@palisadoes  the tests are failing in calendar I will look into them and update this PR

**Comment by palisadoes** [comment]
@aashimawadhwa 

1. This failing test has caused us to merge other PRs that have failed on the push.
2. Please be more careful with your testing regime this has happened frequently before with your calendar based updates.

**Comment by aashimawadhwa** [comment]
@palisadoes  I have implemented the calendar for the first time and wrote the test for the same for the first time.
this thing is new to me and i am learning testing as of now. I am trying to fix this, it's just this 1 test which is failing and I am working on it.

I apologize for the inconvenience happened in past, this will not happen again in future, and i will fix this failing test asap.

**Comment by anshgoyalevil** [comment]
@aashimawadhwa 

Will this timer feature work globally? Since, the code changes in this PR are limited to ```OrgList.tsx```?

**Comment by aashimawadhwa** [comment]
I realized this now, I will make a component and render it on all the screens. @anshgoyalevil

**Comment by anshgoyalevil** [comment]
You may add it in Navbar component since it is rendered on every screen.

**Comment by aashimawadhwa** [comment]
@palisadoes sir,
for failing test of calendar can you open an issue I will solve that on priority.?

**Comment by palisadoes** [comment]
Please open the issue and we'll assign it to you.

**Comment by palisadoes** [comment]
Should this be closed and added to the redesign project? @rishav-jha-mech

**Review by ttaylor92 — APPROVED** [review]

**Comment by palisadoes** [comment]
@aashimawadhwa Please update the tests if applicable and fix the conflicting file.

**Comment by aashimawadhwa** [comment]
Sir this feature needs to be redone a little I thought @rishav-jha-mech  will take care of this.

If not I'll look into it ASAP. 
@palisadoes

**Comment by palisadoes** [comment]
@aashimawadhwa,  please coordinate with @rishav-jha-mech and close this PR and the associated issue if necessary

**Comment by palisadoes** [comment]
Closing. This has been open too long.

**Pull request closed without merging**
