### PR TITLE
Enhancement: React bootstrap alternatives in place of default prompts

### LINKED ISSUE #147: [Enhancement] Replace default browser confirmation prompts with React Bootstrap prompts
**Is your feature request related to a problem? Please describe.**
Currently browser native prompts are being used for confirming user input such as `window.confirm`, `window.alert` and `window.prompt`

**Describe the solution you'd like**
These should be replaced with React Bootstrap alternatives to improve the consistency in the UI of the application, whilst also improving the user experience.

Additionally the appropriate toast notifications should be utilized whenever an action is performed to ensure the user that the action was successful or unsuccessful.

**Approach to be followed (optional)**
For the confirmation prompts the approach outlined in [this article](https://morioh.com/p/d516ea000e8d) should be utilized.

For the toast notifications, react bootstrap has a native toast component which may be found [here](https://react-bootstrap.github.io/components/toasts/)

### PR DESCRIPTION
**Pull request by karan2704**
**What kind of change does this PR introduce?**

UI Enhancement. It replaces the default browser prompts (window.alert, window.confirm etc.) with their react bootstrap alternatives. React-toastify used for toast notifications.

**Issue Number:**

Fixes #147 

**Did you add tests for your changes?**

Not required

**Snapshots/Videos:**
Capture
Capture1

Capture2

**If relevant, did you update the documentation?**

Not required

**Summary**

React bootstrap prompts were used for better user experience and keeping consistency in the UI.

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by yasharth291** [comment]
why the test are not required? @karan2704

**Comment by yasharth291** [comment]
and don't add ```package-lock.json``` this file here

**Comment by karan2704** [comment]
I assumed tests would not be required on UI fixes but alright I'll write the tests and request another PR soon. Also, can you explain what this error (in the pic ) means?
Capture

**Comment by palisadoes** [comment]
@karan2704  Please sync your repo with the latest code and update your PR. The failing Greeting Message should now be fixed.

**Comment by karan2704** [comment]
Alright... I'll do that

**Comment by yasharth291** [comment]
@karan2704  and don't add package-lock.json this file here
I have told you before as well and I don't know why the test is not required here

**Review by yasharth291 — CHANGES_REQUESTED** [review]
do not add package-lock.json as the project is yarn run and secondly write some test to test the credibility of the toast component

**Comment by karan2704** [comment]
Sorry about the package-lock.json thing it was mentioned in .gitignore but still got pushed.... Although I have removed it now.
About the tests for toast I have written (in pic below) and I have referred this [resource](https://javascript.plainenglish.io/testing-with-react-hook-form-and-react-toastify-9dc248465c2c) for the same but it seems to fail. I have also tried --> getByText('alert text') but even that does not seem to work. Can someone help me out with this?


Capture

**Review by yasharth291 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@yasharth291 Should we revert this PR as the tests are failing? @karan2704 Can resubmit his changes after that.

**Comment by palisadoes** [comment]
Reverting as requested by @karan2704 in:
- https://github.com/PalisadoesFoundation/talawa-admin/pull/190

**Pull request merged**
