### PR TITLE
fixed event checkboxes to update

### LINKED ISSUE #658: Bug Report : On Adding Event checkbox of "Recurring Event", "Is Registrable?" is not working
**Describe the bug**
On Adding Event checkbox of "Recurring Event", "Is Registrable?" is not working. On click in checkbox still on edit it is not checked.

**To Reproduce**

1. Login the website and create organization.
2. Click on manage organization.
3. Go to event section and add event.
4. On filling event details check "Recurring Event", "Is Registrable?" box and create event.

**Expected behavior**
On Adding Event checkbox of "Recurring Event", "Is Registrable?" it should work.

**Actual behavior**

https://user-images.githubusercontent.com/86047367/224483841-fb5e8c00-249d-4b52-9813-e7341ac876d4.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akankshat05**
**What kind of change does this PR introduce?**

Bugfix
**Issue Number:**

Fixes #658 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
Before :

https://user-images.githubusercontent.com/72144454/225915642-7ea558a9-f306-4157-8519-21a3dfd8e63c.mp4

After:

https://user-images.githubusercontent.com/72144454/225917745-e9bcd1b9-c473-4a62-9632-634b31b24ba7.mp4

**If relevant, did you update the documentation?**

No
**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please add videos of the before and after functionality

**Comment by noman2002** [comment]
@akankshat05 Please fix the failing tests.

**Comment by akankshat05** [comment]
I will make the changes.

**Comment by akankshat05** [comment]
> Please add videos of the before and after functionality

I have added them.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by akankshat05** [comment]
> Please fix the failing tests
@palisadoes @noman2002 
225903687-f1f72e42-2d56-4a9b-9bf3-e857cbd4e8fc
I have taken the latest pull and on develop branch and also on this PR after running all tests, I am getting the above error, when I did not edit anything in LandingPage. And, sometimes when I run all tests, all of them pass. Sometimes it is displaying a message "A worker process has failed to exit gracefully and has been force exited." and all test pass. May I please know how to proceed now?

**Comment by akankshat05** [comment]
@palisadoes @noman2002 At times all tests are passing
testpass

**Review by noman2002 — APPROVED** [review]
Looks good to me.

**Pull request merged**
