### PR TITLE
Block/Unblock functionality for only members of the organization

### LINKED ISSUE #507: Users that are not member of the organisation should not be fetched for any manage organisation feature
**Is your feature request related to a problem? Please describe.**
 In block/unblock page of the Talawa-admin portal, there are users that are no longer the part of the organisation but still present on the page and there is block button present for them, which will surely give you error `'Member Not Found'`. Need to change the query for fetching the member information in block/unblock, remove member features so that only the members belonging to organisations can have the option for those features.
**Describe the solution you'd like**
According to me in there is` USER_LIST` query in block/unblock page that fetches the user data as whole irrespective of the user being member of the organisation that is need to be replaced `MEMBER_LIST` query that fetches the members for the organisation wherever this kind of issue is there.
Change is required in this code block of block/unblock page
```
const {
    data,
    loading: spammers_loading,
    error,
    refetch,
  } = useQuery(USER_LIST);
```
**Describe alternatives you've considered**
Any alternative approach suggestion is welcomed.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Manoramsharma**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #507 

**Did you add tests for your changes?**

Yes there already exists a test for the changed file.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Manoramsharma Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

The overall code coverage drops below the target threshold of the repository
Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by Manoramsharma** [comment]
@noman2002 can you have review for this PR?

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Manoramsharma** [comment]
Screenshot 2023-03-17 at 2 32 04 PM
Previously all users which have not even joined the organization where fetched here now only the users/members of the particular organisation are fetched that is the recommended behaviour.

**Comment by Manoramsharma** [comment]
@noman2002 I have resolved the failing test issue I was talking about so kindly review and approve the changes.

**Comment by Manoramsharma** [comment]
Screenshot 2023-03-17 at 3 18 54 PM
100% test coverage for the file BlockUser.tsx and overall coverage of 93.7%

**Review by noman2002 — APPROVED** [review]
Looks good.

**Pull request merged**
