### PR TITLE
pagination and placeholder 2117

### PR DESCRIPTION
**Pull request by prayanshchh**
**What kind of change does this PR introduce?**

**Issue Number:**
#2117

Fixes #

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
Screenshot from 2024-09-22 17-23-26
Screenshot from 2024-09-22 17-23-02

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
Its a bugfix

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Added new translation entries for searching organizations in English, French, Hindi, Spanish, and Chinese.
	- Updated the placeholder text in the search input to reflect searching for organizations.

- **Bug Fixes**
	- Removed the `-1` option from the pagination dropdown, simplifying the available rows per page to `5`, `10`, and `30`.

- **Tests**
	- Added new test cases to verify pagination options and search input placeholder.

### CODE REVIEW

**Comment by prayanshchh** [comment]
Do i have to add this for multiple languages?

**Comment by Cioppolo14** [comment]
@prayanshchh Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.  Please address the code rabbit comments and fix the failed checks.

**Comment by prayanshchh** [comment]
The first comment and the linting errors have been fixed sir

**Comment by prayanshchh** [comment]
after this commit, it should pass all the tests

**Comment by prayanshchh** [comment]
'searchOrganizations' translation key has been added in all translation files in public/locales/ directory.
 
 can I resolve the conversation, as I have implemented the changes requested

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
