### PR TITLE
Fix/postsby org

### LINKED ISSUE #1626: Change of post by organisation query
**Describe the bug**
Post by organisation query need to be changed according to this PR [#1722 ](https://github.com/PalisadoesFoundation/talawa-api/pull/1722)

**Additional details**
As PR [#1722 ](https://github.com/PalisadoesFoundation/talawa-api/pull/1722)changed the implementation of the PostByOrganization query,this need to be changed in admin and mobile repo as soon as possible 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AVtheking**
**What kind of change does this PR introduce?**
Replace the postByConnectionQuery with the newly created in the api repo

**Issue Number:**

Fixes #1626 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/132201033/0915207e-cd32-41d5-9267-87edf9e6bcbe

It will require this  [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1920)

### CODE REVIEW

**Comment by AVtheking** [comment]
@palisadoes to make it work correctly api repo would require couple of changes 
I am creating an issue there ,I have solution for them ready

**Comment by palisadoes** [comment]
1. Please fix the conflicting files
2. Add a reference link to the API PR that will need to be merged first

**Comment by palisadoes** [comment]
Is this ready for review?

**Comment by AVtheking** [comment]
Yes ,I would need to increase code coverage that I will do, right now traveling

**Comment by palisadoes** [comment]
1. I'm going to have to merge this as is. Too many people are having difficulties.
2. Please open a separate PR to update the tests

**Comment by AVtheking** [comment]
sir it would require this [PR](https://github.com/PalisadoesFoundation/talawa-api/pull/1920)

**Comment by palisadoes** [comment]
1. Yes, but now others can manage their orgs and work on non post issues. This is important to get work completed over the weekend.
2. Please get the code coverage up in the API PR and open a new one for this issue to get the test code coverage better

**Comment by AVtheking** [comment]
but it would throw error when someone will fetch the post with image uploaded
I have added tests in the API PR

**Comment by palisadoes** [comment]
That's true, but we needed others to work on non-post areas of the code base, and if they couldn't manage an organization, then no work could be done. It wasn't ideal, but we had to make a quick decision. 2-3 days of inactivity at this time is really inconvenient to other contributors

**Comment by palisadoes** [comment]
In the interest of speed, I'm going to open separate issues for the outstanding test cases for this PR for others to work on.

**Pull request merged**
