### PR TITLE
Restore password check functionality

### LINKED ISSUE #1173: User and Admin toggle on Login and Registration Screen
**Is your feature request related to a problem? Please describe.**
We need an interface to login to user portal provided by talawa which can be accessed by this url `http://localhost:3001/user` when you run talawa Admin and talawa API on your local machine

**Describe the solution you'd like**:

1. The login and registration form should have a toggle functionality.
2. This toggle should allow users to switch between user and admin roles seamlessly.
3. Users can select their role preference using a toggle switch to access the respective login or registration form.

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/5d03cfd1-c0f8-40c8-97d2-6d6180569053

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
Fixes #1173 

**Does this PR introduce a breaking change?**

No

**Summary**

Restores password check functionality.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by meetulr** [comment]
@palisadoes This one fixes the error that was merged with #1371.

**Comment by palisadoes** [comment]
It's this the fix for the previous PR?

**Comment by meetulr** [comment]
> It's this the fix for the previous PR?

Yes, and I'll soon fix the failing test.

**Comment by meetulr** [comment]
> It's this the fix for the previous PR?

Actually.. in all the haste of merging, I've made an error in resolving conflicts with the most recent merge #1376 then.
I was about to correct that in my previous pr but it got merged before I could.
Again... I apologize for the confusion and inconvenience.

**Review by rishav-jha-mech — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
