### PR TITLE
[ userTypeFix ] Updated Queries for adminApproved

### LINKED ISSUE #1693: [userTypeFix] Update queries for new `adminApproved` functionality
**Is your feature request related to a problem? Please describe.**
Changes to queries have to be made in Admin repo corresponding to https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Describe the solution you'd like**
Change GraphQl Queries

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Make changes only in the "develop-userType" branch

**Additional context**
follow this issue's description -> https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Rajeshpatel07**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1693 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
In the following Pull Request, I have made updates to the queries related to adminApproved to ensure proper functionality.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Rajeshpatel07** [comment]
@Cioppolo14 
I have fixed the conflicting file and all the test cases are passing.
Talawa Tests

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by palisadoes** [comment]
Please add a video showing that this functionality now works.

**Comment by Rajeshpatel07** [comment]
Here is the working video
[Talawa admin.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/c26fd5d4-d2ec-4af6-921b-6a0dc34c65ba)

**Comment by palisadoes** [comment]
We need to close this. The discussion here states that this may be unnecessary
- https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1711717178931399

**Pull request closed without merging**
