### PR TITLE
created a reusable postNotFound Component with responsive UI

### PR DESCRIPTION
**Pull request by saadabban76**
**What kind of change does this PR introduce?**
Create a reusable PostNotFound Component that will render a good "Post Not found" card component when the search query is null.

feature
Fixes ##698

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://user-images.githubusercontent.com/115649011/225366754-efba3bf0-bb99-450e-84c7-f62348803df7.mp4

**If relevant, did you update the documentation?**
Not required

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by saadabban76** [comment]
Hi @noman2002, hope you are doing good, can you please review this PR ?

**Comment by adi-uchiha** [comment]
Why closed ?
@saadabban76

**Comment by saadabban76** [comment]
> Why closed ? @saadabban76

Ekene asked me not to open a PR before assignment, so I had to close the PR 😅

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please use another message other than 404. This implies there is a site related error, when the search works, but nothing is found. 

We need an error methodology that will be understandable in all languages, hence a text message for search will be much better. Please apply a text message with the appropriate translations.

**Comment by saadabban76** [comment]
> Please use another message other than 404. This implies there is a site related error, when the search works, but nothing is found.
> 
> We need an error methodology that will be understandable in all languages, hence a text message for search will be much better. Please apply a text message with the appropriate translations.

what kind of Image to use other than 404, is it ok to use image with a animated character in it ?

**Comment by saadabban76** [comment]
> > > Please use another message other than 404. This implies there is a site related error, when the search works, but nothing is found.
> > > We need an error methodology that will be understandable in all languages, hence a text message for search will be much better. Please apply a text message with the appropriate translations.
> > 
> > 
> > what kind of Image to use other than 404, is it ok to use image with a animated character in it ?
> 
> Provide feedback as text not as an image. Make sure the text is translatable into the supported languages.

Got It 👍🏼 , I'll commit this changes ASAP !

**Comment by palisadoes** [comment]
Take this PR into consideration

- https://github.com/PalisadoesFoundation/talawa-admin/pull/725

Please fix the failing tests

**Comment by saadabban76** [comment]
I've added translation to the component and made changes in the UI as you asked me to 👍🏼  @palisadoes

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by palisadoes — APPROVED** [review]

**Review by Kevoniat — APPROVED** [review]

**Comment by saadabban76** [comment]
@palisadoes Sir, how do I add points label to the issue, as the issue with points label will be considered for evaluating Gsoc Proposals or the points issues are very limited ?

**Pull request merged**
