### PR TITLE
removed unused setup and docker files/config

### LINKED ISSUE #407: remove setup/docker files and config
**Is your feature request related to a problem? Please describe.**
Setup and docker files are no longer used so they should be removed.

**Describe the solution you'd like**
All files/folders/config related to setup and docker should be removed.

**Describe alternatives you've considered**
-

**Approach to be followed (optional)**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by xoldyckk**
**What kind of change does this PR introduce?**

refactoring

**Issue Number:**

Fixes #407

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

-

**If relevant, did you update the documentation?**

-

**Summary**

Removed the setup and docker files and related config because they weren't being used. Renamed `REACT_APP_TALAWA_URL` to `REACT_APP_TALAWA_API_URL`.

**Does this PR introduce a breaking change?**

-

**Other information**

-

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@xoldyckk Please also create an issue for this and assign it to yourself. Update the PR with this information too. Let's stick with the process.

**Comment by xoldyckk** [comment]
> @xoldyckk The linting is failing. Please fix

The eslint package doesn't even exist in the project.

**Comment by xoldyckk** [comment]
@palisadoes the gotchas are related to yarn versions it seems. I just tried yarn@1.22.19 and eslint works magically out of no where even though it's not installed.

**Comment by palisadoes** [comment]
I think we are using eslint only to lint the code prior to submitting the PR. So it's still needed.

**Comment by palisadoes** [comment]
@xoldyckk Please fix the conflicting files

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
