### PR TITLE
Refactored CSS changes for src/screens/EventManagement

### PR DESCRIPTION
**Pull request by rahulch07**
**What kind of change does this PR introduce?**

Featrure/Refactoring

Fixes:
#2504 
#2512 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

N/A

**If relevant, did you update the documentation?**

N/A

**Summary**

This PR refactors the CSS structure for the EventManagement screens and related components by consolidating all local CSS files from subdirectories into a single global app.module.css file. The redundant local CSS files were removed, and all component references were updated to use the global file, ensuring a centralized and consistent styling approach across the application.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
 
Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for various components through a centralized CSS file.
	- Introduced new CSS variables for responsive design breakpoints.
	- Improved responsiveness and layout for header and button sections in the Organization Action Items component.

- **Bug Fixes**
	- Updated error handling in the ItemDeleteModal for clearer error messages.

- **Chores**
	- Removed outdated CSS modules for Event Dashboard, Event Agenda Items, Event Attendance, and Organization Action Items.
	- Consolidated styles into a global stylesheet for better management.

- **Tests**
	- Improved test assertions for the OrganizationScreen component related to drawer functionality and window resizing.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@rahulch07 Please fix the failed tests.

**Comment by palisadoes** [comment]
Please fix the failing tests and ensure CodeRabbit.ai approves your changes

**Comment by palisadoes** [comment]
1. Please fix the failing tests. 
    1. You may have to fix a test that is not related to this PR as in some rare cases we merge faulty test code. If this is the case, fix the test in this PR. Do not open another issue.
1. Please make sure that CodeRabbit.ai approves the PR.
1. Please fix any conflicting files

**Comment by rahulch07** [comment]
> 1. Please fix the failing tests.
>    
>    1. You may have to fix a test that is not related to this PR as in some rare cases we merge faulty test code. If this is the case, fix the test in this PR. Do not open another issue.
> 2. Please make sure that CodeRabbit.ai approves the PR.
> 3. Please fix any conflicting files

Fixed all the failing test cases and approved by Coderabbit.ai. 👍

**Comment by palisadoes** [comment]
PTAL @varshith257 @AVtheking

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
1. Ensure that CodeRabbit.ai approves your work
1. Please fix any conflicting files

**Comment by AVtheking** [comment]
@rahulch07  our motive is to have a single css file across the codebase so that we can reuse styles. Do not create any new css files try to integrate them in our main css file.Also why are there lots of unrelated changes? Please try to only make changes related to the issue you are solving this make easier for the reviewer to review.

**Comment by rahulch07** [comment]
@palisadoes @AVtheking resolved all the conflicting files and removed the unnecessary changes. Had to force push thats why not able to resolve conversations.
image

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by palisadoes** [comment]
Please make coderabbit.ai approve your PR

**Comment by rahulch07** [comment]
@palisadoes unable to get approval from coderabbit.ai because the conversation in not resolving. Any suggestions?
image

**Comment by palisadoes** [comment]
@codrabbitai full review

**Comment by palisadoes** [comment]
I got it to trigger its new required changes.

**Comment by palisadoes** [comment]
@codrabbitai review

**Comment by rahulch07** [comment]
should I make a new PR?

**Comment by palisadoes** [comment]
Yes.

**Comment by palisadoes** [comment]
It gave its review

**Pull request closed without merging**
