### PR TITLE
pagination and placeholder fix - 2117

### PR DESCRIPTION
**Pull request by prayanshchh**
**What kind of change does this PR introduce?**
Placeholder and Pagination bug fix

**Issue Number:**
#2117
Fixes #

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
image
image

**If relevant, did you update the documentation?**
No

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Added a new translation key for searching organizations, enhancing localization.
	- Updated the placeholder text in the search input field to reflect organization search instead of user search.

- **Bug Fixes**
	- Removed the unlimited rows option from the pagination settings, streamlining row display options.

- **Tests**
	- Introduced new test cases to ensure correct pagination options and placeholder text in the search input.

### CODE REVIEW

**Comment by prayanshchh** [comment]
@Cioppolo14  can you please review this?

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
- Your PR has too many unnecessary files that don’t relate to your issue. 
- Closing

**Comment by prayanshchh** [comment]
I was actually fixing that only, i will create new pr sir

**Pull request closed without merging**
