### PR TITLE
Revamp and Modular Event Screen

### PR DESCRIPTION
**Pull request by duplixx**
**What kind of change does this PR introduce?**

**Issue Number:** #1611 

Fixes #

**Did you add tests for your changes?**

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/b82d3332-ee95-4d7b-8518-8dfdec823e32

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Huy1996** [comment]
@duplixx Please fix the failing test.

**Comment by duplixx** [comment]
@aashimawadhwa @palisadoes: I have added eslint-disable for future use of functions in event calendar UI. @wasifkareem is working on revamping EventCalender UI .

**Comment by duplixx** [comment]
@wasifkareem, I am removing unused functions from my PR because you will be adding those functions in your revamped calendar.

**Comment by Cioppolo14** [comment]
@duplixx Please fix the failing test application check.

**Comment by wasifkareem** [comment]
> @wasifkareem, I am removing unused functions from my PR because you will be adding those functions in your revamped calendar.

sure @duplixx , I'm working on the calendar, we have to add holidays, let me know if you have any ideas for it, I'm thinking of using [date-holiday-npm](https://www.npmjs.com/package/date-holidays) . let me know if you have better suggestions.

**Comment by duplixx** [comment]
> > @wasifkareem, I am removing unused functions from my PR because you will be adding those functions in your revamped calendar.
> 
> sure @duplixx , I'm working on the calendar, we have to add holidays, let me know if you have any ideas for it, I'm thinking of using [date-holiday-npm](https://www.npmjs.com/package/date-holidays) . let me know if you have better suggestions.

I see, are we considering country-specific holidays? If yes, then we can go with this package; otherwise, you can map the international holidays in an array just like days and months are added.

**Comment by duplixx** [comment]
image
@Cioppolo14, I am facing failed tests only in the calendar components. If I fix them and this PR gets merged, then @wasifkareem will have to rework on the removed and changed code. How should we proceed further? @palisadoes @aashimawadhwa

**Comment by wasifkareem** [comment]
> > > @wasifkareem, I am removing unused functions from my PR because you will be adding those functions in your revamped calendar.
> > 
> > 
> > sure @duplixx , I'm working on the calendar, we have to add holidays, let me know if you have any ideas for it, I'm thinking of using [date-holiday-npm](https://www.npmjs.com/package/date-holidays) . let me know if you have better suggestions.
> 
> I see, are we considering country-specific holidays? If yes, then we can go with this package; otherwise, you can map the international holidays in an array just like days and months are added.

we don't know yet, I've asked Aashima in my issue thread. will look into it.

**Comment by duplixx** [comment]
> Hi @duplixx , the eventdata array from admin side done not have creator object, I'm using creator id to see if the event creator is admin or not. can you please use the same query that is used on the user side so that we can have creator info available
> 
> admin side eventdata object Screenshot from 2024-03-11 13-14-39
> 
> user side eventdata obj image


@wasifkareem In my part I am not using integration anywhere there won't be issue by your approach

**Comment by Olatade** [comment]
Hi @duplixx, is this ready for PR, please fix the failing tests.

**Comment by duplixx** [comment]
@Olatade yeah now its ready

**Comment by Huy1996** [comment]
@duplixx Could you fix the failing codecov check?

**Comment by duplixx** [comment]
@Huy1996 I've made changes that will significantly increase coverage when @wasifkareem submits a pull request for the subtasks of this PR. The event search functionality isn't being developed at this time, so some of the code coverage won't be addressed.

**Comment by Cioppolo14** [comment]
@Kevoniat @anwersayeed Can you review this PR?

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
Please fix the failing tests.

**Comment by duplixx** [comment]
@palisadoes all tests passes ⚡️

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
