### PR TITLE
feature: search on enter key press

### LINKED ISSUE #1174: Improvement in the SearchBars throughout Talawa Admin
**Is your feature request related to a problem? Please describe.**
currently talawa have Dynamic Search Functionality .

**Describe the solution you'd like**
we need to implement search only after the user presses the "Enter" key, it is typically referred to as a "submit on enter" search.

**Additional context**
Implement this on all the search bars across talawa .

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by racky7**
**What kind of change does this PR introduce?**
feature

**Issue Number:**

Fixes #1174 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Implemented search only after the user presses the 'Enter' key across all the search bars on Talawa.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Review by beingnoble03 — CHANGES_REQUESTED** [review]
@racky7 I don't see any point of having `utils/debounce.ts` if it's no longer in use anywhere in the codebase. Please check if we are using it, and remove if it's not being used.

**Comment by beingnoble03** [comment]
@racky7 did you check if the utility wasn't being used anywhere in the codebase?

**Comment by racky7** [comment]
@beingnoble03 Yes I had checked.

**Review by beingnoble03 — DISMISSED** [review]

**Comment by beingnoble03** [comment]
@racky7 please fix the linting errors

**Comment by racky7** [comment]
@beingnoble03 I've examined the issue and found numerous occurrences of the 'any' type in the app. The .eslintrc.json configuration is set to trigger an error upon encountering 'any'.

**Comment by palisadoes** [comment]
@tasneemkoushar Please take a look at the failing GitHub action.

**Comment by palisadoes** [comment]
1. The linting config file has been reverted. Please merge with your upstream and make an updating commit.
2. Please fix the conflicting file

**Review by beingnoble03 — APPROVED** [review]
Looks good.

**Review by aashimawadhwa — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
