### PR TITLE
fix: improve code coverage for src/components/Advertisements/core/Adv…

### LINKED ISSUE #1133: Code Coverage: Create tests for src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
**What kind of change does this PR introduce?**

Added code coverage for src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx

**Issue Number:**

Fixes #1133

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

 No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
What is the coverage of your test file ?

**Comment by meetulr** [comment]
> What is the coverage of your test file ?

The coverage of src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.tsx is now 100%, after i made the necessary changes. I didn't change any other component or it's test file.

**Comment by palisadoes** [comment]
@SiddheshKukade @DMills27 Please review. This PR will get the repo up to 95% code coverage.

**Review by SiddheshKukade — APPROVED** [review]

**Comment by SiddheshKukade** [comment]
Looks good. Can be merged 👍🏻

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
