### PR TITLE
Fix incorrect toast Notification.

### LINKED ISSUE #1019: Use of incorrect react-toast notification.
**Describe the bug**
There are a lot of place where promise messages is shown as warnings. I think that should be removed with promise messages given by react-toastify. 
Like in this image adding the attendee is shown with warning symbol:
Screenshot 2023-11-01 002603
Instead of that it should be like this as shown in the video with the text "Adding the attendee." and when it is added it should be "Attendee added"

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/6b8316db-0da2-4e7d-b87e-047a09b631c8

There are a lot of places where wrong react-toast are used. 
image

**Expected behavior**
A clear and correct react-toastify message should be used in all the places.

**Actual behavior**
Wrong message patterns are there in lot of places.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by skbhagat0502**
**What kind of change does this PR introduce?**

A bug fix.

**Issue Number:**

Fixes #1019 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Previously, promise notifications were shown with warnings. This was used all around the website which was not making a good sense and feel like something gone wrong. Now I changed all the promise notifications to `toast promise` from warnings.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by skbhagat0502** [comment]
@kb-0311 @rishav-jha-mech @beingnoble03 I am stuck here at this `EventRegistrantsModal.tsx`.  I am not able to figure out the issue in my code. I am sure that the test have been written correctly. There is some issue with the code only. Please help me what need to be changed as I am stuck. The test is failing for only `EventRegistrantsModal.tsx`.

//all imports
type ModalPropType = {
  show: boolean;
  eventId: string;
  orgId: string;
  handleClose: () => void;
};

interface InterfaceUser {
  _id: string;
  firstName: string;
  lastName: string;
}

export const EventRegistrantsModal = (props: ModalPropType): JSX.Element => {
  const [member, setMember] = useState<InterfaceUser | null>(null);

  const [addRegistrantMutation] = useMutation(ADD_EVENT_ATTENDEE);
  const [removeRegistrantMutation] = useMutation(REMOVE_EVENT_ATTENDEE);

  const {
    data: attendeesData,
    loading: attendeesLoading,
    refetch: attendeesRefetch,
  } = useQuery(EVENT_ATTENDEES, {
    variables: { id: props.eventId },
  });

  const { data: memberData, loading: memberLoading } = useQuery(MEMBERS_LIST, {
    variables: { id: props.orgId },
  });
  const notifyAddRegistrant = (): Promise<void> => {
    return toast.promise(addRegistrant, {
      pending: 'Adding the attendee...',
      success: 'Added the attendee successfully!',
      error: 'There was an error in adding the attendee!',
    });
  };
  const addRegistrant = async (): Promise<void> => {
    if (member == null) {
      toast.warning('Please choose an user to add first!');
      return Promise.reject();
    }

    await addRegistrantMutation({
      variables: {
        userId: member._id,
        eventId: props.eventId,
      },
    });
    attendeesRefetch();
  };

  const notifyDeleteRegistrant = (userId: string): Promise<void> => {
    return toast.promise(() => deleteRegistrant(userId), {
      pending: 'Removing the attendee...',
      success: 'Removed the attendee successfully!',
      error: 'There was an error in removing the attendee!',
    });
  };
  const deleteRegistrant = async (userId: string): Promise<void> => {
    await removeRegistrantMutation({
      variables: {
        userId,
        eventId: props.eventId,
      },
    });
    attendeesRefetch();
  };

  // Render the loading screen
  if (attendeesLoading || memberLoading) {
    return (
      <>
        <div className={styles.loader}></div>
      </>
    );
  }

  return (
    <>
      <Modal
        show={props.show}
        onHide={props.handleClose}
        backdrop="static"
        centered
      >
        <Modal.Header closeButton className="bg-primary">
          <Modal.Title className="text-white">Event Registrants</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <h5 className="mb-2"> Registered Registrants </h5>
          {attendeesData.event.attendees.length == 0
            ? `There are no registered attendees for this event.`
            : null}
          <Stack direction="row" spacing={1}>
            {attendeesData.event.attendees.map((attendee: InterfaceUser) => (
              <Chip
                avatar={
                  <Avatar>{`${attendee.firstName[0]}${attendee.lastName[0]}`}</Avatar>
                }
                label={`${attendee.firstName} ${attendee.lastName}`}
                variant="outlined"
                key={attendee._id}
                onDelete={() => notifyDeleteRegistrant(attendee._id)}
              />
            ))}
          </Stack>
          <br />

          <Autocomplete
            id="addRegistrant"
            onChange={(_, newMember): void => {
              setMember(newMember);
            }}
            options={memberData.organizations[0].members}
            getOptionLabel={(member: InterfaceUser): string =>
              `${member.firstName} ${member.lastName}`
            }
            renderInput={(params): React.ReactNode => (
              <TextField
                {...params}
                label="Add an Registrant"
                placeholder="Choose the user that you want to add"
              />
            )}
          />
          <br />
        </Modal.Body>
        <Modal.Footer>
          <Button variant="success" onClick={notifyAddRegistrant}>
            Add Registrant
          </Button>
        </Modal.Footer>
      </Modal>
    </>
  );
};

**Comment by skbhagat0502** [comment]
Hey @palisadoes,

Quick update—I've sorted out all the React toast notifications except for one in `EventRegistrantsModal.tsx`. Despite my best efforts, I am not able to find out the solution. For now, I reverted the code to its previous state, making it merge-ready solely for EventRegistrantsModal.jsx.

I'm planning to raise a new issue specifically for the challenge in `EventRegistrantsModal.tsx`.It might require some more changes in the file in order for the toast to work correctly without failing tests. So in my opinion creating a separate issue will be better.

I am saying this because after a thorough investigation, I found that the problem lies in the `attendeesRefetch()` in `EventRegistrantModal.tsx`. When I exclude it, all tests pass smoothly, but the moment it's in the mix, tests break. I've double-checked, and the tests are solid, Any insights on this would be golden.

**Comment by aashimawadhwa** [comment]
Did you checked the test code for the other react toast throughout the talawa admin? @skbhagat0502

**Comment by skbhagat0502** [comment]
> Did you checked the test code for the other react toast throughout the talawa admin? @skbhagat0502

Yes they are all correct.

**Comment by EshaanAgg** [comment]
@skbhagat0502 The code LGTM but I can see a decrease in the test coverage. Can you let me know the reason for the same?

**Comment by skbhagat0502** [comment]
@EshaanAgg  I also don't have any idea that why it is showing low test coverage. The files which I have edited has 100 percent test coverage.It might be due to some other files but don't know the exact reason.

**Comment by palisadoes** [comment]
We have seen codecov have rounding errors before. The 0.06% decrease is essentially zero.

**Review by beingnoble03 — APPROVED** [review]
LGTM.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
