### PR TITLE
Fixes: #453 Updated packages  to the latest version.

### LINKED ISSUE #453: Resolve dependency conflicts
**Describe the bug**
1. Run the commands
     ```
            npm i --package-lock-only
            npm audit
     ```
1. The output shows a large number of dependency conflicts

**To Reproduce**
See above

**Expected behavior**
1. These conflicts need to be resolved.
1.  Update the GitHub action for pull-requests so that they fail when future dependency conflicts are found.

**Actual behavior**

See above

**Screenshots**
This is sample output from the `npm i --package-lock-only` command
image

**Additional details**
See above

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**

 updated all the packages that could possibly create npm warnings

**Issue Number:**

Fixes #453 

**Did you add tests for your changes?**

yes
**Snapshots/Videos:**

Screenshot 2023-02-10 at 6 52 54 PM (2)

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
Screenshot 2023-02-10 at 7 19 18 PM (2)

it is working fine in my local machine @palisadoes , why it is failing here.?

**Comment by palisadoes** [comment]
Please check the [Action.test.ts](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/state/helpers/Action.test.ts) file that the test is failing on.

image

**Comment by palisadoes** [comment]
@aashimawadhwa 
1. Just make the suggested change listed in the linting error and restore the prettier because that didn't seem to change anything. 
1. Let's see if that works.

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa
> 
>     1. Just make the suggested change listed in the linting error and restore the prettier because that didn't seem to change anything.
> 
>     2. Let's see if that works.

will do it sir

**Comment by aashimawadhwa** [comment]
can i close this PR will create a new one need to do some changes. @palisadoes

**Comment by palisadoes** [comment]
Ok

**Comment by noman2002** [comment]
Closing this as discussed above. Submit a fresh PR, once completed.

**Pull request closed without merging**
