### PR TITLE
Setup script for .env configuration file

### LINKED ISSUE #1233: Create a Setup Script for the `.env` configuration file
**Is your feature request related to a problem? Please describe.**

1. The current `INSTALLATION.md` file describes how to manually setup the `.env` file
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/main/INSTALLATION.md#creating-env-file 
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file

**Describe the solution you'd like**
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file
1. It should validate the parameters entered and that any services related to the parameters are working correctly
1. The `INSTALLATION.md` file must be updated with the new procedure
1. The table of contents must be regenerated with a link to the new instructions visible

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1233 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/9f1c5018-d7b3-4a1b-90a8-2af8190fc4e5

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
Will check it thoroughly and confirm later.

**Comment by palisadoes** [comment]
@SiddheshKukade Please remember your review. It's been some time

**Comment by SiddheshKukade** [comment]
Looks good. I tried a few combinations

**Review by SiddheshKukade — APPROVED** [review]

**Review by palisadoes — CHANGES_REQUESTED** [review]
@disha1202

You have not updated `INSTALLATION.md` to make people know that the setup script exists
Use the one in the API repo as a guide

**Comment by disha1202** [comment]
@palisadoes 

I have updated the installation guide. 
Please take a look.

**Review by palisadoes — CHANGES_REQUESTED** [review]
@disha1202 

1. The script does not check to see whether the API is actually running
1. The script assumes any character that is not N is yes. This is not valid
1. If you make any edits to the .env file in the script then any pre-existing comments already existing in the .env file are removed
1. If you make any edits to the .env file in the script and then hit CTRL-C then any pre-existing comments already existing in the .env file are removed
1. The script must assume a default of Y, if a pre-existing configuration parameter exists
1. If any value in the .env file is commented out but the rest are valid, the script fails telling you `Please copy the contents of .env.example to .env file` This is not valid. The script should automatically insert missing values

Please test the script more thoroughly

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please fix the failing test

**Comment by disha1202** [comment]
Hi @palisadoes 

I have made all the requested changes and also tested the script. 

I am not sure why the test is failing, I have not made any changes in that file

image

**Review by palisadoes — CHANGES_REQUESTED** [review]
@disha1202 
- I can't test. It hangs when testing the API URL when the URL is valid.

**Comment by disha1202** [comment]
> @disha1202
> 
> * I can't test. It hangs when testing the API URL when the URL is valid.

It takes a little bit of time because we are making an API call to test whether the server is running or not.
[Screen Recording 2024-01-14 at 7.21.57 PM.mov.zip](https://github.com/PalisadoesFoundation/talawa-admin/files/13931723/Screen.Recording.2024-01-14.at.7.21.57.PM.mov.zip)

**Review by palisadoes — CHANGES_REQUESTED** [review]
@disha1202
Waiting a minute during installation is a very long time. Verification should be much shorter, for example it doesn't take a minute to log in from Talawa-Admin using the API. Users will abort the installation because of the delay. What options are there to make this quicker and equally effective?

**Comment by disha1202** [comment]
> @disha1202
> Waiting a minute during installation is a very long time. Verification should be much shorter, for example it doesn't take a minute to log in from Talawa-Admin using the API. Users will abort the installation because of the delay. What options are there to make this quicker and equally effective?

@palisadoes 
I have updated the code to reduce response time. 
Please take a look.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the failing tests. The code looks OK

**Comment by disha1202** [comment]
@palisadoes 
Fixed the failing tests which were related to this PR.

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
The tests are still failing. Please merge your code with the latest upstream

**Comment by disha1202** [comment]
Updated the PR with the latest upstream. 

The tests are still failing.

**Comment by palisadoes** [comment]
Tests are still failing

**Comment by palisadoes** [comment]
@disha1202 

1. Merge your code with the latest upstream that may fix the failing `Test Application` tests. 
2. The introspection one is being fixed elsewhere.

**Comment by disha1202** [comment]
> @disha1202
> 
> 1. Merge your code with the latest upstream that may fix the failing `Test Application` tests.
> 2. The introspection one is being fixed elsewhere.

@palisadoes 

I have updated the PR with the latest changes but the tests are still failing.

**Comment by palisadoes** [comment]
This file shouldn't be a part of this PR. That may be the cause
- `src/screens/OrgPost/OrgPost.tsx`

**Comment by disha1202** [comment]
> This file shouldn't be a part of this PR. That may be the cause
> 
> * `src/screens/OrgPost/OrgPost.tsx`

I updated `src/screens/OrgPost/OrgPost.tsx` to fix the type errors. 

Screenshot 2024-01-19 at 9 40 34 PM

**Comment by palisadoes** [comment]
That file isn't required in this PR. It must not need included.

**Comment by palisadoes** [comment]
@disha1202 

If this file is no longer in the PR, why is it being linted in the tests? Please make a minor commit to see whether it triggers the correct action 

- `src/screens/OrgPost/OrgPost.tsx`

**Comment by palisadoes** [comment]
@disha1202

1. We need this completed soon.
2. We have other PRs depending on updating the setup script.

**Comment by disha1202** [comment]
> @disha1202
> 
> If this file is no longer in the PR, why is it being linted in the tests? Please make a minor commit to see whether it triggers the correct action
> 
> * `src/screens/OrgPost/OrgPost.tsx`

The tests are still failing for `src/screens/OrgPost/OrgPost.tsx`.

**Comment by palisadoes** [comment]
Yes. Please create a new one.

Closing

**Pull request closed without merging**
