### PR TITLE
Single search modal instead of two search modal

### LINKED ISSUE #1155: Searching form members to be a single search modal
**Is your feature request related to a problem? Please describe.**
Requirement of a single search bar instead of  first name and last name search modal to provide a better search experience.

**Describe the solution you'd like**
A single search bar to search names in all 3 roles users, members and admins.

**Additional context**

**Current Situation:** 
Screenshot 2023-12-07 at 7 46 04 PM

**Expected Results:**
Screenshot 2023-12-07 at 7 46 55 PM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Min2who**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1155 

**Snapshots/Videos:**

Berfore:
image

After changes:
https://github.com/PalisadoesFoundation/talawa-admin/assets/127925465/08cc8e04-efac-4385-8cfa-b83464a42008

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Min2who** [comment]
@rishav-jha-mech can you review the PR?

**Comment by aashimawadhwa** [comment]
Please fix the failing test from the workflow  [here](https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7144581493/job/19458497850?pr=1166) @Min2who

**Comment by palisadoes** [comment]
We had to revert a PR that was causing tests to fail incorrectly. Please submit a minor commit to trigger an update of the GitHub workflow

**Comment by palisadoes** [comment]
@aashimawadhwa @rishav-jha-mech This is ready for review

**Comment by palisadoes** [comment]
@aashimawadhwa @rishav-jha-mech All checks have passed. Please review

**Review by aashimawadhwa — APPROVED** [review]
Looks good to me 👍🏼

**Comment by aashimawadhwa** [comment]
we can merge this @palisadoes

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
