### PR TITLE
Fix add existing user functionality

### LINKED ISSUE #1842: Add existing member to an organization functionality not working
**Describe the bug**

The add existing member functionality is not working due to update in user schema.

**To Reproduce**

1. Login to Admin portal
2. Select an Organization
3. Navigate to the people screen
4. Click on existing user
5. undefined undefined will be displayed instead of the username
6. Click on add, an error will appear

**Expected behavior**

The add existing user should add members to the organization without any error

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

The add existing user functionality not working and resulting in errors.
 
**Screenshots**

Screenshot 2024-03-29 at 2 54 12 PM

Screenshot 2024-03-29 at 2 54 08 PM

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

bugfix

**Issue Number:**

Fixes #1842 

**Did you add tests for your changes?**

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/04014014-de66-4de5-8e9b-bc1cde405a32

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by disha1202** [comment]
Hi @palisadoes 

I have fixed the failing tests related to the add member functionality.
Although there are some other tests failing as well which are not related to this PR 
image

**Comment by palisadoes** [comment]
1. Please merge with the latest upstream and verify
2. All the PRs we have merged in past day passed all their tests.

**Comment by disha1202** [comment]
> * Please merge with the latest upstream and verify
> * All the PRs we have merged in past day passed all their tests.

My branch is up to date with the latest upstream. Also, I haven't changed anything in the file whose test cases are failing.

**Comment by palisadoes** [comment]
@meetulr This failing test may be related to one of your recent PRs. PTAL

**Comment by meetulr** [comment]
Ok I'll check shortly😅

**Comment by meetulr** [comment]
Ahh yes! It is indeed failing because of an oversight from me, sorry about that😅.

I forgot to set a date in that test, and the test is checking for the occurences of a weekDay in a month. As it is right now, it will fail for every 5th occurence, and for any but the last occurence of that weekDay in that month.

We just have to set the date here, that would allow testing of all these options.

```javascript
    const startDatePicker = screen.getByLabelText('Start Date');
    const endDatePicker = screen.getByLabelText('End Date');

    fireEvent.change(startDatePicker, {
      target: { value: formData.startDate },
    });

    fireEvent.change(endDatePicker, {
      target: { value: formData.endDate },
    });
```

@disha1202 can you fix it in this PR? Just have to add this right after line 243 in that test, i.e. setting the date.

**Comment by disha1202** [comment]
> Ahh yes! It is indeed failing because of an oversight from me, sorry about that😅.
> 
> I forgot to set a date in that test, and the test is checking for the occurences of a weekDay in a month. As it is right now, it will fail for every 5th occurence, and for any but the last occurence of a weekDay in that month. (it's failing today because it is the 5th Saturday)
> 
> We just have to set the date here, that would allow testing of all these options.
> 
> ```js
>     const startDatePicker = screen.getByLabelText('Start Date');
>     const endDatePicker = screen.getByLabelText('End Date');
> 
>     fireEvent.change(startDatePicker, {
>       target: { value: formData.startDate },
>     });
> 
>     fireEvent.change(endDatePicker, {
>       target: { value: formData.endDate },
>     });
> ```
> 
> This test is failing in other PRs too. @disha1202 can you fix it in this PR? Just have to add that code right after line 243 in `src/components/RecurrenceOptions/RecurrenceOptions.test.tsx`, i.e. setting the date.
> 
> or I could fix it separately, let me know @palisadoes Sorry for the inconvenience😅

Sure, I'll fix it in this PR.

**Comment by disha1202** [comment]
This PR is ready for review.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
