### PR TITLE
feat: Add User and Admin toggle on login pages

### LINKED ISSUE #1173: User and Admin toggle on Login and Registration Screen
**Is your feature request related to a problem? Please describe.**
We need an interface to login to user portal provided by talawa which can be accessed by this url `http://localhost:3001/user` when you run talawa Admin and talawa API on your local machine

**Describe the solution you'd like**:

1. The login and registration form should have a toggle functionality.
2. This toggle should allow users to switch between user and admin roles seamlessly.
3. Users can select their role preference using a toggle switch to access the respective login or registration form.

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/5d03cfd1-c0f8-40c8-97d2-6d6180569053

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by meetulr**
Fixes #1173

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/fb5b03f7-7143-4ea3-bba6-d2364d78a51c

**Summary**

Added a toggle for navigating between the ADMIN and the USER login pages without having to manually change the URL.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by meetulr** [comment]
The Login/Registration toggle is intact as well.

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/7de41983-d8c8-4950-9c40-45ee7966afe6

**Comment by rishav-jha-mech** [comment]
@meetulr, the tab buttons should have theme colour of Palisadoes, adjust the logo, etc to accommodate the whole login page into one, so that the user does not have to scroll down too much, also attack screenshots of mobile view, this page should be responsive

**Comment by meetulr** [comment]
I've made the adjustments on the LoginPage as it's login and register would be used as a reference when refactoring those #1377. And I've extracted the toggle for keeping it DRY. Let me know if the changes are ok.
Thanks.

Design Adjustments
Mobile view

**Comment by Tarunmeena0901** [comment]
hey @meetulr , that's a nice way to add a toggle but don't you think just for toggling we should not route to localhost:3000/user page and should just render the components of admin and user on conditional basis using redux state management on the same page this will also remove the lag while toggling , overall improving the user experience .

or maybe it's fine if we just need to make it work 😄

**Comment by meetulr** [comment]
> hey @meetulr , that's a nice way to add a toggle but don't you think just for toggling we should not route to localhost:3000/user page and should just render the components of admin and user on conditional basis using redux state management on the same page this will also remove the lag while toggling , and make look more consistent. overall improving the user experience .
> 
> or maybe it's fine if we just need to make it work 😄

I agree, and that's what I was about to suggest, after completing this issue (to avoid overstepping), since it's only concerned with adding a toggle. I wanted to make Login and Registration components common, and instead of navigating, we could just toggle state and handle login/registration based on that state.
An issue was already created for that #1377.
But then again, maybe seperate routes are required for more clarification (admin/user portal). The designs need to be synced though!

**Comment by rishav-jha-mech** [comment]
There will be only one route @meetulr, and by default User section will be active, we will be removing `/user` endpoint in https://github.com/PalisadoesFoundation/talawa-admin/issues/1377

**Review by rishav-jha-mech — DISMISSED** [review]

**Comment by meetulr** [comment]
> There will be only one route @meetulr, and by default User section will be active, we will be removing `/user` endpoint in #1377

Ahh! I see, I misunderstood that issue. That's great though👍.

**Comment by Tarunmeena0901** [comment]
> > hey @meetulr , that's a nice way to add a toggle but don't you think just for toggling we should not route to localhost:3000/user page and should just render the components of admin and user on conditional basis using redux state management on the same page this will also remove the lag while toggling , and make look more consistent. overall improving the user experience .
> > or maybe it's fine if we just need to make it work 😄
> 
> I agree, and that's what I was about to suggest, after completing this issue (to avoid overstepping), since it's only concerned with adding a toggle. I wanted to make Login and Registration components common, and instead of navigating, we could just toggle state and handle login/registration based on that state. An issue was already created for common components #1377. But then again, maybe seperate routes are required for more clarification (admin/user portal), in which case, the designs need to be synced.

oh even I overlooked that the issue exist already  then we have more of a reason to do it in single routes so we don't have to change it later . 
I don't think you will need any but i will be more than happy to help just ping me on slack whenever you want👍🏻

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Review by palisadoes — DISMISSED** [review]

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by meetulr** [comment]
Too many pr's are being merged, so it's creating merge conflicts again and again.

**Comment by rishav-jha-mech** [comment]
@meetulr it is what it is /s

**Comment by meetulr** [comment]
> @meetulr it is what it is /s

Yes, I totally understand. I'm just saying that's why I made multiple commits😅.

**Comment by meetulr** [comment]
There's been much activity earlier, and too quickly. And I've been hasty with merging too. I'll close this pr and open a new one. I'm sorry about the confusion.

**Review by palisadoes — APPROVED** [review]

**Comment by meetulr** [comment]
@palisadoes this pr needs to be reverted, I realize that in a hurry to fix the merge conflicts, I've made a mistake. That's why I was asking to open a new pr after closing this one. I'm sorry about that, I've fixed it now.
Too much happened too quickly😅.

**Comment by palisadoes** [comment]
Open a new one with the fix

**Pull request merged**
