### PR TITLE
fix the loading state

### LINKED ISSUE #2110: Improving User Experience During Login/Registration with Non-Intrusive Loading Indicators
**Is your feature request related to a problem? Please describe.**
Currently, when a user attempts to log in or register, the entire form disappears, and a circular loader is displayed in the center of the screen. This abrupt transition can be disorienting and frustrating for users. After the loader, the user is either redirected or remains on the same page with an error pop-up. This process blocks the entire page, which is not user-friendly and can lead to a poor user experience.
**Describe the solution you'd like**
To improve the user experience, the form should not disappear entirely. Instead:

1. Disable Form on Submit: When the form is submitted, disable the form fields and submit button to prevent multiple submissions.
2. Dim Background: Reduce the opacity of the background when the loader appears to indicate that an action is being processed without completely hiding the form.
3. Top Loader Indicator: or we can Use a progress bar or loader at the top of the page instead of a full-screen loader. This keeps the form visible and provides a visual indicator that the process is ongoing.

**Describe alternatives you've considered**

1. we can reduce the opacity of lower back ground 
2. or we can disable the form field and show a progress bar on top of page

**Additional context**
1. login page
Screenshot 2024-07-22 210756
2. after click on login
Screenshot 2024-07-22 211213

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AnshulKahar2729**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #2110 

**Did you add tests for your changes?**

No.

**Snapshots/Videos:**

https://github.com/user-attachments/assets/2e9e0aad-4731-4c81-a0d8-e6685faa1b7c

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced user experience by disabling form controls and buttons during loading states to prevent unintended interactions.

- **Bug Fixes**
	- Simplified loading state management, improving responsiveness and clarity during the login process.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. Is this necessary? Are we adding code we don't really need?
2. For example, if logging in doesn't have a loading screen, then we'll need to remove it for every screen selected for logout. There is no user experience consistency

**Review by AnshulKahar2729 — COMMENTED** [review]
I think the login form one is pretty standard, you will be able to see it everywhere because people try out different credentials many times and you can't show that big loading screen every time for that, but for other stuff, you can. Talking about consistency, maintaining a different loading mechanism could also be a sign of consistency, we can implement that in every form out there, and for the rest of the things, loader will make sense. Let me know, what you think, I will accordingly make the changes.

**Review by AnshulKahar2729 — COMMENTED** [review]
Done

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
I'll approve this as most websites follow this design aesthetic, however we must not eliminate the loading page anywhere else. We have other more important areas to focus on, such as reducing our code bloat and the resulting high memory utilization.

**Comment by AnshulKahar2729** [comment]
> I'll approve this as most websites follow this design aesthetic, however we must not eliminate the loading page anywhere else. We have other more important areas to focus on, such as reducing our code bloat and the resulting high memory utilization.

Yes sure and I'll try to contribute to more serious issues next time. This was my first time contributing to the talawa, so I picked an easier one.

**Pull request merged**
