### PR TITLE
fix: Interactive card

### PR DESCRIPTION
**Pull request by techfussion**
What kind of change does this PR introduce?
feature

Issue Number:
#573 

Fixes:

Did you add tests for your changes?
No ran automated test

Snapshots/Videos:

wrapping cards with react-router-dom link

If relevant, did you update the documentation?

Summary
Added a on click functionalities that link cards to the menu from the navbar. Users can click on a card and it'll take them to the appropriate section. Issue detailed on #573 

Does this PR introduce a breaking change?
No

Other information
Utilized targets variable destructured from appRoute:
  ```
const appRoutes = useSelector((state: RootState) => state.appRoutes);
  const { targets, configUrl } = appRoutes;
```
Used map and filter function to retrieve appropriate url and consumed by react-router-dom `<Link>` :

```
<Link
    className={`card ${styles.cardContainer}`}
    to={`${targets
      .filter((target: any) => {
        const { name } = target;
        return name == 'People';
      })
      .map((target: any) => {
        return target.url;
      })}`}
>

```
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

Please also fill in the template for the pull request as completely as you can. I greatly helps others searching for code changes in future and helps others understand the summarized rationale for the work you have done

**Comment by techfussion** [comment]
Okay

**Comment by palisadoes** [comment]
Please also make a small commit to rerun the tests. We made some changes to the GitHub actions.

**Comment by techfussion** [comment]
Okay i'll do that in a while. I've read the PR_GUIDELINES.md and fixed some of my errors.

**Comment by palisadoes** [comment]
Please fix the first comment so that the issue automatically closes. The PR_GUIDELINES.md file has details.

**Pull request closed without merging**
