### PR TITLE
Switch package manager to npm

### LINKED ISSUE #546: Convert Talawa-Admin to use the NPM package manager
**Describe the bug**

1. Talawa-Admin currently uses Yarn v1. This is end of life.
1. We need to upgrade the package manager to a current product
1. For the sake of consistency, we want to use NPM like Talawa-API

This has caused problems with developing new code like this:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/493#issuecomment-1458162310

**To Reproduce**

1. Update packages
2. Incompatibility errors

**Expected behavior**

When updating packages:

1. No deprecation warnings. 
1. No package incompatibilities 

**Actual behavior**

1. Deprecation warnings. 
1. Package incompatibilities 

**Screenshots**

image

**Additional details**

- See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Shofiya2003**
**What kind of change does this PR introduce?**
The PR includes changes to convert Talawa-Admin to use the NPM package manager instead of yarn.

**Issue Number:**

Fixes #546 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
The documentation has been changed to replace the steps that involve yarn with NPM 
The following `.md` files have been changed:
https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/CONTRIBUTING.md
https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md
https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/PR_GUIDELINES.md

**Summary**
This PR solves the problem which arose due to yarn v1. To maintain consistency with Talawa API, we switched the package manager to NPM. 
Problems due to yarn v1
https://github.com/PalisadoesFoundation/talawa-admin/issues/493#issuecomment-1458162310

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by Shofiya2003** [comment]
Please suggest changes, if any.

**Comment by Cioppolo14** [comment]
@Shofiya2003 Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

The overall code coverage drops below the target threshold of the repository
Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. Thank you!

**Comment by palisadoes** [comment]
1.Please check the `pull-request.yml` and `push.yml`files in the `.github/workflows directory`
1. We use them as part of the testing regime. They have references to yarn in them

**Comment by Shofiya2003** [comment]
> 

I changed all the references to yarn in those files

**Comment by Shofiya2003** [comment]
@palisadoes @Cioppolo14 
https://github.com/reduxjs/react-redux/issues/1886
This error occurs when the workflow runs `npm run typecheck` . We would need to upgrade the react version or use `overrides`
I'll get back with a solution that works.

**Comment by kayceeDev** [comment]
I have a question, why do we need to change the package manager? most people prefer yarn and I will outline my reasons below:

Both Yarn and NPM are popular package managers in the JavaScript ecosystem, and they serve similar purposes. Yarn was created by Facebook and was introduced as an alternative to NPM. However, both have their own pros and cons. Here are some points to consider:

Yarn Pros:

- Faster and more reliable installation and dependency management.
- Offline caching of packages and parallelized downloads.
- Lockfile is more deterministic.
- Better support for workspaces and monorepos.

NPM Pros:

- Comes bundled with Node.js, which means you don't need to install any additional software.
- Provides better security features such as package vulnerability scanning and audit reports.
- Has a larger community, which means more resources and support are available.
- NPM supports automatic publishing to the NPM registry from GitHub repositories.


In conclusion, both Yarn and NPM have their own advantages, and choosing one over the other depends on your specific needs and preferences. If you're working with a mono repo or have large-scale projects with complex dependencies, Yarn might be a better choice. If security is a priority for you or you need to publish packages to the NPM registry from GitHub repositories, NPM might be a better choice.

My questions are, while we can change to yarn later, is this a non-trivial issue? Can't we look at more important issues like the dashboard redesign? Is it not more important to consider upgrading to a more important package like the `react-router`?

The `Installation.md` file is clear and concise and anyone who has node and `npm` can be able to migrate to yarn successfully.

If all these have been considered and we still want to move to npm, then I am ok with it. Else, `yarn` can do same thing as `npm`

**Comment by xoldyckk** [comment]
@kayceeDev If you're really talking about package manager pnpm takes the cake. It's way ahead of both npm and yarn in terms of features. But should we use it? I'm not so sure, contributers are having trouble just setting up node.js here. There's also many contributers who use windows, and imo windows has weird quirks related to global installations caching yarn and pnpm use.

I don't currently see any use for either yarn or pnpm, except for saving storage space. And I don't think that's something we should push on contributers since most of them are only familiar with npm.

**Comment by kayceeDev** [comment]
> @kayceeDev If you're really talking about package manager pnpm takes the cake. It's way ahead of both npm and yarn in terms of features. But should we use it? I'm not so sure, contributers are having trouble just setting up node.js here. There's also many contributers who use windows, and imo windows has weird quirks related to global installation caching yarn and pnpm use.
> 
> I don't currently see any use for either yarn or pnpm, except for saving storage space. And I don't think that's something we should push on contributers since most of them are only familiar with npm.

What I am saying is, is this really important, changing package manager? If we think it is then no problems.

**Comment by xoldyckk** [comment]
@kayceeDev Yes there is a problem. The project uses yarn v1. It has reached end of life.

**Comment by kayceeDev** [comment]
> @kayceeDev Yes there is a problem. The project uses yarn v1. It has reached end of life.

Hahaha. End of life indeed. So why shouldn't upgrade the docs to use recent yarn versions instead of a complete overhaul. Just a thought though. I like your humor between 😁

**Comment by xoldyckk** [comment]
@kayceeDev If the project can work with latest npm versions, there wouldn't be any problems running it with yarn or pnpm. If we're really going to take the storage space on contributer's local system into consideration I'd advice using pnpm instead of yarn.

You see this I gave this issue 10 points as it's not as easy as it looks. Try changing the package manager or using yarn 3 on your local system, you'll know what I'm talking about.

**Comment by kayceeDev** [comment]
> @kayceeDev If the project can work with latest npm versions, there wouldn't be any problems running it with yarn or pnpm. If we're really going to take the storage space on contributer's local system into consideration I'd advice using pnpm instead of yarn.
> 
> You see this I gave this issue 10 points as it's not as easy as it looks. Try changing the package manager or using yarn 3 on your local system with talawa-admin, you'll know what I'm talking about.

I totally get you. It's fine with your decision. I am just being open minded to these changes. Thank you for indulging me.

**Comment by palisadoes** [comment]
@Shofiya2003 Please update the PR with the latest code changes. This should fix the failing `type error `tests.

**Comment by palisadoes** [comment]
Closing as the issue has been reassigned

**Pull request closed without merging**
