### PR TITLE
BugFix - Validation Error when Querying allotedRoom and allotedSeat

### LINKED ISSUE #1662: GraphQL Validation Error when Querying allotedRoom and allotedSeat in eventCheckIns
**Describe the bug**
When executing the GraphQL query for eventCheckIns, which includes fields allotedRoom and allotedSeat in the checkIn object, the server returns a GraphQL validation error. The error messages indicate that these fields cannot be queried on the type CheckIn.

image
image

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by krishna619**
**What kind of change does this PR introduce?**
Fixing GraphQL Validation Error when Querying allotedRoom and allotedSeat

Bugfix

**Issue Number:**

Fixes #1662 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/02019c24-6463-4746-8342-2226653c50e2

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by krishna619** [comment]
@palisadoes please review.

**Comment by pranshugupta54** [comment]
Hey @krishna619, there are more files in Talawa-Admin which contain `allotedRoom` and `allotedSeat` which will cause issue. For example TableRow and its test file, it's going to fail the test due to this.

**Comment by aashimawadhwa** [comment]
@pranshugupta54 please let the maintainers review the code first?

**Comment by aashimawadhwa** [comment]
@krishna619  please work around on all the remaining files with the issue.

**Comment by krishna619** [comment]
@aashimawadhwa 
Hey
I have removed it from the remaining files as well from the latest commit .

**Comment by Cioppolo14** [comment]
@noman2002 @beingnoble03 Can you review this PR?

**Comment by palisadoes** [comment]
We are going to pause merging PRs into the `develop` branch to facilitate fixing the roles of Members, Admins and Super Admins.

They need to assigned on a per organization basis versus per API instance. This is the tracking issue.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1965

Reviews of PRs for all branches will continue

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by krishna619** [comment]
@palisadoes can you close this PR as merged, as it is covered in #1744

**Pull request closed without merging**
