### PR TITLE
Add Multi Language Support For User Not Found and Form Validation 

### LINKED ISSUE #1579: Bug Report: When language preferences are switched, the warnings for invalid inputs are still showing in English
**Describe the bug**
When the preferred language is not english, warnings (both in top right or below the log in credentials) are not showing in the preferred language.  They remain in English. 

**To Reproduce**

1. Set language on login page to any language except English
2. Attempt to login with bad credentials
3. Observe the warnings remaining in English

**Expected behavior**
Once the preferred language is chosen, all the following must be in the preferred language on the admin and user portal pages:

1. All notifications
2. All warnings and errors
3. All text 

**Screenshots**

The following are provided as only one of many other examples of this issue.

Screenshot 2024-02-11 134100

Screenshot 2024-02-11 134133

**Additional Details**
The location of language translation files is here: /talawa-admin/tree/develop/public/locales

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sauradip07**
**What kind of change does this PR introduce?**
Bug fix

**Issue Number:**

Fixes #1579

**Did you add tests for your changes?**

No need To add Tests

**Snapshots/Videos:**
Screenshot from 2024-02-20 20-59-38
Screenshot from 2024-02-20 21-00-16
Screenshot from 2024-02-20 21-00-35
Screenshot from 2024-02-20 21-01-00
Screenshot from 2024-02-20 21-01-14
Screenshot from 2024-02-20 21-01-33
Screenshot from 2024-02-20 21-01-45
Screenshot from 2024-02-20 21-02-04

**Summary**

`For all 5 Languages Support is Added`

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
This PR is incomplete. The issue requires you to add translations for:

1. All notifications
2. All warnings and errors
3. All text 

Reference
- #1579

**Comment by palisadoes** [comment]
1. I've asked the others to review.
2. We'll create a separate issue to make all visible text translatable

**Comment by Sauradip07** [comment]
> 1. I've asked the others to review.
> 2. We'll create a separate issue to make all visible text translatable

Ok, got it.

**Comment by palisadoes** [comment]
Please refactor the code so that the tests pass

**Comment by Sauradip07** [comment]
I don't know why this show
Screenshot from 2024-02-25 13-59-43

even i try `npm run lint:fix` command also but it not fixed 
please help

**Comment by palisadoes** [comment]
Please ask the talawa-admin slack channel. We have many other PRs without this issue

**Comment by Olatade** [comment]
@Sauradip07 please can you fix the failing checks?

**Comment by palisadoes** [comment]
Please add tests. The patch is significantly below the levels of the repo. (55.9% vs 96.7%)

**Comment by palisadoes** [comment]
Please fix the conflicting files so that we can review

**Pull request closed without merging**
