### PR TITLE
Added the limit to workflow to ensure all non-test Typescript files have < 600 lines

### PR DESCRIPTION
**Pull request by varun7678**
What kind of change does this PR introduce?
Feature

Issue Number: #1298

Fixes https://github.com/PalisadoesFoundation/talawa-admin/issues/1298

Did you add tests for your changes?

No

Snapshots/Videos:

I have tested it out locally and its working fine!

Other information

Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by varun7678** [comment]
Hello @palisadoes
please take a look here

**Comment by palisadoes** [comment]
I'm going to close this PR and the other one and unassign you as this is a variation of the concern I posted in the slack channels where we have an unnecessary profession of PRs

**Comment by palisadoes** [comment]
You are not even assigned the issue for the PR. 

Why the flagrant disregard for our policies?

**Comment by varun7678** [comment]
> You are not even assigned the issue for the PR.
> 
> Why the flagrant disregard for our policies?

I am new to this community and I was not aware of that!
I understood ! will keep it in mind
Thank you!

**Comment by palisadoes** [comment]
1.Please do not waste the time of our volunteers like this again. 
1. You potentially robbed an opportunity for someone else to participate
1. It was not in the spirit of our code of conduct which is documented in a markdown file in all our repositories

This was not a considerate act on your part. It must not be repeated

**Comment by palisadoes** [comment]
> > You are not even assigned the issue for the PR.
> > 
> > Why the flagrant disregard for our policies?
> 
> I am new to this community and I was not aware of that!
> I understood ! will keep it in mind
> Thank you!

There is no excuse for this.

It is clearly stated in:

1.The CONTRIBUTING.md, ISSUE_GUIDELINES.md and PR_GUIDELINES.md files in the root directory of the repo and referenced in the README.md file located there too which acts as the home page for the repo.
1. Many of the videos in our "Developers - Getting Started" YouTube channel.
1. Pinned posts in our slack community
1. The pinned issues in every repo

You also referenced an issue in this PR that wasn't assigned to you.

Your actions imply that you didn't take the time to research the expectations of our contributors that would be expected of any newcomer, or at worst, disregarded a trail of guidelines meant to create an equitable environment to all.

We try to run a professional, respectful community. Please make the effort to abide by those expectations.

**Pull request closed without merging**
