### PR TITLE
Adds required tests for OrganizationEvents.tsx and Fixes a minor bug in Calendar

### LINKED ISSUE #482: Increase the code coverage for OrganizationEvents.tsx
**Describe the bug**

- Increase the code coverage for `/screens/OrganizationEvents/OrganizationEvents.tsx` to 100%.
- Add required tests or alter the existing tests in the `/screens/OrganizationEvents/OrganizationEvents.test.tsx` file.

**Additional details**
Assignable only after #476 is merged.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by beingnoble03**
**What kind of change does this PR introduce?**
Adds required tests for `OrganizationEvents.tsx` and fixes a minor bug in `Calendar`.

**Issue Number:**

Fixes #482 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by beingnoble03** [comment]
@palisadoes ptal. Sorry for the delay. I had my mid-semester exams.

**Comment by palisadoes** [comment]
Can you get the coverage up to 100%. Please also attach a screenshot when you do, just in case an updated CodeCov doesn't get calculated

**Comment by beingnoble03** [comment]
@palisadoes the file coverage is less because of this piece of code
```javascript
(rowsPerPage > 0
                    ? data.eventsByOrganizationConnection.slice(
                        page * rowsPerPage,
                        page * rowsPerPage + rowsPerPage
                      )
                    : data.eventsByOrganizationConnection
 )
```
While looking at this code, I found out that this branch is useless as rowsPerPage can never be less than or equal to 0.
So, I think we can safely replace this code by 
```js
data.eventsByOrganizationConnection
                    .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
```

**Comment by beingnoble03** [comment]
Screenshot 2023-03-05 at 7 59 27 PM

**Comment by Kevoniat** [comment]
@beingnoble03  can you resolve the conflicts

**Comment by Kevoniat** [comment]
other than that the change looks good

**Review by noman2002 — APPROVED** [review]

**Comment by noman2002** [comment]
@beingnoble03 pull the latest code to this PR.

**Comment by beingnoble03** [comment]
This also fixes a minor bug in `Calender` component from #537.

**Review by noman2002 — COMMENTED** [review]
2 uncovered line is there in Calendar.tsx. Please have a look at it and try to achieve the coverage.

**Comment by beingnoble03** [comment]
image

I can see many uncovered lines in `Calendar.tsx`, weren't these supposed to be covered in #552.

**Pull request merged**
