### PR TITLE
change Twitter to X

### LINKED ISSUE #2147: Change Twitter to X links
**Describe the bug**

In social column it should be X instead of twitter.
**To Reproduce**

1. Scroll down to footer
2. Check socials

**Expected behavior**
Should show "https://x.com/palisadoesorg?lang=en"
**Actual behavior**
the link shows "https://twitter.com/palisadoesorg?lang=en" 

**Screenshots**
image
**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AnshulKahar2729**
**What kind of change does this PR introduce?**

feature

**Issue Number:**
Fixes #2147

**Did you add tests for your changes?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Added a "Videos" section to the contributing guidelines for better navigation and resource availability.
  
- **Changes**
	- Updated references throughout the application from "Twitter" to "X", including logo imports, social media links, and associated data structures, to reflect the rebranding.
  
- **Bug Fixes**
	- Adjusted test cases to ensure they correctly reference "X" instead of the deprecated "twitter" key, maintaining test accuracy.

### CODE REVIEW

**Comment by AnshulKahar2729** [comment]
I am fixing the checks... Give me some time

**Comment by AnshulKahar2729** [comment]
Could someone from the team please explain about the different types of fails? I understand that the branch check failed, and I will fix that and create a new pull request after closing this one. However, I'm not sure what "Runs Introspection on the GitHub talawa-api repo on the schema.graphql file" means.
I am new to the org, I am ready to make efforts from my side, I just need proper navigation.

**Comment by palisadoes** [comment]
Please click the links for the failed tests. The causes are self explanatory

**Comment by palisadoes** [comment]
1. We'll open another issue to fix the introspection.
2. There are other reasons for the failures

**Comment by AnshulKahar2729** [comment]
> 1. We'll open another issue to fix the introspection.
> 2. There are other reasons for the failures

I have been assigned the issue in talawai-api. I will solve that issue and will soon close this PR to resolve the branch issue

**Comment by palisadoes** [comment]
Closing. You are using the incorrect branch

**Pull request closed without merging**
