### PR TITLE
 Bugfix: Setup Script for the REACT_APP_BACKEND_WEBSOCKET_URL

### LINKED ISSUE #2183: Setup Script doesn't set the REACT_APP_BACKEND_WEBSOCKET_URL
**Describe the bug**

1. The setup script doesn't set the REACT_APP_BACKEND_WEBSOCKET_URL `.env` file variable
    1. This parameter is required for the proper functioning of plugins
1. The use of this parameter is not described in the `INSTALLATION.md` file

**To Reproduce**

1. Run the setup script. The parameter is not requested or updated
2. The parameter is not described in the `INSTALLATION.md` file

**Expected behavior**

1. The parameter must be automatically configured based on the value of `REACT_APP_TALAWA_URL` parameter value
2. The parameter must be described in the `INSTALLATION.md` file

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Yashgupta9330**
bugfix : Setup Script for the REACT_APP_BACKEND_WEBSOCKET_URL

Fixes  #2183

Summary of Changes:
Introduced a new setup script to configure the environment variable REACT_APP_BACKEND_WEBSOCKET_URL.
Added a configuration file for REACT_APP_BACKEND_WEBSOCKET_URL in the setup folder.
Updated setup.ts to handle the new WebSocket URL configuration.

Did you add tests for your changes?
Yes
Note: Add unit tests and all test are successfully executed

Documentation Updates
Updated Installation.md to reflect the new setup process for configuring WebSocket URLs, providing clear instructions for developers.

## Summary by CodeRabbit

- **New Features**
	- Added a new section in the installation guide for configuring the WebSocket URL in the `.env` file.
	- Introduced a prompt during setup to ask users for their Talawa WebSocket endpoint if not already set.

- **Documentation**
	- Enhanced clarity of environment variable descriptions and setup instructions in the installation guide.

- **Tests**
	- Added unit tests for the new WebSocket URL prompting functionality to ensure correct user interaction.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by Yashgupta9330** [comment]
The test cases I authored are running successfully; however, 4-5 test cases, which were written by someone else, are failing. I will need to address and resolve those test cases as well

**Comment by Yashgupta9330** [comment]
I am experiencing an issue where the failing test cases sometimes run successfully, while at other times they do not. This intermittent behavior is making it challenging to identify the root cause of the problem.

**Comment by Yashgupta9330** [comment]
Screenshot 2024-10-06 202022
@palisadoes  You can see in the image below that all test cases are running successfully.

**Comment by palisadoes** [comment]
Closing. Inactivity

**Pull request closed without merging**
