### PR TITLE
userTypefix - Profiledropdown fix

### LINKED ISSUE #1812: [userTypeFix] Incorrect usertype in Profile dropdown
**Describe the bug**
Shows Null value on Profile dropdown

**To Reproduce**

1. Login via Superadmin
2. Check the Profile dropdown on top right

**Expected behavior**
Change according to new usertype

**Actual behavior**
Shows Null

**Screenshots**

image

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by pranshugupta54**
**What kind of change does this PR introduce?**
Bug fix

**Issue Number:**

Fixes #1812 

**Did you add tests for your changes?**

- 100% test pass
- 100% code coverage

**Snapshots/Videos:**

**Admin:**
image
**Superadmin:**
image

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by dhanagopu** [comment]
@pranshugupta54 please fix the failing check.

**Comment by pranshugupta54** [comment]
@dhanagopu, it's failing on introspection issue (not related to this PR)

**Comment by meetulr** [comment]
@pranshugupta54 Please wait until you're assigned to the issue before you raise a PR.
And you're opening new issues and are asking to be assigned there too. Others are following the rules, you should too😅.

**Comment by pranshugupta54** [comment]
Hey,

Sorry if it seemed like I was doing things the wrong way (PR without getting assigned). But fixing the `userType` issues is really important right now. After we merged some stuff, it's causing big problems for launching the web portal. Like the PR I made fixes an ID problem that's making pages show up as blank.

Just so you know, I only have one other thing assigned to me, which is already done and waiting for approval.

If the people in charge think it's better to close this, that's okay with me. My main goal is to get these important issues sorted out.

Thanks for understanding.

**Comment by meetulr** [comment]
@pranshugupta54 Alright I guess😂. Yes `userType` fixes are important. Though other contributors are busy with their proposals right now, we have two months to fix these issues (now saying we need to chill). And I'm not here to enforce anything, just reminding😅. I know you've been actively contributing for the betterment of the project.

**Comment by Cioppolo14** [comment]
I am closing this as this issue isn't assigned to you. Please follow the process, we must do this even if the issues are important.

**Pull request closed without merging**
