### PR TITLE
 Allow Spaces in First and Last Name Fields on Sign-Up Form

### LINKED ISSUE #2283: Sign-up form incorrectly treats blank spaces as special characters, causing validation errors
**Describe the bug**
When attempting to sign up, the form validation incorrectly recognizes blank spaces as special characters. As a result, users encounter validation errors when they input a name with spaces, even though spaces should be valid characters.

**To Reproduce**

1. Navigate to the sign-up form.
2. Enter the first name or last name with spaces.
3. Submit the form.

**Expected behavior**
Spaces should be ignored, and the user should be able to submit the form without errors.

**Actual behavior**
A validation error triggers a pop-up notification stating that only lower and upper-case characters are allowed.

**Video:**

https://github.com/user-attachments/assets/5b19d04c-fc3f-44e3-829a-226f57859a3d

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by syedali237**
**What kind of change does this PR introduce?**

BugFix

**Issue Number:**

Fixes #2283 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/user-attachments/assets/456c40f5-1058-4b57-8ff9-79c19e8e5e76

**If relevant, did you update the documentation?**

No

**Summary**

This PR fixes an issue in the sign-up form where blank spaces in the first name and last name fields were incorrectly recognized as special characters, causing validation errors. The validation now correctly allows spaces between characters, while ignoring leading or trailing spaces. As a result, users can input names with spaces without encountering validation issues.

**Does this PR introduce a breaking change?**

No

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for first and last names during the signup process, allowing letters, spaces, and hyphens while preventing consecutive spaces or hyphens.
	- Improved error handling for reCAPTCHA verification to simplify user feedback.

- **Bug Fixes**
	- Adjusted validation logic to ensure names are trimmed and meet length requirements.

- **Tests**
	- Expanded test coverage for the `LoginPage` component, including various user interactions, edge cases, and integration with the Talawa-API.

### CODE REVIEW

**Comment by syedali237** [comment]
@varshith257 Can you review this PR?

**Comment by varshith257** [comment]
@syedali237 Better add/modify tests for the same?

**Comment by palisadoes** [comment]
1. Does this work on the admin portal and user portal's user profile pages?
2. If not, the feature isn't complete. 
3. It is not a consistent UX if a user cannot add spaces to their own profile, nor if an Admin cannot update any user's profile data with spaces.
4. Please fix. You haven't done so.

**Comment by syedali237** [comment]
@palisadoes, I will review the points you’ve mentioned. Thanks for the feedback!

**Review by noman2002 — APPROVED** [review]

**Review by noman2002 — CHANGES_REQUESTED** [review]
Please make the suggested changes.

**Comment by syedali237** [comment]
@noman2002 will be completing this task shortly.

**Comment by syedali237** [comment]
This functionality already works on both the User and Admin Portals.

Users can edit their profile, including names with spaces, and the changes are correctly reflected.

https://github.com/user-attachments/assets/f1e4fbe2-1ea5-4947-bcea-11a07ea7a179

Admins can also update their and any user's profiles, including names with spaces. The updates are properly reflected.

https://github.com/user-attachments/assets/2a3e97fd-06d0-46c8-badc-27046b0d02a6

**Review by palisadoes — DISMISSED** [review]
Please make sure your code passes all tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by palisadoes** [comment]
@noman2002 PTAL and merge if OK

**Review by varshith257 — APPROVED** [review]

**Pull request merged**
