### PR TITLE
Added Yearly Calendar Screens for admin and user portals

### LINKED ISSUE #1423: Implement year view in calendar of event screen for both admin and user portal
**Is your feature request related to a problem? Please describe.**
The current calendar interface lacks a comprehensive overview for long-term planning, particularly a year-to-year breakdown that provides insights into activities across all months.

**Describe the solution you'd like**
Implementation of a year view in the calendar, where all months and their associated activities for the entire year are listed. This feature aims to facilitate long-term planning and enhance the user's ability to visualize and manage yearly schedules effectively.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
To address this need, we recommend incorporating a year view feature into the calendar interface. This view should comprehensively list all months and their corresponding activities, providing users with a bird's-eye view of their yearly schedule.

**Additional context**
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #1423

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Admin Portal
[Yearly Calender Admin Portal.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/e89a0a16-42ea-4f52-aad7-434ca4dd96ae)

User Portal
[Yearly Calender User Portal.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/391c1605-eef1-4fd5-987d-ca767d661d38)

**If relevant, did you update the documentation?**

N/A

**Summary**
Added Yearly Calendar screens similar to google calendar in admin and user portals.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Thanks,

1. The Admin screen layout is as expected

    image

1. The User portal must look the same. It needs to use the same styling as Admin

    image

1. You also need to merge with the latest upstream. This view no longer exists

    image

**Comment by Cioppolo14** [comment]
@Anvita0305 Please fix the failing tests.

**Comment by Anvita0305** [comment]
1. Updated the User Portal Screen
image
2. Working on tests for missing lines, will update the code soon.

**Comment by palisadoes** [comment]
Thanks. This is more consistent.

**Comment by duplixx** [comment]
@Anvita0305 awesome work, just a little suggestion can you match the font style of existing calender in this

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
