### PR TITLE
 update packages for "Upgrade deprecated sane library #1225" 

### LINKED ISSUE #1225: Upgrade deprecated `sane` library
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Shubh152**
**What kind of change does this PR introduce?**
bugfix

**Issue Number:**

Fixes #1225 
Fixes PR #1430 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
removed jest-enzyme as it was no longer used and changed failing tests

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Kevoniat @tasneemkoushar Can you review this PR?

**Comment by Cioppolo14** [comment]
@Shubh152 Please do not close any PRs unless a reviewer specifically asks you to do so. This creates extra work for our team. Do not do this in the future.

**Comment by Shubh152** [comment]
Sorry for the inconvenience. Will not happen again.

**Review by noman2002 — CHANGES_REQUESTED** [review]
Fix the conflicting files.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
