### PR TITLE
fixes usage of userType in orglist screen and some modifications in Login

### LINKED ISSUE #1445: Admin: Fix the usage of userType
### NOTE

1. This issue will require close coordination with persons assigned issues in the reference section.
2. You may find it easier to split responsibilities in a different way than proposed here to be more efficient is creating the goal

**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.

This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
2. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
3. All other `userType`s would be on a per organization basis

This means that all code logic referencing the `userType` will need to be updated accordingly.

_TALAWA API_

Additional considerations include:

1. New user registrations will need to default to the `userType` `USER` if not done so already
1. The Schema will need to be updated to reflect this requirement
1. Mutations and queries will need to be updated and in some cases new ones added.

_TALAWA ADMIN_

Additional considerations include:

1. The current screen that edits a person's userType will need to be updated. A design is being created for this and will be reflected in the Figma file on our Design Guide page:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA MOBILE_

No expected changes as userType isn't referenced in the code base

**Actual behavior**

- The schema doesn't apply a person's `userType` by organization. 

**Screenshots**

The current schema:

image

**Additional details**

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa/issues/2373
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by adi790uu**
**What kind of change does this PR introduce?**

refactoring

**Issue Number:**

Fixes #1445 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/132701661/fe9681be-bc5c-4b29-9d97-a9e9fdac0da3

**If relevant, did you update the documentation?**

No

**Summary**

This PR fixes the usage of usertype in orglist screen and some more modifications to Login.

**Does this PR introduce a breaking change?**

yes

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@adi790uu 

1. Are the failing tests to be expected at this point?
2. If not, please fix them.

**Comment by adi790uu** [comment]
@palisadoes I have fixed them

**Comment by palisadoes** [comment]
Please fix the failing tests. They are still there

**Comment by adi790uu** [comment]
Okay @palisadoes got it will fix them.

**Comment by adi790uu** [comment]
@palisadoes I have fixed failing tests.

**Comment by Olatade** [comment]
@adi790uu you still have some unsuccessful tests.

**Comment by adi790uu** [comment]
@Olatade yeah unit tests have passed,code coverage has dropped and introspection check is failing.

**Comment by adi790uu** [comment]
I believe we should worry about coverage at the very end of this issue.

**Comment by adi790uu** [comment]
And Target branch test will fail as this Pr is created against develop-userTypeFix

**Comment by adi790uu** [comment]
I am working on fixing the introspection test.

**Comment by adi790uu** [comment]
@palisadoes don't know why the 1 test is failing in Test Application workflow when I am testing the components individually they are not failing.

**Comment by adi790uu** [comment]
and for introspection fix I am going to create a seperate issue.

**Comment by palisadoes** [comment]
Done

**Comment by adi790uu** [comment]
@palisadoes somehow test application workflow has passed now, introspection is failing I think this can be merged.Seperate issue for introspection test should be created.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Work on introspection when all the Admin code has been converted to the new `userType` functionality

What else remains to be done?

**Comment by adi790uu** [comment]
@palisadoes
1.MemberDetail
2.OrganizationPeople
3.UserPortal/Home.tsx
4.UserPortal/Organizations
5.UserPortal/Users

most probably these only

**Comment by palisadoes** [comment]
That means we should be closer to merging the code back into `develop` for Admin and the API.

This would be on the critical path.

We should create issues for each of those screens and get others to assist and speed things up.

I think you said you'd do that, but never gave the list.

Are we able to create those issues now for those screens?

**Comment by adi790uu** [comment]
@palisadoes I did share the list:
 https://github.com/PalisadoesFoundation/talawa-admin/issues/1445#issuecomment-1975178243

I will create the issues as this PR is now merged.

**Comment by adi790uu** [comment]
> 1. Thanks for the reminder. 
> 1. I'll create the issues because there is some specific wording that needs to be added to each

Okay @palisadoes .

**Pull request merged**
