### PR TITLE
Added Pinning functionality in the create post modal.

### LINKED ISSUE #1122: Pinning functionality in the create post modal
**Is your feature request related to a problem? Please describe.**
Adding pin post option in the create post modal in post screen under dashboard.

**Describe the solution you'd like**
The pin post modal should have a toggle button to enable pinning and unpinning post through the create post modal itself.

**Additional context**
you can take reference for the toggle button UI from the create organization modal.
Screenshot 2023-12-04 at 10 59 26 PM

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by AmitSharma512**
**What kind of change does this PR introduce?**

Pinning functionality in the create post modal.

**Issue Number:**

Fixes #1122 

**Summary**

I added the pinning functionality in the create post modal to pin the post in the create post modal itself.

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
@AmitSharma512 Please get the code coverage for the file you edited up to 100%. That is the cause of the failed tests.

**Comment by AmitSharma512** [comment]
> @AmitSharma512 Please get the code coverage for the file you edited up to 100%. That is the cause of the failed tests.

I updated the code and added tests for the same.

**Comment by AmitSharma512** [comment]
@aashimawadhwa I have updated the code and added tests for the same, plz review it.

**Comment by noman2002** [comment]
@AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.

**Comment by AmitSharma512** [comment]
> @AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.

image

I have added the test for the modified files

**Comment by AmitSharma512** [comment]
> @AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.

image

only those lines are left which are not updated by me.

**Comment by noman2002** [comment]
> > @AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.
> 
> image
> 
> only those lines are left which are not updated by me.

You have to write the test for all the missing lines in a file which you edit. Please add the tests for missing lines and get it to 100%

**Comment by AmitSharma512** [comment]
> > > @AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.
> > 
> > 
> > image
> > only those lines are left which are not updated by me.
> 
> You have to write the test for all the missing lines in a file which you edit. Please add the tests for missing lines and get it to 100%

I have written test for all the missing lines, this screenshot is showing the current code coverage.

**Comment by noman2002** [comment]
> > > > @AmitSharma512 Please attach a screenshot of 100% code coverage of file you edited.
> > > 
> > > 
> > > image
> > > only those lines are left which are not updated by me.
> > 
> > 
> > You have to write the test for all the missing lines in a file which you edit. Please add the tests for missing lines and get it to 100%
> 
> I have written test for all the missing lines, this screenshot is showing the current code coverage.

This is still showing 95% , please get it to 100%.

**Comment by AmitSharma512** [comment]
@noman2002 at above you can see the codecov report, it is showing that %coverage is 94.49 and after my changes it is 95.45.
So, it is improved.

**Comment by AmitSharma512** [comment]
@aashimawadhwa i have made the required changes and written the tests for the same also, plz review it.

**Comment by palisadoes** [comment]
The test code coverage is dropping significantly with this PR. Please get to at least 95% coverage for all your edited files. Though there may be issues to increase the coverage for the file, the aim is for them to reach 100% coverage

**Comment by AmitSharma512** [comment]
@palisadoes after getting all the files covered, the percentage will still be 94.46% as the previous code, without any changes is also not above 95 percent.

**Comment by palisadoes** [comment]
So this is because you submitted the PR before we reached 95%?

**Comment by palisadoes** [comment]
Please try merging your code in this PR with the latest upstream. That should fix it.

**Comment by AmitSharma512** [comment]
@palisadoes now the test coverage is 95.43% which is above 95%

**Comment by palisadoes** [comment]
The patch is still only 80% according to the last set of tests. Please fix.

image

**Comment by palisadoes** [comment]
There is some minor work that needs to be done to get is to the desired 100% test coverage on this file. Please try to get us there. The reliability of our code is very important

- https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1129?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation

**Comment by palisadoes** [comment]
Is this still being worked on?

**Comment by AmitSharma512** [comment]
@palisadoes yes

**Comment by noman2002** [comment]
@AmitSharma512 Its been more than 3 weeks since this PR is open. Please update on this or I have to close it.

**Comment by noman2002** [comment]
Closing due to inactivity.

**Pull request closed without merging**
