### PR TITLE
refactored: src/screens/OrgSettings from Jest to Vitest(fixes: #2567)

### LINKED ISSUE #2567: Refactor: `src/screens/OrgSettings` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/OrgSettings` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by devender18**
**What kind of change does this PR introduce?**
Refactoring

**Issue Number:**

Fixes #2567

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
Screenshot 2024-12-10 at 4 40 49 PM

Screenshot 2024-12-10 at 5 44 44 PM

**If relevant, did you update the documentation?**
Not Relavant

**Summary**
This PR migrates the existing tests for OrgSetting.tsx from Jest to Vitest

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **Tests**
	- Updated the test suite for the `OrgSettings` component for improved clarity and functionality.
	- Added new tests for dropdown rendering in settings tabs.
	- Adjusted existing tests for URL parameter handling and error message assertions.
	- Enhanced control flow by modifying test setup and teardown processes.
	- Improved file filtering to exclude test files from processing in documentation checks.

### CODE REVIEW

**Comment by palisadoes** [comment]
1. Please make sure coderabbit.ai approves your PR
1. Make sure all tests pass (except introspection)

**Comment by devender18** [comment]
1. coderabitai has approved the changes.
2. All checks have passed, except for Introspection.
3. Although code coverage appears reduced, this is not due to my changes. As shown in the attachments, the coverage for my changes is 100%.

@palisadoes I do have one doubt, initially, the following check failed. 
Screenshot 2024-12-13 at 12 30 30 AM


In the TSdoc workflow, the .test.tsx file is skipped. Shouldn’t the .spec.tsx files be skipped as well?
Screenshot 2024-12-13 at 12 07 00 AM

**Comment by Cioppolo14** [comment]
@devender18  Please fix the failing tests.

**Comment by devender18** [comment]
@Cioppolo14 "PR Workflow / Checks if sensitive files have been changed without authorization (pull_request) ", this check is failing because I have made the changes in workflow please review once as per my last comment, thanks :)

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
