### PR TITLE
[userTypeFix] Fixed front-end GraphQL schema in the admin portal, Advertisement functionality, and the introspection test.

### PR DESCRIPTION
**Pull request by Anubhav-2003**
**What kind of change does this PR introduce?**
Bugfix.

**Issue Number:**
Fixes: #1807 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**
Currently after the develop-usertype-fix branch was merged into the develop, a major issue was the discrepancies, in the front-end schema that was causing the GraphQL introspection to fail. This PR aims to fix the bugs, and make the introspection pass.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Anubhav-2003 Please fix the failed test application check.

**Comment by Anubhav-2003** [comment]
> @Anubhav-2003 Please fix the failed test application check.

Yes ma'am, working on it. Thank You

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, I have fixed the introspection issue, as well as the implementation of the advertisement functionality. Please review. 

Also sir, can you please add this to the project https://github.com/orgs/PalisadoesFoundation/projects/24 as I think only you can add it there.

Thank You.

**Comment by palisadoes** [comment]
Please fix the conflicting files.

**Comment by palisadoes** [comment]
Please fix the tests

**Comment by Anubhav-2003** [comment]
> Please fix the tests

yes sir, working on it. Thank you.

**Comment by Anubhav-2003** [comment]
@palisadoes Respected sir, please review.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
