### PR TITLE
Add ldap authentication

### LINKED ISSUE #1070: Add support for LDAP authentication
Talawa-Admin currently authenticates its users against the application’s database. In many cases organizations will want to use some sort of central authentication authority.

We need a Talawa-Admin option that delegates all password management to an external LDAP system.

1. The configuration must clearly show that LDAP is the authentication method of choice.
1. Both LDAP and LDAPS must be supported
1. The appropriate documentation must be created
1. Your code must be 100% tested to maintain our test coverage

### PR DESCRIPTION
**Pull request by skbhagat0502**
**What kind of change does this PR introduce?**

A feature request.

**Issue Number:**

Fixes #1070 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Added the ldap authentication method.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by skbhagat0502** [comment]
@aashimawadhwa This PR is not complete. I am not sure that what to do next. Is this the complete thing that is expected for this issue. Do I need to do anything more or should I proceed with writting test.

**Comment by skbhagat0502** [comment]
> @aashimawadhwa This PR is not complete. I am not sure that what to do next. Is this the complete thing that is expected for this issue. Do I need to do anything more or should I proceed with writting test.
I have also pushed changes to the talawa api. Please have a look and tell me what should be done next.

**Comment by skbhagat0502** [comment]
> > @aashimawadhwa This PR is not complete. I am not sure that what to do next. Is this the complete thing that is expected for this issue. Do I need to do anything more or should I proceed with writting test.
> >Also I am not able to push changes to the talawa api. I don't know what is the problem.

**Comment by skbhagat0502** [comment]
> > > @aashimawadhwa This PR is not complete. I am not sure that what to do next. Is this the complete thing that is expected for this issue. Do I need to do anything more or should I proceed with writting test.
> > > Also I am not able to push changes to the talawa api. I don't know what is the problem. But I will fix it.

**Comment by skbhagat0502** [comment]
@aashimawadhwa currently the talawa admin interacts with the mongodb database for everything that is shown in the website. So the question arises how this will work if I add the ldap authentication method. How a user who is registered using ldap will be able to interact with the application.

**Comment by skbhagat0502** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/16b8e6ac-94eb-406a-9c51-6aeda7ba6a8b

I have completed the ldap authentication. Please have a look. I am now working on test and error messages.

**Comment by aashimawadhwa** [comment]
This implementation looks good to me i will review it properly till you submit the tests @skbhagat0502

**Comment by palisadoes** [comment]
@skbhagat0502 

Typically the Administrator would select local authentication or LDAP as a system wide configuration. That way you wouldn’t need to have separate LDAP and regular buttons.

So there needs to be a setting at the super admin level for this. The default would be local auth, with an LDAP option. If selected, the LDAP configuration parameters would be set on that screen.

Documentation for this would need to be added to the CONFIGURATION.md file to at least know that the option exists. 

Please investigate how systems using optional LDAP authentication work to see the best approach you would like to propose. 

Consider a likely scenario. LDAP is enabled by the super administrator in the portal, but they don’t have an LDAP config. They are suddenly unable to administer anything. How would they recover?

**Comment by skbhagat0502** [comment]
@palisadoes, I've been delving into the documentation, and it seems that there's a need for flexibility at the community level when it comes to authentication methods. In various communities, some super admins may opt for local authentication, while others prefer LDAP. To cater to this, it makes sense to display both authentication options on the website for community members, because we cannot create different instances of Talawa admin for each community and we cannot determine which authentication method to show when users open the website.

For empowering super admins to choose the authentication method for their community, we can incorporate an option at the super admin level. We can give them access for creating a organizational unit and set up the admin credentials.
To streamline this, my suggestion is to have a single LDAP server set up centrally, managed by us. We can give access to super admins to create different organizational units (OUs) within the central LDAP server, each corresponding to a community. Super admins can manage users within their community's OU.

Storing user emails or unique identifiers within each OU will serve as a bridge between MongoDB and the LDAP server, facilitating seamless communication. This approach not only aids in preventing the locking of administrative powers for super admins but also provides a standardized and more manageable solution. Super admins can reset passwords if needed, enhancing the overall user experience.

Also we need to update the design of the login and register page. So that if a user chooses the option for ldap authentication they can choose there ou and then register and login themselves. One more thing it might be chanlenging for us to make it easy for database to communicate but I am trying to find a way. One suggestion is to have a unique identifier like email that will be used as a bridge for communication between the ldap server and the mongodb database. Also my thought is that we should manage this issue in chunks so that we can avoid any potential bugs.

I'm also gearing up to update the documentation to reflect these enhancements. Additionally, I'm on the lookout for systems that effectively implement LDAP authentication as an alternative option for more insights and best practices.

Finally my thought is that once it is merged we can work on adding the access for super admins to create ou's for there community and adding the option in the login and register page to choose a ou before login or register using ldap.
Looking forward to your thoughts and suggestions on refining these strategies.

**Comment by palisadoes** [comment]
Comments:
1. The Talawa API instance must use either LDAP or local authentication, not both. The purpose of LDAP is to have centralized access control and therefore once implemented there must not be an option for local control. This must be transparent to the user. Having a choice between login methods is not in keeping with this goal. It is not a good security practice for the end user to choose the type of security their account should have. The Admin must make the choice behind the scenes as they know best the appropriate security for their needs.
1. There needs to be a way for only the Super Admin to override the LDAP login in case they have a misconfiguration and no one can access the apps. All other users must not have a choice. You haven't explained how this would be achieved. 
1. The LDAP server will be managed by the systems administrators for the community, not us.  
1. Admins must not have the option of selecting the type of authentication, only Super Admins.

Questions:
1. How will you handle different user roles with LDAP?
1. Are you proposing a single OU per API instance / community? 
    1. If not, how will you handle the creation of OUs for each organization in an intuitive way? 
    1. If so, how will you differentiate between access to different organization? 
1. Where and how will the API LDAP configuration be stored?

**Comment by skbhagat0502** [comment]
Hey @palisadoes, I got a bunch of questions swirling in my mind that I'd love to clear up all before diving into implementation. GitHub conversations tend to stretch, so was thinking, could we chat on Slack channel of talawa admin? Would really appreciate 10 mins of your time for a quick discussion. I am messaging you right now on talawa admin channel. Once you are avilable then message me. We will have a disscussion. Hope you don't mind. 
Thanks.

**Comment by palisadoes** [comment]
@EshaanAgg @skbhagat0502 is having difficulties with this PR and the Husky prechecks. Can you provide some assistance?

**Comment by skbhagat0502** [comment]
Hi @EshaanAgg I am getting error when I commit. This is due to husky pre-comit. I am gettting this error in talawa api as I need to edit some unauthorized files. How could I proceed because I am not able to push my code.

**Comment by EshaanAgg** [comment]
Just add the --no-verify flag while committing and it will bypass the Husky validation. Then you can make the PR.

**Comment by skbhagat0502** [comment]
> Just add the --no-verify flag while committing and it will bypass the Husky validation. Then you can make the PR.

Ok @EshaanAgg thanks.

**Comment by noman2002** [comment]
@skbhagat0502 Any update on this ?

**Comment by skbhagat0502** [comment]
> @skbhagat0502 Any update on this ?

@noman2002 my college exams are going on so I am on a break. Once my exams are over I will surely get back to this.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by palisadoes** [comment]
Closing due to inactivity and other priorities

**Pull request closed without merging**
