### PR TITLE
fixed: #455 Added translation for hint text in placeholder

### LINKED ISSUE #455: Bug: Hint text not changing according to the language.
**Describe the bug**
on changing the language the hint text in the Text filed remains in English and it does not look good.

**To Reproduce**

1. run talawa api and admin in your local machine
2. choose any other language expect English
3. see the issue on the signup page and login page

**Expected behavior**
The hint text should change as per the language.

**Actual behavior**
The hint text is not changing as of now.

**Screenshots**

Screenshot 2023-02-09 at 2 05 34 PM
Screenshot 2023-02-09 at 2 05 14 PM
Screenshot 2023-02-09 at 2 05 14 PM

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**

bugfix: added translation for the hint text

**Issue Number:**

Fixes #455 

**Did you add tests for your changes?**
not required

**Snapshots/Videos:**

Screenshot 2023-02-10 at 2 32 23 AM (2)
Screenshot 2023-02-10 at 2 32 30 AM (2)

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

No

**Other information**

Not Any

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@aashimawadhwa What tests can be added to ensure this doesn't happen again?

**Comment by Kevoniat** [comment]
> @aashimawadhwa What tests can be added to ensure this doesn't happen again?

These are mostly text changes not sure if any test pick that up

**Comment by palisadoes** [comment]
Thanks @Kevoniat . Please review

**Review by Tajcore — CHANGES_REQUESTED** [review]
@aashimawadhwa could you resolve the failing test case by configuring the language the test suite would be using (let's keep it at english)

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa could you resolve the failing test case by configuring the language the test suite would be using (let's keep it at english)

made the required changes please review.

**Review by Tajcore — CHANGES_REQUESTED** [review]
Please run prettier in the different locales' json files

**Comment by aashimawadhwa** [comment]
> Please run prettier in the different locales' json files

done @Tajcore

**Review by Tajcore — APPROVED** [review]
LGTM

**Review by palisadoes — APPROVED** [review]

**Comment by anshgoyalevil** [comment]
@Tajcore @palisadoes I was just checking on the Changes made via this PR, but, I didn't get the expected results.

image
image
.
+ Etc.

All placeholder texts are not being translated. @aashimawadhwa What are your opinions on this.?

**Comment by aashimawadhwa** [comment]
> @Tajcore @palisadoes I was just checking on the Changes made via this PR, but, I didn't get the expected results.
> 
> image image .
> 
>     * Etc.
> 
> 
> All placeholder texts are not being translated. @aashimawadhwa What are your opinions on this.?
I just checked some placeholders are left I will make a pr for them and work on it. thank you for letting me know  .

**Comment by palisadoes** [comment]
@aashimawadhwa I don't understand your response.
1. I asked the question on how we could test this and was told that it would be difficult. Once again, how can we test this? I really want to have good code. With the volume of requests we sometimes have to assume code integrity, especially with persons who have made previous PRs. 
1. This is fixable, let's see how we can get a quick resolution.

**Comment by aashimawadhwa** [comment]
I have already added the test  for all the changes i made in this PR and all of them were working perfectly fine,  this PR only contained translations for login and signup page and there working test. I have created a new issue for rest of the placeholders, that i will be fixing soon. there are actually no resolution degradation or failing tests.
@palisadoes .

**Comment by palisadoes** [comment]
1. Thanks, I didn't notice that they were slightly different.
1. Please check slack on the #talawa-admin channel

**Pull request merged**
