### PR TITLE
Remove Filter on the organizations screen

### LINKED ISSUE #1189: Remove Filter on the organizations screen
**Describe the bug**
Remove filtering in the organization screen, the aim is to remove the filter code.

**To Reproduce**

1. login into the talawa admin dashboard
2. go to the orglist
3. navigate the filter button
4. see the issue

**Screenshots**
Screenshot 2023-12-13 at 12 04 40 PM

**Additional details**
NA

### PR DESCRIPTION
**Pull request by Hasnain01-hub**
**What kind of change does this PR introduce?**
BugFix

**Issue Number:**

Fixes #1189

**Did you add tests for your changes?**
No

**Snapshots/Videos:**
orglist

**If relevant, did you update the documentation?**

**Summary**
Removed the filter option in the organization screen, the aim was to remove the filter feature code.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@Hasnain01-hub Please fix the failing tests. Our test code coverage system will fail if any of these conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold
3) The code does not comply with our linting check or other related formatting requirements 

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by Hasnain01-hub** [comment]
@Cioppolo14 Please check now.

**Comment by aashimawadhwa** [comment]
can you write test for the uncovered lines, you can check it here.

https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1272?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=PalisadoesFoundation

**Comment by noman2002** [comment]
@aashimawadhwa I think tests are not being effected in this PR.

**Comment by Hasnain01-hub** [comment]
@aashimawadhwa Yes, the failing tests are not due to changes done in this PR.

**Comment by rishav-jha-mech** [comment]
LGTM, also no tests are failing RN, so @palisadoes this can be merged now

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
