### PR TITLE
Feat/dropdown for time

### LINKED ISSUE #1239: Calendar Times Must be Dropdown or Clock Motif
**Is your feature request related to a problem? Please describe.**

1. The user has to enter the start and stop times for an event, while the dates are entered using the mouse
2. This is an inconsistent user experience

**Describe the solution you'd like**
1. Create a suitable interface
1. The solution must accommodate the mandatory use of seconds in the calendar timing
1. Work with @aashimawadhwa or @rishav-jha-mech for the desired interface selection
1. 100% test code coverage for the solution

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

1. Talawa image
image
1. Google image
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by VaibhavTalkhande**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #1239 

**Did you add tests for your changes?**

No but covers 100% test on changed files
**Snapshots/Videos:**
   
[Screencast from 2023-12-25 19-23-21.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/49303222/6705e852-55de-4230-a34e-24b7a6a4cab7)

**If relevant, did you update the documentation?**

**Summary**

create a  select form which improves user interface and user experience where user can select time form option given 
**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by VaibhavTalkhande** [comment]
@palisadoes  i have doing the changes by not including seconds

**Comment by EshaanAgg** [comment]
@VaibhavTalkhande Please checkout Material UI's [Time Picker](https://mui.com/x/react-date-pickers/time-picker/) components. They are visually more appealing, and they improve accessibility by allowing users to use keyboard navigation as well as use a mix of UI and typing to enter the time.

**Review by EshaanAgg — CHANGES_REQUESTED** [review]
Please address the comment above.

**Comment by VaibhavTalkhande** [comment]
> @VaibhavTalkhande Please check out Material UI's [Time Picker](https://mui.com/x/react-date-pickers/time-picker/) components. They are visually more appealing, and they improve accessibility by allowing users to use keyboard navigation as well as use a mix of UI and typing to enter the time. Integrating them would be the way forward IMO.

Ok fine I will use material ui i thought react bootstrap is used originally so # worked with it but I need to install material ui in project will that be ok and need some time

**Comment by EshaanAgg** [comment]
Material UI is added to the project as a dependency. You might need to add the additional date-picker package, and that is fine.

You can take on your time to work on the PR, but do drop weekly updates here to keep it active. Request a review when completed. Happy holidays!

**Comment by VaibhavTalkhande** [comment]
> Material UI has already been added to the project as a dependency. You might need to add the additional date-picker package, and that is fine.
> 
> You can take your time to work on the PR, but do drop weekly updates here to keep it active. Request a review when completed. Happy holidays!

Ok I will  give a update weekly. 
Thanks 😊

**Comment by palisadoes** [comment]
@rishav-jha-mech @aashimawadhwa Your thoughts on this design approach would be welcom

**Comment by VaibhavTalkhande** [comment]
> @rishav-jha-mech @aashimawadhwa Your thoughts on this design approach would be welcom

Should I move forward with material ui

**Comment by aashimawadhwa** [comment]
> > @rishav-jha-mech @aashimawadhwa Your thoughts on this design approach would be welcom
> 
> Should I move forward with material ui

cannot we solve this with react-bootstrap? i think @rishav-jha-mech  should have a major say

**Comment by rishav-jha-mech** [comment]
@aashimawadhwa @EshaanAgg, if we should have a dropdown for selecting time, it can be done using bootstrap also. But since we are using MUI too, we can use `DatePicker` and `TimePicker` components from there.

But the UI will not blend in with other input elements, right ?, for that @VaibhavTalkhande you need to

1. Use custom styling for both the above mentioned components (Make it look similar to other input boxes)
2. Make sure that the user can not select a time in past while creating an event
3. By default `DatePicker` will be rendered. and `All Day ?` is `true`, when `All Day` is set to `false` render the start and end time using `TimePicker` component.

This change will be required in all the places where we are using time/date drop downs, just make sure that the styling looks similar to Bootstrap, you should make this a custom component since we will be using this a lot in our project and we would not want to write the custom CSS everywhere we use it.

`react-datepicker` is what we are using at the moment, If you manage to eliminate the project's dependency on this library, feel free to remove it from the package.json file as well.

**Comment by VaibhavTalkhande** [comment]
> @aashimawadhwa @EshaanAgg, if we should have a dropdown for selecting time, it can be done using bootstrap also. But since we are using MUI too, we can use `DatePicker` and `TimePicker` components from there.
> 
> But the UI will not blend in with other input elements, right ?, for that @VaibhavTalkhande you need to
> 
> 1. Use custom styling for both the above mentioned components (Make it look similar to other input boxes)
> 2. Make sure that the user can not select a time in past while creating an event
> 3. By default `DatePicker` will be rendered. and `All Day ?` is `true`, when `All Day` is set to `false` render the start and end time using `TimePicker` component.
> 
> This change will be required in all the places where we are using time/date drop downs, just make sure that the styling looks similar to Bootstrap, you should make this a custom component since we will be using this a lot in our project and we would not want to write the custom CSS everywhere we use it.
> 
> `react-datepicker` is what we are using at the moment, If you manage to eliminate the project's dependency on this library, feel free to remove it from the package.json file as well.

Ok I will make two custom components of date and time using mui and  will replace react date picker  and

**Review by palisadoes — CHANGES_REQUESTED** [review]
1. You have 23 files in this pull request. Many of them have nothing to do with solving the issue. Please don't include them in this pull request.
1. You are doing something wrong

**Comment by VaibhavTalkhande** [comment]
Ok

**Comment by VaibhavTalkhande** [comment]
@palisadoes  fixed the issue i was updating my branch i didnt see that change in pr

**Review by noman2002 — CHANGES_REQUESTED** [review]
Add validation, that end time cannot be less than or equal to start time.

**Comment by VaibhavTalkhande** [comment]
> Add validation, that end time cannot be less than or equal to start time.
Ok I will do it i have created made this thing in date component wher user cannot select past date

**Comment by palisadoes** [comment]
Please fix the conflicting files

**Comment by rishav-jha-mech** [comment]
@VaibhavTalkhande please fix the conflicting files, once those two components are ready, upload its pic here so that we can review the UI as well

**Comment by VaibhavTalkhande** [comment]
> @VaibhavTalkhande please fix the conflicting files, once those two components are ready, upload its pic here so that we can review the UI as well

Ok

**Comment by aarishshahmohsin** [comment]
I think this date selector can be implemented. 
hello
This is minimal and will serve the purpose. I prefer this one.

one more option is the material ui one . 


comment on the issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/1239#issuecomment-1879968979

**Pull request closed without merging**
