### PR TITLE
 fix: Fixed likes and comments not working with User Posts

### LINKED ISSUE #1688: Bug: Likes and Comments for User Posts not working
**Describe the bug**
The likes and Comments card which shows comment for specific post in User is not working because `ORGANIZATION_POST_LIST` query is missing `likedBy` and `comments` array which are responsible for above features in UI.

In [`src/Screen/UserPortal/Home/Home.tsx`](https://github.com/PalisadoesFoundation/talawa-admin/blob/e04abf34a2924c4680d4bc81d59fe85afa618ed6/src/screens/UserPortal/Home/Home.tsx#L333-L366) when we we look at code for rendering posts we require `likedBy` and `comments` array to be returned by `ORGANIZATION_POST_LIST` results which is not being returned as a result above features don't work.

**To Reproduce**

1. Sign in as user
2. Open an organization page
3. Like Or Add comment
4. Reload the Page the changes would be reset

**Expected behavior**
On liking or commenting the posts (in user's Organization Dashboard) the changes made should be persistent and be able to render on screen even after reload

**Actual behavior**
On liking or commenting the posts (in user's Organization Dashboard) the changes made are wiped out. as on reload the new data is not being fetched due to missing attribute in query.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/17522da5-c243-47f5-8325-07e50fc27928

### PR DESCRIPTION
**Pull request by Doraemon012**
**What kind of change does this PR introduce?**

- This PR is a **bug fix**.

**Issue Number:**
- Fixes #1688

**Did you add tests for your changes?**
No.

**Snapshots/Videos:**

[Screencast from 2024-04-06 12-23-31.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/d1c51534-c443-4d50-86f8-ff160e2c7bc3)

**If relevant, did you update the documentation?**
No.

**Summary**

- This PR addresses a bug related to the likes and comments functionality for user posts.
- The bug caused the likes and comments not to persist after reloading the page, and the likes on comments rendering only after reloading the page.
- This was caused by the `ORGANIZATION_POST_LIST` query not returning the required `likedBy` and `comments` arrays, and the fact that the `likedBy` array was not changed immidiately when the user liked a comment.`

**Does this PR introduce a breaking change?**

No.

**Other information**

N/A

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by palisadoes** [comment]
Please get the test code coverage of the patch higher. It's only 11%

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please get the test code coverage of the patch higher. It's only 11%

**Comment by Doraemon012** [comment]
@palisadoes, I'm working on it, will commit the changes ASAP

**Comment by Doraemon012** [comment]
@palisadoes  I have written the tests. Please take a look.

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
