### PR TITLE
refactored CSS files in src/screens/Users

### LINKED ISSUE #2528: Refactor CSS files in src/screens/Users
# Refactor CSS files in src/screens/Users

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

### PR DESCRIPTION
**Pull request by antriksh-9**
**What kind of change does this PR introduce?**

refactored CSS files in src/screens/Users

**Issue Number:**

Fixes #2528 

**Did you add tests for your changes?**
No

**Snapshots/Videos:**

Tests:

Screenshot 2024-12-04 204005

After changes:

Screenshot 2024-12-04 203352

**If relevant, did you update the documentation?**
Not Relevant

**Summary**
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern.

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced layout and responsiveness for user interface components.
	- Introduced new styles for `.listBox` and `.notFound` classes.

- **Bug Fixes**
	- Improved logic for user type handling and loading states in the Users component.
	- Updated rendering logic for "not found" messages to enhance accessibility.

- **Style**
	- Updated styles for button containers and input fields, including responsive adjustments for various screen sizes.
	- Renamed and modified styles for input elements to improve layout and usability.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@antriksh-9  Please fix the failing tests.

**Comment by antriksh-9** [comment]
> @antriksh-9 Please fix the failing tests.

I ran `npm run test` for this particular file and I got all tests passed, I have attached a screenshot in pr description. 
Which tests do I need to fix here then?

**Comment by antriksh-9** [comment]
@coderabbitai review

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by palisadoes** [comment]
1. Please make sure coderabbit.ai approves your PR
1. Make sure all tests pass (except introspection)
1. Please make sure that the code coverage for your patch reaches at least 95%

**Comment by palisadoes** [comment]
Please fix the conflicting file

**Comment by antriksh-9** [comment]
@palisadoes 
I am getting eslint error in Users.tsx file for `no-explicit-any` 
`94:16  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any`
So what should I use instead of `any` or can I do this: `"@typescript-eslint/no-explicit-any": "off" `?

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
