### PR TITLE
Fixed Bug #2455

### PR DESCRIPTION
**Pull request by AryanSwaroop**
**What kind of change does this PR introduce?**

Fixed User role not displaying bug in people section. This PR changes the interface that was causing mismatch.

**Issue Number:**

 #2455

**Did you add tests for your changes?**

yes

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

No , not relevant

**Summary**

The people section without any role looks empty and error full so this PR solves it , when users like me use this software.
https://github.com/PalisadoesFoundation/talawa-admin/issues/2455

**Does this PR introduce a breaking change?**

Np

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Updated member role representation to use GraphQL typename instead of user-defined type.
- **Tests**
	- Introduced new tests to ensure the structure of `InterfaceMember` is maintained.

### CODE REVIEW

**Comment by Cioppolo14** [comment]
@AryanSwaroop Please fix the first comment so that each issue listed automatically closes.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please add tests so that this doesn't happen again

**Comment by AryanSwaroop** [comment]
sure ! on it

**Comment by AVtheking** [comment]
Update your branch with latest upstream .
Add test so that it doesn't happens in future

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
