### PR TITLE
fix: Fixed inconsistent left drawer expansion/collapse behavior

### LINKED ISSUE #1897: Inconsistent Left Drawer Expansion/Collapse Behavior
**Describe the bug**
The left drawer expansion/collapse functionality for screens smaller than `820px` is inconsistent. When the screen width is less than or equal to `820px`, the left drawer fails to function properly, both in the SuperAdmin screen and the Organization Dashboard screen.

**To Reproduce**

1. Login as SuperAdmin.
2. Adjust the screen width to tablet size or anything less than or equal to `820px`.
3. Attempt to interact with the left sidebar by clicking on it.
4. Navigate to any organization Dashboard.
5. Adjust the screen width to tablet size or anything less than or equal to `820px`.
6. Try clicking on the left sidebar.

**Expected behavior**
The left drawer should expand and collapse smoothly when clicked, mirroring its functionality on screens wider than `820px`.

**Actual behavior**
Expansion and collapse of the left drawer for both the SuperAdmin screen and Organization Dashboard screen are malfunctioning on screens with a width of `820px` or less.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/fdb4cbee-40ea-487b-a0db-2baf00bb079a

**Additional details**
Same as above.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**

Refactoring of the left Drawer component in tablet  and mobile screens.

**Issue Number:**

Fixes #1897 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/4f9ecbff-758c-46ec-98d4-5e39895d6e77

Also fixes

- Current Situation

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/67cb7e78-5743-4273-bff7-320d55628ecc

- After the fixes from this PR

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/bb9e8c82-73bd-400f-9eaa-f4e7ff323738

 

**If relevant, did you update the documentation?**
N/A

**Summary**
- Adjusted the left drawer component to function properly on screens with a width of 820px or less.
- Ensured smooth expansion and collapse of the left drawer when clicked.
- Ensured the overflow-y of content is handled in smaller screens.
- Modified the changes for organization dashboard screens to match the superadmin screens when the left drawer is collapsed.
- Covered the changes with tests.
- Ensured no other functionality got affected.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, this PR fixes another bug which I had already mentioned in the PR description. Do I need to raise an issue for that then link this PR to that issue?

**Review by palisadoes — APPROVED** [review]

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar I think its fine as it is, but would you mind confirming that the issue that is fixed but not documented isn't in an existing open issue? In case that issue needs to be closed?

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, I've verified that there is no existing issue for the fix I've made.

**Comment by Cioppolo14** [comment]
Thank you! @akhilender-bongirwar

**Pull request merged**
