### PR TITLE
Update Router Function [Fixes #636]

### LINKED ISSUE #636: Router issue causing ```OrgUpdate```, ```Peoples``` and other such pages to break
**Describe the bug**
In the recent PR https://github.com/PalisadoesFoundation/talawa-admin/pull/580 The ```window.location.replace(url);``` was replaced with ```history.push(url);``` due to which, all the pages which were relying on window's url are failing to load.

**To Reproduce**

1. Open Admin Panel
2. Try opening Peoples page
3. You will be redirected to Organizations Page
4. Same goes for OrgUpdate page.

**Expected behavior**
The pages must load.

**Actual behavior**
They aren't loading.

**Screenshots**
Not Relevant.

### PR DESCRIPTION
**Pull request by anshgoyalevil**
**What kind of change does this PR introduce?**
In the recent PR https://github.com/PalisadoesFoundation/talawa-admin/pull/580 The window.location.replace(url); was replaced with history.push(url); due to which, all the pages which were relying on window's url are failing to load. This PR merge that parameter.

**Issue Number:**

Fixes #636 

**Did you add tests for your changes?**
Not Relevant

**Snapshots/Videos:**
Not Required

**If relevant, did you update the documentation?**
Not Required

**Does this PR introduce a breaking change?**
No

**Other information**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by aviraldevv** [comment]
@anshgoyalevil  <Calendar eventData={data?.eventsByOrganizationConnection} /> try optional chaining tests should pass I have tried in my local system with your changes.
Screenshot_398

**Comment by anshgoyalevil** [comment]
@aviraldevv 

Same here. Tests are passing in my local system.

I have just made an empty commit. Lets see if it resolves the problem

**Comment by anshgoyalevil** [comment]
@aviraldevv Thanks for figuring the possible cause for this issue, but the issue got resolved by re-running the Workflow.

This seems like an issue with improper tests written.

**Comment by aviraldevv** [comment]
> @aviraldevv Thanks for figuring the possible cause for workflow failure, but all tests got passed on re-running the Workflow.
> 
> This seems like an issue with improper tests written.

Reason why sometimes tests are failing. We should do optional chaining to prevent this.

**Comment by anshgoyalevil** [comment]
@aviraldevv 

Please create a new issue for resolving this, so it doesn't affect other PRs.

**Comment by aviraldevv** [comment]
> @aviraldevv
> 
> Please create a new issue for resolving this, so it doesn't affect other PRs.

@anshgoyalevil Actually this issue is being tackled by some other contributor.

**Comment by anshgoyalevil** [comment]
@palisadoes 

Please review this PR as it will resolve the whole functionality of admin panel which is currently broken.

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
