### PR TITLE
Fixes #478 : Implemeneted calendar to the Event tab

### LINKED ISSUE #478: Convert Events Page into a Calender View
**Is your feature request related to a problem? Please describe.**
The events are currently displayed in a tile view on the events page. We have a button that we can use to create events with, however they just show up as tiles. The creation and viewing of events over a calendar is what we actually desire. It will be easier to use and more convenient in this way.

**Describe the solution you'd like**
Events can be added to, viewed, edited, and deleted on a calendar. An event should have descriptions that include the title, start and conclusion times, the nature of the event, etc.

**Additional context**
You can take reference from the images below.

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
New Feauture

**Issue Number:**

Fixes #478 

**Did you add tests for your changes?**
yes

**Snapshots/Videos:**

[www_screencapture_com_2023-3-6_16_59.webm](https://user-images.githubusercontent.com/73706697/223098871-c4cc9655-2936-45ec-8840-c6ae20afc087.webm)

**If relevant, did you update the documentation?**
not Required

**Summary**
Implemented the calendar for the event tab in the dashboard , with visible events on the respective dates. 

**Does this PR introduce a breaking change?**
not any

**Other information**

not any
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@palisadoes  please review once.

**Comment by aashimawadhwa** [comment]
I am not able to get the error, all the test are passing but there are console warn which i am not getting. @palisadoes

**Comment by palisadoes** [comment]
1. Please do a minor commit to see if it fixes it.
1. Also ask the #talawa-asmin slack channel for assistance

**Comment by aashimawadhwa** [comment]
@palisadoes  After undoing all the changes I made the warnings still exists, not sure how should I proceed now.

**Comment by palisadoes** [comment]
Could this be due to you using the latest version of Yarn?

- https://github.com/PalisadoesFoundation/talawa-admin/issues/493

**Comment by aashimawadhwa** [comment]
The issue can be this or there exists some variable with have a typo  any of these could be the reason.  @palisadoes

**Comment by palisadoes** [comment]
Unfortunately this is not an area of expertise for me. @xoldyckk @noman2002 @Kevoniat @Tajcore Do you have any suggestions?

**Comment by palisadoes** [comment]
I've asked some of the mentors to take a look. Hopefully they'll have an answer

**Comment by aashimawadhwa** [comment]
The test and functionality of calendar is working fine and I feel we have to enhance this feature in the future. 

The chnages i made are not causing any warnings for now, 
We can have the calendar view in production until i look into why this is happening.
Can this be done @palisadoes

**Comment by palisadoes** [comment]
It's now failing because the code coverage levels have declined.

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1. The overall code coverage drops below the target threshold of the repository
1. Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by aashimawadhwa** [comment]
> 1. he overall code coverage drops below the target threshold of the repository


 I checked for the failing tests, and the major uncovered test are in organization events and that too for filters, after the calendar view we do not need them and a lot will be removed from this file.
 
 I am refraining to remove this much in one PR to not cause any failure.
 For eg we cannot filter by location, tittle etc in the calendar view. after implementing the calendar correctly we can focus on the code coverage for these files. @palisadoes

**Comment by noman2002** [comment]
> Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:
> 
>     1. The overall code coverage drops below the target threshold of the repository
> 
>     2. Any file in the pull request has code coverage levels below the repository threshold
> 
> 
> We do this to ensure the overall reliability of the code base is maintained.

I think the coverage drop is obvious because there is a lot of file and functional changes. I think we should merge this if all the tests are passing and open separate issues to get the coverage up one by one for each file.

**Review by noman2002 — APPROVED** [review]

**Comment by palisadoes** [comment]
@aashimawadhwa  Please open an issue to test:
- [src/components/EventCalendar/Calendar.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/537?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvRXZlbnRDYWxlbmRhci9DYWxlbmRhci50c3g=)

This issue addresses  tests for [.../screens/OrganizationEvents/OrganizationEvents.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/537?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3NjcmVlbnMvT3JnYW5pemF0aW9uRXZlbnRzL09yZ2FuaXphdGlvbkV2ZW50cy50c3g=)
- https://github.com/PalisadoesFoundation/talawa-admin/issues/482

**Pull request merged**
