### PR TITLE
Proper Testing Of Pagination In All List Views

### LINKED ISSUE #472: Feature Request: Proper Testing of pagination in all List Views
**Is your feature request related to a problem? Please describe.**
We are displaying various lists throughout our UI, like `OrgList`, `UserList`, `AdminList` etc. A common problem across the tests of all these components is that there is no check on the fact if the pagination of the results is working correctly or not (i.e. the right cards are being displayed on the right page, and the results are displayed in the correct order)

**Describe the solution you'd like**
In all of these components/screens, we must add additional tests.
1. Use a library like `faker.js` to pro-grammatically generate large `MOCKS` (around 100-150 items).
2. Add tests that mock and test the following functionality:
- When the `itemsPerPage` is all, the count of the elements rendered must be equal to the length of the items mocked.
- For any two randomly chosen `itemsPerPage` values, we must choose two random `pageNumbers` and compare the data of the first and the last elements of the page to that of the MOCK. Random selection of the numbers must be done, to ensure the tests are non deterministic and thus offer more comprehensive testing.

**Approach to be followed (optional)**
- Migrate one such component according to the approach described. 
- Treat it as a parent issue, and open child issues for all components where such pagination components are being used.

**Additional context**
This would help to improve the quality of our testing, and not just the coverage.

### PR DESCRIPTION
**Pull request by Sheguun**
**What kind of change does this PR introduce?**
The PR introduces proper testing of pagination in all list views.

feature

**Issue Number:**
Fixes #472

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**
No

**Summary**
It comprises of tests used to affirm that the pagination feature in pages utilizing it is working correctly.

**Does this PR introduce a breaking change?**
Yes. A single test is broken due to an update to the setup required to test the pagination feature in OrgList page.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

**Comment by Sheguun** [comment]
> Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Alright sir @palisadoes

**Comment by Sheguun** [comment]
@palisadoes @kevoniat please review it. The issue has been solved

**Comment by Sheguun** [comment]
@palisadoes For this error "checking for unauthorized file changes", there's no concrete information for me to debug

**Comment by palisadoes** [comment]
Please fix the failing tests. Lint the code.

Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by Sheguun** [comment]
> Please fix the failing tests. Lint the code.
> 
> Our test code coverage system will fail if either of these two conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 
> We do this to ensure the overall reliability of the code base is maintained.

@palisadoes I'm surprised because I have fixed all these errors that is now showing up. Something must have happened in the overall code.

**Comment by anshgoyalevil** [comment]
@Sheguun 

You have added two new packages ```faker``` and ```lodash```. This made changes to package.json file which triggered the unauthorized file changes CI.

- Use can use custom test data in place of using faker's random data
- You may equate the mocks and the returned query without lodash too. Check out other tests which follow that approach.

For fixing lint errors, run ```yarn lint:fix```

**Comment by Sheguun** [comment]
> > @Sheguun
> > You have added two new packages `faker` and `lodash`. This made changes to package.json file which triggered the unauthorized file changes CI.
> > 
> > * Use can use custom test data in place of using faker's random data
> > * You may equate the mocks and the returned query without lodash too. Check out other tests which follow that approach.
> > 
> > For fixing lint errors, run `yarn lint:fix`
> 
> Alright will try it out... Thanks

@anshgoyalevil I have some questions tho..

If the tests comparing the query data was passing, I wouldn't have used lodash.
How do we generate 100 random organizations data without that library? (Faker is for the random data generation. Lodash is for the comparison of the mock data.)

**Comment by anshgoyalevil** [comment]
@Sheguun 

Use case of faker is justified. But, using lodash for mock data comparison seems a bit odd here.

Let's wait for mentors suggestions.

Meanwhile you can commit the linted code

**Comment by Sheguun** [comment]
> @Sheguun
> 
> Use case of faker is justified. But, using lodash for mock data comparison seems a bit odd here.
> 
> Let's wait for mentors suggestions.
> 
> Meanwhile you can commit the linted code

@anshgoyalevil @palisadoes Jest cannot perform deep object comparison, that's why I made use of lodash.

**Comment by Sheguun** [comment]
> @Sheguun
> 
> I just checked your code changes. You actually don't need `faker` and `lodash`.
> 
> Why to put random data in mocks using faker, when you can just add manual data. Just rethink about the approach. You are generating fake first name, last name, etc using faker, but would the tests fail if you add hardcoded `"firstname"` and `"lastname"` there instead of `faker.name.fullName()` thing while running the loop.
> 
> Also, you can compare two objects if they are deep equal using Jest using the following example syntax.
> 
> ```ts
> test('Correct mock data should be queried', async () => {
>     const dataQuery1 =
>       MOCKS[0]?.result?.data?.organizationsMemberConnection?.edges;
>     const dataQuery2 =
>       MOCKS[1]?.result?.data?.organizationsMemberConnection?.edges;
>     const dataQuery3 = MOCKS[2]?.result?.data?.users;
> 
>     expect(dataQuery1).toEqual([
>       {
>         __typename: 'User',
>         _id: '64001660a711c62d5b4076a2',
>         firstName: 'Aditya',
>         lastName: 'Memberguy',
>         image: null,
>         email: 'member@gmail.com',
>         createdAt: '2023-03-02T03:22:08.101Z',
>       },
>     ]);
> ```
> 
> Btw, your code looks pretty good. You have added the Types for TypeScript neatly.

Thank you so much @anshgoyalevil 
I want have some clarity please... I am testing the pagination feature of the pages using the Pagination component. I need to render lots of organization which will be rendered on the page based on the value of rowsPerPage. If 30 is selected from the rowsPerPage, how do I then render 30 organizations if we are making use of manual creation of the organization. Does it mean I have to manually create at least 30 organizations?

**Comment by anshgoyalevil** [comment]
@Sheguun 

You didn't get my point. You don't have to manually create mock data of 30 orgs. You have to pass the value of each object inside the object loop as same.

For example:

Instead of this:
```
for (let x = 0; x < 100; x++) {
  organizations.push({
    _id: faker.datatype.uuid(),
    image: '',
    name: faker.name.fullName(),
    creator: {
      firstName: faker.name.firstName(),
      lastName: faker.name.lastName(),
    },
    admins: [
      {
        _id: faker.datatype.uuid(),
      },
    ],
    members: {
      _id: faker.datatype.uuid(),
    },
    createdAt: faker.date.birthdate().toString(),
    location: faker.address.city(),
  });
}
```

You can use:

```
for (let x = 0; x < 100; x++) {
  organizations.push({
    _id: x,
    image: '',
    name: "orgx",
    creator: {
      firstName: "firstname",
      lastName: "lastname",
    },
    admins: [
      {
        _id: x+99,
      },
    ],
    members: {
      _id: x+199,
    },
    createdAt: any date,
    location: "location",
  });
}
```

**Comment by Sheguun** [comment]
> @Sheguun
> 
> You didn't get my point. You don't have to manually create mock data of 30 orgs. You have to pass the value of each object inside the object loop as same.
> 
> For example:
> 
> Instead of this:
> 
> ```ts
> for (let x = 0; x < 100; x++) {
>   organizations.push({
>     _id: faker.datatype.uuid(),
>     image: '',
>     name: faker.name.fullName(),
>     creator: {
>       firstName: faker.name.firstName(),
>       lastName: faker.name.lastName(),
>     },
>     admins: [
>       {
>         _id: faker.datatype.uuid(),
>       },
>     ],
>     members: {
>       _id: faker.datatype.uuid(),
>     },
>     createdAt: faker.date.birthdate().toString(),
>     location: faker.address.city(),
>   });
> }
> ```
> 
> You can use:
> 
> ```ts
> for (let x = 0; x < 100; x++) {
>   organizations.push({
>     _id: x,
>     image: '',
>     name: "orgx",
>     creator: {
>       firstName: "firstname",
>       lastName: "lastname",
>     },
>     admins: [
>       {
>         _id: x+99,
>       },
>     ],
>     members: {
>       _id: x+199,
>     },
>     createdAt: any date,
>     location: "location",
>   });
> }
> ```

@anshgoyalevil Thanks so much for this

**Comment by anshgoyalevil** [comment]
> <h2>Manage this branch in <a href="https://app.squash.io/accounts/">Squash</a></h2>Test this branch here: <a href='https://sheguunpagination-tests-erc3i.squash.io' target='_blank'>https://sheguunpagination-tests-erc3i.squash.io</a><br/>

@palisadoes 

This is the default Squash Behaviour. I will create a PR to disable it temporarily, until I start adding the CD files.

**Comment by palisadoes** [comment]
@anshgoyalevil 

1. When and how was this enabled? Please provide a reference PR. I review so many.
1. We have other repos where it could have been tested.
1. We need a communication strategy for slack

Better planning is needed. The less unexpected things the better.

**Comment by Sheguun** [comment]
@palisadoes @anshgoyalevil The issue assigned to me has been fixed but when running all test altogether, some test are failing due to the default time allocated to them.
Is there anything that could be done?

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil 
> 
> 1. When and how was this enabled? Please provide a reference PR. I review so many.
> 1. We have other repos where it could have been tested.
> 1. We need a communication strategy for slack
> 
> Better planning is needed. The less unexpected things the better. 

Sir, the Squash PR Comments are enabled by default when we install this tool. It is not because of any PR.

Could you please provide me the details of those Repositories where we could test things out. I stay active on slack, we can continue over there, and if my chat shows inactive, you may DM me, I will be online right then.

**Comment by Sheguun** [comment]
@palisadoes @kevoniat Pease review it. My own issue gas been fixed.
What i noticed is, the error is not coming from my own test because it has been fixed. The error is coming from other test.

**Comment by Sheguun** [comment]
@anshgoyalevil I'd like to have a Google Meet call with you please. When will you be free?

**Comment by palisadoes** [comment]
Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.

Your PR has been assigned reviewers. Please contact them either in this PR or via slack to get your code reviewed and approved. They should also be the:

1) arbitrators of future discussions with other contributors about the validity of your changes
2) point of contact for evaluating the validity of your work
3) person who verifies matching issues by others that should be closed.

Please make sure your code passes all tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by Sheguun** [comment]
> Please fix the first comment so that each issue listed automatically closes. The PR_GUIDELINES.md file has details.
> 
> Your PR has been assigned reviewers. Please contact them either in this PR or via slack to get your code reviewed and approved. They should also be the:
> 
> 1. arbitrators of future discussions with other contributors about the validity of your changes
> 2. point of contact for evaluating the validity of your work
> 3. person who verifies matching issues by others that should be closed.
> 
> Please make sure your code passes all tests. Our test code coverage system will fail if either of these two conditions occur:
> 
> 1. The overall code coverage drops below the target threshold of the repository
> 2. Any file in the pull request has code coverage levels below the repository threshold
> 
> We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

@palisadoes Please what first comment are you referring to? Thanks

**Comment by Sheguun** [comment]
> ## [Codecov](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) Report
> > Merging [#797](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([878bbb3](https://github.com/PalisadoesFoundation/talawa-admin/commit/878bbb34e3393e361865d4f7b54bf9574596725c)) into [develop](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/commit/f8747de19dafeeca09a131924f986a53b9e1cbec?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation) ([f8747de](https://github.com/PalisadoesFoundation/talawa-admin/commit/f8747de19dafeeca09a131924f986a53b9e1cbec)) will **increase** coverage by `0.06%`.
> > The diff coverage is `n/a`.
> 
> ```diff
> @@             Coverage Diff             @@
> ##           develop     #797      +/-   ##
> ===========================================
> + Coverage    91.54%   91.61%   +0.06%     
> ===========================================
>   Files           64       64              
>   Lines         1467     1467              
>   Branches       369      369              
> ===========================================
> + Hits          1343     1344       +1     
> + Misses         118      117       -1     
>   Partials         6        6              
> ```
> 
> [Impacted Files](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)	Coverage Δ	
> [...components/AdminDashListCard/AdminDashListCard.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvQWRtaW5EYXNoTGlzdENhcmQvQWRtaW5EYXNoTGlzdENhcmQudHN4)	`100.00% <ø> (ø)`	
> [...c/components/OrgAdminListCard/OrgAdminListCard.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvT3JnQWRtaW5MaXN0Q2FyZC9PcmdBZG1pbkxpc3RDYXJkLnRzeA==)	`100.00% <ø> (ø)`	
> [...components/OrgPeopleListCard/OrgPeopleListCard.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvT3JnUGVvcGxlTGlzdENhcmQvT3JnUGVvcGxlTGlzdENhcmQudHN4)	`100.00% <ø> (ø)`	
> [src/components/PaginationList/PaginationList.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvUGFnaW5hdGlvbkxpc3QvUGFnaW5hdGlvbkxpc3QudHN4)	`100.00% <ø> (ø)`	
> [...components/SuperDashListCard/SuperDashListCard.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvU3VwZXJEYXNoTGlzdENhcmQvU3VwZXJEYXNoTGlzdENhcmQudHN4)	`100.00% <ø> (ø)`	
> [src/components/UserListCard/UserListCard.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL2NvbXBvbmVudHMvVXNlckxpc3RDYXJkL1VzZXJMaXN0Q2FyZC50c3g=)	`100.00% <ø> (ø)`	
> [src/screens/OrgList/OrgList.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3NjcmVlbnMvT3JnTGlzdC9PcmdMaXN0LnRzeA==)	`98.07% <ø> (+1.92%)`	
> [.../screens/OrganizationPeople/OrganizationPeople.tsx](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/797?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation#diff-c3JjL3NjcmVlbnMvT3JnYW5pemF0aW9uUGVvcGxlL09yZ2FuaXphdGlvblBlb3BsZS50c3g=)	`84.26% <ø> (ø)`	
> mega We’re building smart automated test selection to slash your CI/CD build times. [Learn more](https://about.codecov.io/iterative-testing/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation)

@anshgoyalevil @kevoniat Please review the code as all checks is passed. Thank you

**Comment by anshgoyalevil** [comment]
@Sheguun 

Please update the first comment. First comment means the PR description where you have written what this PR is about. Use the GitHub's syntax for linking an issue which closes that issue when the linked PR is merged.

It looks like
```
Fixes #issuenumber
```

**Comment by Sheguun** [comment]
> @Sheguun
> 
> Please update the first comment. First comment means the PR description where you have written what this PR is about. Use the GitHub's syntax for linking an issue which closes that issue when the linked PR is merged.
> 
> It looks like
> 
> ```
> Fixes #issuenumber
> ```

Thank you for this @anshgoyalevil

**Comment by anshgoyalevil** [comment]
You have changed the ```yarn.lock``` file. It is not supposed to be modified.

**Comment by Sheguun** [comment]
> You have changed the `yarn.lock` file. It is not supposed to be modified.
> 
> Rest everything looks good.

What can be done now please?

**Comment by anshgoyalevil** [comment]
> > @Sheguun
> > Please update the first comment. First comment means the PR description where you have written what this PR is about. Use the GitHub's syntax for linking an issue which closes that issue when the linked PR is merged.
> > It looks like
> > ```
> > Fixes #issuenumber
> > ```
> 
> Thank you for this @anshgoyalevil So if u get you well, I should edit it this way: Fixes #797 right?

Yes.

**Comment by Sheguun** [comment]
@anshgoyalevil After fixing the yarn.lock, the workflow was tested again but it failed... Is there something I'm doing wrong please?

You can take a look at the code coverage

**Comment by kayceeDev** [comment]
I am thinking that generating these times slows the test down. He can make the data smaller. @Sheguun you can also look at what @anshgoyalevil suggested to remove commits that are not yours in the PR.

**Comment by Sheguun** [comment]
Screenshot from 2023-03-27 14-54-46
This is what i got when i ran the test again @anshgoyalevil @kayceeDev

**Comment by anshgoyalevil** [comment]
> Screenshot from 2023-03-27 14-54-46 This is what i got when i ran the test again @anshgoyalevil @kayceeDev

Seems like you haven't implemented the test correctly. Try using ```jest.setTimeout()``` method, if it works.

**Comment by Sheguun** [comment]
> > Screenshot from 2023-03-27 14-54-46 This is what i got when i ran the test again @anshgoyalevil @kayceeDev
> 
> Seems like you haven't implemented the test correctly. Try using `jest.setTimeout()` method, if it works.

Alright let me do that

**Comment by Sheguun** [comment]
@palisadoes Please assign some mentors to rerun this test. Someone else's test is the one having issues and it's affecting the whole workflow.

I've solved my own issue for long. Please I'd appreciate it if the code is checked again. Mine is fixed

**Comment by Sheguun** [comment]
Screenshot from 2023-03-27 20-33-47

@palisadoes Please review it. All the test have passed. Thank you

**Comment by palisadoes** [comment]
Your PR has been assigned reviewers. Please contact them either in this PR or via slack to get your code reviewed and approved. They should also be the:

1) arbitrators of future discussions with other contributors about the validity of your changes
2) point of contact for evaluating the validity of your work
3) person who verifies matching issues by others that should be closed.

Please make sure your code passes all tests. Our test code coverage system will fail if either of these two conditions occur:

1) The overall code coverage drops below the target threshold of the repository
2) Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained. This is a prerequisite for getting your PR approved. Assigned reviewers regularly review the PR queue and tend to focus on PRs that are passing.

**Comment by Sheguun** [comment]
Hello @ttaylor92 @palisadoes @kevoniat
Please I'd like you to review this workflow.

**Review by Kevoniat — APPROVED** [review]

**Comment by Sheguun** [comment]
Thank you sir @Kevoniat

**Comment by Sheguun** [comment]
@palisadoes Please can you assign another reviewer for this? I'm waiting for the second review so the PR could be merged. Thanks

**Pull request merged**
