### PR TITLE
Fixed Inconsistent Use of Icons to Minimize Left Column Navbar in Event Management Screen

### LINKED ISSUE #1240: Inconsistent use of icons to minimize the left column navbar
**Is your feature request related to a problem? Please describe.**
The `event dashboard `page does not use the same minimization method as the other screens in the app

**Describe the solution you'd like**
Use the same method used in the main organization pages

**Describe alternatives you've considered**
- None

**Approach to be followed (optional)**
Consider the approach used in this issue
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1159

**Additional context**
1. Calendar Screen
image
1. Event dashboard page
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by akhilender-bongirwar**
**What kind of change does this PR introduce?**
- Implemented the same minimization method used in the main organization pages, ensuring a consistent user experience throughout the application.

**Issue Number:**

Fixes #1240 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/05bfc843-9d58-45bb-adc2-677d40da121c

**If relevant, did you update the documentation?**
No

**Summary**
Now there is consistency in minimization of the left column navbar in event mangement screen.

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by EshaanAgg — APPROVED** [review]
LGTM

**Comment by palisadoes** [comment]
The intention was for there to be a single way to expand and retract the left drawer. We still have two ways which is not intuitive.

1. The expectation that this would be the sole methodology of expanding the drawer
    image
1. And that this way would be the only way to retract it.
   image

In all cases on this screen

**Review by palisadoes — CHANGES_REQUESTED** [review]
The intention was for there to be a single way to expand and retract the left drawer. We still have two ways which is not intuitive.

1. The expectation that this would be the sole methodology of expanding the drawer
    image
1. And that this way would be the only way to retract it.
   image

In all cases on this screen

**Comment by akhilender-bongirwar** [comment]
@palisadoes  according to the solution stated in the issue, I have implemented the same method for opening and closing the sidebar as used in the remaining main organization pages to maintain consistency throughout the application. Please check the video below.

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/f4e236cc-1090-4d0e-93cd-da68623692e9

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
We'll need to open another issue specifically for the modification for consistency

**Pull request merged**
