### PR TITLE
fix: simplified error messages for invalid inputs at profile settings

### LINKED ISSUE #2464: Bug : Simplify error messages for user at Talawa User Portal
**Describe the bug**
In Talawa User portal when the user tries to update information with empty or invalid data, error in **not** user friendly way appears. Makes it hard to understand the user what required fields they are missing or giving an invalid data into. 

**To Reproduce**

1. Go to `Talawa User Portal`
2. Go to `settings` 
3. Submit data in invalid or empty format
4. Click on save changes

**Expected behavior**
Error should come one by one in a user friendly format. 

**Actual behavior**
```
Variable "$phoneNumber" got invalid value ""; Value is not a valid phone number of the form +17895551234 (7-15 digits): Variable "$grade" got invalid value ""; Value "" does not exist in "EducationGrade" enum. Variable "$empStatus" got invalid value ""; Value "" does not exist in "EmploymentStatus" enum. Variable "$maritalStatus" got invalid value ""; Value "" does not exist in "MaritalStatus" enum.
```

**Screenshots**
image

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by bandhan-majumder**
**What kind of change does this PR introduce?**

A bugfix.

**Issue Number:**

Fixes #2464 

**Snapshots/Videos:**

https://www.loom.com/share/0a0e7d6b5b754bbfb8e9b6b8bd6e6161?sid=074df4c5-6119-43f7-827d-6108f36f6cee

**Summary**

While updating user profile at Talawa User Portal, user used not to get user friendly errors. I have simplified the error which will come one by one in a user friendly readable manner helping user to understand the fields they are missing/giving wrong data into. I have also added translation of errors.

**Other information**
 
Added a 400 handler too.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Introduced new error messages for better user feedback on validation issues, including phone numbers, education grades, employment statuses, and marital statuses.
	- Added general error messages for server response issues and generic errors across multiple languages (English, French, Hindi, Spanish, Chinese).

- **Bug Fixes**
	- Improved error handling logic to provide more specific feedback based on different error scenarios.

- **Documentation**
	- Enhanced localization for error messages to improve clarity for users in various languages.

### CODE REVIEW

**Comment by bandhan-majumder** [comment]
I can use map. But it will still use includes method. As backend is returning a string of all errors combined, I need to check it that way.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by bandhan-majumder** [comment]
1. graphql error may arise because the graphql setup of talawa-api is not completed yet ( have not changed anything related to gql) .
2. This is treating the errors.json files (including translation) as TypeScript files, it's showing the ` "key" : "values" ` relations as not used in a function call. JSON files should be ignored while checking the linting. It expects every expression to be used in a function call or assignment.

Please let me know if I need to change anything.

**Comment by palisadoes** [comment]
Please submit your PRs against our `develop-postgres` branch. To facilitate our reviews, the source and target branches in the PR must be different. The failing test indicates this. Closing.

**Comment by bandhan-majumder** [comment]
Sorry but I have pushed it against `develop-postgres` branch and it has passed that rest too. Please correct me if I am wrong. The reason of failing is that it's treating errors.json files as TypeScript file and getting unused expression which should be ignored for json files.

**Pull request closed without merging**
