### PR TITLE
Redesigned the Event Management's Dashboard tab for the talawa admin portal

### LINKED ISSUE #1749: ADMIN REDESIGN: redesign the Event Management's Dashboard tab for the talawa Admin portal
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management Dashboard Tab for the talawa Admin portal
- we want the dashboard to be as a card and match the consistency in terms of designs as we follow across talawa.
- This issue is for a single tab i.e dashboard that renders the details of the event.

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:

Screenshot 2024-03-20 at 12 12 00 AM

Desired Result:
Screenshot 2024-03-20 at 12 13 24 AM

Related Issues: 

#1748 

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Sahi1l-Kumar**
**What kind of change does this PR introduce?**
A redesign.

**Issue Number:**
Fixes #1749 

**Did you add tests for your changes?**
No.

**Snapshots/Videos:**

image

**If relevant, did you update the documentation?**

**Summary**
In the following PR, I have redesigned the Event's dashboard screen for the talawa admin portal according to the figma file [here](https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1)

**Does this PR introduce a breaking change?**
No.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes.

### CODE REVIEW

**Comment by Sahi1l-Kumar** [comment]
I am not able to manually link this PR back to [this](https://github.com/orgs/PalisadoesFoundation/projects/27/views/1) project. Maybe I need certain permissions to the repo.

**Comment by palisadoes** [comment]
Please add the missing tabs. We need them as place holders. Use a component methodology of possible

**Comment by Sahi1l-Kumar** [comment]
> Please add the missing tabs. We need them as place holders. Use a component methodology of possible

Isn't the tabs supposed to be implemented in this issue?
https://github.com/PalisadoesFoundation/talawa-admin/issues/1748

**Comment by palisadoes** [comment]
OK. Thanks for the reminder

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
