### PR TITLE
[ Feature ] Select Organization on the Registration screen

### LINKED ISSUE #1440: Admin - Select organization on registration
**Is your feature request related to a problem? Please describe.**

We are working on migrating the approval of requests to join organizations to a new Admin screen as outlined in this issue:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1416

Prior to this the process was:

1. New registrants joined the Community
1. Super Admins would approve the request
1. Approved registrants would login and select an organization

There were disadvantages to this approach:

1. This gave too much responsibility to the Super Admin who may not necessarily know people requesting to join in the way an Admin would. 
1. The two step process where the organization was selected post approval, could have been reduced to a simpler single step.

**Describe the solution you'd like**

_TALAWA API_

- This new requirement means that:
    1.  New `USER`s and `NON_USER`s will need to select an organization when registering so that the request can be directed to the correct organization's Admin screens.
    1. The setup script needs to create a single organization with a generic name on installation to facilitate registration to choice of at least one organization
    1. There can never be less than one organization in the DB
    1. The registration mutation must include organization ID information that issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1416 will be able to detect.
    1. The current GitHub action pull request workflow needs to be updated so that the default organization is created successfully. This is in addition to the already existing test data importation test.
    1. The default organization creation mode mutation needs set the registration approval required flag to True to err on the side of caution.

_TALAWA MOBILE_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA ADMIN_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_OTHER_

1. You will need to write tests for the updated code 
1. All other functionality must be maintained
1. We will need to add your Figma page designs to our official Figma document

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. Related issues:
     1. https://github.com/PalisadoesFoundation/talawa-api/issues/1703
     3. https://github.com/PalisadoesFoundation/talawa/issues/2330
     4. https://github.com/PalisadoesFoundation/talawa-admin/issues/1440
1. User definitions in the DB schema
image

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by karthxk07**
**What kind of change does this PR introduce?**

Feature, Select Organization on the Registration screen

**Issue Number:**

Fixes #1440 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[Screencast from 14-04-24 12:55:33 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/ec5b09aa-a93b-40b9-8ad4-1cee760ad4ad)

**Summary**

Now users can select on the registration screen , which organization they want to join starting with. WIth the updated backend code, if the Organization requires user registration, it will create membershipRequest in that organization, otherwise the user can directly join the organization

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Please fix the linting and testing tests

**Comment by Cioppolo14** [comment]
@karthxk07 Please fix the failing tests.

**Comment by Azad99-9** [comment]
@karthxk07 while working on this feature didn't you encounter a bug where, on successful registration to a org which has`userRegistrationRequired: true` the membershipRequest is added to the org's membershipRequests field but at the same time not being reflected in the user's membershipRequests field.

**Comment by karthxk07** [comment]
@Azad99-9 I didn't check on that. However, Is it really necessary though?

**Comment by Azad99-9** [comment]
Yes it is necessary because it is generating bugs in mobile side.Kindly check on that once.

**Comment by karthxk07** [comment]
@Azad99-9 That sure is a problem. However, this PR is made to the admin repo. The changes are simply using the new signup mutation introduced in this PR(https://github.com/PalisadoesFoundation/talawa-api/issues/1703). You might want to open a new issue for that in the api repo.

**Comment by Azad99-9** [comment]
@karthxk07 The issue I am talking about is this https://github.com/PalisadoesFoundation/talawa-api/issues/2242#issue-2255025763 .

Actually there is a requirement in the mobile app to show the org to which the request was sent. To get this functionality we need the signup mutation to work properly.

**Comment by Cioppolo14** [comment]
@karthxk07 Please fix the failing tests.

**Review by palisadoes — CHANGES_REQUESTED** [review]
Please find a way to make it easier for the user to select an organization. As you can see all four test organizations are listed using only their names. No other distinguishing feature is used.

image

**Comment by palisadoes** [comment]
The message text after registering is incorrect:

image

**Comment by palisadoes** [comment]
It otherwise looks OK

**Comment by karthxk07** [comment]
@palisadoes I looked into the issues sir, I have added the address alongside the Organization name. Here is how it looks now(also I changed the plain select component with a material UI Autocomplete component, which will give users ability to search through a large list of organizations instead of scrolling manually to the organization's name)

[Screencast from 28-04-24 04:23:51 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/6098cc89-b5f0-47f0-9508-0c0e18305988)

**Comment by palisadoes** [comment]
1. Why is  `package-lock.json` edited and not `package.json`?
2. This means that whenever we next make changes to `package.json` your changes will be overwritten. It's not a good best practice.
3. Make your changes to `package.json`, or exclude  `package-lock.json` from this PR (don't delete it from the repo)

**Comment by karthxk07** [comment]
@palisadoes Sir, I didnt realize the `package-lock.json` file got effected by the changes too. I have reverted back the changes to `package-lock.json`. Any other changes?

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
Thanks, I've merged it.

**Pull request merged**
