### PR TITLE
[Code Coverage ]Add Test: Plugin.helper.ts for #261

### PR DESCRIPTION
**Pull request by SiddheshKukade**
What kind of change does this PR introduce?**
Testing Added for Plugin.helper.ts #261 

**Issue Number:**

#261 

**Did you add tests for your changes?**
yes
**Snapshots/Videos:**

image

**Summary**
Added  a test file 
**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**
Yes

### CODE REVIEW

**Comment by SiddheshKukade** [comment]
## Code Coverage for the file is 80% due to test is not checking the line no 4 and 9 
image
## Line No 4 and 9 Contains these statement 
image
## I am trying to cover it different ways but no results 
### can anyone suggest a solution ?

**Comment by palisadoes** [comment]
@DangaRanga @yasharth291 can you think of any ways to solve this?

**Review by yasharth291 — APPROVED** [review]

**Comment by yasharth291** [comment]
> @DangaRanga @yasharth291 can you think of any ways to solve this?

we can test if the data is coming or not

**Comment by palisadoes** [comment]
Siddesh were you able to use Yasharth's suggestion to fix this?

**Comment by SiddheshKukade** [comment]
@palisadoes  @yasharth291

**Review by yasharth291 — APPROVED** [review]

**Comment by yasharth291** [comment]
this could be case where we can ignore it

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
