### PR TITLE
Feature: Ability to change pre-login imagery

### LINKED ISSUE #1334: Add the ability to change pre-login imagery
**Is your feature request related to a problem? Please describe.**
1. Communities need the ability to change the social media icons and logo images upon login.
1. We don't want users thinking that they are always logging into Palisadoes

**Describe the solution you'd like**

1. Our login screen is not specific to organizations, so we'll need to make this change at the Community level.
1. This will require the creation of a Community Profile button at the Super Admin level which would lead to a Community Profile edit screen
1. This screen must be designed in keeping with our Talawa Admin Figma design found here
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
1. The logo and social media icons to be edited are visible in the attached screen shots
1. By default, when the Palisadoes Logo is changed, the Palisadoes specific social icons should disappear so that the Community can add theirs. If the Logo is left blank, then the Palisadoes imagery should return, but the database parameters must remain so that the Admin doesn't have to re-enter the information.
1. This will require the creation of a new collection in the API
1. Please work with @aashimawadhwa and @rishav-jha-mech on the design approval before submitting a PR
1. You will need to write valid tests for your code
1. No other functionality must be affected

**Related Issues**
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Images that should be editable: 
    image
1. Location of the Community Profile
    image

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by git-init-priyanshu**
**What kind of change does this PR introduce?**

feature

**Issue Number:**

Fixes #1334 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

[Screencast from 27-02-24 07:41:53 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/f3165213-d2d5-4fde-8307-8864b7ea2f50)

**If relevant, did you update the documentation?**

No

**Summary**

I have created the UI for the Community Profile page. The functionalities are not available right now as corresponding APIs are still in progress. 

**Does this PR introduce a breaking change?**

No.

**Other information**

This PR is work in process.

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes.

### CODE REVIEW

**Comment by palisadoes** [comment]
Please post a video to prove the functionality where:

1. You change all the URLs
1. Upload a new image
1. Logout
1. Visit the login screen
1. See the updated image
1. Click through to all the changed URLs to see that they have been updated
1. Log back in
1. Revert the changes
1. Logout
1. See the original URLs and imagery
1. Click through on the new URLs to the social media sites

**Comment by palisadoes** [comment]
1. Please fix the conflicting files
2. Also remember the video

**Comment by git-init-priyanshu** [comment]
> 1. Please fix the conflicting files
> 2. Also remember the video

Yes sir. I am waiting for the APIs to be completed.

**Comment by git-init-priyanshu** [comment]
@palisadoes sir, I have a doubt. If the user is not logged in, how can we determine which organization they belong to and display the images accordingly?

**Comment by palisadoes** [comment]
The image and social icons would be on the login screen

**Comment by palisadoes** [comment]
Reviewers. This is dependent on the merging of this PR and closing this issue:

1. https://github.com/PalisadoesFoundation/talawa-api/pull/1935
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Comment by Cioppolo14** [comment]
@noman2002 @Kevoniat Can you review this PR?

**Comment by Cioppolo14** [comment]
@git-init-priyanshu Can you resolve the conflicting files?

**Comment by git-init-priyanshu** [comment]
[screen-capture.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/56e03b07-ab96-4bd1-9291-490b8a2e0301)
[screen-capture (1).webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/5c589925-3d33-494f-b61b-7e999711fe75)
[screen-capture (2).webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/24ad7791-8d24-4b15-9249-c538a8aae04d)

**Comment by git-init-priyanshu** [comment]
hey @palisadoes , I have created my own APIs for this and I have now created videos for all the points you asked me to show. Right now, we need to reload the website to see the changed data but I will fix it soon. Apart from this if there any problem with the flow then let me know. Thanks.

**Comment by Cioppolo14** [comment]
@git-init-priyanshu Please fix the failing test application check and conflicting files.

**Comment by palisadoes** [comment]
> hey @palisadoes , I have created my own APIs for this and I have now created videos for all the points you asked me to show. Right now, we need to reload the website to see the changed data but I will fix it soon. Apart from this if there any problem with the flow then let me know. Thanks.

Thanks for the effort made in doing this. It's an important feature that Admins will want to see.

**Comment by palisadoes** [comment]
Are you basing your code off this PR? The code shouldn't be supported in the API yet.
- https://github.com/PalisadoesFoundation/talawa-api/pull/1935

Please fix the conflicting files

**Comment by git-init-priyanshu** [comment]
> Are you basing your code off this PR? The code shouldn't be supported in the API yet.
> 
> * [Added support for pre-login imagery talawa-api#1935](https://github.com/PalisadoesFoundation/talawa-api/pull/1935)
> 
> Please fix the conflicting files

No, sir. Since the PR on the backend side is not completed yet, I have attempted to create my own APIs locally. This allows me to complete the frontend side beforehand without waiting for the backend PR to be merged. Once the backend PR is merged, I will only need to make a few changes to make it work again. Thank you.

**Comment by palisadoes** [comment]
1. Use this link to show you how to check out pull requests locally.
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
1. Apply it to this PR. That way you don't have to do the extra work later
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1935

**Comment by palisadoes** [comment]
1. Please fix the conflicting files
1. Does your API fix pass all the required tests for the latest upstream? This PR seems to be stalled.
    - https://github.com/PalisadoesFoundation/talawa-api/pull/1935

**Comment by git-init-priyanshu** [comment]
> 1. Please fix the conflicting files
> 1. Does your API fix pass all the required tests for the latest upstream? This PR seems to be stalled.
>     - https://github.com/PalisadoesFoundation/talawa-api/pull/1935

Right now APIs do not have their test files because I wanted everything to work and make that video. If you allow then I will create them ASAP.

**Comment by palisadoes** [comment]
1. Please test your code against the latest API upstream. This PR was merged.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1935
3. If you find any API errors, please create issues to get them fixed

**Comment by git-init-priyanshu** [comment]
> 1. Please test your code against the latest API upstream. This PR was merged.
>    
>    1. [Added support for pre-login imagery talawa-api#1935](https://github.com/PalisadoesFoundation/talawa-api/pull/1935)
> 2. If you find any API errors, please create issues to get them fixed

Ok sir.

**Comment by palisadoes** [comment]
Review the API code, create an issue to resolve the problem(s) to meet your needs, ask to be assigned.

**Comment by palisadoes** [comment]
If you think it would be faster, you could also consider:

1. writing the tests for your API solution. 
1. purging the code base of the API PR either manually or reverting the changes (if it's not too late)

**Comment by git-init-priyanshu** [comment]
Ok sir.

**Comment by palisadoes** [comment]
What approach are you taking?

**Comment by git-init-priyanshu** [comment]
> What approach are you taking? Your code or fixing the deficiencies in the API PR?

I am not going to  revert the PR. I'll just make the necessary changes.

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
This is a useful PR to get merged with the corresponding API PR. Please fix the conflicting files.

**Comment by git-init-priyanshu** [comment]
> This is a useful PR to get merged with the corresponding API PR. Please fix the conflicting files.

Yes sir, I will try to do it ASAP.

**Comment by palisadoes** [comment]
Please fix the failing test

**Comment by git-init-priyanshu** [comment]
Hey @palisadoes , Can you check now.

**Review by palisadoes — APPROVED** [review]

**Comment by git-init-priyanshu** [comment]
> What happens if the community only has only one social media account?
> 
> 1. Will the rest of the icons be visible on the login screen? They should not be.
> 2. Will these icons have URLs for Palisadoes? If so, this is not the desired outcome.

Yes sir, It has already been taken care of. Here is the video:
[Screencast from 25-03-24 11:41:04 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/df45897f-9090-4523-b16b-9846f251174c)

**Pull request merged**
