### PR TITLE
Fixed Settings page Header

### LINKED ISSUE #486: Fix the Settings Page's header
**Is your feature request related to a problem? Please describe.**
On the settings page, we have four options
+ Update your details.
+ Update Organizations.
+ Delete Organization.
+ See Request.

When We choose any of the above options, the Title at the top remains the same that is `Settings`. We want this title to reflect which option is chosen among the above four.
Screenshot from 2023-02-19 14-46-34

**Describe the solution you'd like**
Once We click on any of the options above. For example, Update Organization, then in place of `Settings ` `Update Organization `should appear as header

**Describe alternatives you've considered**
The contributor is free to pitch any other idea on this.

**Approach to be followed (optional)**
We want to minimize changes to the existing design. Hence no new CSS, no new responsive design, just the enabling of previously disabled or incorrectly implemented features

### PR DESCRIPTION
**Pull request by anurag0006**
**What kind of change does this PR introduce?**
a bugfix

**Issue Number:**

Fixes #486 

**Did you add tests for your changes?**
not required

**Snapshots/Videos:**
[Screencast from 24-02-23 03:04:06 PM IST.webm](https://user-images.githubusercontent.com/107215525/221144109-6820005f-e7ec-4d83-951e-cece0b8a0329.webm)

**If relevant, did you update the documentation?**

**Summary** 
The Pr closes #486 .. It makes the settings page header dynamic

**Does this PR introduce a breaking change?**
No

**Other information**
not Needed

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Review by noman2002 — CHANGES_REQUESTED** [review]
Keep settings as it is and add these as sub heading of settings.

**Comment by noman2002** [comment]
And also fix the linting errors

**Comment by anurag0006** [comment]
Yeah sure!... Should i also reduce the font-size of sub heading(as compared to heading) maybe by some pixels so that the Ui looks more good ?

**Comment by anurag0006** [comment]
@noman2002 , how does this look?
[Screencast from 24-02-23 03:48:25 PM IST.webm](https://user-images.githubusercontent.com/107215525/221153929-1346d22f-c5ba-4992-a15f-bcedbc954676.webm)

**Comment by noman2002** [comment]
> @noman2002 , how does this look? [Screencast from 24-02-23 03:48:25 PM IST.webm](https://user-images.githubusercontent.com/107215525/221153929-1346d22f-c5ba-4992-a15f-bcedbc954676.webm)

Just make a sub heading under the settings. This is not looking good.

**Comment by anurag0006** [comment]
@noman2002  please have a look...Is it ok now?
[Screencast from 24-02-23 07:50:12 PM IST.webm](https://user-images.githubusercontent.com/107215525/221201590-7dbd1479-df5d-4b8a-9c98-43986ec1a0b5.webm)

**Comment by anurag0006** [comment]
sorry for these mistakes there was some problem with my local system, so i was getting some errors and wasnt able to fix them....Along with solving this issue i also solved some other minorUI bugs 


the main issue i solved was :
[Screencast from 24-02-23 07:50:12 PM IST.webm](https://user-images.githubusercontent.com/107215525/221256650-16716155-0232-42f4-91ca-632812ec8a12.webm)



This is how the Ui of the settings page(navbar ) was on smaller screens which i noticed while exploring the portal:
Screenshot from 2023-02-24 15-52-23
![Screenshot from 2023-02-24 15-48-20]


screenshot of fixed ui
image

**Comment by anurag0006** [comment]
@palisadoes  sir, Please review

**Review by noman2002 — APPROVED** [review]
Good work

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
If you use corporate Gmail, you have the option of replacing the Gmail logo with that of your organization. That would be an interesting design idea

**Comment by anurag0006** [comment]
> If you use corporate Gmail, you have the option of replacing the Gmail logo with that of your organization. That would be an interesting design idea 

I didn't get it...sir can you please elaborate a but on this?

**Comment by palisadoes** [comment]
I'm looking at too many PRs. Sorry, my mistake.

**Pull request merged**
