### PR TITLE
Added support for Event Venues

### LINKED ISSUE #1390: Admin - Add support for event venues
**Is your feature request related to a problem? Please describe.**

We need the ability to add functionality to assign a venue to an event. Currently you can assign geographic coordinates, but you cannot also provide one of a list of pre-defined venues (eg. "Conference Room", "Sports Field" or "Theater") This would be a useful capability to add.

**Describe the solution you'd like**

The aim would be for Admins to do CRU activities (no deletions, but disabling/enabling) for venues on an Org screen, and for these venues to appear as options whenever events are scheduled.

1. The design must be in keeping with our standards found in the Talawa Admin Figma file located here:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
    2. Work with @rishav-jha-mech @aashimawadhwa on the design while the API work is completed
1. See the API issue below for the requirements there.
    1. Coordinate your work with the person assigned that issue

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

Related issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1640
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1390

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Feature Request

**Issue Number:**

Fixes #1390 

**Did you add tests for your changes?**
Yes

**Snapshots/Videos:**
[event venues.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/d6148138-7ae1-416c-b69b-b1837e9762da)

**If relevant, did you update the documentation?**
N/A

**Summary**
Added Support for Venues - Add Venue, View all the venues, Update a venue

**Does this PR introduce a breaking change?**
No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Anvita0305** [comment]
This is same as #1723 . Previous PR was closed due to branch name ambiguity.

**Comment by Olatade** [comment]
@Anvita0305 please fix the failing test

**Comment by Anvita0305** [comment]
@Olatade 'Checks if no unauthorized files are changed' test is failing because I have changed .github/workflows/pull-request.yml file. Actually, one of the files is having >600 lines so I have updated the above file.
image

**Review by varshith257 — APPROVED** [review]
LGTM

**Pull request merged**
