### PR TITLE
fixes: #550 added test for the calendar

### LINKED ISSUE #550: Increase the code coverage for Calendar.tsx #482
**Describe the bug**

- Increase the code coverage for components/EventCalendar/Calendar.tsx to 100%.
- Initiate a test file in  components/EventCalendar and add required tests 

The current code coverage can be found here:
- https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src/components/EventCalendar/Calendar.tsx

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aashimawadhwa**
**What kind of change does this PR introduce?**
bug fix

**Issue Number:**

Fixes #550 

**Did you add tests for your changes?**
yes

**Summary**
Increase the code coverage for components/EventCalendar/Calendar.tsx 

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@palisadoes  can you help me generating the code cov report?

**Comment by palisadoes** [comment]
The tests are failing so the report won't be generated

- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4359429650/jobs/7621306013

**Comment by aashimawadhwa** [comment]
I saw and the test for calendar is 71% and the failing tests are in organizationPeople file not in calendar, what should i do now

**Comment by palisadoes** [comment]
It's failing on src/screens/OrganizationEvents/OrganizationEvents.test.tsx

**Comment by palisadoes** [comment]
Search for "FAIL" case sensitive in the logs

**Comment by palisadoes** [comment]
We need to clear up the other messages too

**Comment by palisadoes** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/pull/554 This person may have found the issue

**Comment by aviraldevv** [comment]
@aashimawadhwa  ` <Calendar eventData={data.eventsByOrganizationConnection} />` this line that you've added in your last PR to `OrganizationEvents.tsx` is causing the tests to fail.

**Comment by aashimawadhwa** [comment]
@palisadoes  can we then merge these tests? and fix the organization.tsx by the new issues that we will be creating?

**Comment by aviraldevv** [comment]
@aashimawadhwa Did you try to fix `OrganizationEvents.tsx` ??

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa Did you try to fix `OrganizationEvents.tsx` ??

I have tried earlier but could not fond a way back then, I need some time to look into it will have to research a little.

**Comment by aashimawadhwa** [comment]
> It's failing on src/screens/OrganizationEvents/OrganizationEvents.test.tsx


we have created a new issue for this, you can merge this PR. it contains the tests for the calendar

**Comment by palisadoes** [comment]
No it can't be merged, it's failing here. Please fix.

```
FAIL src/screens/OrganizationEvents/OrganizationEvents.test.tsx
  ● Organisation Events Page › It is necessary to check correct render

    TypeError: Cannot read properties of undefined (reading 'eventsByOrganizationConnection')

      210 |             </Row>
      211 |           </div>
    > 212 |           <Calendar eventData={data.eventsByOrganizationConnection} />
          |                                     ^
      213 |         </Col>
      214 |       </Row>
      215 |       <Modal

      at OrganizationEvents (src/screens/OrganizationEvents/OrganizationEvents.tsx:212:37)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:17356:20)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19063:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22293:18)
      at node_modules/react-dom/cjs/react-dom.development.js:11327:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11322:9)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11309:3)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21893:9)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16139:5)
      at InternalState.state.forceUpdate (node_modules/@apollo/client/react/hooks/useQuery.js:28:9)
      at InternalState.Object.<anonymous>.InternalState.setResult (node_modules/@apollo/client/react/hooks/useQuery.js:244:14)
      at Object.onError [as error] (node_modules/@apollo/client/react/hooks/useQuery.js:114:27)
      at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (node_modules/zen-observable/lib/Observable.js:240:7)
      at node_modules/@apollo/client/utilities/observables/iteration.js:4:68
          at Array.forEach (<anonymous>)
      at Object.iterateObserversSafely (node_modules/@apollo/client/utilities/observables/iteration.js:4:25)
      at ObservableQuery.Object.<anonymous>.ObservableQuery.reportError (node_modules/@apollo/client/core/ObservableQuery.js:454:9)
      at Object.error (node_modules/@apollo/client/core/ObservableQuery.js:426:23)
      at node_modules/@apollo/client/utilities/observables/iteration.js:4:68
          at Array.forEach (<anonymous>)
      at iterateObserversSafely (node_modules/@apollo/client/utilities/observables/iteration.js:4:25)
      at Object.error (node_modules/@apollo/client/utilities/observables/Concast.js:37:21)
      at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
      at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
      at SubscriptionObserver.error (node_modules/zen-observable/lib/Observable.js:240:7)
      at node_modules/@apollo/client/utilities/observables/asyncMap.js:27:40

```

**Comment by aviraldevv** [comment]
Hey @aashimawadhwa  `<Calendar eventData={data?.eventsByOrganizationConnection} />` try using this it might fix your issue.

**Comment by aviraldevv** [comment]
> > Hey @aashimawadhwa `<Calendar eventData={data?.eventsByOrganizationConnection} />` try using this it should fix your issue. Actually data property is getting called even when it is `undefined` , above code snippet will prevent `data` from being called in case it is `undefined`.
> 
> I tried this but this earlier but it is not working for 

> > Hey @aashimawadhwa `<Calendar eventData={data?.eventsByOrganizationConnection} />` try using this it should fix your issue. Actually data property is getting called even when it is `undefined` , above code snippet will prevent `data` from being called in case it is `undefined`.
> 
> I tried this but this earlier but it is not working for the errors.

Bad luck. Then we must make sure `eventByOrganizationConnection` is defined.

**Comment by aviraldevv** [comment]
@aashimawadhwa I can see that you have not defined `eventsByOrganizationConnection`  in the data object. This must be causing the problem. Also try optional chaining with it and see if it fixes.

**Comment by aviraldevv** [comment]
Check this out @aashimawadhwa 
Screenshot_386

Screenshot_387
There is no `eventsByOrganizationConnection` property in the data.

**Comment by aviraldevv** [comment]
Tests have passed sucessfully @aashimawadhwa .
Screenshot_388

**Comment by aashimawadhwa** [comment]
> Tests have passed sucessfully @aashimawadhwa . Screenshot_388

Its integrated with other mocks and its failing now because of them if I am not wrong.

**Comment by aviraldevv** [comment]
> > Tests have passed sucessfully @aashimawadhwa . Screenshot_388
> 
> Its integrated with other mocks and its failing now because of them if I am not wrong.

I have never seen this before tbh.

**Comment by aashimawadhwa** [comment]
@palisadoes  WDYT?

**Comment by aviraldevv** [comment]
@aashimawadhwa please check if I am not wrong in the latest commit you have added `eventsByOrganizationConnection` property only in the mocks it should also be added to parent file.

**Comment by aviraldevv** [comment]
> > @aashimawadhwa Please check in the latest commit you have added `eventsByOrganizationConnection` property only in the mocks it should also be added to parent file.
> 
> Organization by event connection already exsist there.

are tests running properly in local system??

**Comment by aashimawadhwa** [comment]
@palisadoes @noman2002 looking forward for your insights.

**Comment by noman2002** [comment]
I'm not able to figure out this issue. @aashimawadhwa Do some research over it and let us know.
@palisadoes Is there any changes we made in the CI/CD for the warnings ?

**Comment by aashimawadhwa** [comment]
> 

I have fixed all the warning for the calendar, there are console warnings of file that I didn't even touched, not sure what is the reason .

**Comment by aviraldevv** [comment]
@aashimawadhwa merge your current branch to latest commits and try to rerun the workflows , idk I can see this branch is 9 commits behind the Talawa-admin develop branch. I am not sure whether these commits were made after your PR request. Please check once.

**Comment by aviraldevv** [comment]
> > 
> 
> I have fixed all the warning for the calendar, there are console warnings of file that I didn't even touched, not sure what is the reason .

@aashimawadhwa those console warnings were not because of your changes, these were some of the legacy irregularities in our test files which had piled over a long time. The new issues we had created along with @anshgoyalevil were for those warnings only.

**Comment by aashimawadhwa** [comment]
Iknow if you read the chats i was saying the same thing that even after removing the changes the console warning exists @aviraldevv

**Review by noman2002 — APPROVED** [review]

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
