### PR TITLE
FIxes the container width on Collapse of sidebar

### LINKED ISSUE #2994: Main Container Fails to Expand on Sidebar Collapse
**Describe the bug**
The main container of the chat does not expand when the sidebar is collapsed, leaving empty space where the sidebar was previously displayed.

**To Reproduce**

1. Go to Chat in sidebar
2. Click on Collapse
3. Observe the main chat container not expanding to occupy the freed space.

**Expected behavior**
When the sidebar is collapsed, the main chat container should expand to occupy the full width of the screen, ensuring an optimal user experience.

**Actual behavior**
The main chat container remains the same size, leaving an empty area where the sidebar was, resulting in a suboptimal layout.

**Screenshots**
Video Replicating the problem:

https://github.com/user-attachments/assets/23c79b7c-a1f6-44fb-9f67-f65cf6fd283c

**Additional details**
None

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by CHIRANTH-24**
**What kind of change does this PR introduce?**

Bugfix

**Issue Number:**

Fixes #2994 

**Did you add tests for your changes?**

Yes,
This is my first time writing Unit Test

**Snapshots/Videos:**

https://github.com/user-attachments/assets/f16323d8-ad89-485d-8cbf-532a7032a493

**If relevant, did you update the documentation?**

**Summary**

This PR improves the sidebar's interactivity by dynamically changing the container's className based on the hideDrawer state. It allows the sidebar to expand or collapse when the menu button is clicked, enhancing user experience.

**Does this PR introduce a breaking change?**

No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **New Features**
	- Enhanced chat interface with dynamic styling for drawer visibility.
- **Tests**
	- Added comprehensive test cases for chat component's class name changes.
- **Style**
	- Implemented conditional CSS classes for improved user interface responsiveness.

### CODE REVIEW

**Comment by CHIRANTH-24** [comment]
@palisadoes could you please let me know what changes should i make?

**Comment by CHIRANTH-24** [comment]
@palisadoes could you please let me know what needs to be changed?

**Comment by palisadoes** [comment]
Please submit your PRs against our `develop-postgres` branch. This is a temporary requirement as we prepare to migrate our API backend to Postgres.

Also if applicable, make sure your branch name is different from `develop-postgres` when resubmitting.

Closing.

**Comment by CHIRANTH-24** [comment]
@palisadoes im not able to "chat" in develop-postgres.
From which branch should i checkout my new branch?

**Pull request closed without merging**
