### PR TITLE
Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 

### LINKED ISSUE #1783: Test: Create tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by aarishshahmohsin**
**What kind of change does this PR introduce?**

Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 

**Issue Number:**

Fixes #1783 

**Did you add tests for your changes?**

NA

**Snapshots/Videos:**

NA

**If relevant, did you update the documentation?**

NA

**Summary**

Added tests for src/screens/OrganizationActionItems/ActionItemUpdateModal.tsx 

**Does this PR introduce a breaking change?**

NA

**Other information**

NA

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by pranshugupta54** [comment]
Do we need to have a new file for this? How are the current tests implemented for this file? Is it done in some other component? This file had 17/20 code coverage, how did 17 got covered without test file?

Also this PR has some indirect changes, please fix them - https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1834/indirect-changes

**Comment by aarishshahmohsin** [comment]
@pranshugupta54 

> Do we need to have a new file for this? How are the current tests implemented for this file? Is it done in some other component? This file had 17/20 code coverage, how did 17 got covered without test file?

hello
There are no tests for this file right now in the develop branch. It is a recently created file and it is recommended to have separate testing files for different components.


> Also this PR has some indirect changes, please fix them - [app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1834/indirect-changes](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1834/indirect-changes)


There is already an issue created for this file [(link)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1785).
Making separate tests for it would not make other tests impact its coverage.

**Comment by pranshugupta54** [comment]
> There is already an issue created for this file [(link)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1785).
> Making separate tests for it would not make other tests impact its coverage.

Indirect changes due to this PR should be fixed here itself otherwise we'll get into a loop of indirectly failing tests.

**Comment by pranshugupta54** [comment]
> There is already an issue created for this file [(link)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1785). Making separate tests for it would not make other tests impact its coverage.

Ohk, the indirect change is in a file which does not have a test file itself `src/screens/OrgList/OrganizationModal.tsx` and relies on parent component

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
