### PR TITLE
Fixed: Unauthorized Access to Different Portals and Dashboard by Manipulating Endpoints

### PR DESCRIPTION
**Pull request by rahulch07**
**What kind of change does this PR introduce?**

[BugFix]: Unauthorized Access to Different Portals and Dashboard by Manipulating Endpoints

**Issue Number:**

Fixes [#1837](https://github.com/PalisadoesFoundation/talawa-api/issues/1837)

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**

Admin:

https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/78999447-9034-4180-83b8-eaeac21a264e

User:

https://github.com/PalisadoesFoundation/talawa-admin/assets/87270395/85960e37-d926-4210-8d4a-5532a671576b

**Summary**

This issue fixes the issue of unauthorized access to different portal by manipulating the endpoints.(e.g. User able to access admin dashboard)

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

### CODE REVIEW

**Comment by rahulch07** [comment]
@Cioppolo14 fixed the failed test application check. Please review.

**Comment by Cioppolo14** [comment]
@Tajcore @ttaylor92 Can you review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by rahulch07** [comment]
Updating PR code for changes made.

**Comment by Cioppolo14** [comment]
@rahulch07 Please let us know when it is updated. Thank you.

**Comment by rahulch07** [comment]
@Cioppolo14 @Tajcore @ttaylor92 I have updated my code according to recent changes. Please review.

**Comment by palisadoes** [comment]
Please fix the failing tests

**Comment by rahulch07** [comment]
@palisadoes I this these test are failing because I have made PR from my local develop branch. Should I close this PR and make a new PR from another branch?

**Comment by palisadoes** [comment]
Yes. Closing

**Pull request closed without merging**
