### PR TITLE
fix: Moved organization location to about section

### PR DESCRIPTION
**Pull request by techfussion**
What kind of change does this PR introduce?
feature

Issue Number:

Fixes: #572

Did you add tests for your changes?
No

Snapshots/Videos:
before:

after:

UI before:

UI after:

If relevant, did you update the documentation?

Summary
I moved organization location rendered on the same row as company name to the about section as sugested on issue #572

**Does this PR introduce a breaking change?
No

Other information

Have you read the contributing guide?
Yes

### CODE REVIEW

**Review by noman2002 — COMMENTED** [review]
Add a screenshot for the changes.

**Comment by techfussion** [comment]
@noman2002  done

**Review by noman2002 — CHANGES_REQUESTED** [review]
Align the orgName to the left, it is not looking good in the center.

**Comment by techfussion** [comment]
@noman2002 @palisadoes  I think it looks better if it's in the center or totally removed. Here are some screenshots:
Current:

Others:




Should we leave the 'Current' or implement one from 'Others'?

Also if the orgName was a little longer it would look good in the center.

**Comment by palisadoes** [comment]
1. Please fix the conflicting files
1. Having the name of the organization displayed twice is unnecessary. Please remove it a and let the one in the menu navbar remain.

**Comment by techfussion** [comment]
On it

**Pull request closed without merging**
