### PR TITLE
feat: functionality to view unread messages and mark messages as read.

### LINKED ISSUE #2352: Add feature to view unread messages and mark messages as read in chat (GSoC)
**Is your feature request related to a problem? Please describe.**
Add feature to view unread messages and mark messages as read in chat

**Describe the solution you'd like**
view unread messages and mark messages as read in chat

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by disha1202**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #2352 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

## Summary by CodeRabbit

- **New Features**
	- Updated terminology in the application, changing "Add On Store" to "Plugin Store" and simplifying advertisement creation label.
	- Introduced a Docker setup guide in the installation documentation.
	- Added multiple new error messages for input validation across various languages.
	- Enhanced styling capabilities with new CSS custom properties.
	- Improved user interface with updated button styles and layout adjustments.

- **Bug Fixes**
	- Fixed error handling and validation messages for user inputs.

- **Documentation**
	- Updated installation instructions and added a Docker setup section.
	- Enhanced clarity in README and pull request templates.

- **Tests**
	- Transitioned from Jest to Vitest for unit tests, with updated mocking and assertions.
	- Added new test cases for various components and improved existing tests for clarity and functionality.

- **Chores**
	- Updated dependencies and configuration files for better performance and maintainability.

### CODE REVIEW

**Comment by palisadoes** [comment]
@disha1202 

Please:

1. Fix the conflicting file
2. Make the code coverage tests pass
3. Make code rabbit approve the PR

**Comment by noman2002** [comment]
@disha1202 Any update on this one ?

**Comment by palisadoes** [comment]
@disha1202 We have made significant changes to the `develop-postgres` branch that there will be major conflicts with this PR when we merge. 

Can you close this and merge against that branch?

**Comment by palisadoes** [comment]
@disha1202 I rebased your PR against the `develop-postgres` branch. We did some changes to the UI/UX color scheme. Please make sure that those are maintained when you refactor the conflicting files.

**Comment by Cioppolo14** [comment]
@disha1202 I am going to close this as it seems inactive.

**Comment by palisadoes** [comment]
Reopening. GSoC

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by palisadoes** [comment]
Please fix:

1. Any failing tests (Click on the `details` link for more information)
1. Any conflicting files

Make sure CodeRabbit.ai approves your changes

**Comment by palisadoes** [comment]
@disha1202 

Please fix the conflicting files and ensure coderabbit.ai approves the changes

**Comment by disha1202** [comment]
Closing this PR 
The changes and functionality for unread messages is implemented in PR #2360

**Pull request closed without merging**
