### PR TITLE
CodeQL config

### LINKED ISSUE #62: CodeQL GitHub Action Needs to Run Only on Pull Requests
**Describe the bug**

The current [CodeQL GitHub Action configuration file](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/codeql-analysis.yml) has a number of deficiencies. The file is located in our [workflows directory](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows)

1. It runs as a cron job on a regular basis. **This must be removed as it utilizes unnecessary resources.**
2. It only runs on the master branch. It must run on all our branches
3. It runs on pushes. It must only run on pull requests (PRs)

**To Reproduce**

1. Push to a branch. 
2. Issue a pull request

**Expected behavior**

It should only be run on a pull request

**Actual behavior**

See above

**Screenshots**

None

**Additional details**

Parent Issue: #58

### PR DESCRIPTION
**Pull request by akshatgarg12**
**What kind of change does this PR introduce?**

**Issue Number:**

Fixes #62 

**Did you add tests for your changes?**

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

similar to #67 
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
@akshatgarg12 We just want changes in the `.github/workflows` directory. You are overwriting all of the master branch with new code.

**Comment by palisadoes** [comment]
@akshatgarg12 Focus on the `develop` branch with the other issues. The GitHub action is running OK in `develop`. It'll get into the other branches eventually.

**Comment by palisadoes** [comment]
@akshatgarg12 [Join our slack organization](https://join.slack.com/t/thepalisadoes-dyb6419/shared_invite/zt-qa1hbp06-GJrilN35oIYfddC9Vf0kRA) It'll help a lot.

**Comment by akshatgarg12** [comment]
@palisadoes Sure sir.

**Comment by akshatgarg12** [comment]
@palisadoes I have already created a PR for the alpha branch PR : #71  , shall i create one for master aswell regarding this #62  ?

**Comment by palisadoes** [comment]
@akshatgarg12 Yes, go ahead.

**Pull request closed without merging**
