### PR TITLE
 Admin - Add support for event venues

### LINKED ISSUE #1390: Admin - Add support for event venues
**Is your feature request related to a problem? Please describe.**

We need the ability to add functionality to assign a venue to an event. Currently you can assign geographic coordinates, but you cannot also provide one of a list of pre-defined venues (eg. "Conference Room", "Sports Field" or "Theater") This would be a useful capability to add.

**Describe the solution you'd like**

The aim would be for Admins to do CRU activities (no deletions, but disabling/enabling) for venues on an Org screen, and for these venues to appear as options whenever events are scheduled.

1. The design must be in keeping with our standards found in the Talawa Admin Figma file located here:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
    2. Work with @rishav-jha-mech @aashimawadhwa on the design while the API work is completed
1. See the API issue below for the requirements there.
    1. Coordinate your work with the person assigned that issue

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

Related issues:
- https://github.com/PalisadoesFoundation/talawa-api/issues/1640
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1390

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by Anvita0305**
**What kind of change does this PR introduce?**
Feature

**Issue Number:**

Fixes #1390 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
[Screencast from 13-03-24 08:55:59 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/91a833d2-006b-405e-80f9-7199e90fabd7)

**Summary**
Added Support for Venues - Add Venue, View all the venues, Update a venue

**Does this PR introduce a breaking change?**
No

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by Olatade** [comment]
@Anvita0305 please can you fix the failing tests

**Comment by Olatade** [comment]
@Anvita0305 have you attempted to fix the failing tests?

**Comment by Anvita0305** [comment]
Yeah @Olatade, fixed the failing test

**Comment by Huy1996** [comment]
@ttaylor92 @anwersayeed Could you please review this PR?

**Comment by palisadoes** [comment]
This is an update on the PR merging freeze:

1. In the next few hours we will be merging the `develop-userTypeFix` branch into the `develop` branch. 
1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. This merge will cause some conflicts in your PR.

We decided to do this at the beginning of the weekend to give us all time to adjust PR code and create bug fixes that may arise.

Update your code at or after midnight GMT on the morning of March 23, 2024. (5:30am IST). 

If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by palisadoes** [comment]
## The PR merging freeze is lifted.

1. We are working on bug fixes that may arise. These should be few and are being tracked here:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24
1. Please update your PRs and local repos. Fix any new merge conflicts that may have occurred.
    
Background:

1. The `develop-userTypeFix` branch was created to fix a long standing design flaw where Admins were Admins of all organizations, not specific ones.
1. The `userType` field has been removed from the User collection and it has been replaced by an `appUserProfileId` field.
    1. This field is `null` if the user isn’t registered to use the apps. This will help people to add users manually during the event checkin process, or if an Admin wants to manually add someone in the Admin dashboard.
    1. When not `null` the `AppUserProfileID` will reference a `AppUserProfile` collection with App related information such as the organizations for which a user may be an Admin.
    1. The updated schema can be found here https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql
    1. This is the parent issue that we have been using to track progress:
        1. https://github.com/PalisadoesFoundation/talawa-api/issues/1965
1. If your PRs have already been approved, request a re-review after fixing the conflicts and refactoring to the new `AppUserProfileID` methodology.

**Comment by Cioppolo14** [comment]
@Anvita0305 Please fix the conflicting files.

**Comment by Anvita0305** [comment]
Hello, I have resolved the conflicts. However, the tests are failing because /home/runner/work/talawa-admin/talawa-admin/src/GraphQl/Mutations/mutations.ts file has >600 lines. So, how should I tackle this?

**Comment by palisadoes** [comment]
Is it unavoidable to be refactored? If so, then add the file to the GitHub action file `pull-request.yml` as part of the PR

**Comment by Anvita0305** [comment]
> Is it unavoidable to be refactored? If so, then add the file to the GitHub action file `pull-request.yml` as part of the PR

I think that it cannot to be refactored as it contains all the mutations.

**Comment by palisadoes** [comment]
Thanks,

1. OK, please update the file mentioned
2. Also, fix the linting related issues

**Comment by Anvita0305** [comment]
The linting test is failing because source and target branch names are same. Sorry, I didn't realize it while opening the PR. So should I close this PR and open a new one?

**Comment by varshith257** [comment]
@Anvita0305 Add the file causing the test fail to check number of lines in pull-request.yml.

**Comment by palisadoes** [comment]
Please close and reopen with a new branch.
The protection has a valid rationale

**Comment by palisadoes** [comment]
Closing

**Pull request closed without merging**
