### PR TITLE
test: adding test for organizationdashboard.tsx

### LINKED ISSUE #395: Code Coverage: Create tests for OrganizationDashboard.tsx
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/screens/OrganizationDashboard/OrganizationDashboard.tsx
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### LINKED ISSUE #399: Code Coverage: Create tests for constant.ts
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/Constant/constant.ts
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

### PR DESCRIPTION
**Pull request by arunavabasu-03**
**What kind of change does this PR introduce?**

This pull request is to include a comprehensive test for the organizationdashboard.tsx  file, which will ensure its proper functionality and performance before it is integrated into the main codebase.

**Issue Number:**

Fixes #395

**Did you add tests for your changes?**

yes

**Snapshots/Videos:**

**If relevant, did you update the documentation?**

**Summary**

Adding test for constant.ts

**Does this PR introduce a breaking change?**

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

yes

### CODE REVIEW

**Comment by palisadoes** [comment]
@Kevoniat please review

**Review by noman2002 — CHANGES_REQUESTED** [review]
Rename Mocks.ts to OrganizationDashboardMocks.ts

**Comment by noman2002** [comment]
@arunavabasu-03 As the code coverage is not generated. Please attach a screenshot.

**Review by palisadoes — APPROVED** [review]

**Comment by palisadoes** [comment]
@noman2002 Please take a final look

**Review by noman2002 — APPROVED** [review]
Looks Good.

**Pull request merged**
