### PR TITLE
Profile Page for Members

### LINKED ISSUE #479: Implement the ability to view information about people who are members to your organization.
**Is your feature request related to a problem? Please describe.**
If you select the People menu option from the Navbar, you may get a complete list of all the members of your organization. The member's name displays on the list with a "Add Admin" button next to it. Nothing occurs if we click on any of the names in the list. Furthermore, there is no other method to view any potential further information on that person. 
Below is the image for the current functionality that needs below feature:-

**Describe the solution you'd like**
When an admin clicks on a name in the member list, all of the information about that person should be displayed. Also, once we have drilled down to the person page, where all of his available information is visible, we want the "Add Admin" button to be available there.

**Approach to be followed (optional)**
Refer to the images below. First, we require the member list, and after selecting a member, we require information similar to that shown in the second image below.

### PR DESCRIPTION
**Pull request by rishav-jha-mech**
**What kind of change does this PR introduce?**

Feature

**Issue Number:**

Fixes #479 

**Did you add tests for your changes?**

Yes

**Snapshots/Videos:**
User Details - Google Chrome 07-03-2023 17_14_36

User Details - Google Chrome 07-03-2023 17_14_43
a867159f.png)

**If relevant, did you update the documentation?**

Not required, nor relevant.

**Summary**

Profile page had to be made for better understanding of a user.

**Does this PR introduce a breaking change?**
No it does'nt.

**Other information**

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

### CODE REVIEW

**Comment by palisadoes** [comment]
Please fix the failing tests. Our test code coverage system will fail if either of these two conditions occur:

1. The overall code coverage drops below the target threshold of the repository
1. Any file in the pull request has code coverage levels below the repository threshold

We do this to ensure the overall reliability of the code base is maintained.

**Comment by rishav-jha-mech** [comment]
Yeah sure, I'm working on the tests, will fix this soon 🚀

**Comment by palisadoes** [comment]
@rishav-jha-mech Please make a small commit to restart the tests. We made some updates to the GitHub actions.

**Comment by rishav-jha-mech** [comment]
Same issue again, code coverage test did pass last time, this time it did not (I have not changed any lines on that file).

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
