### PR TITLE
[REFACTOR]: Jest to Vitest migration for UserListCard.test.tsx

### LINKED ISSUE #2824: Refactor `src/components/UserListCard/UserListCard.test.tsx` from Jest to Vitest
**Is your feature request related to a problem? Please describe.**
A clear and concise description of **Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor the file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

1. Refer to the merged PR for the base Vitest configuration:
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
1. Vitest reference site:
    1. https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359
what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

### PR DESCRIPTION
**Pull request by hustlernik**
**What kind of change does this PR introduce?**

This PR migrates the test cases in src/component/UserListCard.test.tsx from Jest to Vitest, ensuring compatibility with Vitest .

✅ Replace Jest-specific functions and mocks with Vitest equivalents
✅ Ensure all tests in src/component/UserListCard.test.tsx from Jest to Vitest.pass after migration using npm run test:vitest
✅ Maintain the test coverage for the file as 100% after migration
✅ Upload a video or photo for this specific file coverage is 100% in the PR description

**Issue Number:**

Fixes #2824 

**Did you add tests for your changes?**

No

**Snapshots/Videos:**

image

**Does this PR introduce a breaking change?**

No

**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-admin/blob/master/CONTRIBUTING.md)?**

Yes

## Summary by CodeRabbit

- **Tests**
	- Updated test file for the `UserListCard` component with improved import statements and simplified function calls.
	- Changed testing framework from `jest` to `vitest` and updated mocking approach.
	- Modified test case syntax for consistency.

### CODE REVIEW

**Review by palisadoes — CHANGES_REQUESTED** [review]
Why was this file edited? It is out of scope of the PR

- src/components/CheckIn/tagTemplate.ts

**Comment by hustlernik** [comment]
@palisadoes this file was trouble due to some type error.
image

#2804 Is it linked to this PR.

**Comment by palisadoes** [comment]
It might have been, however all the PR tests passed. Pleases make the appropriate adjustments to fix it.

**Comment by syedali237** [comment]
@hustlernik pull the latest changes from develop-postgres, and install the new package that was introduced. As in the PR that you mentioned package.json was modified.

**Comment by palisadoes** [comment]
@coderabbitai full review

**Review by palisadoes — APPROVED** [review]

**Pull request merged**
